### ISSUE TITLE
ディープリンク対応

### ISSUE THREAD

**Issue by tmurakami** [cocoa-mhlw/cocoa#100]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

現状 COCOA では、保健所から発行された処理番号を入力して陽性登録(TEK 送信)する仕様となっていると認識していますが、高熱にうなされているかもしれない陽性者に番号入力を強いるのは酷です。

## 解決策についてお書きください / Describe the solution you'd like

ディープリンク(アプリリンク)に対応できないでしょうか？
そうすれば、番号入力はスキップできるのではないかと思います。

## その他 / Additional context

以下に Xamarin でのディープリンク実装方法の説明があります。
https://docs.microsoft.com/ja-jp/xamarin/xamarin-forms/app-fundamentals/deep-linking

exposure-notifications-android でも`ens://`と`https://`を設定しています。
https://github.com/google/exposure-notifications-android/blob/master/app/src/main/AndroidManifest.xml#L73-L84

----
Internal IDs:
- Product Backlog Item 2945

**Comment by keiji** [comment]
ありがとうございます。

これは現在、陽性判明時に処理番号8桁を陽性者に送信して、陽性者自身の手でアプリに入力しているが、これを「処理番号を含むURL（URI）リンクの形で送信して、陽性者がリンクを開けば処理番号の入力が完了した状態でアプリが起動するようにすることでユーザーの負荷を減らすことができる。という要望ですね。

エッジケースですが、COCOAをインストールしたきり、利用を開始していない人がそのリンクを開いてしまったときにすべてを吹き飛ばして陽性登録画面にいかないようにしないといけない。みたいなのはあるので、そういった部分を丁寧にカバーしないといけませんね。
処理番号8桁を発行するサーバー側の対応も必要になることに加えて、URLが送られてくるとスパムを疑われる可能性があるので事前にしっかりとした説明が必要で、そのあたりオペレーションが変わる負荷も確認する必要がありそうだなと感じています。

ひとまず開発チームに共有します。

**Comment by tmurakami** [comment]
合わせて、有効期間の長いメール/SMS用の番号についても検討頂ければと思います。
(リファレンスでは電話用とSMS用とで2種類の番号を発行できるようです)
https://github.com/google/exposure-notifications-verification-server#about-the-server

今は有効期間が 1時間だと思うので、寝すごしてしまった場合再発行になってしまうのではないかと思います。

**Comment by keiji** [comment]
これ実装したらどんな感じになるか、そろそろ試してみます。
