### ISSUE TITLE
[iOS] ホーム画面で「陽性登録者との接触結果を確認」を押しても画面が開かないことがある

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#1001]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

回線が輻輳している場合などネットワーク接続が安定しない環境で「陽性登録者との接触結果を確認」ボタンを押しても接触確認結果画面が表示できない。

動作情報を確認したところ、`OnClickExposures`内での`ExposureRiskCalculationConfigurationRepository.GetExposureRiskCalculationConfigurationInternalAsync`で例外が起きていた。例外は`IOException`でも`HttpException`でもなく`TaskCanceledException`。これはタイムアウト？

```
        public Command OnClickExposures => new Command(async () =>
        {
            try
            {
                UserDialogs.Instance.ShowLoading(AppResources.Loading);
                loggerService.StartMethod();

                var exposureRiskCalculationConfiguration = await exposureRiskCalculationConfigurationRepository
                    .GetExposureRiskCalculationConfigurationAsync(preferCache: true);
                loggerService.Info(exposureRiskCalculationConfiguration.ToString());
```

## 解決策についてお書きください / Describe the solution you'd like

`TaskCanceledException`が発生してもキャッシュされた`ExposureRiskCalculationConfiguration`があればそれを使う。

## その他 / Additional context

ネットワーク接続で`TaskCanceledException`が発生する条件は抑えておいた方がいい（同じ環境であれば、他のネットワーク接続でも発生しているはずなので）。

----
Internal IDs:
- Bug 7646

**Comment by b-wind** [comment]
HttpClient が Timeout プロパティに設定した時間内に応答を受け取れなかった場合、 TaskCanceledException が発生する実装と認識しています。


もちろん他の場所で TaskCanceledException が発生している可能性もありますが。
