### ISSUE TITLE
フォークしたリポジトリからのPull RequestでSonarCloudの実行が失敗する

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#1007]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

https://github.com/cocoa-mhlw/cocoa/pull/996

https://github.com/cocoa-mhlw/cocoa/runs/6409746066?check_suite_focus=true

こんな感じで、フォークしたリポジトリからのPRについてはSonarCloudの実行が必ず失敗する。

```
Run ./.sonar/scanner/dotnet-sonarscanner begin /k:"cocoa-mhlw_cocoa-app" /o:"cocoa-mhlw" /d:sonar.login="" /d:sonar.host.url="https://sonarcloud.io/" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
SonarScanner for MSBuild 5.5.3
Using the .NET Core version of the Scanner for MSBuild
The format of the analysis property sonar.login= is invalid
Default properties file was found at /Users/runner/work/cocoa/cocoa/.sonar/scanner/.store/dotnet-sonarscanner/5.5.3/dotnet-sonarscanner/5.5.3/tools/net5.0/any/SonarQube.Analysis.xml
Loading analysis properties from /Users/runner/work/cocoa/cocoa/.sonar/scanner/.store/dotnet-sonarscanner/5.5.3/dotnet-sonarscanner/5.5.3/tools/net5.0/any/SonarQube.Analysis.xml
Error: Process completed with exit code 1.
```

`/d:sonar.login`が空文字になっている。

`/d:sonar.login`に`/d:sonar.login="${{ secrets.SONAR_TOKEN }}"`が設定されている。このsecretsはリポジトリに設定されていて、フォークしたリポジトリからのPull Requestの時には適用されない。

https://docs.github.com/ja/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow

> 注釈: GITHUB_TOKENを除き、フォークしたリポジトリからワークフローがトリガーされた場合、シークレットはランナーに渡されません。

## 解決策についてお書きください / Describe the solution you'd like

フォークしたリポジトリからのPull Requestでも正常にSonarCloudが実行される方法を検討する。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

SonarCloudに失敗してもGitHub Actionsを失敗扱いにしない。

## その他 / Additional context

まずは失敗扱いにしないようにして、その後、SonarCloudが正常実行される方策を考える。

**Comment by b-wind** [comment]
https://portal.productboard.com/sonarsource/1-sonarcloud/c/50-sonarcloud-analyzes-external-pull-request?utm_medium=social&utm_source=portal_share


https://community.sonarsource.com/t/code-analysis-on-pull-request-from-forked-repository-with-github-actions/43986/6


対応していないっぽいですね。

**Comment by b-wind** [comment]
試していませんが、fork したリポジトリの方でも SonarCloud のアカウントを別途作成してTOKEN他を設定すればそのリポジトリからのPRでは動くのかも。

**Comment by keiji** [comment]
失敗した場合もワークフローを続けてSonarScanner関係のステップだけ実行しないようにした。
（本当はSonarScannerのステップが失敗したらキャンセル扱いにしたかったけど、それらしい構文が見当たらなかった。
