### ISSUE TITLE
陽性情報の登録画面において、キャンセルが英語表記になっている

### ISSUE THREAD

**Issue by Murayu0225** [cocoa-mhlw/cocoa#103]
## 不具合の内容 / Describe the bug

_この表記が意図的なものであれば、クローズしてもらって構いません。_

#57 にて[この部分](https://github.com/cocoa-mhlw/cocoa/blob/235499fc7320c27c7dfb0ee63a1e7180d18c6b7b/Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx#L89-L91)を確認していたところButtonCancelに与えられている表記が、英語のCancelとなっているのに気付いたので、日本語のキャンセルに修正する。

## 再現手順 / Steps to reproduce

1. '陽性情報の登録' に行き、
2. '同意して陽性登録する' をクリックし、
3. '登録する' をクリックし、
4. 登録する際の確認ダイアログにて、Cancelと表示される。

## 期待される挙動 / Expected behavior

英語で「Cancel」と表示されるよりも日本語で「キャンセル」と表示された方がよいと思います。

## スクリーンショット / Screenshots

![cocoa-3.jpg](https://user-images.githubusercontent.com/37988559/113466609-2274d300-9478-11eb-991b-9be830ea25cf.jpg)

## 動作環境 / Environments

- デバイス：Galaxy S10
- OS：Android（iOSでも確認済み）
- バージョン：1.2.2

## その他 / Additional context

#57 にて  @yoshitomo-g さんがiPhoneでのスクリーンショットを提供してくれました。そちらでも、同様の状態であることを確認済みです。

**Comment by yoshitomo-g** [comment]
この件、投げっぱなしのような形なってしまっていたので、せめて情報の補足を。
スクリーンショット取得時の環境は次の通りです。

- デバイス：iPhone SE（第2世代）
- OS：iOS 14.4.1
- バージョン：1.2.2

また、このリソースは、使用中止をする際の確認ダイアログでも参照されています。
https://github.com/cocoa-mhlw/cocoa/blob/1ad7c7cdee98c13c6ff9a89d7ed250310e996ae9/Covid19Radar/Covid19Radar/ViewModels/Settings/SettingsPageViewModel.cs#L51-L56

前述の環境で、下記スクリーンショットのように表示されることを確認しました。
![IMG_0874](https://user-images.githubusercontent.com/77680020/113479714-955b6980-94cb-11eb-9b06-f8762ce5874f.PNG)

**Comment by keiji** [comment]
ありがとうございます。
OKと並べるとCancelは違和感ないのですが、日本語の「同意する」と並べるとかなりの違和感があります。OKは適切に翻訳できなさそうなので置いておくとして「キャンセル」と日本語で記述するほうが良さそうです。

念のため、Cancel表記が意図的なものか開発チームにも確認します。
なるべく早い段階でご相談したいと思っています。

----

2つめのコメントの画面を見て、なにかいろいろ考えないといけないな…と思いました。

2つめのコメントの画像、「アプリの使用中止」の解説文には「使用を中止して過去14日間の接触履歴を **消去**」とあるのにダイアログのタイトルは「すべてのデータを **削除** する」とあり、さらにメッセージに「すべてのデータを **リセット** しますか？」と、表記揺れが気になります。

ユーザーに混乱を与えないという意味ではダイアログは

 * タイトル アプリの使用を中止しますか？
 * メッセージ 過去14日間の接触履歴を消去します
 * ボタン（Negative） キャンセル 
 * ボタン（Positive） OK または 使用中止 などの具体的なアクション 

が良いのかなと思いますが、ここまでいくと様々な言語の翻訳にも影響してしまいそうです。

どこからどこまでをやるのか。という話になりますが、ひとまず今回のIssueで指摘されているCancel -> キャンセルは手軽にできてユーザーの利益が大きい施策なので、切り離して考えていければとと思います。

**Comment by Murayu0225** [comment]
yoshitomo-g さん
他の部分でもButtonCancelが与えれていたんですね。気がつきませんでした。ありがとうございます。一応、元のコメントにもAndroidでの画像を追加しておきます。

Keiji さん
確認の方をよろしくお願いします。
確かに、他にも考えるべき点がありそうです。

**Comment by Murayu0225** [comment]
yoshitomo-g さん
他の部分でもButtonCancelが与えれていたんですね。気がつきませんでした。ありがとうございます。一応、元のコメントにもAndroidでの画像を追加しておきます。

Keiji さん
確認の方をよろしくお願いします。
確かに、他にも考えるべき点がありそうです。

**Comment by yoshitomo-g** [comment]
@keiji さん
> 2つめのコメントの画面を見て、なにかいろいろ考えないといけないな…と思いました。
> 
> 2つめのコメントの画像、「アプリの使用中止」の解説文には「使用を中止して過去14日間の接触履歴を **消去**」とあるのにダイアログのタイトルは「すべてのデータを **削除** する」とあり、さらにメッセージに「すべてのデータを **リセット** しますか？」と、表記揺れが気になります。

私もスクリーンショットを投稿前に眺めていて、同様のことを感じました。ダイアログの表記の変更としては概ね同意なのですが、ユーザビリティとしてはこの画面自体にも考慮するべき点があるように思えます。案はあるのですが、コメントは #104 に集約したほうが良いでしょうか。

**Comment by keiji** [comment]
@yoshitomo-g 
画面も違いますし、文言変更の枠組みを超えての検討であれば別Issueにする方がスムーズに進みそうです。

案、楽しみにしています！
