### ISSUE TITLE
COCOA v2.0.1リリース状況

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#1031]
COCOA v2.0.1（`release/v2.0.1`ブランチ）のリリース準備を進めています。

リリースノート
https://github.com/cocoa-mhlw/cocoa/releases/tag/v2.0.1

何事もなければ、9日からローリングアップデートを開始します。
今回はv2.0.0から大きな機能の変更はなく漸進的な改良に留まります（v2.0.1に含まれる具体的な変更点は後ほど更新します）。
β版の配布は行わず（ #932 ）、ローリングアップデートはする。という取り扱いになります。

PS.
v2.1.0ではDiagnosisApi v3への変更が予定されているので、パブリックベータを実施して、リリース予定日ももっと早くに共有できるようにしたいと考えています。

**Comment by keiji** [comment]
Google PlayならびにApp Storeでの審査は通過済みとの連絡を受けています。

**Comment by keiji** [comment]
Google PlayならびにApp Storeでの審査は通過済みとの連絡を受けています。

**Comment by keiji** [comment]
v2.0.1のローリングアップデート（段階的リリース）を開始しました。
本日の公開割合は1％です。

（これiOSだと任意にアップデートできるんですよね

**Comment by b-wind** [comment]
iOS の強制アップデート（App Store アプリのアカウント画面開いて下に引っ張る）操作でアップデート出来ました。

**Comment by keiji** [comment]
本日の公開割合はGoogle PlayならびにApp Storeともに2％です。

Google Playは公開割合を自由に設定できるのですが、App Storeは経過とともに固定なので、App Storeに合わせる形で開発チームがGoogle Play側を調整しています。

**Comment by parasite2006** [comment]
私も強制アップデートでさきほどiOS版v2.0.1を導入しました。
ホーム画面で「陽性登録者との接触結果を確認」ボタンを押して出てくる「過去14日間の接触」という画面上で、「陽性者との接触は確認されませんでした」の表示と一緒に出てくる「情報を保存」ボタンを押すと、exposure_data.jsonというファイルの保存場所を聞かれて指定の場所に保存することができました。このファイル名には日付の情報が入っていないので、同じ場所に繰り返し保存させようとすると「既存の項目を置き換えますか？」と聞かれ、上書きされるのが嫌ならここで「両方とも残す」を選ぶ必要がありました。
exposure_data.jsonの中身を見てみると、これまで「設定」の「接触通知」から表示させてきたExposureChecks(日付).jsonファイルとはだいぶ違っているようで、どこかで判読法を調べなければ。

**Comment by keiji** [comment]
@parasite2006 
COCOAログチェッカーの方にPull Request投げました。
https://github.com/ktansai/COVID-19-ExposeChecker/pull/73

基本的にはExposureWindowを読むことで「接触日」を知ることができます。
ExposureChecks.jsonの場合「どの時点の接触確認で診断キーがマッチしたのか」までだったので、接触日に関しては以前より精度の高い情報が得られると思います。

**Comment by parasite2006** [comment]
情報ありがとうございます。
exposure_data.jsonファイルのExposureWindows部分にある"DateMillisSinceEpoch"という項目が接触日の情報を持っている
https://twitter.com/info_kvaluation/status/1535496027733565440
と別のところで教えていただきました。これを知っているだけでも、exposure_data.jsonファイルを肉眼で見た時に"DateMillisSinceEpoch"の項目が何個見えるかで接触の回数がわかるのですね。

引用のツイートには"DateMillisSinceEpoch"の数値をExcelを使って日付に直す方法が紹介されていましたが、実際にやってみると計算式を埋め込んだ2つ目のセルの書式設定を「日付」と指定しておく必要がありました。

**Comment by keiji** [comment]
本日（13日）の公開割合はGoogle PlayならびにApp Storeともに20％です。

**Comment by keiji** [comment]
本日（14日）の公開割合はGoogle PlayならびにApp Storeともに50％です。
（この投稿も自動化できないかと思ってしまう。

**Comment by keiji** [comment]
COCOA v2.0.1の公開割合は、Google PlayならびにApp Storeともに100％です。

**Comment by b-wind** [comment]
一応。 手持ちの Android 機複数台で v2.0.1 へのアップデートが確認出来ました。

完全に自動アップデートに任せている人に行き渡るにはもうちょっとかかる感じでしょうか。

**Comment by daisuke-nogami** [comment]
過去のデータをみると、Androidの場合は、1日で5割以上、3日で7~8割、1週間で9割以上に浸透していました。
v2.0.0のローリングアップデートの時には、公開割合が100%になる日の時点で2割以上に浸透済みで
1日早く進行したような感じですので、今回も週末にはほとんど行き渡る人には行き渡ると思います。

**Comment by keiji** [comment]
`version.json`が更新され、開発チームよりリリース作業が完了したとの報告を受けました。

本チケットはクローズします。何かあればDiscussion（ #1032 ）か、別途Issueを作成してください。
