### ISSUE TITLE
「アプリに関するお問い合わせ」ページの題名が正しく表示されない

### ISSUE THREAD

**Issue by Takym** [cocoa-mhlw/cocoa#108]
## 不具合の内容
「アプリに関するお問い合わせ」ページの題名がメニューにおいて「アプリに関するお」と表示されます。画面幅が狭いデバイスでは「お問い合わせ」まで描画されません。

## 再現手順

1. 左上の「三」をタップします。
2. メニューにてお問い合わせページを探します。
3. ページの題名が省略されます。

## 期待される挙動
「アプリに関するお問い合わせ」の途中で改行するか、メニュー内では「お問い合わせ」と表示します。

## スクリーンショット

![image](https://user-images.githubusercontent.com/15681312/113631948-33eef280-96a5-11eb-8fe7-0f1794769408.png)

## 動作環境

- デバイス：iPhone 7
- OS：iOS
- バージョン：1.2.2

**Comment by keiji** [comment]
ありがとうございます。ドロワーメニュー内の表記は「お問い合わせ」が良いと思います。念のため調整に2, 3日お時間をいただければと思います。

**Comment by keiji** [comment]
「アプリに関するお問い合わせ」を「お問い合わせ」に、
「アプリの設定」を「設定」に変更と言うことで話がまとまりました。

welcome contributionです。よろしくお願いします。
