### ISSUE TITLE
濃厚接触者の待機期間変更の影響を検討する

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#1088]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

濃厚接触者の待機期間が見直されたのでCOCOAへの影響を確認する。

事務連絡
令和４年３月１６日
令和４年７月 22 日一部改正
B.1.1.529 系統（オミクロン株）が主流である間の当該株の特徴を踏まえた感染者の発生場所毎の濃厚接触者の特定及び行動制限並びに積極的疫学調査の実施について

https://www.mhlw.go.jp/content/000968056.pdf

> 濃厚接触者の待機期間の見直しを行いました。なお、令和４年７月 22 日の改正による濃厚接触者の待機期間の見直し（７日間から５日間への短縮等）については、令和４年７月 22 日より適用となり、同日時点で濃厚接触者である者にも適用いたします。

## 解決策についてお書きください / Describe the solution you'd like

「7日間は」を「5日間は」に変更する必要がある？

![Screen Shot 2022-06-21 at 17 20 11](https://user-images.githubusercontent.com/932136/180599174-176821ab-b137-4932-ad7d-83608ab1308f.png)

## その他 / Additional context

接触通知の表示に影響するかも要確認。

----
Internal IDs:
- N/A

**Comment by daisuke-nogami** [comment]
こちらの変更は不要です（変えるべきではありません）。

この期間短縮は、感染を与えるリスクがある期間が縮まったことを意味しません。
「社会機能維持のために、強制的に自宅待機となる期間が長いと困るので、
　感染を与えるリスクがある期間は普段以上に感染予防に気を遣うので、
　普通に活動できるようにして欲しい」
という要望に応えるためのものです。

ですので、待機期間を説明した直後にも、従前と同様の7日間の配慮を求める記述が
そのまま残されています。

> ・上記いずれの場合であっても、７日間が経過するまでは、検温など自身による健康状態の確認や、高齢者や基礎疾患を有する者等感染した場合に重症化リスクの高い方（以下「ハイリスク者」という。）との接触やハイリスク者が多く入所・入院する高齢者・障害児者施設や医療機関（以下「ハイリスク施設」という。）への不要不急の訪問（※３）、感染リスクの高い場所の利用や会食等を避け、マスクを着用すること等の感染対策を求めることとする。

> 事業所等で感染者と接触（※）があった者は、接触のあった最後の日から一定の期間（目安として７日間）はハイリスク者との接触やハイリスク施設への訪問、不特定多数の者が集まる飲食や大規模イベントの参加等感染リスクの高い行動を控えるよう、事業所内に周知すること。また、症状がある場合には、速やかに医療機関を受診することを促すこと。

**Comment by keiji** [comment]
こちら「変更なし（影響なし）」となったのでクローズします。
