### ISSUE TITLE
becon.accuracy

### ISSUE THREAD

**Issue by KitKuru** [cocoa-mhlw/cocoa#11]
https://qiita.com/shu223/items/7c4e87c47eca65724305#accuracy%E7%B2%BE%E5%BA%A6%E3%81%AE%E8%A8%88%E7%AE%97
これを見ると

beaconservice.csの
                        data.MinDistance = (beacon.Accuracy < data.MinDistance ? beacon.Accuracy : data.MinDistance);
                        data.MaxDistance = (beacon.Accuracy > data.MaxDistance ? beacon.Accuracy : data.MaxDistance);
は誤解してると心配しますが

**Comment by zipperpull** [comment]
#34 に別途 Issue を立てさせていただきましたが、BeaconService.cs は現状プロジェクト構成に含まれていないファイルで使用されていないと思います

**Comment by keiji** [comment]
https://github.com/cocoa-mhlw/cocoa/blob/20f3e8c570175f1ad693ccbf90ef74aff22de7fd/Covid19Radar/Covid19Radar.Android/Services/UnUsed/BeaconService.cs

https://github.com/cocoa-mhlw/cocoa/blob/20f3e8c570175f1ad693ccbf90ef74aff22de7fd/Covid19Radar/Covid19Radar.iOS/Services/UnUsed/BeaconService.cs

この２つについてはUnUsedなのでCOCOAでは使用していませんね。使っていないファイルを消す件に関しては対応が必要として、このIssueはCloseしますね。
