### ISSUE TITLE
全数届出見直しのCOCOAへの影響を検討する

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#1101]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

新型コロナ 専門家の有志が今後の医療や保健所の対応で提言
https://www3.nhk.or.jp/news/html/20220802/k10013747591000.html

> 新型コロナウイルス対策にあたる専門家の有志は、より多くの医療機関で入院できるようにすることや、保健所や医療機関の負担になってきた感染者の全数把握を段階的に見直すことなど、今後の医療や保健所の対応についての提言をまとめました。

現時点では専門家有志による提言の段階で、方針として決定したわけではないと理解している。
その上で、今後、全数把握の見直しがされた時にCOCOAへの影響はどのようなものか。検討しておく必要があると考える。

## 解決策についてお書きください / Describe the solution you'd like

COCOAの機能を停止する（一時停止・または完全停止）。

COCOAは、陽性者の全数把握を根拠に提供されていると理解している。

全数把握が見直されると、そもそもHER-SYSへの発生届けの提出が行われず（限定的になる？）、接触通知APIの仕組みそのものが成立しなくなる。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

COCOAの機能を継続する。

接触通知APIの仕様上は、自己検査キットなどの結果をSelf Test扱いで登録することが可能。

しかしながら、Self Testでの登録は現時点でもやっていないことなので、全数把握の見直しが出ている局面で、敢えてそちらに進むことは厳しいのではないかと、個人的には感じている。

## その他 / Additional context

世界各国の接触通知アプリの運用状況については、次のDiscussionにあります。
https://github.com/cocoa-mhlw/cocoa/discussions/1000

**Comment by keiji** [comment]
停止または一時停止するとしたら、こんな感じを想定。

## アプリ側
 * COCOAアプリをアップデートして、「サービスを停止しました」「サービスを一時的に停止しています」と表示するようにする
   * 画面には停止（または一時停止）に関する詳細や、ウェブサイトへのリンクを付けるなど、丁寧に説明する
   * 可能であれば、通知してでも利用者にお知らせしたい（ただ、COCOAから通知するだけで利用者を驚かせることもあるので要検討
 * バックグラウンドでの接触確認は停止する
 * 接触通知APIの動作を停止する

## サーバー側
 * 陽性情報登録は受け付けるがデータベースには保存しない
     * 前のバージョンの利用者が陽性情報を登録したケースに対応するため
     * HER-SYSから処理番号の発行が停止されれば、1週間ほどでValidな陽性登録自体が存在しなくなる想定
 * 診断キーの生成を停止する
     * 停止から14日後には空のリストを配信することになる想定
 * サーバー自体は廃止せず保持する（COCOAからアクセスしたときにサーバー自体は存在する状態にする

**Comment by daisuke-nogami** [comment]
> COCOAは、陽性者の全数把握を根拠に提供されていると理解している。

根拠ではないですが、陽性登録を希望する人すべてに処理番号を発行できている前提が、
HER-SYSに全ての陽性者の電話番号が登録されていることにあります。

> 全数把握が見直されると、そもそもHER-SYSへの発生届けの提出が行われず（限定的になる？）、
> 接触通知APIの仕組みそのものが成立しなくなる。

HER-SYSへの電話番号が入力された発生届を前提としてCOCOAが運用されているため、
発生届の入力が減ると、陽性登録を行える人が限定されてしまう、というのが精密な理解です。

ですので、

- 全数報告義務が続いても電話番号が登録されなければ、全ての希望者へのCOCOAの処理番号の提供ができない
- 法令上の「発生届を全数報告すること」の義務がなくなっても、陽性者の電話番号がHER-SYSに入力される限りにおいては、全ての陽性者に対して処理番号が自動発行される
- 電話番号を入れる入れないは、まだ揺らぎがある（やっぱり入れてもらいます、となり得る）ことも理解して、ステップを行き来できる状況にするのが望ましい

という状況であることを理解する必要があります。

**Comment by keiji** [comment]
新型コロナ全数把握見直し 入国時の陰性証明も免除へ 岸田首相 - NHK Web
https://www3.nhk.or.jp/news/html/20220824/k10013785011000.html

> この中で、岸田総理大臣は、医療機関に対し、感染者の氏名や生年月日などの詳細な報告を求めている全数把握について「自治体の判断で、患者の届け出の範囲を、高齢者、入院を要する者、重症リスクがあり治療薬投与等が必要な方などに限定することを可能とする」と述べ、全数把握を見直し、自治体の判断で報告の対象を、高齢者や重症化リスクが高い人などに限定できるようにする方針を明らかにしました。

全数把握が見直されることが「HER-SYSに陽性者全員の情報を入力しない自治体がある」ということになるとすれば、接触通知機能への影響は大きいと考えます。

少なくともCOCOAは、地域や自治体に応じて稼働する・しないが切り替えられるようなシステムではないことを確認した上で、影響を確認して、方針を定める必要がありますね。

現時点で、全数把握の見直しがいつ、どのような形で行われるのか分かりませんが、準備は必要と言うことで。

**Comment by keiji** [comment]
岸田首相 新型コロナ 感染者の全数把握見直し 今後全国一律で
https://www3.nhk.or.jp/news/html/20220827/k10013790701000.html

> 新型コロナ感染者の全数把握の見直しをめぐり、岸田総理大臣は、いずれは全国一律の措置に移行するとしたうえで、報告の対象外となる自宅療養者への支援体制などの準備状況を見極めて移行時期を判断する考えを示しました。
> （中略）
> これについて岸田総理大臣はオンラインで記者団の取材に応じ「見直しはウィズコロナに向けた新たな段階への移行策の1つとして進めるもので、全国一律で導入することを基本としている」と述べ、いずれは全国一律の措置に移行する方針を示しました。

**Comment by keiji** [comment]
本日、河野大臣の閣議後会見においてCOCOAの機能停止する方針について発表されました。

v2.1.0はリリースを中止して、以後、COOCAの機能停止版の検討および開発を行います。

**Comment by daisuke-nogami** [comment]
補足です。
具体的なやり取りは、まだデジタル庁に記者会見の議事録・動画が上がっておらず確認できておりませんが、先ほど、以下のような連絡を受けました。

閣議後記者会見において、記者からの「全数届出ルールが変わったあとのCOCOAへの影響」に関する質問に答える形で、「全数届出ルールが変わったあとにCOCOAは機能停止に向かうこと」「利用者には何らかのアンケートを依頼することになるのでアプリはそのままにしてほしいこと」「様々な対応が必要なのでスケジュールを含めた詳細はしばらく待ってほしいこと」が示された。

これを踏まえ、アプリ上の対応の準備を進めるため、Githubへの投稿とIssue起票が行われています。
なお、COCOAの方針に絞った説明ではなかったため、この質疑の表現では伝わりきらない点がありますが（例：消さない理由はアンケートを依頼するためだけではない、等）、アプリ上の対応について、順次 #1132 に紐付ける形で起票されるIssueをご確認いただけますと幸いです。
