### ISSUE TITLE
COCOAを機能停止する

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#1132]
本日、河野大臣の閣議後会見においてCOCOAの機能停止する方針について発表されました。

v2.1.0はリリースを中止して、以後、COOCAの機能停止版の検討および開発を行います。

_Originally posted by @keiji in https://github.com/cocoa-mhlw/cocoa/issues/1101#issuecomment-1244830878_

詳細は別途更新します。

接触アプリ「ココア」停止とデジタル相
https://nordot.app/942262545987977216

> 　河野太郎デジタル相は13日の記者会見で、新型コロナウイルス感染者の全数把握簡略化を受けて、感染者との接触を通知する国のアプリ「COCOA（ココア）」は機能停止になると明らかにした

----

また、機能停止に向けた作業詳細についてはIssueの形で追加します。

**Comment by daisuke-nogami** [comment]
補足です。
先ほど、以下のような連絡を受けました。

> 閣議後記者会見において、記者からの「全数届出ルールが変わったあとのCOCOAへの影響」に関する質問に答える形で、「全数届出ルールが変わったあとにCOCOAは機能停止に向かうこと」「利用者には何らかのアンケートを依頼することになるのでアプリはそのままにしてほしいこと」「様々な対応が必要なのでスケジュールを含めた詳細はしばらく待ってほしいこと」が示された。

（記者会見の動画が公開されましたので、大臣の文言を確認しましたが、修正すべき齟齬はありませんでしたので連絡内容は更新しませんでした）
https://twitter.com/dnogami_ex_dena/status/1569584162511925248

これを踏まえ、アプリ上の対応の準備を進めるため、Githubへの投稿とIssue起票が行われています。

なお、COCOAの方針に絞った説明ではなかったため、この質疑の表現では伝わりきらない点がありますが（例：消さない理由はアンケートを依頼するためだけではない、等）、アプリ上の対応について、順次起票されるIssueをご確認いただけますと幸いです。

なお、公表の経緯からわかるように、現時点で厚生労働省からはCOCOAに関する発表は、こちらの事務連絡の最終ページの説明のみとなっております。

With コロナの新たな段階への移行に向けた全数届出の見直しについて
https://www.mhlw.go.jp/content/000988989.pdf
> （２）接触確認アプリ（COCOA）について
> 接触確認アプリ（COCOA）は、発生届が出された方を対象に、陽性者に対して登録に必要な処理番号が発行される仕組みとなっている。
> 全数届出の見直しにより、発生届の届出対象となる方が限定されるため、見直し後は、発生届が出された者のみに対し、処理番号が発行され、陽性登録が可能となる。発生届を出さずに健康観察等を行う場合、処理番号は発行されない。

**Comment by keiji** [comment]
機能停止版は、大きく次の機能を搭載しようと検討しています。

 1. COCOAが終了したことを通知で利用者に知らせる機能
 2. 接触通知APIを明示的に停止する機能
 3. バックグラウンドでの接触確認処理を停止する機能
 4. 機能停止時に、利用者の接触情報（データ保存で出力されるもの）を提出してもえないか聞く（任意・スキップ可能）
 5. 機能停止時に、利用者の合意の元、利用者調査に回答してもらえるか聞く（任意・スキップ可能）

## 停止処理について

1, 2, 3は、利用者に「COCOAが停止した事実を知らせる」ために必要と考えています。
起動したら「COCOAは終了しました。アンインストールしてください」とだけ表示される止め方だと、多くの問い合わせの発生が発生すると考えています（停止の画面にいろいろ説明を書いても、利用者層のばらつきを考えると厳しいものがある）。
少なくとも停止から一定期間は、周知する期間が必要と考えています。

## アンケート（利用者調査のお願い、および接触情報の提出のお願い）について

4, 5は、任意であり、4, 5をスキップしても、利用者は停止処理（1, 2, 3）を実行できます。

これらは機能停止とは関係なく、今後「COCOAとはなんだったのか」を検討するときに欲しいのでデータを集めたいという意図です。
COCOAの停止処理を完了したあとは、利用者調査以外の他のアンケートが表示されることはありません。

バックグラウンドとして、COCOAがどの程度動いていたのか、ぼくらは知るすべを持ちません。プライバシーに最大限配慮した設計であるが故に「ちゃんと動いているの？」という質問に答えられませんでした。

接触データ自体に、利用者や利用者が接触した陽性者を特定可能な情報は含まれていない認識です。
また、本来であればアプリを運用し、開発を継続する上で最低限のデータの解析は不可欠であると個人的には考えています（個人の考えです）。

利用者のプライバシーを侵害しない形で情報を取得して、きちんとした形で提供する。このことはCOCOA2の開発当時からDiscussion #532 などでは検討してきました。そして、v2.1.0 でようやく「通知の発生イベントを取得する（利用者の合意の元通知が発生したことをサーバー側に送信して・集計する機能）」が実現できる運びとなりました（停止に伴い、v2.1.0はリリースされないわけですが）。

さて、COOCAの機能を停止して終わらせるのではなく、COCOAに関する反省と、次に活かす（つなげる）ための知見をまとめよう。という話が出ています。

今後COCOAに関するこれまでを検討をする上で「どういう人たちがCOCOAを使っていたのか」はデータとして欲しい。また「実際にどのような接触が発生していたのか」もわかれば、今後公衆衛生の改善を考える上で役に立つのではと考えています（これはぼくも同じ考えです）。

その上で、利用者から情報をいただく以上、プライバシーに関する懸念や解決すべき課題は当然に存在する認識です。
プライバシーに関する懸念が払拭できなければ4, 5については搭載しないという判断も十分にあり得ます。
（そうなれば、定量的な情報はほとんど得られなくなりますが、可能な範囲で今後につなげる努力をしたいと考えています）。

もちろん、COCOAの今後についてGitHubコントリビューターの皆様からのご意見も重要です。
なにかお考えや懸念等あれば、こちらのIssueのコメントでもいいですし、これから個々のIssueを作りますので、そちらにコメントをしていただければと思います。

よろしくお願いいたします。

**Comment by daisuke-nogami** [comment]
有山さん整理の4.に対応するIsssueとして#1138 が、5.に対応するIssueとして #1138 + #1140 を起票しました。
1. ～ 3. や、その他のご意見があれば遠慮なくいただければと思います。

**Comment by daisuke-nogami** [comment]
サーバーの撤去、アプリの公開停止など、全ての機能停止の処理が完了しましたのでCloseします。
