### ISSUE TITLE
iOS 設定アプリから COCOA を開くと使用履歴がリセットされる

### ISSUE THREAD

**Issue by hsm-hx** [cocoa-mhlw/cocoa#118]
## 不具合の内容 / Describe the bug

iOS 設定アプリから COCOA を開くと使用履歴がリセットされ、使用開始日が上書きされてしまう。

## 再現手順 / Steps to reproduce

1. iOS から通知される「月ごとのアップデート」を開く
2. iOS 設定アプリ中の「接触通知をAppで表示」をタップする
3. アプリが初期化され、インストール時の状態に戻る(使用開始日が現象発生日に更新されます)

## 期待される挙動 / Expected behavior

iOS 設定アプリ中の「接触通知をAppで表示」をタップしてもアプリの使用履歴が消去されないことが望まれるかと思います。

## 動作環境 / Environments

- デバイス： Apple iPhone SE 第2世代
- OS：iOS 14.4.2
- バージョン： COCOA 1.2.2

## その他 / Additional context

2回ほど同じ動作を行い、どちらも以上のような挙動になりました。
動作環境については起票日現在で確認した情報を記載しておりますが、最後に上記動作を行ったのが 2021/02/18 でしたので(利用開始日から判断)、恐らく現象発生時の動作環境は同デバイスで利用可能な2ヶ月前の最新バージョンだったかと思います。

**Comment by keiji** [comment]
ありがとうございます。
「接触通知をAppで表示」経由でアプリを起動すると使用履歴がリセットされる（ユーザーデータが消えている？）現象ですね。

2ヶ月前と言うことは、ちょうど2月18日にリリースされたv1.2.2でユーザーデータが消えてしまう不具合は修正済みという認識ですが、その経路でのアプリの起動をぼくが試したことがないので、ひとまず手元のiPhoneで再現試験してみます。

**Comment by keiji** [comment]
実験をしていて、使用開始日がリセットされ続ける現象（ #124 ）にはまってしまい確認が遅くなりました。

v1.2.2をインストールして初期設定後、端末の日付を変えて使用日数が更新された状態にしてから、再現手順を実行しましたが、利用履歴がリセットされる現象は確認できませんでした。

v1.2.1以前では確かに使用履歴がリセットされるバグがあったのですがv1.2.2で修正済みという認識です。今回ぼくが踏み抜いた #124 と同じ状態になっていた可能性がありますが、端末ロケールの変更などはしていませんか？

**Comment by hsm-hx** [comment]
ご確認ありがとうございます！

今最新バージョン確認の上再度確認してみたところ、起票させていただいた現象については解消されておりました。
ご指摘いただいた通り現象発生前後に端末ロケールを変更した覚えがありますので、アプリの起動経路ではなくロケール設定の問題かもしれません。
当Issueについては解決ということで問題ありません(現象報告が不適切で申し訳ありません……！)。お忙しい中ご丁寧な対応ありがとうございます 🙇

**Comment by keiji** [comment]
不適切なんてとんでもないことです。確認をきっかけに #124 を見つけることができました。
今後も気になったことがあればどんどんIssueで教えてください。
