### ISSUE TITLE
接触確認アプリが利用するTEKの脆弱性について

### ISSUE THREAD

**Issue by moonmile** [cocoa-mhlw/cocoa#12]
既に厚生労働省にメール済みですが、記録として issue にも上げておきます。

※悪意利用の可能性があるので、詳細は伏せます。

**Comment by moonmile** [comment]
- [https://github.com/google/exposure-notifications-internals/issues/19 It's risk that it distributes camouflaged RPIs. · Issue #19 · google/exposure-notifications-internals]

Android のほうは、公開されているコードが実機とは異なる可能性が高いので、対処済みではないかという結論です。

**Comment by b-wind** [comment]
@keiji @halsk @heykuro こちら、詳細は伏せられているので検討する場を別途設けるか、検証チームで引き取って頂くのが妥当では無いかと思います。

**Comment by moonmile** [comment]
これは、RPI の時刻を詐称した場合、EN API を騙して大量の陽性者を生成できるのではないか？という懸念で当時 up したものです。
Google の EN 内では、受信時刻との検証も行っている（らしい）とのことなので、クローズしても大丈夫です。

**Comment by moonmile** [comment]
具体的には、ここの話です。

[It's risk that it distributes camouflaged RPIs\. · Issue \#19 · google/exposure\-notifications\-internals](https://github.com/google/exposure-notifications-internals/issues/19)

**Comment by keiji** [comment]
そうですね。ぼくの理解だと診断キーサーバーから診断キー（TEK）と合わせて影響のある日時帯も配信していて、判定時にはその日時帯に生成されうるRPIであるかを検証しているという認識です。

本Issueはcloseしますが、脆弱性に関する情報は、なかなか表だって相談できる内容でもないと思いますので、専用の通報窓口を設けることについて検討した方がいいかもしれませんね。

**Comment by heykuro** [comment]
(close済みですが、、)

@b-wind さん、すみません。こちら返答できていませんでした。
脆弱性関連課題は @keiji  さんも書かれているようにこちらで議論するのも限界があるのと、一般の問い合わせ窓口へご連絡いただくというのも少し違うと思いますので、今後の連携プロセスについては考えますね(内部の課題とします)。

**Comment by NewGyu** [comment]
ひっそりとFAQに掲載されていました。
https://github.com/google/exposure-notifications-internals/blob/main/en-risks-and-mitigations-faq.md#rpi-spoofing-using-reported-diagnosis-keys
