### ISSUE TITLE
[Android] スクリーンリーダーで「陽性者との接触を確認する」ボタンが正しく読み上げられない

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#125]
## 不具合の内容 / Describe the bug

ユーザー補助（視覚補助）のスクリーンリーダー（TalkBack）を有効にしたとき「陽性者との接触を確認する」ボタンが「button exposures ボタン」と読み上げられる。

iOSのスクリーンリーダーでは、正しく「陽性者との接触を確認する」と読み上げられる。

## 再現手順 / Steps to reproduce

1. '設定' に行き、
2. 'ユーザー補助' をタップして、
3. 'TalkBack' をタップして、
4. 「TalkBackの使用」をタップして有効にする。
5. COCOAを起動して、
6. 「陽性者との接触を確認する」ボタンをタップすると、
7. 「button exposures ボタン」と読み上げられる。

## 期待される挙動 / Expected behavior

「陽性者との接触を確認する ボタン」と読み上げられる。

## スクリーンレコード / Screen Record

https://user-images.githubusercontent.com/932136/115690199-c545b080-a397-11eb-8dbb-4b562caf0bf1.mp4

## 動作環境 / Environments

- デバイス： Pixel 3
- OS：Android 12 Developer Preview 3（他のバージョンでも発生する可能性がある
- バージョン：1.2.3

----
Internal Tracking ID: BUG 2107
Internal Tracking ID: Product Backlog Item 2106:

**Comment by i-maruyama** [comment]
https://github.com/cocoa-mhlw/cocoa/blob/a41c653e8430175899dcbefcec1c4db12ce09e07/Covid19Radar/Covid19Radar/Views/HomePage/HomePage.xaml#L52-L56

以上のコードの AutomationId を読み上げているようです。AutomationProperties.HelpText を設定する必要があるのではないでしょうか？
参考： https://docs.microsoft.com/ja-jp/xamarin/xamarin-forms/app-fundamentals/accessibility/automation-properties

こちらは再現環境がなく試していませんが、同様の記述した以下のようなページ(初期起動からの説明ページ)でも、起こるかもしれません。
https://github.com/cocoa-mhlw/cocoa/blob/a41c653e8430175899dcbefcec1c4db12ce09e07/Covid19Radar/Covid19Radar/Views/Tutorial/TutorialPage1.xaml#L97-L102

ご参考まで。

**Comment by keiji** [comment]
ありがとうございます。

'AutomationId' が設定されている部品に 'AutomationProperties.HelpText' を設定していくのが良さそうですね。

もっと言えば、AutomationIdがなくても、すべての部品にHelpTextを付けていくのが確実かもしれません（文言変更時のメンテナンス漏れが心配ではありますが、リソース共通ならそれほどリスクも高くないかな？）

**Comment by tatsu-jp** [comment]
この件を少し調査していたので参考までに情報共有しておきます。

https://docs.microsoft.com/ja-jp/xamarin/xamarin-forms/app-fundamentals/accessibility/automation-properties の**重要**に記載されている仕様により、単純にHelpTextを設定すると自動テストが上手く動かなくなる可能性がありますので、UIテストも考慮した設計にする必要がありそうです。

あと、シミュレータでTalkbackを動作させていて以下が気になりました。
(実機では結果が異なるかもしれません)

- メニュー/ヘルプのリスト項目は2度読み上げられる(Automation IDを2回利用しているからだと思われます)
- メニュー/ヘルプのリスト件数とTalkBackの内容が一致しない（ユーザー視点で）
  - メニュー：7個と読み上げられる（メニュー上は5個しかなく、ユーザーはNo.1とNo.7を見つけられない）
  - ヘルプ：6個と読み上げられる（メニュー上は4個しかなく、ユーザーはNo.1とNo.6を見つけられない）
 →List viewの個数を全てカウントしているような振る舞いに見えます(ListViewの先頭の定義とListView.Behaviorsを含めると個数が合う)。

### 参考
＃すみませんが、エンコードが良くないので音割れしてます。ご注意ください。

#### ＜メニューテスト＞
https://user-images.githubusercontent.com/29404405/118399090-66bdda80-b696-11eb-856a-82968965dec5.mp4

#### ＜ヘルプメニューテスト＞
https://user-images.githubusercontent.com/29404405/118399099-71786f80-b696-11eb-8389-d1c482d2c956.mp4


よろしくお願いします。
