### ISSUE TITLE
アプリを開いたとき（復帰したとき）に使用日数が更新されないことがある

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#126]
## 不具合の内容 / Describe the bug

COCOAを開いたときに、本来は更新されているはずの使用日数が正常にカウントアップされていないときがある。

## 再現手順 / Steps to reproduce

1. COCOAを起動して使用日数を確認する
2. ホームボタンを押すなどしてホーム画面へ遷移する（バックグラウンドへ
3. 日付が変わったときにCOCOAを起動する。このとき、スプラッシュスクリーンが表示されないこと（バックグラウンドからの復帰）を確認する
4. 使用日数がカウントアップされていない

## 期待される挙動 / Expected behavior

アプリを開いたときに、使用日数が更新されているタイミングであれば表示に反映する

## 動作環境 / Environments

- デバイス：iPhone 8で確認しているが、他のiOS端末やAndroid端末でも発生しうる
- OS：iOS 14.4.2で確認しているが、他のバージョンやAndroidでも発生しうる
- バージョン：1.2.2 および 1.2.3

----
Internal Tracking ID: BUG 1795

**Comment by b-wind** [comment]
ページの初期化時に固定値を設定しているので、日付が変更になった後再初期化が走らない限り更新されないと言う事でしょうか。

https://github.com/cocoa-mhlw/cocoa/blob/e106594fb8359f79f3fdb19cac4f26b800245f8f/Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs#L52-L53

**Comment by b-wind** [comment]
v1.2.4 にて対応されたように思います。

https://github.com/cocoa-mhlw/cocoa/blob/8052045323e6a54826f04d3d2b705cf775736e1f/Covid19Radar/Covid19Radar/ViewModels/HomePage/HomePageViewModel.cs#L49-L60
