### ISSUE TITLE
バックグラウンドタスクが端末の消費電力機能によりユーザーの想定した以上に制限されないようにする

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#127]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

バックグラウンド実行が、端末の消費電力機能により制限されて起動しない。起動してもキャンセルされるという事象が確認されている。

## 解決策についてお書きください / Describe the solution you'd like

本Issueでは、同じ目的の複数の取り組み（Issue）をまとめていく。

 - [ ] ~~電池の最適化ホワイトリストへの登録 （導線を作るかの検討 #123 ）~~
 - [x] Force-stop handling（ #136 ）
 - [x] WorkManagerライブラリのアップデート（ #144 ）
 - [ ] ~~Foreground Service化~~
 - [ ] ~~WorkerのForeground化~~

## その他 / Additional context

ユーザーの期待に反しない限りは、できることはすべて検討して、効果が見込めるものを実行していきたい。
----
Internal IDs:
- Feature 1515

**Comment by kmuto** [comment]
最新Cocoaバージョンで5月11〜14日の間に止まっていることに気付きました。

- HUAWEI P20
- Android 10 (EMUI 10.0.0)
- 期間中に 端末は頻繁に常用利用、端末再起動せず、Cocoaは明示的に開かず(明示killもせず)

省電力設定で、Cocoaについては「手動で管理」
- 自動起動 有効
- 他のアプリによる起動 有効
- バックグラウンドで実行 有効

画面については
https://twitter.com/kmuto/status/1393362947661975556
のスレッドにて。

**Comment by i-maruyama** [comment]
上コメントについては、ログで "Info","Start","FetchExposureKeyBatchFilesFromServerAsync" が無ければバックグラウンドが停止中、という判定で良いと思いますので、ログが取れる人は、確認されると良いと思います。

ちなみに Debug_Mock (PR #191), 実機 Aquos sense3lite (Android 10 、長エネ設定・・・） でも再現しました。  BackgroundFetchWorker.DoWork() のルーチンにも入らないようです。 Debug なら 6時間を１５分まで短くできます。

（ #136 で治ると良いですね。）

**Comment by keiji** [comment]
@kmuto 最近はHUAWEI P20、バックグラウンドタスクの調子はいかがですか？

**Comment by kmuto** [comment]
5/28以来毎日稼働しているようです。
途中で1度アプリを開いたことがあったので、「長期に触らない」状態で見ないとはっきりとは言えないですが。

**Comment by keiji** [comment]
おかげさまでAndroid版でのバックグラウンドでの接触確認は安定して動作しているという認識です。
Descriptionに記載したその他の施策については実施せずとして、今週末を目処に本Issueはクローズする予定です。
