### ISSUE TITLE
サードパーティライセンスを確認して最新に反映する

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#130]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

#129 に関連して、今では使っていなさそうなライブラリもサードパーティライセンス一覧にある。

## 解決策についてお書きください / Describe the solution you'd like

[サードパーティライセンス](https://github.com/cocoa-mhlw/cocoa/blob/master/COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md)を確認して整理する。

 * 使用しているのに掲載されていないライセンス（追加候補）
   * CommonServiceLocator ( #129 )
 * 使用していないのに掲載されているライセンス（削除候補）
   * AndroidAltBeaconLibrary
   * SQLite-net

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

やる。

## その他 / Additional context

現在のCOCOAが表示するライセンス一覧はウェブサイト上のものなので、そちらと同期する必要がある。

 * https://covid19radarjpnprod.z11.web.core.windows.net/license.html

----
Internal IDs:
- Prepare Item 2943

**Comment by keiji** [comment]
Font Awesome Freeのライセンスに文字化け有り。要調整。

https://github.com/cocoa-mhlw/cocoa/blob/master/COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md#font-font-awesome-free

**Comment by keiji** [comment]
Noto Sans CJK JP

> This license is copied below,

とあるが、ライセンスの表記がない。

https://github.com/cocoa-mhlw/cocoa/blob/master/COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md#font-font-awesome-free

**Comment by keiji** [comment]
Roboto 

https://github.com/cocoa-mhlw/cocoa/blob/master/COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md#font-font-awesome-free

Apache License 2.0である表記はもう少し詳しい方がいいかも。
https://www.apache.org/licenses/LICENSE-2.0#apply これを書くとか。

**Comment by keiji** [comment]
Material Design Icons

> This license is copied below,

とあるが、ライセンスの表記がない。

https://github.com/cocoa-mhlw/cocoa/blob/master/COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md#font-font-awesome-free

**Comment by keiji** [comment]
Building an App to Notify Users of COVID-19 Exposure

> Copyright Â© 2020 Apple Inc.

©の前にtypoあり。

https://github.com/cocoa-mhlw/cocoa/blob/master/COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md#sample-code-building-an-app-to-notify-users-of-covid-19-exposure

**Comment by keiji** [comment]
[COCOAが表示しているライセンス一覧](https://covid19radarjpnprod.z11.web.core.windows.net/license.html)に、フォント系のライセンス表記が含まれていない。追加の必要あり。

**Comment by b-wind** [comment]
> Noto Sans CJK JP
>> This license is copied below,
>
> とあるが、ライセンスの表記がない。

一つ上の行に、「SIL Open Font License, Version 1.1.」の記述があります。

**Comment by b-wind** [comment]
> Material Design Icons
> 
> > This license is copied below,
> 
> とあるが、ライセンスの表記がない。

コメントの意味がよく分かりませんが、

> Copyright (c) 2014, Austin Andrews (http://materialdesignicons.com/), with Reserved Font Name Material Design Icons.

こちらの物をコピーしてきているようです。


ICON/FONT/Code でライセンスは分かれていますが、 ICON/FONT に関しては Apache 2.0 で良い様です。
CODE はフォントファイル作成等に使われている物なので、特にこちらで記述する必要は無さそうに見えます。


https://github.com/Templarian/MaterialDesign/blob/master/LICENSE

**Comment by keiji** [comment]
> 一つ上の行に、「SIL Open Font License, Version 1.1.」の記述があります。

ここで言う This license is copied below, と言うのは「ライセンス全文は以下に記載するよ」と言う意味であると理解してます。
実際、いくつかのサイトを見て回りましたがこの記述の後にライセンスの全文が記載されているので、それに倣った方がいいかなと思います。

 * https://mitene.us/oss_license
 * https://www.lego.com/en-at/legal/notices-and-policies/open-source/

**Comment by b-wind** [comment]
> ここで言う This license is copied below, と言うのは「ライセンス全文は以下に記載するよ」と言う意味であると理解してます。
なるほど、現状の文章がおかしな事になっていると言うことですね。
全文引用する価値で異論ありません。

**Comment by b-wind** [comment]
> Font Awesome Freeのライセンスに文字化け有り。要調整。

参考までに原文（おそらく）のリンクを張っておきます。
https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt

**Comment by b-wind** [comment]
Android Beacon Library の copyright がハッキリしないのが気になってみたところ、

https://github.com/cocoa-mhlw/cocoa/blob/master/COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md#androidaltbeaconlibrary


LICENCE ファイルの下部に一応記述がありました。
https://github.com/AltBeacon/android-beacon-library/blob/0068dd2bcc1546c8d0eac21a42ebf48041a64aeb/LICENSE#L190-L191

私自身は、これを正規の copyright と読むべきか判断を保留しています。

**Comment by b-wind** [comment]
Android Beacon Library は以下のコミットで削除された後、使われて無さそうなのでライセンス表記も削除で良さそうです。

https://github.com/cocoa-mhlw/cocoa/commit/c9a03606b852a6c7a5e57222bc2f36bd4a2ce0fb#diff-ed4334d1a32586df68db843e3986da17d8f79ee28fcbe935dae8e1312c5aab04L85

**Comment by b-wind** [comment]
AndroidAltBeaconLibrary は当初から削除対象に入って居ましたね。失礼しました。

**Comment by b-wind** [comment]
COCOA に含まれる、Xamarin.ExposureNotification はオリジナルである MS の物から、COVID-19Radar Contributors による改変、及び v1.2.3 では COCOA Developer （仮）による改変が行われている物と認識しています。
それぞれに置いて著作権を放棄している等の扱いは見られないので、以下の様に併記するのが適切かと思います。


```
Xamarin.ExposureNotification

Copyright (c) Microsoft Corporation.
Copyright (c) 2020 COVID-19Radar Contributors.
Copyright (c) 2021 COCOA Developer.
```

正確な記述ルールと言うよりは、慣習として記述されるものと認識しています。

https://ja.stackoverflow.com/questions/3040/mit%E3%83%A9%E3%82%A4%E3%82%BB%E3%83%B3%E3%82%B9%E3%81%AE%E3%82%BD%E3%83%95%E3%83%88%E3%82%A6%E3%82%A7%E3%82%A2%E3%82%92%E3%83%95%E3%82%A9%E3%83%BC%E3%82%AF%E3%81%97%E3%81%9F%E5%A0%B4%E5%90%88%E3%81%AE%E3%83%A9%E3%82%A4%E3%82%BB%E3%83%B3%E3%82%B9%E8%A1%A8%E8%A8%98

**Comment by daisukekoba** [comment]
> 
> 
> > Material Design Icons
> 
> font ファイルを見る限り、http://materialdesignicons.com/ こちらの物をコピーしてきているようです。
> 
> > Copyright (c) 2014, Austin Andrews (http://materialdesignicons.com/), with Reserved Font Name Material Design Icons.
> 
> 直下にある Google の物や SIL Open Font Lisence に対する記述は謎です。個人的には無視して良さそうに思います。

私が記述を追加した後にライセンスが更新されたため、現状のライセンスと不一致になっています。
https://github.com/Templarian/MaterialDesign-Webfont/commit/ec5a9dd7973e19aed7484dfd338d1e2a93bd60b7

**Comment by daisukekoba** [comment]
> Noto Sans CJK JP
> 
> > This license is copied below,
> 
> とあるが、ライセンスの表記がない。

> Material Design Icons
> 
> > This license is copied below,
> 
> とあるが、ライセンスの表記がない。

これは私が間違えました。

> and is also available with a FAQ at: http://scripts.sil.org/OFL

のリンク先にライセンスが記述されていたため、英語をちゃんと読まずにライセンス本文を省略しました。

**Comment by b-wind** [comment]
@daisukekoba なるほど。確かにだいぶ記述が違いますね。
変更の経緯が分かると助かります。

**Comment by daisukekoba** [comment]
> Font Awesome Freeのライセンスに文字化け有り。要調整。

https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt ではなく https://github.com/FortAwesome/Font-Awesome/blob/master/README.md を参照したところ、元の文字がUnicodeの U+2014 (EM Dash) であったため文字化けしました。

**Comment by keiji** [comment]
@daisukekoba ありがとうございます。ライセンスは途中で変更されても遡及しない認識なので、ライセンスはファイルがバンドルされた時点の正しいものだという認識です。新しいライセンスが適用されたフォント・プログラムに置き換えることがあれば、そのタイミングでに新しいライセンスに置き換えるのが良いと思います。

ライセンス全文についてはお気になさらないでください。今回、フォントファイルのオフセット化を検討する過程で調べるまでは、ぼくも気づいていませんでしたので…。

**Comment by b-wind** [comment]
> ライセンスは途中で変更されても遡及しない認識


@keiji 別の話なのですが、これはわりと面倒な問題に思えていて今のサーバーのファイルを参照する形だとライブラリバージョン＆ライセンス形態が変更された後に旧バージョン利用者からは間違った情報が見えてしまうことになる気がします。


滅多に無いこととは言え、確実にするならライセンスファイル等々はアプリケーションに同梱して同バージョンの間は一貫して見られる形にする方が良い様に思えます。


WebView でローカルファイルを参照する方法はこちらに記載があります。
https://docs.microsoft.com/ja-jp/xamarin/xamarin-forms/user-interface/webview

**Comment by keiji** [comment]
そうですね。ライセンスは各バージョンに紐付くはずなので、外部に持っていると今後ますますややこしくなります。

v1.2.3でCommonServiceLocatorが追加されましたが、これも"v1.2.3から"のような記述にすることでいったんクリアしたという経緯があります。
そのこともあって、開発チームとも、ライセンス情報はローカルに持たせようみたいな話はしています（まだ具体的なスケジュールはでていませんが）。

Issue立ててWelcomeContributionにしてもいいかもしれませんね。

**Comment by b-wind** [comment]
Issue を建てるとすると、以下の３つの内容になりそうですね。（３つに分けるべきかは悩み中）

1.  COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md がメインの変更対象である事をどこかに明記する。
2. COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md から HTML を作成する方法（GitHub Actions 等で自動化出来るとベター）
3. COCOA から 2 で生成された HTML ファイルを参照するようにコード変更

**Comment by keiji** [comment]
ひとまず3についてIssueを立てるのがよいかと思います。

2については、しばらくの間、HTMLは手動更新でも大きな問題は起こらなそうな感じがします（ライセンス変更はそうそう頻繁に発生しないし、発生するとしたらオープンソースライブラリーの登録から自動的にライセンス拾う仕組みを入れた方が良さそう）。

1については #69 でカバーできそうですね。最終的にはCONTRIBUTIONのあたりを更新することになります。

**Comment by b-wind** [comment]
そう頻繁に起こることでは無いと言うのは同感です。

Issue の立て方についても異論はありません。

**Comment by b-wind** [comment]
１点訂正を。

上記で記した ２ の作業は細かく分けると、以下の様になるかと思います。


1. 主に利用ライブラリの増減が有った時、 COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md を更新
2. 次のリリース直前までに、内容を HTML 化し所定の場所に配置する


となるかと思います。
これらをすべてGitHub上でやってしまうのか、２は開発チームにお任せして良いのか、どちらでも構いませんが出来れば文書として残しておいた方が良いと思います。
Issue としては #69 で同様に纏められそうかなと。（開発チームとの相談は必要だと思いますが）

**Comment by tatsu-jp** [comment]
@keiji さん、
本件、対応内容の認識が以下で合っているかを確認させてください。

[サードパーティライセンス](https://github.com/cocoa-mhlw/cocoa/blob/master/COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md)に以下の修正を加える
-  Noto Sans CJK JPのライセンスを追加(https://github.com/cocoa-mhlw/cocoa/issues/130#issuecomment-826491540)
- Robotoのライセンスを変更(https://github.com/cocoa-mhlw/cocoa/issues/130#issuecomment-826492032)
- Material Design Iconsのライセンスを追加(https://github.com/cocoa-mhlw/cocoa/issues/130#issuecomment-826492354)
- Building an App to Notify Users of COVID-19 Exposureのtypo修正(https://github.com/cocoa-mhlw/cocoa/issues/130#issuecomment-826492636)

本Issueでは対応しない
- フォント系のライセンス表記が含まれていない件(https://github.com/cocoa-mhlw/cocoa/issues/130#issuecomment-826493436)
- Font Awesomeの件(https://github.com/cocoa-mhlw/cocoa/issues/130#issuecomment-828526273)
- #69 で対応予定の件(https://github.com/cocoa-mhlw/cocoa/issues/130#issuecomment-828513590)

**Comment by keiji** [comment]
はい。
挙げていただいている次の項目に加えて、「Font Awesomeの件 = Font Awesomeのライセンスが一部文字化けしている件」も対応したいと考えています。

サードパーティライセンス（COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md）に次の修正を加える

 -  Noto Sans CJK JPのライセンス全文を追加(https://github.com/cocoa-mhlw/cocoa/issues/130#issuecomment-826491540)
 - Robotoのライセンスを変更(https://github.com/cocoa-mhlw/cocoa/issues/130#issuecomment-826492032)
 - Material Design Iconsのライセンス全文を追加(https://github.com/cocoa-mhlw/cocoa/issues/130#issuecomment-826492354)
 - Building an App to Notify Users of COVID-19 Exposureのtypo修正(https://github.com/cocoa-mhlw/cocoa/issues/130#issuecomment-826492636)
 - Font Awesomeの件(https://github.com/cocoa-mhlw/cocoa/issues/130#issuecomment-828526273)

**Comment by tatsu-jp** [comment]
コメントありがとうございます。
土日で対応してPR出したいと思います。

よろしくお願いします。

**Comment by tatsu-jp** [comment]
@keijiさん、
対応する上で不明点があるので、以下を確認させてください。

#### Noto Sans CJK JP対応の件
1. アプリ([Web](https://covid19radarjpnprod.z11.web.core.windows.net/license.html))側ではライセンス所有者がGoogleとなっていますが、以下にはAdobeと記載あります。

```
https://github.com/googlefonts/noto-cjk/blob/main/README-third_party.md
The copyright is held by Adobe, while the trademarks on the names are held by Google.
```
  AdobeのサイトにもEULAがありました。
  - Noto Sans CJK JP Regular : https://fonts.adobe.com/variations/43111/eula
  - Noto Sans CJK JP Medium: https://fonts.adobe.com/variations/43112/eula

"Copyright Adobe Inc."が正しいのではないかと思っていますが、Googleと記載する理由等あれば、すみませんがコメント頂けると助かります。

2. アプリ([Web](https://covid19radarjpnprod.z11.web.core.windows.net/license.html))側の発行年が2011年(Notoの提供開始ですかね？)になっています。一方で、Noto Sans CJKのリリース年は2014年(参考：[Google Developers Blog](https://developers.googleblog.com/2014/07/noto-cjk-font-that-is-complete.html))でした。法的には2011年と記載する(CJKはNotoの一部と見做す)という理解で良いでしょうか？法的な扱いに詳しくないので、すみませんがコメント頂けると助かります。

#### Roboto対応の件
Robotoのリリース年(オープンソースとして)は2015年(参考：[Google Open Source Blog](https://opensource.googleblog.com/2015/05/roboto-googles-signature-font-is-now.html))でしたが、2011年から部分提供しているようなので2011年と記載します([Web](https://covid19radarjpnprod.z11.web.core.windows.net/license.html)版は2011年)。(法的な解釈等で)問題あればご指摘ください。

#### Building an App to Notify Users of COVID-19対応の件
> ©の前にtypoあり。

RAWテキスト上に該当する文字がありませんでした。typoではなく、GitHub側のレンダリング時の問題でしょうか。
読み手としては気になるので、© を (c)に置き換えるようにしたいと思います(他部分と表記を統一)。問題あればご指摘ください。

**Comment by keiji** [comment]
## Noto Sans CJK JPのライセンス
Adobeのサイトには「提供: Google」となっているのでGoogleのままで良いと考えます。

 * https://fonts.adobe.com/fonts/noto-sans-cjk-jp

一方、Wikipediaを見るとAdobeと共同開発という記述もありますね。

https://ja.wikipedia.org/wiki/Noto

> Notoフォントファミリーの中で日本語、中国語(繁体 / 簡体字)、韓国語を担うのがNoto Sans CJKである。Adobeと共同開発し、2014年7月16日に公開された[5]。ウェイトは7種(Thin 100, Light 300, DemiLight 350, Regular 400, Medium 500, Bold 700, Black 900)が用意されている。他のNotoフォントファミリーやRobotoと組み合わせて使うことを想定している。
> AdobeはSourceフォントファミリーという枠組みを持っており、このフォントも源ノ角ゴシックとして公開されている。Noto Sans CJKとの違いはフォント名と一部のウェイト表記であり、それ以外はすべて同一である。そのためNoto Sans CJKの従属欧文もSource Sansがベースであり、フォント形式がPostScriptアウトラインによるOpenType[6]となっている。

Google Fontsのattributionを見る限り、フォントのシュルによってはAdobeになるようです。

 * https://fonts.google.com/attribution

一方、Sans CJKについてはattributionに明確な規定がありません。
Adobeから取得したらAdobe, Googleから取得したらGoogleになるのかもしれません。

とはいえ、いま使われているファイルはCovid19Radarの頃のものなので、その時点で設定されたCopyrightが正と判断するのが妥当かと思います。ということで、Copyrightは現状のままGoogleでいきましょう。

## Roboto対応の件

ご指摘の通り、attributionでRobotoのyearは2011になっていますね。
ありがとうございます。そのようにお願いします。

 * https://fonts.google.com/attribution

## Building an App to Notify Users of COVID-19対応の件

いま手元のエディタで確認したら © の前に Â が見つかっています。これを削除したいという意図です。

<img width="721" alt="Screen Shot 2021-05-16 at 18 38 49" src="https://user-images.githubusercontent.com/932136/118392753-1f275680-b676-11eb-9e77-48d078e1b718.png">

**Comment by daisukekoba** [comment]
> とはいえ、いま使われているファイルはCovid19Radarの頃のものなので、その時点で設定されたCopyrightが正と判断するのが妥当かと思います。ということで、Copyrightは現状のままGoogleでいきましょう。

12b6d7efe56eda19b9f025194c65b948c149fb7a でフォント等が追加されていますが､ライセンスについて書かれていなかったため､フォントファイルの名前とプロパティからライセンスの記述を追加しました。

4ce99f42f1af30c7291b955a25c65011f4f6323f
```
Add font licenses

https://github.com/FortAwesome/Font-Awesome
https://github.com/googlefonts/noto-cjk
https://github.com/googlefonts/roboto
https://github.com/Templarian/MaterialDesign-Webfont
```

[COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES](https://github.com/cocoa-mhlw/cocoa/blob/master/COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md) に無い [Web](https://covid19radarjpnprod.z11.web.core.windows.net/license.html) 独自の記述は私ではないため分かりません。

**Comment by tatsu-jp** [comment]
typoの件、ご確認ありがとうございます。vscodeでは確認できなかったのですが、xcodeエディタで開いたら確認できました。
修正すると以下のようなdiffになり、Unicode表記の©(U+00A9)になりました(元々はUTF-8で記述されていたようです)。

```
diff --git a/COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md b/COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md
index 39dde674..612abaa9 100644
--- a/COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md
+++ b/COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md
@@ -413,7 +413,7 @@ permissions and limitations under the License.
 
 Swift Protobuf is licensed under Apache 2.0., see ACKNOWLEDGEMENTS.txt for more information.
 
-Copyright © 2020 Apple Inc.
+Copyright <A9> 2020 Apple Inc.
```

Notoの件は了解しました。

**Comment by tatsu-jp** [comment]
上の件の補足です。修正すると、vscodeでは残念ながら文字化けします。。。

<img width="189" alt="typo修正後のvscode画面" src="https://user-images.githubusercontent.com/29404405/118394538-35d2ab00-b680-11eb-9c49-228fb104ac27.png">

**Comment by keiji** [comment]
わお、だとすると最初にしていただいたように(C)にするのが無難でしょうか……

**Comment by tatsu-jp** [comment]
はい、ビューア側のサポート状況によって表示内容がブレてしまうので、(C)にした方が良さそうです。

**Comment by keiji** [comment]
@daisukekoba 
いまのWeb版のライセンスは、以前、そもそもフォント系のライセンスが記載されてなかったので取り急ぎ追加したものになります（ https://github.com/cocoa-mhlw/cocoa/issues/130#issuecomment-826493436 ）。

ちなみに今後はライセンスファイルはアプリ内部に持とうということになっていますね（ #163 ）

**Comment by tatsu-jp** [comment]
@keiji さん、
> 一方、Sans CJKについてはattributionに明確な規定がありません。
> Adobeから取得したらAdobe, Googleから取得したらGoogleになるのかもしれません。

念のため、cocoaに組み込まれているNotoSansCJKjp-Medium.otf/NotoSansCJKjp-Regular.otfのattributionを確認したところ、以下になっていました。

```
Copyright © 2014, 2015 Adobe Systems Incorporated (http://www.adobe.com/).
```

> いま使われているファイルはCovid19Radarの頃のものなので、その時点で設定されたCopyrightが正と判断するのが妥当かと思います。

上記のコメントと https://github.com/cocoa-mhlw/cocoa/issues/130#issuecomment-841796373 を踏まえると、追加されているフォントのプロパティに記載されている会社をライセンス保有者にするのが正しい気もしています。
何度もすみませんが、Web表記(Google)に合わせる方向で問題ないのかを確認させてください。

- Web上の記載：Copyright 2011 Google Inc.
- フォントプロパティ：Copyright © 2014, 2015 Adobe Systems Incorporated (http://www.adobe.com/).

**Comment by keiji** [comment]
ありがとうございます。Noto Sans CJKのCopyright Holder（Attribution）については、ご指摘の通り `Copyright © 2014, 2015 Adobe Systems Incorporated (http://www.adobe.com/).` が正しいことが確認できました。

ちょうどGoogle FontsのIssueでそのものズバリな質問があり、そこに「Noto Sans CJKのattributionはAdobeだよ」というやりとりを見つけました。

https://github.com/googlefonts/noto-fonts/issues/861#issuecomment-285083734

> For Noto Sans CJK, the copyright attribution is:
> Copyright © 2014, 2015 Adobe Systems Incorporated (http://www.adobe.com/).
For other Noto fonts, the copyright attribution is:
> Copyright 2015, 2016, 2017 Google Inc. All Rights Reserved.

ちなみに、Webで検索するとNoto Sans CJKでもGoogle IncをCopyright Holderとして記載しているところがあったので、ここは間違いやすい部分のようです。

https://www.lego.com/ja-jp/legal/notices-and-policies/open-source/

**Comment by tatsu-jp** [comment]
ご確認ありがとうございました。まさにズバリな質問ですね。
PRを上げたのでよろしくお願いします。

**Comment by keiji** [comment]
#212 がマージされてライセンスファイルをローカルで持つことになったので、もう一度`COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md`を見直します。

`SQLite-net`は使っているのか。`Google.Protobuf`はライセンス一覧から漏れているのではないか（そもそもiOS版でProtbuf使ってる？）。再度検討・調整します。
