### ISSUE TITLE
[Android] バージョンチェックが機能していない

### ISSUE THREAD

**Issue by b-wind** [cocoa-mhlw/cocoa#133]
## 不具合の内容 / Describe the bug

情報共有の為のIssueです。

COCOA には以下のファイルにアクセスして新しいバージョンがある場合にアップデートを促す機能があります。
しかし、現状 Android 版 v1.2.3 が出ているにもかかわらず、以下のファイルが更新されていないため新しいバージョンに気づかない可能性があります。

https://covid19radarjpnprod.z11.web.core.windows.net/version.json
```json
{
    "version": "1.2.2"
}
```

## 再現手順 / Steps to reproduce

1. COCOA 1.2.2 以前をで初期登録し、再起動を行う。
2. バージョンアップを促すメッセージが出ない。

## 期待される挙動 / Expected behavior

通常であれば /version.json が更新され、アップデートを促すメッセージが表示されることが期待されます。
ただし、今回はiOS版をリリースしていないことから意図的に/version.jsonを更新していないものと想定して居ます。

## スクリーンショット / Screenshots

本来表示されるべきメッセージ。

!<img src="https://user-images.githubusercontent.com/144311/116510036-41437980-a8ff-11eb-8ee0-1759bb4a1d6b.png" width="50%" hight="50%" >

## 動作環境 / Environments

- デバイス：（ Any ）
- OS：（Android）
- バージョン：(1.2.2以前)

## その他 / Additional context

Android/iOS 版が同時にアップデートされることを前提に作られた機能かと思いますが、
iOS 版 v1.2.3 をリリースしないことで機能しない事は承認されている物と考えています。
この為特に対応策等は提示しません。

情報共有を目的としていますので、１週間程度の掲示のあとcloseする予定です。

**Comment by keiji** [comment]
ご賢察の通り、iOSの方のリリースがされないため、バージョンチェック用のファイルは更新しないという判断をしています。

この点、AndroidとiOSで違うファイルを読みに行くようにするのが理想ですね。

**Comment by b-wind** [comment]
iOS 版がリリースされない等と言った情報は公式に見た覚えが無いのですが（単に見落としならすいません）、事後で良いのでわかりやすいところに記述して戴けると助かります > @halsk @heykuro 

単純な方法としては通知する内容を Issue にして、pin止めしておく等の方法があります。
https://docs.github.com/ja/github/managing-your-work-on-github/pinning-an-issue-to-your-repository

**Comment by tmurakami** [comment]
OS 別にファイルを分けたとしても、旧バージョンの利用者さんの為に現行の`version.json`は更新を続けることになると思いますので、ファイルを分けるのであれば運用を工夫(スクリプトを組むとか修正するとか)する必要はありそうです。

**Comment by keiji** [comment]
幸いにして、バージョンアップ時のメッセージは「最新バージョンがあります」というものです。
幸いにして具体的なバージョンを利用者に示すものではないので、AndroidとiOSで読みに行くファイルを分けたバージョンをリリースした後は、現行のversion.jsonに記載するバージョンを'99.99.99'にすることもできそうです。

**Comment by b-wind** [comment]
手元に古いバージョンがあったので、バージョンアップ時のスクリーンショットを追加しました。

**Comment by heykuro** [comment]
@b-wind  さん、ありがとうございます。

>iOS 版がリリースされない等と言った情報は公式に見た覚えが無いのですが（単に見落としならすいません）、事後で良いのでわかりやすいところに記述して戴けると助かります

こちらご指摘の通りですね。。分かりづらくすみません。
今後同様にOSごとのリリースに差異があった場合は、リリース時の周知内容を工夫したいと思います。(1.2.3について今から厚労省ホームページ上に追記するかどうかは次回リリースタイミングも踏まえて考えますね。)

**Comment by b-wind** [comment]
GW も終わりましたし、告知としては十分かと思います。当初の予定通り、close します。
