### ISSUE TITLE
[Android] AQUOS sense3 lite でフォントを切り替えると一部の画面で書体が乱れる

### ISSUE THREAD

**Issue by tmurakami** [cocoa-mhlw/cocoa#134]
## 不具合の内容 / Describe the bug

AQUOS sense3 lite でフォントを切り替えると、一部の画面で端末フォントの書体と COCOA 指定フォントの書体が混在してしまう。

- 使い方 (メイン画面右上)
- 使い方各項目 (「どのようにして接触を記録していますか？」等)
- メニュータイトル (「ホーム」「アプリの設定」等)
- 陽性登録画面の「はい」「いいえ」等
- 利用規約本文
- プライバシーポリシー本文
- ライセンス画面

## 再現手順 / Steps to reproduce

1. COCOA を起動する
2. メニューが正しく表示されることを確認
3. 設定 > ディスプレイ > 詳細設定 > 文字フォント設定 > 文字フォント切替で「SH クリスタルタッチ」に変更
4. 端末再起動
5. COCOA を起動する

## 期待される挙動 / Expected behavior

全ての画面で統一された書体となる。

## スクリーンショット / Screenshots

以下を参照。
https://github.com/cocoa-mhlw/cocoa/issues/120#issuecomment-828529042

## 動作環境 / Environments

- デバイス： AQUOS sense3 lite
- OS：Android
- バージョン： 1.2.3

## その他 / Additional context

おそらくはスタイルの適用漏れだと思います。
https://github.com/cocoa-mhlw/cocoa/issues/120#issuecomment-828937033

スタイルの適用方法ですが、例えばメイン画面のLabelのように明示的にキーを指定して適用する方法
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/styles/xaml/explicit
の他に、特定のコントロール全てに暗黙的に適用する方法があります。
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/styles/xaml/implicit
この暗黙的に適用する方法でStyleをApp.xamlに定義すれば良いように思います。

**Comment by keiji** [comment]
スタイルの適用漏れですね。使い方の一覧画面などもフォントの適用漏れがあるようです。

なお #120 のコメントにも記載したのですが、アプリ内のカスタムフォントについては、それ自体使用しなくてもいいのではないか（システムフォントで表示すればよいのではないか）という検討（ #132 ）も進めています。

**Comment by b-wind** [comment]
カスタムフォントは廃止するようですが（ https://github.com/cocoa-mhlw/cocoa/issues/114#issuecomment-836289043 ）、取りあえずフォント指定はしておくのか、特にフォントを指定しないのかどちらが良いのでしょうね。

**Comment by tmurakami** [comment]
バージョン 1.2.4 にて、書体が端末フォントで統一されていることを確認しました。
本件 close します。
ご対応ありがとうございました。
