### ISSUE TITLE
[Android] Force-stop Handlingの適用（ExposureNotification SDKアップデート）

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#136]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

#123 の検討過程で提案をもらったもの。

https://github.com/cocoa-mhlw/cocoa/issues/123#issuecomment-825804467

一部端末でバックグラウンドタスクが実行されない。実行されてもキャンセルされる場合がある現象が確認されている。

通常アプリはユーザーやシステムから強制停止されると、次回起動するまでバックグラウンドタスクの実行が制限される（スケジュールされない）。一部の端末ではバッテリー消費を低減する目的で、自動的にアプリを強制停止している可能性がある。

## 解決策についてお書きください / Describe the solution you'd like

「Force-stop Handling」はExposure Notification APIのバージョン1.5から追加された機能。

Google Play ServicesがEN APIを使っているアプリのプロセスを再起動することで、強制停止の状態から復帰させる。

Force-stop handlingについて、具体的な適用方法についてGoogleから回答を得ている。

 * SDK v1.5 以降へのアップデートが必要
 * SDKのアップデートで利用可能になる

とのことで、まず`Xamarin.GooglePlayServices.Nearby.ExposureNotification`をアップデートすることになる（現在は`18.0.2-eap.6`）。

----

バージョンアップについては以前Pull Request（ #22 ）をもらっています。現時点で一気に更新してしまうのは避けて、ライブラリをそれぞれアップデートしていきたいので、こちらで巻き取らせてくださいと調整済です。

----
Internal Tracking ID: NFR 2262

**Comment by keiji** [comment]
`Xamarin.GooglePlayServices.Nearby.ExposureNotification`については現在、手に入る最新のバージョンは`19.7.1-eap.1`となっている。

https://www.nuget.org/packages/Xamarin.GooglePlayServices.Nearby.ExposureNotification/

`19.7.1-eap.1`が使っているSDKは`play-services-nearby-exposurenotification-1.7.1-eap.aar`なので、これでForce-stop Handlingは有効になる。

https://github.com/xamarin/XamarinComponents/blob/f39add7ad854c3a8d8ad6a9284220a3d1073e055/Android/ExposureNotification/build.cake#L3-L4

----

個人的には、最新の`play-services-nearby-exposurenotification-1.8.3-eap.aar`を参照したバージョンを作ってあるので、こちらが使えないかなとも思います。

https://github.com/xamarin/XamarinComponents/pull/1133

こちらはPreAuthorizeにも対応しています（COCOAでは利用していませんが）。

Microsoftの人、マージしてくれないかなぁ…

**Comment by tmurakami** [comment]
ご無沙汰しております。

https://github.com/cocoa-mhlw/cocoa/issues/123#issuecomment-827269844 でおっしゃっていた

> COCOAの場合はApplicationのonCreateでWorkerを登録する

対応は不要という回答を Google から頂いたということでしょうか？
私も @keiji さんと同じように`Application#onCreate`で WorkRequest を enqueue する必要があると考えていたので、ちょっと意外です。

**Comment by keiji** [comment]
Application.onCreateでのWorker登録については質問に含めていますが、ライブラリのアップデートのみとのことでした（後述するテストで動作確認が取れたので、本当に要らないのかと再質問はしていません）。

ぼくの手元でも、つぎのPull RequestでビルドしたAPKをインストールしてテストをしてみました。
https://github.com/cocoa-mhlw/cocoa/pull/141

 1. COCOAをインストールして利用を開始する
 2. `adb shell dumpsys jobscheduler` でJobSchedulerの登録状態を確認する
 3. `adb shell am force-stop [APP_PACKAGE_NAME]` でアプリを強制停止する
 4. `adb shell dumpsys jobscheduler` でJobSchedulerの登録状態を確認して、アプリのJobがない（消えている）ことを確認する 
 5. 6時間程度待つ（Force-stop handlingでアプリの再有効化）
 6. `adb shell dumpsys jobscheduler` でJobSchedulerの登録状態を確認して、アプリのJobがある（復帰している）ことを確認する

この手順で、アプリのJobが復帰していることを確認しています。なお、アプリの設定画面から「強制停止」を選択するとJobは復帰しなかったので、`adb shell am force-stop` とは意味合いが異なる様子です。

バックグラウンドでの動作安定化については取り組みを続けていく予定です。ApplicationでのWorker登録に切り替える選択肢も持っておきたいと考えています。

**Comment by tmurakami** [comment]
@keiji お返事ありがとうございます。

> この手順で、アプリのJobが復帰していることを確認しています。

#141 に書いていましたね。失礼致しました。

**Comment by keiji** [comment]
それにしてもドキドキしますよね。
ExistingPeriodicWorkPolicy も`KEEP`になっているのでWorker登録自体をApplication側に移動してもいいかもしれません。

**Comment by tmurakami** [comment]
FYI です。

force-stop された場合は WorkManager 初期化時に Job を復元するようです。
https://github.com/androidx/androidx/blob/9b770633fafed35c5185f1cc2b52612a451ccdb9/work/workmanager/src/main/java/androidx/work/impl/utils/ForceStopRunnable.java

PendingIntent が force-stop でクリアされることを利用して force-stop かどうか判別しているようです。
https://github.com/androidx/androidx/blob/9b770633fafed35c5185f1cc2b52612a451ccdb9/work/workmanager/src/main/java/androidx/work/impl/utils/ForceStopRunnable.java#L146-L167

そこのコメントに書いてありますが、いくつかの OEM では AlarmManager のバグにより SecurityException が発生するらしいので

- WorkManager のバージョンアップ
- `Application#onCreate`で再スケジュール

のどちらか (もしくは両方) の対応を考えたほうが安全かもしれません。

**Comment by keiji** [comment]
WorkManagerのバージョンアップについてはしない理由がないので、あとは施策として追加でApplication#onCreateで再スケジュールするように変更するかどうかですね。

現在COCOAがターゲットにしているバージョンで動作するWorkManagerは、バックエンドにAlarmManagerを使っていない（JobSchedulerを使っている）と理解しているので、その点はあまり心配していません。とはいえ、ぼくもWorkManagerのすべての実装を見たわけではありませんし、リスクを低減する意味でもApplication#onCreate移動は検討したいですね（その場合にiOS側のスケジューラーに影響があるかも念のため確認します）。

**Comment by tmurakami** [comment]
> バックエンドにAlarmManagerを使わない（JobSchedulerを使う）と理解している

言葉足らずで申し訳ありません。
ForceStopRunnable は API レベル (使用される Job ディスパッチサービス) に関係なく force-stop 判別の為に AlarmManager を利用しているようです。

当該クラスは「force-stop されていたら Job を再スケジュールする」というものです。
これは WorkManagerImpl が生成されるときに`WorkManagerImpl#internalInit`から呼び出されます。
https://github.com/androidx/androidx/blob/9b770633fafed35c5185f1cc2b52612a451ccdb9/work/workmanager/src/main/java/androidx/work/impl/WorkManagerImpl.java#L764

ForceStopRunnable では「`isForceStopped`が`true`であれば Job を再スケジュールする」という処理を行っています。
https://github.com/androidx/androidx/blob/9b770633fafed35c5185f1cc2b52612a451ccdb9/work/workmanager/src/main/java/androidx/work/impl/utils/ForceStopRunnable.java#L180-L182
https://github.com/androidx/androidx/blob/9b770633fafed35c5185f1cc2b52612a451ccdb9/work/workmanager/src/main/java/androidx/work/impl/WorkManagerImpl.java#L675-L694

`isForceStopped`では「AlarmManager は force-stop でキャンセルされる」という仕様を利用して PendingIntent の存在有無で force-stop を判別しています。
https://github.com/androidx/androidx/blob/9b770633fafed35c5185f1cc2b52612a451ccdb9/work/workmanager/src/main/java/androidx/work/impl/utils/ForceStopRunnable.java#L153

このアラームの予定時刻は 10 年後ですので
https://github.com/androidx/androidx/blob/9b770633fafed35c5185f1cc2b52612a451ccdb9/work/workmanager/src/main/java/androidx/work/impl/utils/ForceStopRunnable.java#L300
ForceStopRunnable ではアラームを実行させる為ではなく、force-stop を判別する為だけに AlarmManager を利用しているように見えます。

あと、追加でお伝えしたいことがあります。
先に私が述べた

> AlarmManager のバグにより SecurityException が発生するらしい

の対応
https://github.com/androidx/androidx/commit/9b770633fafed35c5185f1cc2b52612a451ccdb9
について WorkManager 2.5.0 のソース (work-runtime-2.5.0-sources.jar) を確認しましたが、残念ながら当該修正コードは含まれていませんでした。
ですので、現時点で ForceStopRunnable のコミットメッセージにあった some popular devices をケアする為には、`Application#onCreate`での再スケジュールを行う他ないかもしれません。

ご参考まで。

**Comment by keiji** [comment]
ありがとうございます。そうか、状態判別でAlarmManagerを使っているところでSecurityException出すんですね。
"some **popular** devices"という記述も不安なので、これは「WorkManagerをApplication#onCreateで再スケジュールする」と言うIssueにした方が良さそうです。

**Comment by b-wind** [comment]
たまたま見かけた改善事例があったので貼っておきます（このIssue が適切かどうかは不明ですが）

https://twitter.com/hatano/status/1402783405599719426?s=20
