### ISSUE TITLE
ログ送信後に表示される動作情報IDを何時でも確認できる様にする。

### ISSUE THREAD

**Issue by Takym** [cocoa-mhlw/cocoa#139]
## その機能リクエストは何らかの問題に関連しますか
ログ送信後に動作情報ID付きのメールを送信できる様になります。このIDはメールを送信しない場合は確認する事ができません。また、メールを送信した場合でも、そのメールを削除してしまうと確認できなくなります。個人情報と深い関わりがあるので、何時でも確認できる状態にしておくべきだと思います。

## 解決策についてお書きください
送信した動作情報IDを全て確認できるページを作成します。

## あなたが考える代替案についてご説明ください
上記に加えて下記の項目も確認できた方が良いかも知れません。
* 送信したログの中身の確認
* ログの送信日
* メールを送信したかどうか
* メール送信ボタン

## その他
* 携帯電話を乗っ取られた場合等に確認できてはいけない情報なので、利用者が任意で削除できる様にした方が良いと思います。
* この機能を追加する前の情報は確認できません。

**Comment by b-wind** [comment]
ログの中身の確認は現状送信前の画面でファイル出力出来るようになっていますね。
現実的に差があるかはともかく、送信後に「実際に送った情報」を確認出来た方が良い様には思います。


ただし、中身の性質を考えると「TEKの照合のの記録」（iOS だと「接触チェックの記録」、Android だと「アプリによる接触確認の履歴」）と同じ扱い、つまり端末による本人確認（顔認証・指紋認証・PIN入力... etc）が有った方が良い様には思われます。
シンプルに実装できるものかは確認していません。


動作ログの扱いについては、プライバシーとセキュリティの話題になるので出来ればCIO補佐官のお二人のご意見も伺いたく > @halsk @heykuro 


ログの送信日とIDに付いては確認の意味で見れた方が良いかとは思います。直接的に役にたつケースは少ないと思いますが。


メールを送信したかどうか、はメールソフトに処理が移るのでCOCOAで確認するのは現状のままでは無理ですね。


メール送信ボタンとは？ 意味を取りかねました。

**Comment by keiji** [comment]
ログのアーカイブについては現状は送信後にすぐ消していますね。

プライバシーポリシーで動作情報（ログ）は14日経過後に自動削除となっているので、長期間残しておくとプライバシーポリシー違反になりますし、複数日に渡るアーカイブの取り扱いがややこしくなるので、このあたりは現状の処理が良いと思います。

一方、ぼくもログを送信後、メールの編集画面を表示するまで動作情報IDが表示されない現状に不便に感じています（開発用に使っている端末にはメールアプリの設定をしていないものもありますので）。

「送信後、動作情報IDを画面に表示する」という挙動で、ある程度カバーできそうですがいかがでしょうか。

**Comment by b-wind** [comment]
> プライバシーポリシーで動作情報（ログ）は14日経過後に自動削除

直近14日分のログは保存されていて、任意の第３者が別ファイルに出力可能な状態だと思うのですが、こちらの扱いはどうすべきだと思われますか？


![ファイル出力ボタン](https://user-images.githubusercontent.com/144311/116777229-68897a80-aaa8-11eb-9eca-4767c3c9bcae.png)

**Comment by keiji** [comment]
任意の第三者というのは利用者のことでしょうか。

基本的にCOCOAは、端末の利用者が使うという前提で設計されていると認識しています。この画面から利用者が動作情報を確認するために別の場所に配置（出力）したのであれば、それは利用者の意思に基づくもので、任意の第三者が別ファイルに出力可能な状態ではないとぼくは理解しています。

また、仮に利用者以外の第三者が利用者の合意を得ずに端末のロックを外すなどしてCOCOAを利用できる状態にあるとすれば、それはまた別の問題が発生していると考えます。

**Comment by b-wind** [comment]
> また、仮に利用者以外の第三者が利用者の合意を得ずに端末のロックを外すなどしてCOCOAを利用できる状態にあるとすれば、それはまた別の問題（COCOAの範疇を超える）が発生していると考えます。


なるほど、お考えは理解しました。

**Comment by Takym** [comment]
@b-wind さん

> メール送信ボタンとは？ 意味を取りかねました。

動作情報IDの一覧ページから再度メールを送信する為のボタンです。

**Comment by Takym** [comment]
@keiji さん

> 「送信後、動作情報IDを画面に表示する」という挙動で、ある程度カバーできそうですがいかがでしょうか。

動作情報IDを画面に表示した上で、コピーできる様にしておけば利用者がメモを取る事ができますし、良いと思います。

**Comment by keiji** [comment]
@Takym あたらしく「動作情報IDを送信後、画面に表示する」みたいなIssueを立てましょうか。

このIssueは送信した動作情報ID一覧画面のようなものを作るかについて検討した結果として、一旦won't fixとしてcloseしたいと考えています。

**Comment by Takym** [comment]
@keiji #140 にて立て直しました。

**Comment by Takym** [comment]
#140 を立ててから10日以上経過したのでこの Issue は閉じさせて頂きます。
