### ISSUE TITLE
動作情報IDを送信後、画面に表示する。

### ISSUE THREAD

**Issue by Takym** [cocoa-mhlw/cocoa#140]
## その機能リクエストは何らかの問題に関連しますか
> ログ送信後に動作情報ID付きのメールを送信できる様になります。このIDはメールを送信しない場合は確認する事ができません。また、メールを送信した場合でも、そのメールを削除してしまうと確認できなくなります。個人情報と深い関わりがあるので、何時でも確認できる状態にしておくべきだと思います。

## 解決策についてお書きください
画面に動作情報IDを表示し、コピーできる様にします。
利用者は動作情報IDのメモを取る事で何時でも確認できる様になります。

## あなたが考える代替案についてご説明ください
> ~~送信した動作情報IDを全て確認できるページを作成します。~~

## その他
#139 に関連します。

----
Internal IDs:
- PBI 2913

**Comment by Murayu0225** [comment]
@keiji 
こちら、仮で作成しました。（位置調整は後程行います。）
動作情報IDをコピーするを選択した際にコピー完了を示すポップアップ表示は、あった方が良いでしょうか。

![Screenshot_20210910-180529_COVID-19 Contact App.jpg](https://user-images.githubusercontent.com/37988559/132830035-95c8fbca-5a45-4338-b76c-7b6a521a4989.jpg)
