### ISSUE TITLE
[Android] WorkManagerライブラリのアップデート

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#144]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

#123 の検討過程で提案をもらったもの。

WorkManagerは、Androidでバックグラウンドタスクの実行を管理するライブラリ（バックエンドはJobScheduler）。

https://github.com/cocoa-mhlw/cocoa/issues/123#issuecomment-828944244

> 一方、COCOA では （Xamarin 経由ですが）2.3 が指定されているように見えます。

## 解決策についてお書きください / Describe the solution you'd like

> こちらを最新の 2.5.0.1 に入れ替えるだけでも幾つかの端末での動作は改善するのでは無いでしょうか。（すべての端末で問題無くなるとは思っていません）
> https://www.nuget.org/packages/Xamarin.AndroidX.Work.Runtime/2.5.0.1

## その他 / Additional context

個人的な理想を言えば、その他のライブラリも含めて、アップデートしたらすぐに追従するPRをして、開発チームに取り込んでもらうくらいのスピード感でいきたい（実際の取り込み段階では、stableかbetaかで判断は分かれそう）

**Comment by tatsu-jp** [comment]
@keiji さん、
(アプリの中身を少し理解できたので)、good first issue/welcome-contributionラベルのある本issueに対応できるかを検討しています。
対応する上で質問させてください。

修正自体は以下を変更すれば良いだけだと思いますが、どのようなテストをしてPRすれば良いのか分からず困っています。

https://github.com/cocoa-mhlw/cocoa/blob/b147fbb61e2b666a53ff3123e63dc86d68f00af5/Covid19Radar/Xamarin.ExposureNotification/Xamarin.ExposureNotification.csproj#L50

- Androidビルド確認：EN APIをサポートしているversion 5.0 (API level 21)以降でReleaseビルド確認しようと思っています。全APIレベルでビルド確認した方が良いのでしょうか。認識が合っているのかを確認させてください。
- 動作確認：バックグラウンドタスク実行の挙動が改善されたかを確認できる方法を思いついていないので、方法あればコメント頂けると助かります。 

すみませんが、実機テストで使える端末が今手元にないのでシミュレータ(Debug_Mock)での確認になります。

**Comment by keiji** [comment]
ありがとうございます！

ビルドはお使いの環境でのみ確認していただければ大丈夫です。ReleaseビルドについてもPull RequestをいただいたらGitHub Actionsが自動で各Configuration、プラットフォーム別のビルドとユニットテストまで実行して、問題があればここでわかります。

[GitHub Actionsの実行例](https://github.com/cocoa-mhlw/cocoa/actions/runs/844319767)

動作確認については、基本的には「アップデート後もこれまで通り動いて、これまであった不具合が改善されている」というようなもので、確認が難しいというのは承知しているので、最終的には開発チーム側で行うリリース前テストで検出することを想定しています。

よろしくお願いいたします。

**Comment by tatsu-jp** [comment]
コメントありがとうございます。
すみません、ci.ymlノーチェックでした。素晴らしいテストがあるので安心してPRできます。

土日で対応して後でPR出します。
よろしくお願いします。

**Comment by tatsu-jp** [comment]
@keiji さん、
ライブラリアップデートの影響を確認するためにWorkmanager近辺のコードを見ていて、一点気になった点があるのですみませんが教えてください。

#27 で対応されたSetRequiresDeviceIdle(true)を外す修正に関する質問です。
以下には残っているのですが問題ないのでしょうか(意図的に残している？)。

https://github.com/cocoa-mhlw/cocoa/blob/b147fbb61e2b666a53ff3123e63dc86d68f00af5/Covid19Radar/Xamarin.ExposureNotification/ExposureNotification.android.cs#L126-L132

参考：[Android デベロッパー>ドキュメント>ガイド>WorkRequest の定義>定期的な処理のスケジュール設定](https://developer.android.com/topic/libraries/architecture/workmanager/how-to/define-work?hl=ja#schedule_periodic_work)

**Comment by keiji** [comment]
はい。大丈夫です。ご指摘の箇所はXamarin.ExposureNotificationライブラリのデフォルト設定になります。
設定はMainActivitiyで上書きされるので、実際にWorkerが登録される際は`SetRequiresDeviceIdle(false)`が適用されます。

https://github.com/cocoa-mhlw/cocoa/blob/872cc86eea3d081f48a63805a6ac1f53c3293184/Covid19Radar/Covid19Radar.Android/MainActivity.cs#L29-L37

**Comment by tatsu-jp** [comment]
ありがとうございます。理解が深まりました。
PRを発行したのでご確認お願いします。
