### ISSUE TITLE
masterブランチの保護を設定する提案

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#146]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

#75 対応のためにCI.ymlを編集したところ、本来フォーク先（keiji/cocoa）で作業すべきところを、cocoa-mhlw/cocoaのファイルを直接書き換えてしまいました。

## 解決策についてお書きください / Describe the solution you'd like

今後このような間違いが起こらないように（ぼくが起こさないように）、GitHubのブランチ保護を設定して、masterの直接変更を防止する措置を取ることを提案します。

保護されたブランチについて
https://docs.github.com/ja/github/administering-a-repository/about-protected-branches

具体的には`master`ブランチに対して、次の設定をすることを提案します。

 * Require pull request reviews before merging （masterの変更にはPull Requestが必要になる）
 * Include administrators （管理者にも制限が適用される）

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

直接ファイルを書き換えできるのは管理者だけなので、一人一人が気をつける方法もありますが、人間なので間違いはどうしても避けられません。ぼくも二度とやりませんとは確信を持って言えないというのが正直なところで、制限設定により保護するのがより望ましいと考えます。

## その他 / Additional context

間違えて変更した箇所については #145 でRevertするPull Requestを提出済みです。

**Comment by heykuro** [comment]
ありがとうございます！確かに今後関係者が変わっていったり増えていったりすることはありうるので、対策をとっておく必要がありますね。

>Require pull request reviews before merging （masterの変更にはPull Requestが必要になる）
>Include administrators （管理者・コラボレーターにも制限が適用される）

少なくともPRは必須にしたいですね。

**Comment by keiji** [comment]
> 少なくともPRは必須にしたいですね。

はい。まずは「Require pull request reviews before merging」を有効にして「1 approve」を要件にするのでどうでしょうか。

当初「管理者にも制限をかける（Include administrators）」という提案をしていましたが、そもそもコラボレーターは管理者（Administrator）ではないのではと言う気がしてきました。

管理者（おそらくcocoa_dev）に制限はかけずに当初やりたいこと（直接書き換えミスの防止）ができるかを検討するという意味でも、今は「Include administrators」は触らないほうが良さそうです。

**Comment by b-wind** [comment]
コラボレーターは招待されたリポジトリに対し、特定の権限を持って居るものでは無いと認識しています。
コラボレーターが持って居る権限の内容は招待するときに個別に設定しているようです。


ここで Admin Role を選択すれば 管理者兼コラボレーター と言う設定も出来そうですが試したことは無いです。


https://docs.github.com/ja/organizations/managing-access-to-your-organizations-repositories/adding-outside-collaborators-to-repositories-in-your-organization


!<img src="https://docs.github.com/assets/images/help/repository/manage-access-invite-choose-role-add.png" width="50%" hight="50%">

**Comment by keiji** [comment]
設定が完了して、無事にぼくがmasterの直接編集ができなくなったことを確認したので、本Issueをcloseします。

![Screen Shot 2021-05-07 at 16 11](https://user-images.githubusercontent.com/932136/117412215-7b3ffb80-af4f-11eb-804a-29fb70672a08.jpg)
