### ISSUE TITLE
[Android] 正確なアラーム（AlarmManager.setExact...）の利用にパーミッションが必要になる（Android 12）

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#150]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

Android 12（開発コード: S）では、AlarmManagerのsetExact...系の利用にパーミッションが必要になる。

> ターゲットが Android 12 で正確なアラームを使用するアプリは、新しいパーミッション SCHEDULE_EXACT_ALARM をリクエストする必要があります。これは通常のパーミッションなので、マニフェストで宣言すれば初回起動時に自動的に付与されます。ただし、ユーザーがこのパーミッションを持つアプリを確認したり、[Settings] の [Special App Access Permissions] からパーミッションの付与と取り消しを行ったりできるようになります。アプリで正確なアラームが必要な場合は、パーミッションがなくなった場合の処理を忘れないようにしてください。アプリのパーミッションの状態を確認できるようにするため、新しい API canScheduleExactAlarms() を追加しています。一般的には、可能な限り正確なアラームを使わないようにアプリを移行することをお勧めします。詳しくはこちらをご覧ください。 

https://android-developers-jp.googleblog.com/2021/04/android-12-developer-preview-3.html
https://developer.android.com/about/versions/12/behavior-changes-12#exact-alarm-permission

COCOAでは、動作情報（ログ）の洗い替え処理に`setExactAndAllowWhileIdle`を使用しているので影響を受ける。

https://github.com/cocoa-mhlw/cocoa/blob/04e708aff00537ff93f1bbd58c0547da4fbc85a9/Covid19Radar/Covid19Radar.Android/Services/Logs/LogPeriodicDeleteServiceAndroid.cs#L44-L47

## 解決策についてお書きください / Describe the solution you'd like

可能であればログの洗い替え処理をWorkManagerに移行する。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

`SCHEDULE_EXACT_ALARM`パーミッションを追加する。その場合、ユーザーにパーミッションをRevokeされた場合の手当が必要になる。

"ターゲットが Android 12 で正確なアラームを使用するアプリ"とあるので、おそらく`targetSdkVersion`をAndroid 12のAPI Versionにしない限り制約を受けない。将来的にtargetSdkVersionを更新するまでは延命はできそう（要確認）。

Developer Preview 3時点ではCOCOAのパーミッションをユーザーがrevokeするユースケースはなさそうだけど、リリース時点ではわからないので注意する。

![Screenshot_20210504-022854](https://user-images.githubusercontent.com/932136/116911215-83fbad80-ac81-11eb-83a0-93262846c08a.png)

## その他 / Additional context

 - [ ] SCHEDULE_EXACT_ALARMパーミッションが必要になるのがtargetSdkVersion="S"以降であることを確認する
 - [x] targetSdkVersion="S" 未満の`setExact`を使っているアプリが、明示的にパーミッションをrevokeされないことを確認する
 - [ ] Android 12のリリース後、targetSdkVersion="S" 未満の`setExact`を使っているアプリが、明示的にパーミッションをrevokeされないことを確認する
----
Internal IDs:
- Prepare Item 1630

**Comment by b-wind** [comment]
ログのRotate処理、そんなに実行タイミングの精度が必要だろうかと言う部分で疑問を持っています。
もちろん高精度で実行できるに越した事は無いのですが。


iOS 側では BGTaskScheduler を使っていて、実行タイミングは正確にコントロール出来ない物だと認識しています。
機種毎のカスタマイズがほぼ無い分、WorkManager よりは安定して実行されているようですが。

https://github.com/cocoa-mhlw/cocoa/blob/04e708aff00537ff93f1bbd58c0547da4fbc85a9/Covid19Radar/Covid19Radar.iOS/Services/Logs/LogPeriodicDeleteServiceIos.cs#L46


また、Application.OnStart / OnResume でも  LoggerFileService.Rotate は呼ばれていますので現状だとアプリケーションのフォアグラウンド実行時にも呼ばれています。
 https://github.com/cocoa-mhlw/cocoa/blob/04e708aff00537ff93f1bbd58c0547da4fbc85a9/Covid19Radar/Covid19Radar/App.xaml.cs#L149-L161


結論としては WorkManager を利用して一日一回程度呼ばれることを確保できれば十分ではないかなと言う印象を持ちました。

**Comment by b-wind** [comment]
余談ですが、EN API を呼び出すバックグラウンド処理でもどうせ LoggerServiceは呼んでいるので、iOS/Android 共に別途スケジューリングしなくてもその時に Rotate すれば良いのかなと言う気はしています。ただ、ここは異論もあるかも知れません。

**Comment by keiji** [comment]
これはWorkManagerを使う方向で。

**Comment by keiji** [comment]
WorkManagerに移行します
