### ISSUE TITLE
[Android] バックグラウンド処理で例外が発生したときにリトライされない

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#155]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

現在COCOAが動かしているXamarin.ExposureNotificationのソースコードでは、WorkManagerが実行するバックグラウンド処理（Worker）から例外が投げられるとリトライを試みる（Result.InvokeRetry()を返す）設定になっている。

https://github.com/cocoa-mhlw/cocoa/blob/b640ba714fecfc23121173fdb207750956dd2e41/Covid19Radar/Xamarin.ExposureNotification/ExposureNotification.android.cs#L205-L224

しかし、ExposureNotificationHandler中で診断キーのダウンロードと接触確認全体で発生するExceptionを受け取ってそのままにしているため、サーバーに到達できないなど例外が発生しても`DoWork`まで例外が上がらずWorkerは成功したことになり、再びのWorker起動（約6時間後）まで接触確認が実行されない。

https://github.com/cocoa-mhlw/cocoa/blob/b640ba714fecfc23121173fdb207750956dd2e41/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L145-L194

## 解決策についてお書きください / Describe the solution you'd like

FetchExposureKeyBatchFilesFromServerAsync の中で `try catch`でExceptionを受けるのを止める。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

すべての例外のログを取る目的でExceptionをcatchしているのなら、ログに出力した後、同じ例外をthrowし直す（Workerが例外をcatchできるようにする）。

## その他 / Additional context

再試行するようになるとバッテリーの消費やサーバー負荷が増大する可能性がある。合わせて、再試行ポリシー（BackoffCriteria）も検討する必要がある。

Androidリファレンス実装の例
https://github.com/google/exposure-notifications-android/blob/ab04ef755cde964a43aa94de8b9d86084d0b4f6f/app/src/main/java/com/google/android/apps/exposurenotification/nearby/ProvideDiagnosisKeysWorker.java#L220-L223

----
Internal IDs:
- BUG 1878

**Comment by b-wind** [comment]
（言うまでも無いかも知れませんが）開発チームに意図を確認した後、 catch を削除するか catch した後再度 throw し直すかを決めると良いかと思います。


再試行ポリシーについては例外の内容にも寄ると思うので、情報が欲しいというのが本音でしょうか。
