### ISSUE TITLE
バージョンアップ時に移行（マイグレーション）する仕組みを作る

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#156]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

v1.2.2で`Application.Current.Properties`から、プラットフォーム固有形式へのデータ保存の移行があった。

v1.2.3ではWorkManagerの`ExistingPeriodicWorkPolicy`が`Replace`から`Keep`へ、WorkerNameが`exposurenotification`から`cocoaexposurenotification`に変更されている（`exposurenotification`はキャンセル）。

今後、日付関係のデータをロケール非依存の形式にする（ #124 ）などの変更が想定されている。

現状を鑑みると、今後アップデート時のメンテナンスコストを低減するため、バージョンアップ（アップデート）時に、特定のバージョンから最新バージョンまでの移行処理を一元的に行う仕組みを用意することが望ましいと考える。

## 解決策についてお書きください / Describe the solution you'd like

`UpdataMigrationHelper`のようなクラスをプラットフォーム別に用意する。

`Migrate(fromVersion, toVersion)`のようなメソッドがあり、`fromVersion`に設定ファイルのバージョンを、`toVersion`に現在のアプリのバージョンを指定すると、必要なマイグレーション処理を順次実行する。

※ 設定ファイル（PreferenceとSecureStorage）に、その設定ファイルのバージョン情報を保存しておく必要がある。

たとえば、v1.2.1をインストールしているユーザーがv1.2.3をインストールすると、`Migrate_121_122`と`Migrate_122_123`が実行されるというイメージ。

移行を行うタイミングは、次の通り想定している。

 * iOSは、UI起動時、バックグラウンド実行時。
 * Androidは、UI起動時、バックグラウンド実行時に合わせて`ACTION_MY_PACKAGE_REPLACED`のBroadcast Intentを受け取るケースも含める（WorkManagerの再登録が必要になる場合があるため。参考：https://github.com/keiji/cocoa/commit/a1f67546d2b560f3563bd0a37b589aee61f7e118 ）。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

データのマイグレーションを簡単にやってくれるパッケージがあれば使いたいけど、SecureStorageまで面倒見てくれるのはなさそう。

## その他 / Additional context

利用者が順当にバージョンアップしてくれればいいけど、v1.2.0 -> v1.2.4とかのケースもあり得るわけで、ここは早めに手当しておかないとマイグレーション・ヘルになる。

----
Internal Tracking ID: PRODUCT BACKLOG ITEM 1676

**Comment by b-wind** [comment]
> ※ 設定ファイル（PreferenceとSecureStorage）に、その設定ファイルのバージョン情報を保存しておく必要がある。
作業的にはここが最重要かなと。
v1.2.3 以前のバージョンは推測になりますが、大きくは問題は出ない…… はず。

**Comment by b-wind** [comment]
通常の使い方だとあまり無いはずだけれど、バージョンダウン時の挙動も一応決めておいた方が良いかもですね。
殆どの場合初期化してしまえばいい気はしますが。

**Comment by keiji** [comment]
試験的に実装してみたけれど、信頼性のあるテストを作るのが大変そう。
