### ISSUE TITLE
DebugPage の追加

### ISSUE THREAD

**Issue by i-maruyama** [cocoa-mhlw/cocoa#160]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

デバッグ用情報表示やページ遷移が行えない

<del>一般ユーザーがビルドした際に、何もできない。私の環境では、Debug, Debug_Mock はともに SplashPage で止まり、 Release は Tutrial に進むものの、認証に失敗しHomePage に到達できない。</del>（Debug_Mock が SplashPage で止まるのは、パッケージバージョンによるものでした。）

## 解決策についてお書きください / Describe the solution you'd like

DebugPage を追加し、一般ユーザーが可能な範囲の機能テストを可能にする。

- 各ページへのナビゲーション
- アプリ上でのTeK のダウンロードと再ダウンロードテスト（LastProcessTekTimestampのリセット）

追記：シンプルなケースについて以下で作成しています。
https://github.com/i-maruyama/cocoa/tree/debugpage

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

幾つかの実装は以下で試験中。
https://github.com/i-maruyama/cocoa/tree/demopage

Visual Studio でRelease ビルドで実行可能。エミュレーター Pixel2 Q10.0と実機 Aquos sense3lite で検証。

Release ビルドで実行させるため #define ReleasePersonal を使っています。本番環境での Release では削除する必要があります。

また(1) #128 に対応するため機能改善が含まれており、(2)デモページ自体は日本語で書いています。

## その他 / Additional context

実機 Aquos sense3lite でのスクリーンショット

<img src="https://user-images.githubusercontent.com/4100714/117519824-4fb92180-afe0-11eb-8b43-3b1fe85a94cb.png" width="25%" height="auto" /><img src="https://user-images.githubusercontent.com/4100714/117519828-50ea4e80-afe0-11eb-9967-f461b8e91a8c.png" width="25%" height="auto" /><img src="https://user-images.githubusercontent.com/4100714/117519829-50ea4e80-afe0-11eb-827c-4639f5483b41.png" width="25%" height="auto" /><img src="https://user-images.githubusercontent.com/4100714/117519830-5182e500-afe0-11eb-94d4-c38d7dc1bffc.png" width="25%" height="auto" />

Exposure Notification については、一般ユーザーが利用できないのは仕方ないが、<del>Debug_Mock が利用可能になると良い。</del>Debug_Mock を用いたテストが行えると良い。
----
Internal IDs:
- NFR 2532

**Comment by b-wind** [comment]
> 私の環境では、Debug, Debug_Mock はともに SplashPage で止まり、 Release は Tutrial に進むものの、認証に失敗しHomePage に到達できない。


構築環境が Android か iOS か分かりませんが、Release/Debug は EN API へのアクセスのため Apple/Google の特別なアカウントなりプロファイルが必要だったかと。事実上 GitHub コミュニティ側で扱う事の無いビルドと考えています。

Debug_Mock は EN API への依存を取り除いているので HomePage ぐらいは見れたような。


1. 一般ユーザーがビルドした際に、何もできない。
2. DebugPage を追加し、一般ユーザーが可能な範囲の機能テストを可能にする。


この二つの関係が、問題点と解決策の対に思えません。２つの Issue に分ける方が適切では無いでしょうか。


1 が出来ないのであれば、コード上のバグであり Debug_Mock ビルドで最低限の動作を確認出来る様にすべきです。
その上で、Debug_Mock では足りない部分があれば何らかの形で補う手段が必要かも知れません。
（現状では接触記録を故意に作り出したり、陽性者登録は出来ませんし）



2 は単純にデバッグ溶出力の追加ですね。Debug_Mock ビルド時にあっても良いと思います。
（DebugPage 自体は以前もあって削除されたようですが内容と経緯は追っていません）

とはいえ、まずは現行アプリでも動作のログ出力を行っていますので、そちらで不足している部分を補っていく方が先決かなとは思います。
これは #148 で指摘されている部分の修正を含むと考えています。

**Comment by keiji** [comment]
ありがとうございます。Debugページについては仰るとおり、あった方がいいとぼくも思います。
接触履歴がある場合とない場合、陽性登録の成功・失敗と言ったケースを簡単にテストできるのがいいですね。

課題としては、一般ユーザーが触れてはいけないと言うことでしょうか。DEBUGビルドの場合のみ含まれる、Release時にはバイナリにそもそも含まれないような、そういう仕組みが求められそうですね。このあたり、AndroidではBuild Variantで分けてうまいことやるのですが、Xamarin.Formsではベストプラクティスが見つけられていません（ #63 )。

ぼくはCOCOAはDebug_Mockでビルドしていて、接触確認API系を利用するDebugやReleaseと言ったビルドはしていません（接触確認APIについては、もっと規模の小さなアプリを個人的に作成して、それを使ってテストしています）。

Debug_Mockは、接触確認APIをデバッグモードで使えるアカウントやプロビジョニングプロファイルをお持ち出ない方でも一通りの操作ができるビルドです。ですので、Debug_Mockでビルドすると、スプラッシュ画面の後に初期設定画面（利用規約等の合意やチュートリアル画面）の後、ホーム画面が開くというのが正常な挙動で、少なくともぼくの手元では問題なく動いています。

スプラッシュ画面から先に進まないという現象は、ビルドしたバイナリを実機に転送する際に不具合が起きている差分のみを転送するモードを使っていて、転送がうまくいっていないときに遭遇したことがあります。

特にいまのCOCOAはパッケージが大きく、ビルド後の転送で失敗することがあります。その場合、次のようにすると改善する場合があります。

 * 実機に接続しているケーブルを一度抜いて再度挿し直す。
 * インストール済みのCOCOAをアンインストールしてから再度インストールを試みる。
 * 実機やエミュレーターを再起動する。
 * Visual Studioを一度完全に終了してから再起動する。
 
また、お使いのXamarin.Androidのバージョンによっても、うまくデバッグできないことがありました（ #40 #53 ）。一度バージョンを確認してみることをお勧めします。

**Comment by Takym** [comment]
あまり良いやり方とは言えませんが、プロジェクトファイルの ItemGroup に条件を指定して Debug ビルド時にのみ取り込む様に設定する事はできます。

**Comment by i-maruyama** [comment]
情報ありがとうございます。おかげで windows で Debug_Mock のビルドには成功しました。（初心者には、かなり大変でした。この情報は別 issue にしたいと思います。）

手元で使い勝手を見ていましたが、デバッグページ自体は引き続き提案したいと思います。（記述は後で変更します。）

情報の中では、この LastProcessTekTimestamp のリセットは、データの再ダウンロードになるためデバッグには便利そうです。この辺りの情報と、ナビゲーションを実装したものになります。ナビゲーションにより、 SplashPage や ContactedNotifyPage（接触ある場合のページ） など通常は辿れないページへも移動できます。

現状では、プリプロセッサ(#if DEBUG)を用いて、Debug か Debug_Mock の場合のみ、メニューバーに debug が表示されます。

皆さんにコードをご覧いただくために、一度 PR してみたほうが良いでしょうか？

https://github.com/i-maruyama/cocoa/commit/a937a9493180c53782a87df3d6f4253ec645653f

**Comment by i-maruyama** [comment]
記述を変更しました。

またスクリーンショットをとったコードは別issueの議論を含んでいましたので、それを除いたブランチを作成しました。DebugPageのファイルをプリプロセッサ(#if DEBUG)を用いて、Debug か Debug_Mock の場合のみ、メニューバーに debug が表示するだけのコードです。

https://github.com/i-maruyama/cocoa/tree/debugpage

**Comment by i-maruyama** [comment]
単なるデバッグページ https://github.com/i-maruyama/cocoa/tree/debugpage に続いて、
>接触履歴がある場合とない場合
について、実装し始めています。

問題は、その仕掛けなのですが、Debug_Mock 以外のDebugでも 同じDebugPage にするため、
1. DebugPageにENをストップ、スタートするボタンを付けて
2. ストップするとカウンタを回し
3. 回ったカウンタで高リスク接触を出すようDetectExposuresAsyncを改変し
4. DebugPageのFetchExposureKeyAsync をボタンを押すごとに陽性者と接触する
という思いつきました。この案は、ENのストップを実質的に担当する
https://github.com/cocoa-mhlw/cocoa/blob/ed5b702b425e460e475efa95622cfe4b7feeea88/Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs#L26-L30
に実装することで可能になります。（その過程で #167, #169が出ました）
<img width="363" alt="debugpage2" src="https://user-images.githubusercontent.com/4100714/118140069-fc612c00-b442-11eb-9132-50b11b95151c.png">

このような実装案でどうでしょうか？（今こちらでは、Debug_Mock でバックグラウンド通知が来るかもと思って放置しています）

**Comment by keiji** [comment]
@i-maruyama 
Issue本題とは直接関係ないんですが、貼っていただいているスクリーンキャプチャ。
英語表示なのに、接触数のところだけ「1個」って日本語で表記されていますね……これ別のIssueにしたいので画像使わせてもらっていいでしょうか。

こういうことも調べられるデバッグページ、いいですね！

**Comment by i-maruyama** [comment]
>これ別のIssueにしたいので画像使わせてもらっていいでしょうか。
もちろんです。お願いします。

**Comment by i-maruyama** [comment]
少し問題を切り分けたいと思います。

1. DebugPage の作成（本 issue PR #178)
2. DebugPage を含む不要ファイルのバイナリからの削除( #114 に引き受けてもらうようコメント。第１案ItemGroup　利用)
3. Debug_Mock の新機能追加と対応する DebugPage (接触発生させる機能追加です。新しく別issueを立てます)
4. ホーム画面への情報表示( LastProcessTekTimestamp と確認日時)#128

上記 1についてのみ、一度 PR #178 を作成しました。

- 目的： Debugと Debug_Mockビルドのとき(#if DEBUG利用)のみ、メニューに現れる DebugPage を作成します。

- ページ表示用３ファイルを追加 DebugPage.xaml, DebugPage.xaml.cs, DebugPageViewModel.cs
- #if DEBUG により、メニューにのみ追加 MenuPageViewModel.cs
- #if DEBUG により、ナビゲーション出来るように追加 App.xaml.cs

デバグ情報は以下です。
- OS情報とBuildオプション DEBUG, USE_MOCK
- json の情報のうち、  appVersion, supportedRegions, apiUrlBase, cdnUrlBase (後者２つは現在のDEBUG_MOCKでは不要ですが、後の利用を想定しています）
- ユーザー許可の有無 Agree (この情報を使って SplashPage を分岐します)
- 開始日時 StartDate （時刻付きです）
- 試用日数 DaysOfUse (ホーム画面と同じ情報)
- 接触人数 ExposureCount  (ホーム画面の「接触確認ボタン」で現れる数です。現状のDEBUG_MOCKではゼロです）
- TEK最新日時一応変換したつもり LastProcessTekTimestamp (現在のDEBUG_MOCKでは無意味です)
- TEK最新日時long LastProcessTekTimestamp
- EN 状態 EN
- ENS 状態 ENS
- ページ表示日時 Now (リロードしないと変わりません)

機能ボタンは, 以下になっており、多くはSettingsPageViewModel.cs の「使用中止」ボタンの機能を分割しているだけです。
- 情報再表示 Reload
- EN開始 StartExposureNotification
- EN終了 StopExposureNotification  (start & stop で、「ENをONにしてメッセージ」を見ることが出来ます）
- DL & OS接触確認 FetchExposureKeyAsync
- 開始日数の消去 RemoveStartDate
- EN情報の消去 RemoveExposureInformation
- ENコンフィギュレーションの消去 RemoveConfiguration
- TEK最新日時の消去 RemoveLastProcessTekTimestamp
- ユーザー許可の消去 RemoveAllUpdateDate
- 終了 Application.Current.Quit(); DependencyService.Get<ICloseApplication>().closeApplication();

各ページへのナビゲーションボタン
+ App.xaml.cs のソースコードに１対１対応させるというルールで作成し、ルールはソースコードにコメントしました。
