### ISSUE TITLE
【質問】COCOA に関連するツールの公開について

### ISSUE THREAD

**Issue by Takym** [cocoa-mhlw/cocoa#161]
アプリのお問い合わせ画面からメールを送らせて頂きましたが、一週間程経っても返信が届きませんでしたのでこちらで質問させて頂きます。接触確認アプリのログファイル(動作情報ファイル)を読み込み、日本語に変換して表示するツールを開発しましたが、これを GitHub にてMITライセンスで公開しても宜しいでしょうか？ツールの名前は `CocoaLogViewer` にしましたが、COCOA のコードは利用せずに開発しました。

**Comment by heykuro** [comment]
@Takym  さん、ありがとうございます。ゴールデンウィークもあり回答が遅れてしまったようです。申し訳ありません。
いただいた内容についてですが、こちらで回答させていただきます。

・任意の取り組みとしてツールを公開いただくことは問題ありません。
・ただ、(念のためですが)政府として推奨、公認という形は少なくとも現時点では難しいため、その点はご了承ください。
・また、ログについてはCOCOAとして定めている保持期間のルールがありますが、今回開発されたサービスにユーザーの方がログ情報を登録、公開される場合については、COCOAのプライバシーポリシー、利用規約の範囲外とし、登録、公開する方の責任において実施いただくこととなります。この点もご了承いただければと思います(→ツールの詳細機能がわからずに書いていますので、特に懸念すべき点が無ければこの点は無視してください)。

GitHubでのコミュニティとしての活動含め、今後もCOCOAの改善についてご協力いただけますと幸いです！

**Comment by Takym** [comment]
@heykuro さん、ご返信ありがとうございます。
ログ情報はアプリのお問い合わせ画面から利用者の意思で抽出する様にしていますので、問題は無いと思います。

**Comment by Takym** [comment]
https://github.com/YigtyORG/CocoaLogViewer にてリポジトリを開きましたのでこの Issue は閉じます。ありがとうございました。
