### ISSUE TITLE
MATを廃止して文字列リソースを管理する

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#162]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

#153 より。

COCOAは現在、Multilingual App Toolkit（MAT）を使って多言語対応（文字列リソース管理）をしている。

MATはWindows専用で、Visual Studio for macからは利用できない。自動翻訳等の便利な機能も現在は使っていない。
言語リソースの追加や削除の手順が煩雑で、またAppResources.*.resxの再生成時にライセンス通知が削除されるため都度付け直す必要がある。

## 解決策についてお書きください / Describe the solution you'd like

MATを廃止して、AppResources.*.resxで文字列リソースを管理していく。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

他の多言語対応のリソース管理ツールキットを採用する。

## その他 / Additional context

残す言語リソースを決める。

COCOAは公式には日本語・英語・中国語に対応しているが、その他の言語対応についてもコントリビュートされている。
一方、翻訳はされていないのにMATによってファイルが生成されている言語もありそうなので調査する。

合わせて、今後、未対応の言語リソースの翻訳が提供された場合の受け入れ体制について開発チームとともに検討していく必要がある。

----
Internal Tracking ID: NFR 2260

**Comment by Takym** [comment]
PR を作成しました。これを #149 や #154 にマージしても宜しいでしょうか？

**Comment by Meiryo7743** [comment]
@keiji 

お手すきの際に Wiki の「[多言語対応時の文字列リソースの追加・変更について](https://github.com/cocoa-mhlw/cocoa/wiki/%E5%A4%9A%E8%A8%80%E8%AA%9E%E5%AF%BE%E5%BF%9C%E6%99%82%E3%81%AE%E6%96%87%E5%AD%97%E5%88%97%E3%83%AA%E3%82%BD%E3%83%BC%E3%82%B9%E3%81%AE%E8%BF%BD%E5%8A%A0%E3%83%BB%E5%A4%89%E6%9B%B4%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)」の更新もお願いしたく存じます。

**Comment by keiji** [comment]
@Meiryo7743 
更新しました！（すっきりした

**Comment by Takym** [comment]
過去バージョンのソースを読まれる方のために残しておいても良かった気がします。

**Comment by Meiryo7743** [comment]
https://github.com/cocoa-mhlw/cocoa/wiki/%E5%A4%9A%E8%A8%80%E8%AA%9E%E5%AF%BE%E5%BF%9C%E6%99%82%E3%81%AE%E6%96%87%E5%AD%97%E5%88%97%E3%83%AA%E3%82%BD%E3%83%BC%E3%82%B9%E3%81%AE%E8%BF%BD%E5%8A%A0%E3%83%BB%E5%A4%89%E6%9B%B4%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6/_history

Wiki の編集履歴から過去のページを遡って閲覧できます。

**Comment by keiji** [comment]
せっかくなので履歴へのリンクを追加しておきました。
