### ISSUE TITLE
Debug_Mock での StopAsyncの bug-fix

### ISSUE THREAD

**Issue by i-maruyama** [cocoa-mhlw/cocoa#167]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

Debug_Mock ビルドで EN の停止が正常に機能していません。

## 解決策についてお書きください / Describe the solution you'd like

https://github.com/cocoa-mhlw/cocoa/blob/ed5b702b425e460e475efa95622cfe4b7feeea88/Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs#L26-L29

を true から false に変更しバグをなくす。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

放置することも１案です。 EN の停止は唯一「アプリの使用停止」で使われるだけで、しかも上記バグは Debug_Mock ビルドにしか影響していません。

## その他 / Additional context

できれば放置せず、バグを潰しておいていただけると、 DebugPage (#160) を作りやすいです。

念の為、 Debug_Mock の Covid19Radar.UnitTests は改変前と改変後で実施して変わらない（エラー２箇所が同じ場所）事は確認しています。

**Comment by i-maruyama** [comment]
一行変えただけですがPRを作ってみました。

詳しく説明すると、StartAsync では trueにして、 StopAsync では false にするはずが、両方 true になっています。
https://github.com/cocoa-mhlw/cocoa/blob/ed5b702b425e460e475efa95622cfe4b7feeea88/Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs#L20-L30

正しく false に直すことで、以下の IsEnableAsync と対応させることができます。
https://github.com/cocoa-mhlw/cocoa/blob/ed5b702b425e460e475efa95622cfe4b7feeea88/Covid19Radar/Covid19Radar/Services/TestNativeImplementation.cs#L32-L36

**Comment by i-maruyama** [comment]
#191　に取り込まれたため、 close します。

**Comment by keiji** [comment]
#191 のfeature branchに伴い、こちらは独立で対応しましょう
