### ISSUE TITLE
接触チェックに漏れが発生する可能性について

### ISSUE THREAD

**Issue by yoshitomo-g** [cocoa-mhlw/cocoa#17]
iOS版のコードを追いかけていて気が付いたのですが、zipファイルのダウンロード完了後に処理が中断した場合、この時のzipファイルに含まれる診断キーとの接触チェックが行われずに漏れてしまうように思えます。具体的には、次の行以降です。
https://github.com/cocoa-mhlw/cocoa/blob/3eac4f45e6bcb5f488cc8116854725eaf5dd62cb/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L164

この行のメソッドでは、各zipファイルの`Created`の値を、最後にダウンロードしたzipファイルの`Created`である`lastTekTimestamp[region]`と比較し、ダウンロードするかどうかを決めています。
https://github.com/cocoa-mhlw/cocoa/blob/3eac4f45e6bcb5f488cc8116854725eaf5dd62cb/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L234-L274

`lastTekTimestamp[region]`はダウンロード毎に更新されます。すべてのzipファイルがダウンロードされると`lastTekTimestamp`が`userData.LastProcessTekTimestamp`に反映され、直後に`userData`の保存処理が呼ばれます。
https://github.com/cocoa-mhlw/cocoa/blob/3eac4f45e6bcb5f488cc8116854725eaf5dd62cb/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L276-L277

接触チェックはダウンロード後に行われるため、ダウンロードしかしていなくても`userData.LastProcessTekTimestamp`が更新され、次回のダウンロードに参照されます。

チェックの対象になるのは直前のダウンロードされたzipファイルのみなので、未チェックのファイルを見つけてこれに加えるような仕組みがないのであれば、冒頭で挙げたところで中断した場合は、その分が対象になりません。
https://github.com/cocoa-mhlw/cocoa/blob/3eac4f45e6bcb5f488cc8116854725eaf5dd62cb/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L176

C#のコーディング経験がないため勘違いもあるかもしれませんが、影響が大きいと思いましたので検証していただけると幸いです。

----
Internal IDs:
- Bug 1518

**Comment by keiji** [comment]
@yoshitomo-g 047b12bfc497e5e32bd96e24c2b5d76c8ca18bcf の変更で、すべてのTEKのダウンロード完了後に更新に変わっていますね。

https://github.com/cocoa-mhlw/cocoa/blob/b823e87df6986d91d2b06b6ff9a4b2b94bf5c0e4/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L231-L269

**Comment by yoshitomo-g** [comment]
データの持ち方は変わりましたが、根本的なところでは変わっていないのではないでしょうか。

チェックまでのプロセスは次のように分けられると思うのですが、3で中断してしまった場合に、その続きから再開されるのではないというのが懸念事項です。1、3、2の順であれば良さそうですが。

1. ダウンロード
2. 最後の `tekItem.Created` をアプリデータに反映
3. チェック

私の見落としているだけで解消できているようであれば、Closeで構いません。

**Comment by b-wind** [comment]
ここで LastProcessTekTimestamp 更新してしまっているのがタイミングとして早いと言う事でしょうか。
接触チェック前なのにチェックした事になってしまっている。
（コードを追い切れてないので私はまだ接触チェックのタイミングがどこか追い切れてません）

https://github.com/cocoa-mhlw/cocoa/blob/047b12bfc497e5e32bd96e24c2b5d76c8ca18bcf/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L266


対案としては以下のどちらかになるでしょうか。
1. LastProcessTekTimestamp の更新を接触チェック後に移動する（できるかどうか？）
2. トランザクションの様な仕組みを利用してエラーが出たらデータを巻き戻す

**Comment by yoshitomo-g** [comment]
> ここで LastProcessTekTimestamp 更新してしまっているのがタイミングとして早いと言う事でしょうか。
> 接触チェック前なのにチェックした事になってしまっている。
> （コードを追い切れてないので私はまだ接触チェックのタイミングがどこか追い切れてません）

そうです。厳密に言えば、どこまでダウンロードしたかを管理して、チェックについてはダウンロードに依存している形ですね。
チェックは次のメソッドの第1引数を166行目でコールバックしていて、
（ダウンロードは154行目）
https://github.com/cocoa-mhlw/cocoa/blob/b823e87df6986d91d2b06b6ff9a4b2b94bf5c0e4/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L129-L194

メソッドの呼び出しとコールバックの中身は次のようになっています。
https://github.com/cocoa-mhlw/cocoa/blob/b823e87df6986d91d2b06b6ff9a4b2b94bf5c0e4/Covid19Radar/Xamarin.ExposureNotification/ExposureNotification.shared.cs#L88-L120

正常に動作していれば問題なさそうですが、中断された場合は前日24時間分として配信された TEK がチェックされないことになるかと。今のところ配信は1日に1回で、アプリ側では新規配信がないかを1日に複数回確認しています。

> 対案としては以下のどちらかになるでしょうか。
> 
>     1. LastProcessTekTimestamp の更新を接触チェック後に移動する（できるかどうか？）
>     2. トランザクションの様な仕組みを利用してエラーが出たらデータを巻き戻す
1のほうが良い感じがしますが、`LastProcessTekTimestamp` に相当する値が途中までしか残らないので大変かもしれません。

検証できないのでアルゴリズムだけになりますが、簡易的なトランザクションとしてこのような方法はどうでしょうか。
チェックはチェックで別管理（仮に `LastChekTekTimestamp` とします）して、正常に完了したら `LastProcessTekTimestamp` をコピーします。ダウンロードの開始前に比較して一致していなかったらチェック未完了なので、ダウンロードの基準を `LastProcessTekTimestamp` ではなく `LastChekTekTimestamp` にします。TEK は外部にあるので、巻き戻すのではなく単純に再実行します。

**Comment by b-wind** [comment]
> 1のほうが良い感じがしますが、LastProcessTekTimestamp に相当する値が途中までしか残らないので大変かもしれません。

「途中までしか残らない」意味を取りかねました。


何を持ってTEKの処理完了とすべきか？に付いて考えてみました。
判断材料として openCACAO の方で考察された以下のシーケンス図を参考にしています。
https://github.com/openCACAO/cocoa-issues/issues/31


結論としては、UserExposureInfo （接触情報）をアプリケーションが保存できた時、一連の処理を完了し再試行の必要等が無くなると言う判断です。

UserExposureInfo 自体はこちらで生成・リストに保存しています。（アプリケーションデータとしての保存はまだのはず）
https://github.com/cocoa-mhlw/cocoa/blob/b823e87df6986d91d2b06b6ff9a4b2b94bf5c0e4/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L111-L112

その後、 ExposureNotificationService. SetExposureInformation を呼び出し、
（これ、ログは後ろにあるべきでは）
https://github.com/cocoa-mhlw/cocoa/blob/047b12bfc497e5e32bd96e24c2b5d76c8ca18bcf/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L120-L122

該当メソッドの中で JSON シリアライズした上で、SecureStorageService に保存しています。
https://github.com/cocoa-mhlw/cocoa/blob/047b12bfc497e5e32bd96e24c2b5d76c8ca18bcf/Covid19Radar/Covid19Radar/Services/ExposureNotificationService.cs#L226-L234


SetBytes で保存されると仮定すれば  ExposureNotificationService. SetExposureInformation の末尾で  LastProcessTekTimestamp を更新すれば目的を達成できるように思います。

**Comment by keiji** [comment]
@yoshitomo-g @b-wind 

#68 の変更でどうですか？

`DownloadBatchAsync`に引数で`lastCreated`を与えて、戻り値で`newCreated`を受け取って、そのリージョンの接触チェックがすべて終わったら保存する流れです。

**Comment by b-wind** [comment]
少し戸惑っているというか、私の理解が正しいか自信が無いので確認させてください。

COCOA のメインページから「陽性者との接触を確認する」ボタンを押した後のページで表示されるのは
PreferenceKey.ExposureInformation に保存されてる値だと思うのですがどうでしょう？

https://github.com/cocoa-mhlw/cocoa/blob/047b12bfc497e5e32bd96e24c2b5d76c8ca18bcf/Covid19Radar/Covid19Radar/ViewModels/HomePage/ExposuresPageViewModel.cs#L24-L34

#68 で変更された SetLastProcessTekTimestamp の実行は現状と同じく SetExposureInformation より前の為、
LastProcessTekTimestamp は更新されるが、ExposureInformation が更新されていないと言う状態があり得ます。

これは現象としては、接触の通知は行われるがアプリを開いても接触の履歴が見られないという事にならないでしょうか。

自分としては SetExposureInformation が実行された後に SetLastProcessTekTimestamp を実行するのが確実に思えます。

**Comment by keiji** [comment]
> COCOA のメインページから「陽性者との接触を確認する」ボタンを押した後のページで表示されるのは
PreferenceKey.ExposureInformation に保存されてる値だと思うのですがどうでしょう？

その理解で正しいと思います。

> #68 で変更された SetLastProcessTekTimestamp の実行は現状と同じく SetExposureInformation より前の為、
LastProcessTekTimestamp は更新されるが、ExposureInformation が更新されていないと言う状態があり得ます。
> これは現象としては、接触の通知は行われるがアプリを開いても接触の履歴が見られないという事にならないでしょうか。

その事象は発生しないとぼくは考えています。

このIssueで指摘されている事象は「複数の診断キーをダウンロード中に、途中で通信が切断するなどの原因でダウンロードが中断し、再度ダウンロードした際に、前回の処理でダウンロードできてしまった診断キーについては『接触確認済』として取り扱われるので、本来されるべき接触確認が実行されない」と言うものと認識しています。

現在の処理では`LastProcessTekTimestamp`のタイムスタンプより後の診断キー（バッチ）をダウンロードするようになっていること。`LastProcessTekTimestamp`の更新タイミングが「接触確認の実行」ではなく、診断キー（バッチ）のダウンロードする都度になっていることが原因と理解しています。

さて、ご指摘の`SetExposureInformation`の更新については`ExposureDetectedAsync` 内で行われています。

https://github.com/cocoa-mhlw/cocoa/blob/b823e87df6986d91d2b06b6ff9a4b2b94bf5c0e4/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L120-L122

`ExposureDetectedAsync`が呼び出されるのは`FetchExposureKeyBatchFilesFromServerAsync`に与えている`Func<IEnumerable<string>, Task> submitBatches`の中です。

https://github.com/cocoa-mhlw/cocoa/blob/b823e87df6986d91d2b06b6ff9a4b2b94bf5c0e4/Covid19Radar/Xamarin.ExposureNotification/ExposureNotification.shared.cs#L88-L120

#68 の変更では、`exposureNotificationService.SetLastProcessTekTimestamp`は`submitBatches`より後に置いていますから、接触確認が終わった診断キー（バッチ）の`lastCreated`が更新されていくと理解しています。

**Comment by b-wind** [comment]
> ExposureDetectedAsyncが呼び出されるのはFetchExposureKeyBatchFilesFromServerAsyncに与えている
> Func<IEnumerable<string>, Task> submitBatchesの中です。

実のところこのあたりの理解が曖昧なのですが、単に私の言語理解が浅いことが理由なので一端疑問は置いておきます。

その他の点については特に問題無いと考えています。私からは以上ですね。

**Comment by keiji** [comment]
一晩考えてみたのですが、これは結構根の深い問題でXamarin.ENの変更が必要になりそうです。

## 接触確認に漏れが発生する可能性

「なにをもって接触確認を終えたと言うか」で対応が変わってくるのですが、
「`submitBatches`を実行したら」という意味では #68 で足ります。

ただ、実際の接触確認は`submitBatches`の中で行われていて、さらにAndroidとiOSで処理が異なります。

https://github.com/cocoa-mhlw/cocoa/blob/b823e87df6986d91d2b06b6ff9a4b2b94bf5c0e4/Covid19Radar/Xamarin.ExposureNotification/ExposureNotification.shared.cs#L88-L123

iOSの方は`PlatformDetectExposuresAsync`を呼んでから、接触があれば`ExposureDetectedAsync`を呼ぶという構造です。つまり、`submitBatches`が呼ばれたら接触確認が終わったと言えると考えます。

一方Androidでは`PlatformDetectExposuresAsync`を呼ぶまでは同じですが、その結果はBroadcastRecieverで受け取るので、ここで`ExposureNotificationHandler`から離れてしまいます。

https://github.com/cocoa-mhlw/cocoa/blob/b823e87df6986d91d2b06b6ff9a4b2b94bf5c0e4/Covid19Radar/Xamarin.ExposureNotification/CallbackService.android.cs#L13-L33

このBroadcastReceiverが呼ばれた時点が接触確認が終わったと言えます。
これを受け取らずに`LastProcessTekTimestamp`が更新されてしまうと、万が一Google Play ServicesやEN APIに以上があって接触確認がうまくいかなかった場合に、取りこぼしが起きる可能性があります。本来は接触があって検査の必要なユーザーに通知が届かず、必要な検査や医療措置が遅れる可能性があります。
COCOAの目的と重要性を考えれば、ここは確実にケアしておくべきとぼくは考えています。

## 修正について

修正についてですが、問題は、このBroadcastReceiverがXamarin.ENの中にあることです。現時点でプロジェクトの中にあるので変更はできますが、将来のことを思えば触りたくないなという気持ちがあります。

代替案として考えたのは、`ExposureNotificationCallbackBroadcastReceiver`と同じIntent-Filterを持つBroadcastReceiverを作って、そこでも結果を受け取ることです。その場合、`AttemptProcessTekTimestamp`のような中間値を作って取り回して、実際に処理が完了した時点で`LastProcessTekTimestamp`に設定するという方法が考えられます。

この方法を採る上での課題は、iOSとAndroidで`LastProcessTekTimestamp`の更新処理がぶつかると言うことです。iOSの方は`submitBatches`の直後に`LastProcessTekTimestamp`の更新を置くのが適切です。Androidでは、そこで更新してしまうとチェック漏れが発生する可能性があります。

iOS側ではXamarin.ENの外に「接触がなかった」と言うイベントを検出する手段が提供されていません（Androidでは`ACTION_EXPOSURE_NOT_FOUND `）。
これは最新のXamarin.ENでも同様なので、場合によってはPullRequestを送るなどする必要がありそうです（PullRequestを送った上で、暫定的にCOCOA内のXamarin.ENを変更するのは問題が起こりにくそう）。

ひとまず本IssueはPRも含めてCloseせず、検討を継続していきたいと考えています。

**Comment by yoshitomo-g** [comment]
見れていない間に話が大きくなっていて、今更になってしまうかもしれませんが・・・。

@b-wind
> > 1のほうが良い感じがしますが、LastProcessTekTimestamp に相当する値が途中までしか残らないので大変かもしれません。
> 
> 「途中までしか残らない」意味を取りかねました。

わかりにくい表現で失礼しました。変数としては `DownloadBatchAsync` の中でしか存在せず、メソッドを抜けた時点で消えてしまうという意味です。（#68 では引数の扱いを変えることでこれが解消されたことになります）

この値は複数の TEK をまとめたzipファイルのタイムスタンプで、`DownloadBatchAsync` の下記行でダウンロードする `list.json` での記述が大元です。中身は2次元配列のJSONです。
https://github.com/cocoa-mhlw/cocoa/blob/b823e87df6986d91d2b06b6ff9a4b2b94bf5c0e4/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L223

配列をループ処理しながら、zipファイルのダウンロード（L240~257）とタイムスタンプである `newCreated` の更新（L258)をして、ループ終了後に `LastProcessTekTimestamp` の更新に使われるのが最後です。v1.2.2の時点では、メソッド内で完結しています。
https://github.com/cocoa-mhlw/cocoa/blob/b823e87df6986d91d2b06b6ff9a4b2b94bf5c0e4/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L231-L267

@keiji
> このIssueで指摘されている事象は「複数の診断キーをダウンロード中に、途中で通信が切断するなどの原因でダウンロードが中断し、再度ダウンロードした際に、前回の処理でダウンロードできてしまった診断キーについては『接触確認済』として取り扱われるので、本来されるべき接触確認が実行されない」と言うものと認識しています。
> 
> 現在の処理では`LastProcessTekTimestamp`のタイムスタンプより後の診断キー（バッチ）をダウンロードするようになっていること。`LastProcessTekTimestamp`の更新タイミングが「接触確認の実行」ではなく「診断キー（バッチ）のダウンロードが完了した直後」になっていることが原因と理解しています。

私の認識と少し違うようなので、すり合わせをさせてください。

危惧しているタイミングは「複数の診断キーをダウンロード中に」ではなく、`LastProcessTekTimestamp` の更新後からチェック結果が `ExposureInformation ` に反映されるまでの間です。`LastProcessTekTimestamp` の更新はダウンロードが終了した後ですので、`DownloadBatchAsync` のループ処理中であれば問題ないと考えています。原因のほうはそれで問題ありません。

**Comment by tmurakami** [comment]
#68 に先に書いてしまいましたが、私自身は`submitBatches()`の後に`LastProcessTekTimestamp`を保存すれば十分なのではないかと考えています。
exposure-notifications-android (EN Expressのベース)でも`provideDiagnosisKeys()`の後に最新TEKアーカイブパスを保存しているようなので。

EN に関する懸念事項を Google に確認することはできないのでしょうか？

**Comment by zipperpull** [comment]
わたしも Google に聞いたほうが早そうという気がしますが。

https://github.com/cocoa-mhlw/cocoa/pull/68#issuecomment-803974624 で @tmurakami さんが参照されているのは
EN v2 (v1.5) 対応後の exposure-notifications-android のソースなのが若干気になります。

EN v1 時代の最後のものは 2020-06-26版 https://github.com/google/exposure-notifications-android/tree/1b215ca7fc99cac292b56a87751421bd1065df75 ですがそもそも downloadServerRepo にあたる
コードがなくて、TEKをどこまで処理したかの情報を取り扱っていなさそうな感じです(考慮されていない？)

v1/v2 など見比べてみての想像なのですが EN v1 が deprecated になった理由の一つが、https://github.com/cocoa-mhlw/cocoa/issues/17#issuecomment-803545271 でも
指摘されている、「通知 (notification) とアプリ内のデータとが整合が取れなくなる場合がある」という
問題なのではないかと思えてきました。

つまり、Android 版の EN v1 では

1. provideDiagnosisKeys 呼び出し
2. broadcast 受信
3. getExposureSummary 呼び出し
4. getExposureInformation 呼び出し
5. 戻り値をアプリ内表示用に保存

という処理順序で 4. まで実行して初めて通知(notification)が表示されるので、
@keiji さんの指摘通り、3. までで止まった場合は通知も表示されずアプリにも表示されない
パターンがあり得ますし、4. で止まった場合は通知は出たけれどアプリ内に表示されないという
可能性があると思います。なので、結局のところ 5. まで終わったところで処理完了とする
(5. まで完了しなかった場合は再度 1. からやり直すので二重通知されることがある) という実装にするのが安全そうです。

上記の EN v1 のころのサンプルでも token を全部呼び出し時に保存して

https://github.com/google/exposure-notifications-android/blob/1b215ca7fc99cac292b56a87751421bd1065df75/app/src/main/java/com/google/android/apps/exposurenotification/nearby/ProvideDiagnosisKeysWorker.java#L106

Receiver の処理が完了したら処理済みとしてmarkするような実装をしているようです

https://github.com/google/exposure-notifications-android/blob/1b215ca7fc99cac292b56a87751421bd1065df75/app/src/main/java/com/google/android/apps/exposurenotification/nearby/StateUpdatedWorker.java#L120

(mark されなかったのはどうするんだろうか？)

これをいくら厳密に直しても二重通知は回避できないので、EN v1.5 以降では token の概念を捨てて、
provideDiagnosisKeys が完了したらそこで atomic に処理完了とみなすことができて、
getExposureWindows は引数もないし何回呼び出しても同じ結果が常に返されるようになっているのではと推測します
(もしかしたら最後の provideDiagnosisKeys の呼び出しに対応する結果が返ってくるのかもですが
それはちょっと仕様としてはダメな気が。)

なので、諸々考え合わせると Google に問い合わせると EN v1.5 以降最新版にしてねという答えが返ってきてしまいそうな気がします。

あと、iOS 側の getExposureWindows は引数に ENExposureDetectionSummary を取る 
(v1 の getExposureSummary と同じように detectExposures のコールバックから呼ばれる前提) 
なので、そもそも同じようなメソッドだけど同じ結果が返ってくるのか(Xamarin.EN でちゃんと共通化できるのか) という
疑問が出てきますね。。

https://developer.apple.com/documentation/exposurenotification/enmanager/3644438-getexposurewindows

**Comment by tmurakami** [comment]
@zipperpull ご説明ありがとうございます。理解できました。

個人的には暫定で良いので`submitBatches()`の後に更新するよう対応頂きたいと思っています。
そうすれば iOS は多分大丈夫でしょうし、Android も`provideDiagnosisKeys()`まではケアできます。
もちろんそれ以上の対応がすぐにできるのであれば、それに越したことはないのですが...

今年 1月の`provideDiagnosisKeys()`障害( https://github.com/corona-warn-app/cwa-app-android/issues/2081 )のこともあり、本 issue の状況がとても気になっています。

**Comment by zipperpull** [comment]
わたしも @tmurakami さんや @yoshitomo-g さんがおっしゃるように

> submitBatches()の後に更新するよう対応

ひとまずここまでを早めに(できるなら今回リリースで？)対応いただくのがよさそうと思いますが
難しそうでしょうか？

https://github.com/cocoa-mhlw/cocoa/pull/68/commits/43275b87f7bd7ec08553adf3c0a43ed716839ef9

だけマージする必要があるイメージで合っていますよね？

**Comment by tmurakami** [comment]
> イメージで合っていますよね？

はい、そのイメージです。

**Comment by keiji** [comment]
ありがとうございます。寝て起きたらいろいろ情報が出ていて驚いています。

@yoshitomo-g 

> 私の認識と少し違うようなので、すり合わせをさせてください。

ご指摘の通り「ダウンロード中断時に…」というのは、ぼくの認識に誤りがありました（PRを作っていて気づきました）。

@tmurakami @zipperpull

#68 についてはひとまず 43275b8 のみに変更する方向でいきます。EN APIに関してはGoogle（およびApple）から協力を得ることができるフローがあるので、引き続き調査を進めていきたいと考えています。

ぼくとしては昨日の朝に改善に着手した時に、修正自体は単純なものだろうと思っていたのですが、複雑な迷路に迷い込んだ感じです。

`provideDiagnosisKeys`のドキュメントを見ると、"After the result Task has returned, files can be deleted."とあって、ファイルを消すのは問題ないのだなと思いますが、やはり「接触確認が完了したタイミング」は確信が持てません。

https://developers.google.com/android/reference/com/google/android/gms/nearby/exposurenotification/ExposureNotificationClient?hl=en#provideDiagnosisKeys(com.google.android.gms.nearby.exposurenotification.DiagnosisKeyFileProvider)

https://github.com/corona-warn-app/cwa-app-android/issues/2081 についても情報ありがとうございます。不勉強ながらぼく自身がこの事例を知らなかったので、とても勉強になります。

**Comment by zipperpull** [comment]
一応イギリスの issue はこちらです
https://github.com/nihp-public/covid-19-app-android-ag-public/issues/39

この #17 とは別問題じゃないかとは思いますが。。(原因不明なのでわかりませんけど)

**Comment by b-wind** [comment]
すでに皆さんがコメントされているので今更なのですが、私も一端 https://github.com/cocoa-mhlw/cocoa/commit/43275b87f7bd7ec08553adf3c0a43ed716839ef9 までを採用する案に賛成です。
ここまでは純粋な改善であり、リグレッションの心配も薄いでしょう。

もちろんその後の @keiji さんの試行錯誤が意味が無いという訳では無く、いずれ解決しなければならない重大な課題と認識しています。

**Comment by zipperpull** [comment]
Google の provideDiagnosisKeys の仕様だと Task が返されるので、broadcast 送信までは完了した時点で
Task は Success 状態にはなるのかなとは思えますね(仕様にはそこまで明記されていないけど)

https://developers.google.com/android/reference/com/google/android/gms/nearby/exposurenotification/ExposureNotificationClient?hl=en#public-abstract-taskvoid-providediagnosiskeys-listfile-keyfiles,-exposureconfiguration-configuration,-string-token

もしそうなると仮定すると、呼び出し前に token を保存して、Success した token のぶんは
フラグを立てておけば、14日以内ならあとから(broadcast の文脈以外でも)
getExposureSummary を呼べばデータは取り出せて通知もそこで出す(https://github.com/cocoa-mhlw/cocoa/issues/17#issuecomment-804097816 でいうと 3以降を後からやる)
仕組みを追加することはできそうかなと思いました。それができる仕組みであれば、
Task が Success したらファイルを消してもよい、という仕様と矛盾はなさそうです。
(ほとんど推測なので万が一やるとしても Google に聞いてみてからで)

**Comment by keiji** [comment]
今のXamarin.ENあとtokenはXamarin.ENの中で生成しているので、そこを変えないといけませんね。
フラグ管理とか入ってくるとDatabaseで持った方がいい気がしますが……ひとまずステータスをwaiting-for-confirmationにして、進展があれば共有しますね。

**Comment by keiji** [comment]
#68 の変更が効果があることを確認できました。

https://twitter.com/h_okumura/status/1404221661591658499

`detectExposureを`したときに`ENErrorDomain Code=16 "(null)" UserInfo={cuErrorMsg=Database inaccessible}`が返ってくるケースが見つかりました。
v1.2.2以前では`LastProcessTekTimestamp`が更新されているので取りこぼしが発生しますが、`LastProcessTekTimestamp`の書き換えタイミングを変更した、Android版のv1.2.3、ならびにiOS版のv1.2.4では修正されているという認識です。

**Comment by b-wind** [comment]
無事 iOS 版でもリリースされ、効果も確認されたようでホッとしています。
提案ですが、この Issue は一端ここで close してしまい、より詳細についての対応は新規 Issue で対応というわけには行かないでしょうか。

理由は単純で、リリースとIssueの対応を見るときに分かりにくくなりそうだと思ったからです。
この Issue は暫定対応、新しいIssueは根本対応という分け方であれば混乱も少ないと思うのですが。

**Comment by yoshitomo-g** [comment]
> 提案ですが、この Issue は一端ここで close してしまい、より詳細についての対応は新規 Issue で対応というわけには行かないでしょうか。

そもそもの懸念していたことが解消されたということであれば、私は close で良いと思います。https://github.com/cocoa-mhlw/cocoa/issues/17#issuecomment-804375212 で暫定対応という方針が出ていますし。
（ https://github.com/cocoa-mhlw/cocoa/issues/17#issuecomment-860302382 のエラーは、`submitBatches()` の中でロックされているファイルを更新しようとして中断したのだろうというくらいにしかわかっていません。）

**Comment by keiji** [comment]
@yoshitomo-g それでは本IssueはCloseしますね。
