### ISSUE TITLE
ビルド＆テスト例のWikiPage 

### ISSUE THREAD

**Issue by i-maruyama** [cocoa-mhlw/cocoa#173]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

- 本プロジェクトに新規貢献しようとしても、ビルドが成功しない問題。
- ビルド成功しても、Release を実行して「使えない」と判断する問題。

## 解決策についてお書きください / Describe the solution you'd like

- とりあえず Debug_Mock の実行成功例を、本プロジェクトの Wiki に書き溜める
- CONTRIBUTING.md には Wiki URLをリンクする。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

- 参考URLも可能。
- Debug_Mock ビルドを終点とする以外に、皆さんの API なども。

## その他 / Additional context

そもそも
https://github.com/cocoa-mhlw/cocoa/wiki
はさみしすぎる。

**Comment by i-maruyama** [comment]
こちらの成功例と失敗例を紹介しておきます。
- 成功: VisualStudio2019 16.8.7 on windows 10 Home にて Debug_Mock /  Any CPU  / Covid19Rador.Android の実行 
- エミュレータ Pixel 2 Q10.0 (Android 10.0 - API29) と実機 Aquos sense3lite

手順
1. （ここは不要な場合もあります）うっかりバージョンアップして動かなくなった VisualStudioを https://social.msdn.microsoft.com/Forums/ja-JP/2ef7e1c4-7a10-4b06-aa50-8e72d678fc8a/xamarin1239812480124541253112464125241254012489260412786112364124 に<del>驚きつつ</del>従って、アンインストール
2. VisualStudio Enterprise **16.8.7 2021 年 3 月 9 日** 16.8.31025.109 Enterprise をDL ( https://docs.microsoft.com/ja-jp/visualstudio/releases/2019/history#release-dates-and-build-numbers )
3. .NETによるモバイル開発のみインストール
4. MultilingualAppToolkitをインストール https://marketplace.visualstudio.com/items?itemName=MultilingualAppToolkit.MultilingualAppToolkit-18308
5. 実機をUSB接続して Debug_Mock /  Any CPU  / Covid19Rador.Android でビルドして、認証後 いつもの HomePage が出れば成功

失敗したポイントは**バージョン**です。16.7 系は、以下のエラーが出ました。
```
エラー	CS8370	機能 'using 宣言' は C# 7.3 では使用できません。8.0 以上の言語バージョンをお使いください。	Covid19Radar.Android	C:\Users\owner\source\repos\cocoa\Covid19Radar\Covid19Radar.Android\Services\DeviceCheckService.cs	41
```
- 16.7.2 2020 年 8 月 18 日 16.7.30413.136 Enterprise
- 16.7.14 2021 年 4 月 13 日 16.7.31205.176 Enterprise

また 16.9 系は、複雑なエラーが出ました。
+ 16.9.0 2021 年 3 月 2 日 16.9.31025.194 Enterprise =>配置エラー[これと同じ？](https://github.com/cocoa-mhlw/cocoa/issues/160#issuecomment-835403411)
+ 16.9.4 最新は以下のエラー
‘‘‘
エラー	CS1061	'RadioButton' に 'Text' の定義が含まれておらず、型 'RadioButton' の最初の引数を受け付けるアクセス可能な拡張メソッド 'Text' が見つかりませんでした。using ディレクティブまたはアセンブリ参照が不足していないことを確認してください	Covid19Radar	C:\Users\owner\source\repos\cocoa3\Covid19Radar\Covid19Radar\Views\HomePage\NotifyOtherPage.xaml.cs	24
‘‘‘

以上です。実際には windows 10 Home でエミュレータ(x86 )を高速に動かすためにいろいろしました。

**Comment by heykuro** [comment]
>そもそも
>https://github.com/cocoa-mhlw/cocoa/wiki
>はさみしすぎる。

おっしゃる通りですね。。

**Comment by i-maruyama** [comment]
Visual Studio Community 16.9.5 for win （現在の最新) でビルド成功したようです。いくつか警告が出るのですが、実機で実行を確認しました。もう一度、再インストールして確かめつつ手順書作りたいと思いますが、これなら無料なので貢献者も増えそうです。

**Comment by keiji** [comment]
ぼくはVisual Studio Community 8.9.9 for macを使っています。

ちなみにCOCOAをビルドするとき関連するコンポーネントのバージョンがあって、About Visual Studioの「Show Detail」ボタンで表示される一覧から確認できます。

```
=== Visual Studio Community 2019 for Mac ===

Version 8.9.9 (build 3)
Installation UUID: 2f92ef14-43de-4c71-be92-99ab22b4a4be
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 6.18.0.23 (d16-6 / 088c73638)

	Package version: 612000125

=== Mono Framework MDK ===

Runtime:
	Mono 6.12.0.125 (2020-02/8c552e98bd6) (64-bit)
	Package version: 612000125

=== Roslyn (Language Service) ===

3.9.0-6.21152.10+c10f884b30737542ddd84ca889a4aad9281ce210

=== NuGet ===

Version: 5.8.0.6860

=== .NET Core SDK ===

SDK: /usr/local/share/dotnet/sdk/5.0.203/Sdks
SDK Versions:
	5.0.203
	5.0.202
	5.0.201
	3.1.409
	3.1.408
	3.1.407
MSBuild SDKs: /Applications/Visual Studio.app/Contents/Resources/lib/monodevelop/bin/MSBuild/Current/bin/Sdks

=== .NET Core Runtime ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	5.0.6
	5.0.5
	5.0.4
	3.1.15
	3.1.14
	3.1.13

=== .NET Core 3.1 SDK ===

SDK: 3.1.409

=== Xamarin.Profiler ===

Version: 1.6.15.68
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 12.5 (18205)
Build 12E262

=== Xamarin.Mac ===

Xamarin.Mac not installed. Can't find /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/Version.

=== Xamarin.iOS ===

Version: 14.16.0.5 (Visual Studio Community)
Hash: ab40b131d
Branch: xcode12.5
Build date: 2021-04-22 08:56:42-0400

=== Xamarin Designer ===

Version: 16.9.0.324
Hash: b1e216c75
Branch: remotes/origin/d16-9
Build date: 2021-04-16 00:02:50 UTC

=== Xamarin.Android ===

Version: 11.2.2.1 (Visual Studio Community)
Commit: xamarin-android/d16-9/877f572
Android SDK: /Users/keiji_ariyama/Library/Android/sdk
	Supported Android versions:
		None installed

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 31.0.2
SDK Build Tools Version: 31.0.0 rc3

Build Information: 
Mono: 5e9cb6d
Java.Interop: xamarin/java.interop/d16-9@54f8c24
ProGuard: Guardsquare/proguard/v7.0.1@912d149
SQLite: xamarin/sqlite/3.34.1@daff8f4
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11

=== Microsoft OpenJDK for Mobile ===

Java SDK: /Users/keiji_ariyama/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android SDK Manager ===

Version: 16.9.0.22
Hash: a391de2
Branch: remotes/origin/dev/bretjohn/readme-tweak~3
Build date: 2021-04-21 21:23:40 UTC

=== Android Device Manager ===

Version: 16.9.0.17
Hash: fc2b3db
Branch: remotes/origin/dev/jmt/d16-9bump~1
Build date: 2021-04-21 21:23:58 UTC

=== Build Information ===

Release ID: 809090003
Git revision: 163d834aa64ba9129e5ef30e49a947ef67bcd809
Build date: 2021-05-06 10:14:43-04
Build branch: release-8.9
Xamarin extensions: 163d834aa64ba9129e5ef30e49a947ef67bcd809

=== Operating System ===

Mac OS X 10.16.0
Darwin 20.4.0 Darwin Kernel Version 20.4.0
    Thu Apr 22 21:46:41 PDT 2021
    root:xnu-7195.101.2~1/RELEASE_ARM64_T8101 x86_64
```

僕は特に「Xamarin.Android」のバージョンでトラブルに見舞われた経験が多いですね…

**Comment by i-maruyama** [comment]
初心者向けの手順書作った（パワポ）のですが、作ってからパワポは GitHub には向かないことを知りました。

[cocoa+win10+Android.pdf](https://github.com/cocoa-mhlw/cocoa/files/6525598/cocoa%2Bwin10%2BAndroid.pdf)

画像＋マークダウンにするのが良いのかな？
