### ISSUE TITLE
開発に係わる情報を 1 つの場所に集約する

### ISSUE THREAD

**Issue by Meiryo7743** [cocoa-mhlw/cocoa#175]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

#90 及び #113 では，開発に係わる情報が `CONTRIBUTING.md` に追記されました。他方，https://github.com/cocoa-mhlw/cocoa/pull/111#issuecomment-818327182 や #173 においては，そういった情報を Wiki に追加・あるいはその提起がなされました。

上記の経緯により，現状ドキュメンテーションが散在している状態です。

## 解決策についてお書きください / Describe the solution you'd like

開発に係わる情報を既存のいずれか 1 つの場所に集約する。Wiki に全面移行する場合は，`CONTRIBUTING.md` からの誘導も必要と思われる。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

第三の選択肢としては，このリポジトリ外で管理することも挙げられます（例：専用リポジトリの作成，サイトの開設など）。ただ，わざわざ手間のかかる方法を採るよりも，先述した「集約」の方が理に適っているでしょう。

**Comment by keiji** [comment]
書いていきます。

https://github.com/cocoa-mhlw/cocoa/wiki/COCOA%E3%81%AE%E3%83%93%E3%83%AB%E3%83%89%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

**Comment by Takym** [comment]
Configuration はそのまま構成で良いのではないでしょうか。

**Comment by keiji** [comment]
Configuration、今のところ変える予定はないですけど、Wikiの説明、変える意味合いになっちゃってますか？

**Comment by Takym** [comment]
「Configuration」(他にも「Build」等)の部分だけが英語になっていたので、日本語で書いた方が読み易いと思いました。参考までに Microsoft の公式サイトでは「構成」表記になっていました。https://docs.microsoft.com/ja-jp/visualstudio/ide/understanding-build-configurations?view=vs-2019

**Comment by keiji** [comment]
わかりました。うちのVisual Studio for macなんでConfigurationsなんだろうって思ったら、そういえばシステム設定、英語で使ってるんでした…。

基本、日本語表記を優先で、見出しに関しては「構成（Configuration）」といった表記でいきたいと思います。
書き進める中で「これは日本語で書いた方がいいよ！」という単語があれば指摘いただけるとありがたいです。

**Comment by tatsu-jp** [comment]
@keiji さん、
Wikiへのコントリビューションはどのように実施すれば良いのでしょうか。

ソースコードと同様に、レビューして本線マージというプロセスを踏む必要があると考えています。
やり方としては以下の2通りが考えられます。違いはデータの持ち方で後の手順は同じです。
リポジトリを複数管理する手間を考えると、方法1.の方が良いかなと思いますが・・・ご意見ください。
ちなみに、Wiki作成の参考にしていたvscodeプロジェクトでは方法2.のやり方でした。

コミットしたい内容は以下です。プロジェクトの活動内容やチケット内で知り得た有益な情報をドキュメント化して、コミュニティメンバーが参照できるようにしたいなと思います(色々な改善も進んでいるので見えるようにできればいいなと)。

https://github.com/tatsu-jp/cocoa/wiki

記載内容が合っているかどうかは、レビュー(認識合わせ)させていただければと思います。。。

### 方法1
1. 本リポジトリ以下に、wiki文書用のディレクトリを作成してドキュメントを追加
2. コード修正と同じように、プルリクエスト作成してレビュー実施
3. コラボレータ側でWikiへマージ

### 方法2
1. Wiki用のリポジトリを作成
2. コード修正と同じように、プルリクエスト作成してレビュー実施
3. コラボレータ側でWikiへマージ

**Comment by keiji** [comment]
@tatsu-jp GitHubのWiiにはPull Request機能がないので、たとえばですが、

1. Wiki用のブランチ docs/wiki を作成
2. 現在のWikiの内容をファイルとして移植
3. コード修正と同じように、プルリクエスト作成してレビュー実施
4. コラボレータ側でWikiへマージ

と言う過程がいいかもしれません。
人手の行程をGitHub Actionsで自動化できるか、そもそもWikiの編集は誰でも編集化に解放してしまう（変更履歴は見られるようにする）のが、一番楽ではありますね。

**Comment by tatsu-jp** [comment]
@keiji さん、
コメントありがとうございます。

GitHub Actionsで自動化する方法を検討しました。これでチェック作業のみになるかと思います。
https://github.com/tatsu-jp/cocoa/blob/docs/wiki/.github/workflows/Wiki.yml
(cherry pickできそうな気がしますが。。。rsyncで処理しています)

Wikiの編集権限を開放しても良いと思います。今はコンテンツがほとんど無いため編集権限を開放して、ある程度のコンテンツが集まってきたらレビュー制に移行する、でも良いと思います。

コントリビュータ視点では、作業は大して変わりませんが、コラボレータと認識合わせする機会があるかどうかが違います。
レビューあった方がコンテンツの内容が良くなりますが、COCOA V2開発の方が優先だと思うので・・・どちらが良いかは判断が難しいところです。

コラボレータはどちらの手番の方が都合良いのでしょうか。
都合の良い手番に合わせて、Wikiを改訂していきたいと思います。

**Comment by keiji** [comment]
#345 の通り、GitHub Pagesを使って管理することにしました。
Issueに対応するPullRequestの取り込み後、変更を提案してもらえれば！

**Comment by tatsu-jp** [comment]
@keiji さん、
ご検討ありがとうございます。Pages 良いですね！！
最新のコンテンツを確認してからプルリク上げていきますね。

**Comment by tatsu-jp** [comment]
@keiji さん、
https://github.com/cocoa-mhlw/cocoa/pull/397 を上げたのでご確認お願いします。
このissueは https://github.com/cocoa-mhlw/cocoa/issues/345 の対応でクローズできそうですね。

**Comment by keiji** [comment]
クローズします。何かあればリオープンしてください。
