### ISSUE TITLE
[iOS] お問い合わせ時にiOS標準メールアプリが未設定だと代わりにGmailが開くがTo欄が空で送信できない

### ISSUE THREAD

**Issue by ypresto** [cocoa-mhlw/cocoa#18]
**Describe the bug**

標準メールアプリのアカウントが１つも設定されてないと、代わりにGmailのメール編集画面が開くが、その際にお問い合わせのTo欄が空になっていて送信できない。
標準メールアプリでは問題なし。

**To Reproduce**

1. デフォルトのメールアプリを、設定されたメールアカウントがない状態にする
2. Gmailをインストール・設定済みにしておく
3. お問い合わせボタンを押す
4. Gmailの編集画面が立ち上がるが、To欄が空になっている

**Expected behavior**

To欄にお問い合わせメールアドレスが入力されている

**Smartphone (please complete the following information):**

 - Device: iPhone 12
 - OS: iOS 14.3
 - Browser Chrome
 - Version 1.2.1

#16 のバグ報告をしようとして発見しました。
下記のEmail.ComposeAsync()のバグ？を踏んでいるようです。
https://github.com/xamarin/Essentials/issues/1401#issuecomment-725705796

----
Internal IDs:
- BUG 1835

**Comment by ypresto** [comment]
誤って途中でissueを作ってしまいましたが編集しました :bow:

**Comment by ypresto** [comment]
https://github.com/xamarin/Essentials/issues/1401#issuecomment-772897901

> Yes, this is on Apple's end still.
> The only real work around is to call "mailto:" directly with launcher.

**Comment by b-wind** [comment]
iOS 側の問題で、現バージョンでも真っ当な対処方法は無さそう。と言う理解で良いでしょうか。

**Comment by kazuhiro4949** [comment]
こちらの件は最新のXamarin.Essentialでは対応済みのようです。
対応したのは1.6.0のようなので、現在のCocoaが利用している1.5.3.2ではまだ未対応となっています。
https://github.com/xamarin/Essentials/commit/e895a73a6bf0131ccf98ef5ccc358236605e2053#diff-8b4441e21bff16e194e6501f695445fcc422b6fedfa801259d9105046aabda46R41

どこかのタイミングでXamarinのアップデートをやれれば自動的に解決しそう

**Comment by keiji** [comment]
では、Xamarin.Essentialの更新Pull Requestについて welcome-contribution つけますね。
やってもいいよと言う方はコメントでお知らせください。Issueにassignします。

**Comment by keiji** [comment]
@ypresto これ、担当の重複を防ぐためアサインしちゃっていいですか？（急いではいません

**Comment by ypresto** [comment]
あ、返事漏れてました。はーい！

**Comment by keiji** [comment]
よろしくお願いします！

**Comment by b-wind** [comment]
現時点の develop ブランチには Xamarin.Essential v1.7.0 が指定されているので改善されているかも知れ無い。
COCOA v1.4.1 時点では未対応。

https://github.com/cocoa-mhlw/cocoa/blob/c5e480b43779b8dec3f196947c7971f147c51e8f/Covid19Radar/Covid19Radar/Covid19Radar.csproj#L64

**Comment by b-wind** [comment]
COCOA v2.0.0 のリリースでは Xamarin.Essential v1.7.0 が使用されている様子。

https://github.com/cocoa-mhlw/cocoa/blob/09615a5c55f7e5fdbf963c466b61fc6c2191d058/Covid19Radar/Covid19Radar/Covid19Radar.csproj#L64

**Comment by keiji** [comment]
直ってるのかも知れないけど、直ってることを確認できていないのでまだオープンです！
（iOSユーザーの誰か確認して欲しい。

**Comment by ypresto** [comment]
直ってました！ありがとうございますー！

（追記：Mail.appの設定あり時はMail.app、そうでなければGmailが送信先ありで開きました

**Comment by keiji** [comment]
@ypresto ありがたい！
