### ISSUE TITLE
接触一覧を表示したときの各日付における接触数が日本語以外の言語でも「○個」と表示される。

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#180]
## 不具合の内容 / Describe the bug

接触一覧を表示したときの各日付の接触数が、英語表示でも（日本語でない言語であっても）「○個」と表示される。

## 再現手順 / Steps to reproduce

1. 端末の言語を英語に設定する。
2. 'COCOA' を起動して、
3. 濃厚接触の可能性があることを示す画面から、
4. 検出された接触一覧画面を開くと、
5. 接触回数が日本語で「○個」と表示されている

## 期待される挙動 / Expected behavior

「n times」など、その言語に応じた単位で表示される。

## スクリーンショット / Screenshots

![close contact](https://user-images.githubusercontent.com/4100714/118140069-fc612c00-b442-11eb-9132-50b11b95151c.png)

（https://github.com/cocoa-mhlw/cocoa/issues/160#issuecomment-840601530 より）

## 動作環境 / Environments

- デバイス：すべての機種
- OS：Android および iOS
- バージョン：1.2.3 で確認

## その他 / Additional context

「n times」とするのは2回以上の接触があったとき？
1回の場合は複数形にせず「1 time」になる？　要確認。

----
Internal Tracking ID: BUG 2305

**Comment by keiji** [comment]
該当部分。「個」については文字列リソースに分離されておらず、固定文字列が使われている。

https://github.com/cocoa-mhlw/cocoa/blob/04e708aff00537ff93f1bbd58c0547da4fbc85a9/Covid19Radar/Covid19Radar/Views/HomePage/ExposuresPage.xaml#L33-L36

**Comment by i-maruyama** [comment]
変更履歴を見ると、「個」が「件」だった時代があるようで何か試行錯誤があった模様です。

**Comment by keiji** [comment]
過去14日間で「件」を使っているので、各日付にも「件」の単位を使ってしまうと混乱を生むかもしれないと判断して「個」にしたのかもしれませんね。

個人的には「個」より「回」の方がいいような気はしますが、ともあれ英語でtimesで良いかについては開発チームの意見も聞きたいところです。週明けに聞きます。

**Comment by Meiryo7743** [comment]
一般に，回数は **once, twice, three times, ...... , _n_ times** のように表現されます。特段の事情がない限り，これに従うのが適切と考えます。

もしも仮に time を使って「1回」を表現するならば，「one time」となるでしょう。念のため Google で「[one time or one times](https://www.google.com/search?hl=en&q=one%20time%20or%20one%20times)」と検索したところ，やはりその場合は time を単数形にするのが正しいようです。

しかし，1 ～ 2 回の場合は上述のように once/twice と表現することの方が圧倒的に多いのもまた事実としてあります。なお，英語話者の中には time を使って表すと，わずかに強調の意図を含むと考える人もいるようです。

#### 参考

- <https://www.englishforums.com/English/PleaseExplanTimes/pdkmd/post.htm>
- <https://forum.wordreference.com/threads/once-or-one-time-one-time-too-many.42750/>
- <https://www.bbc.co.uk/worldservice/learningenglish/grammar/learnit/learnitv304.shtml>

**Comment by keiji** [comment]
こちらPull Request出しています。
当初 Once exposure, Twice exposuresとしていたのですが、その後、Twitterとかでも 1 likeという表記が採用されており、ネイティブにも確認したところ、1 exposureでわかると意見をもらったので、シンプルに 1 exposure, 2 exposuresと変更してあります。
