### ISSUE TITLE
プルリクエストにおける CI の `Checkout` が失敗する

### ISSUE THREAD

**Issue by Takym** [cocoa-mhlw/cocoa#183]
## 不具合の内容
プルリクエストを作成すると自動的にCIが実行されますが、`Checkout` の段階で失敗してしまいます。

## 再現手順

1. プルリクエストを作成します。
2. 自動的にCIの実行が開始されます。
3. 実行完了まで待ちます。
4. 下記の様なエラーが発生します。

```
Error: fatal: unable to access 'https://github.com/cocoa-mhlw/cocoa/': The requested URL returned error: 500
Error: The process '/usr/bin/git' failed with exit code 128
```

## 期待される挙動
正しくチェックアウトされ、検証が開始される。

## 該当する GitHub Actions の実行結果の例
* https://github.com/cocoa-mhlw/cocoa/runs/2593601144
* https://github.com/cocoa-mhlw/cocoa/runs/2593564289

## 動作環境

* OS：全て
* ビルド構成：全て
* バージョン：actions/checkout@v2

**Comment by Takym** [comment]
`actions/checkout` は既に 2.3.4 が出ているのでそちらに更新すべきでしょう。

**Comment by Meiryo7743** [comment]
> Error: fatal: unable to access 'https://github.com/cocoa-mhlw/cocoa/': The requested URL returned error: 500

ステータスコードが 500 ということは，GitHub のサーバー側でエラーが生じたと考えられそうです。列挙なさっている workflow 実行結果の詳細ページにおいて「Re-run all jobs」をすれば，解決するかもしれませんね。

- <https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500>

**Comment by Meiryo7743** [comment]
> `actions/checkout` は既に 2.3.4 が出ているのでそちらに更新すべきでしょう。

https://github.com/cocoa-mhlw/cocoa/blob/b147fbb61e2b666a53ff3123e63dc86d68f00af5/.github/workflows/CI.yml#L20

[GitHub Actions の公式ドキュメンテーション](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses) によると，上に示した `CI.yml` のような指定方法では，v2.x.x のなかで最も新しいものを参照する主旨の記載があります。したがって，`actions/checkout@v2` は `actions/checkout@v2.3.4` と同値です。

> - Using the specific major action version allows you to receive critical fixes and security patches while still maintaining compatibility. It also assures that your workflow should still work.

---

ところで，同ページにおいて GitHub は， 安全性の観点から Action を利用する際はハッシュ値によるバージョン指定を推奨していますね。

> We strongly recommend that you include the version of the action you are using by specifying a Git ref, SHA, or Docker tag number. If you don't specify a version, it could break your workflows or cause unexpected behavior when the action owner publishes an update.
>
> - Using the commit SHA of a released action version is the safest for stability and security.

この辺りについては，少しばかり検討してみても良いのかもしれませんが，不必要な事柄とも言えます。

**Comment by keiji** [comment]
今、GitHub Actions調子悪いっぽいですね。

https://www.githubstatus.com/

> Investigating - We are investigating reports of degraded availability for GitHub Actions.
May 16, 07:17 UTC

ちょっと様子見てみましょう

**Comment by Takym** [comment]
@Meiryo7743 さん
> ステータスコードが 500 ということは，GitHub のサーバー側でエラーが生じたと考えられそうです。列挙なさっている workflow 実行結果の詳細ページにおいて「Re-run all jobs」をすれば，解決するかもしれませんね。

僕のアカウントからは「Re-run all jobs」は権限を持っていないので押せないみたいです。

**Comment by keiji** [comment]
GitHub Actions復旧して、CIが正常に終了することを確認しました。

**Comment by keiji** [comment]
先々週、先週とGitHub Actionsが時々不安定になっていたようですが、現在は復旧していますね。
こちら問題なさそうなら水曜日くらいにCloseします。

**Comment by keiji** [comment]
GitHub Actionsくん、最近調子がいいのでこのIssueはCloseします。
