### ISSUE TITLE
IDeviceVerifierをServiceLocatorで取り扱う

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#185]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

https://github.com/cocoa-mhlw/cocoa/issues/179#issuecomment-841943834 より

現状、IDeviceVerifierはDependencyServiceで依存性解決をしているが、DependencyServiceはAndroidでバックグラウンド動作時に解決できない特性がある。

https://github.com/cocoa-mhlw/cocoa/blob/04e708aff00537ff93f1bbd58c0547da4fbc85a9/Covid19Radar/Covid19Radar.Android/Services/DeviceCheckService.cs#L23-L26

また、デバッグモード導入（ #179 ）の際にifディレクティブを使用しなくてはならず、メンテナンス性を落とす一因になっていると考える。

## 解決策についてお書きください / Describe the solution you'd like

ServiceLocatorで取り扱うようにする。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

IDeviceVerifierはUI側（陽性登録時）から使用される処理に限定されているので現状問題が発生するとは考えにくい。
このままにしていても機能上問題はなさそう。

## その他 / Additional context
#45 に関連。

全部一度にやると大きな変更になるので、このIssueではIDeviceVerifierに限定して対応したい。

----
Internal Tracking ID: NFR 2466

**Comment by i-maruyama** [comment]
PR #191  で確認できました。詳しくは #191 のコードの入手＆コードの検証 をご覧ください。
