### ISSUE TITLE
接触状況を表示する画面のピクトグラムで、「すべきこと」と「すべきでないこと」が無秩序に並んでいる

### ISSUE THREAD

**Issue by yusuke** [cocoa-mhlw/cocoa#186]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?
接触状況を表示する画面のピクトグラムで、「すべきこと」と「すべきでないこと」が無秩序に並んでいるため、一見して何をすべきで、なにをすべきでないことなのかが不明瞭です。

## 解決策についてお書きください / Describe the solution you'd like
すべきことを上に並べ、すべきでないことを下に並べます。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered
すべきでないことについて、さらに🚫のようなアイコンを付けるのもいいかもしれません。

## その他 / Additional context
現状:
![IMG_4909](https://user-images.githubusercontent.com/74894/118427839-1895ef00-b709-11eb-967b-8011658e3d0a.PNG)

改善案:
<img width="697" alt="ScreenShot 2021-05-17 12 21 37" src="https://user-images.githubusercontent.com/74894/118428455-7545d980-b70a-11eb-8d62-0b813c896d19.png">

----
Internal Tracking ID: PRODUCT BACKLOG ITEM 2449

**Comment by yusuke** [comment]
PR予定です

**Comment by keiji** [comment]
ありがとうございます。個人的には「画像を提案いただいた配置する」「禁止バッジは付けない」でいくのが良いかと思います。

ぼくがそう思った理由については次の通りです。

## ピクトグラムの配置変更について
ピクトグラムについて確認したところ、厚生労働省が「ご自由にお使いください」という扱いで公開しているものです。

https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000121431_newlifestyle.html

元の画像は一列に並んでいて、このアプリ向けに配置され直したものなので、配置換えは問題ないと言うことでした。

## 禁止バッジを付ける件
禁止バッジについては今回は見送りたいです。付けるとしてもピクトグラムに付けた方が良いと考えていて、その場合はすこし調整が必要なので、より素早く変更するには見送った方がいいというのがぼくの考えです。

開発チームからは『画像にある7つの項目は、文字情報も合わせるとすべてが「すべきこと」に見える』という話がありました。

密集を回避（すべき）
密接を回避（すべき）
密閉を回避（すべき）

と言ったように、文字情報は筋が通っています。一方、ピクトグラムそのものはご指摘の通り「すべきこと」「すべきでないこと」が混在の状態にあるので、そこを改善するのであればピクトグラムに禁止マークを付けた方が良いだろうとぼくは考えています。

文字列にバッジを付けるのではなく、ピクトグラムそのものを変えるとなると調整が必要になりそうです。どうやって調整するかを問い合わせますが、まずは配置変更をしたいと思います。

----

前述のURL「新型コロナウイルスを想定した「新しい生活様式」の実践例を公表しました」を見て気づいたのですが「外出控え」の項目がありませんね。
公表後に加わったのか（現在は含まれる）、過去には存在したけど現在の生活様式からは削除されているのか（現在は存在しない）、こちらも合わせて確認します。

**Comment by keiji** [comment]
Covid19RadarにIssue上がってました。
あとでCOCOAにもIssue作っておくので、一つのPR（ #187 または #188 ）で対応できるとうれしいです。

https://github.com/Covid-19Radar/Covid19Radar/issues/458

**Comment by yusuke** [comment]
アップデートありがとうございます。

そう、ピクトグラムではすべきこととすべきでないことが表現されており、文字ではすべきことが書いてあるという状態です。

厚生労働省のPDFですでにjpegノイズのようなものがのっていますが、これをベースに配置換えをしたパターンを作ってみますね。
(プライオリティとしては低いですが、オリジナルのベクターデータがあるといいのですね)

**Comment by yusuke** [comment]
外出控え、も入ったパターンが練馬区のサイトにありました。
https://www.city.nerima.tokyo.jp/resource/coronavirus/atarashiiseikatuyoushiki.pdf

**Comment by yusuke** [comment]
PR #187 にて関連ファイルを修正いたしました

**Comment by muojp** [comment]
利用者が迷いにくくなるようにする、すばらしいissue/取り組みだと思います。

> 外出控え、も入ったパターンが練馬区のサイトにありました。
> https://www.city.nerima.tokyo.jp/resource/coronavirus/atarashiiseikatuyoushiki.pdf

@keiji さんが
> こちらも合わせて確認します
と書かれているので蛇足ではありますが、私の把握している範囲で厚労省による資料更新の時系列を補足します。

2020/05/04頃の当初、厚労省のガイドライン内に外出自粛要請が盛り込まれていました。

2020/06/19時点で全国レベルの移動自粛要請が解除された(参照 https://www.nikkei.com/article/DGXMZO60339810T10C20A6EA3000/)ことに伴い、外出の自粛自体は求めないものへとガイドラインが更新されました。

https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000121431_newlifestyle.html
内に
> ※ 感染状況の変化を踏まえ、専門家会議の構成員にも確認いただき、６月19日に一部の記載を変更しました。
と書かれているのがこのあたりです。

行動を変容することを要請する、利用者における心理的プレッシャーがそれなりにあること、不必要なものまで載せると結局どれも守られなくなることから、実効性をあげるために1項目減らして絞り込んだという意図もあるものだと解釈しています。

練馬区のものは、6/19より前に出されたもののコピーだと思われます。
アーカイブのリンクは https://github.com/Covid-19Radar/Covid19Radar/issues/458 内にあります。

**Comment by yusuke** [comment]
@muojp のご指摘を踏まえ(経緯の確認ありがとうございます！)、「外出控え」を減らしたパターンのブランチを作ってみました。

@keiji 現在別ブランチですが、このままPR #187 にマージして重ねるのでも、新たなPRにするのでも可能です。

https://github.com/yusuke/cocoa/commit/0d5fcdb31b0fb6ad26f4019cf3b5a0733fa745b2?short_path=42091fd#diff-42091fdd5026f8a9bda0bb11bca386f379d9caa6579618710ddd0043ceb0e8df

**Comment by yusuke** [comment]
@keiji 
「外出控え」をなくしたパターンを新しいPRとして作成いたしました:  #192 
手続きの都合などで #187 にマージした方が良い場合はお申しつけください。

**Comment by keiji** [comment]
ありがとうございます。現時点では #187 を採用する方向で話が進んでいます。

加えて、「外出控え」を含め、利用者にどのような情報を提示するかについては、情報設計の観点からもきちんと検討しようという話になっています。これは、ピクトグラムそのもの（「すべきこと」と「すべきでないこと」の明示化）や文言（『新しい生活様式』という言葉を使うかどうか）も含めた形で行われる予定です。

具体的な提案をいただいている中で「まずは一歩進めます」という回答しかできないところは心苦しくはあります。
その上で、今回いただいた指摘が「利用者にわかりやすい情報を提示するために、デザインや情報設計を再検討しよう」という開発チームからの発案につながったことは間違いありません。
本当にありがとうございます。

状況については随時アップデートします。

----
ここからは、あくまで有山の個人的な整理として記述するものです。

ご指摘の「外出控え」については、昨年の緊急事態宣言が解除されたタイミングで「新しい生活様式」から外れたようです。
現在、いくつかの地域で緊急事態宣言が発令されていて「不要不急の外出自粛」が求められています。
「外出控え」をただ削除するのか。「不要不急の外出自粛」へ置き換えるのか。表示内容を緊急事態宣言の地域とそうでない地域で分けるべきか（COCOAは位置情報が使えない）。さまざまな調整をするために、もう少しお時間をいただくことになりそうです。

**Comment by yusuke** [comment]
アップデートありがとうございます。 #187 について、「外出控え」を残したまま高解像度化、画像サイズ縮小をしておきました。

**Comment by muojp** [comment]
https://github.com/cocoa-mhlw/cocoa/issues/186#issuecomment-847903501
時間があいてしまいすみません。個人的な整理も含めて丁寧に対応頂きありがとうございます。
現在も感染拡大状況が続き医療事情も非常に厳しい自治体が複数存在しており、関係各位が大変な努力をされていることに頭が下がります。

前提として、今般外出を控えることが望ましい局面が多々あることは広く知られています。目下緊急事態宣言が複数の都道府県で発令されており、まん延防止等重点措置を含めると半数近くの都道府県が該当、表現が適切かは分かりませんが人口カバー率でいうともっと多くの人が外出を控えることを要請される状態にあります。

## 外出は控えるべきなのか

私個人の体験としては緊急事態宣言の解除後、厚労省ガイドラインから「外出控え」のピクトグラムが外れたことに対して大きな安堵感があったことを覚えています。
全国一律の行動制限は経済面のインパクトの大きさに対して実効性が低いため、より精密な行政策をとっていこうというのがポリシー改訂時の専門家要旨でした。

一方、私がアプリ上でこのピクトアイコンに再会したのは確かGo To トラベルで経済面のアクセルを踏んでいこうという話が出た時期でした。
アプリで利用しているアートワークの更新が(開発体制もろもろの都合上)実情に追いついていないのはよくあるもので(特に1国1アプリという体制下では)、最初はそのパターンかと考えました。
しかし、もしこれが専門家の見解をチェリーピッキングしてユーザー行動を制御する意図のアクションであれば、あまりフェアなものとはいえないのではないかと感じ、本リポジトリとは運用上関係ありませんがCovid-19Radar のリポジトリにissueを起票したのだと思い返します。

人の流動が増えるからこそCOCOAによる接触追跡が重要だと感じてアプリをインストールしており、それなのに「えっ、外出は相変わらず控えろということになってるのか? これは専門家諮問のもとで絞り込んだピクトグラムが単に古いだけなのか? 『これ入れるか入れないかでいえば入ってたほうがいいよね』という非専門家的な解釈を入れてないか? それは専門家の取り組みを時間軸無視でつまみ食いして都合よくユーザーに押し付けるものではないか?」という違和感を持った、と表現したほうが誤解少ないかもしれません。

## 現実的対応?

これを現実的にうまくカバーしようと考えてみても、

- 「緊急事態宣言下もしくはまん延等防止措置を適用されている都道府県においては行政の要請にもとづいた外出控えをお願いします」をピクトグラムで提示するのは本来的に無理筋
  - ピクトグラムは見た瞬間に行動の指針を判断できることが期待されるもので、利用者の迷いを生むことなくシンプルにDOs and DON'Tsを提示することにこそ意味がある(本issueの素晴らしさの根底もこの点に対する貢献にあると思っています)。ピクトグラムでの行動要請に関して、複雑な条件付けは利用者の理解を阻害するので望ましくない
- 全国一律のプラクティスでない以上は都道府県単位で位置情報をもとにしてピクトグラムを出し入れすべきなのか?
  - 位置情報にアクセスする選択がまずありえないアプリとして、ユーザー負担を適切に設計する手立てはあるのか??
- ピクトグラム+脚注をすべきなのか?
  - これはバリバリのアンチパターンで、結果的にユーザーの意思決定を阻害するからやめたほうがいい
- ピクトグラム一覧から「外出控え」を削除して文章で注記すべきなのか?
  - まん延防止等重点措置以上の地域指定がすべて解除されたらアプリのリソースを更新して削除する対応が工数面で無難か? 集団免疫獲得(≒COCOAの意義の完遂)までこのまま置いておくか?

軽く検討しただけでも大変そうです。もちろん無限の工数が確保できればきれいな解決も不可能ではないでしょうが、アプリの存在意義に照らして考えるとどうも「外出控え」のピクトグラムを取り除くことはコロナ終息とかなり近い条件設定であり、COCOAが必要な限りは外出抑制が必要なエリアが存在する可能性が高いということでもあります。

このため、「今のところ、他にやるべきことが山ほどあるからそこまでの手は掛けられない。外出を控えることを推奨することにしてピクトグラムは残しておこう」と自分なら考えると思いますし、リソースの限られる状態で実効性のあるcontact tracingを実現することがチームの最重要ターゲットであればなおさらこうなるかなとも思います。

早くCOCOAの存在意義がなくなるほどにコロナ禍が終息してほしいと願うばかりです。

**Comment by cocoa-dev** [comment]
ご提案及びPRいただきありがとうございました。

開発チーム内でデザイナーを含めてブラッシュアップさせていただき、「するべきこと」と「するべきでないこと」をよりひと目でユーザーが理解しやすい見せ方がないかを検討いたしました。
伝わりやすさなど、ご意見をいただけると大変ありがたいです。

![image](https://user-images.githubusercontent.com/69558847/123382556-08f1ac00-d5cd-11eb-8ad0-091c062676ce.png)

**Comment by yoshitomo-g** [comment]
https://github.com/cocoa-mhlw/cocoa/issues/186#issuecomment-868267730
左に追加された記号ですが、文化圏によっては違う意味で認識されるかもしれません。

日本ではバツ印は否定的な意味を持ちますが、チェックマークと同じ扱いである上に肯定的な意味と捉える文化圏もあるそうです。区別しやすくするために色を変えているのだと思いますが、それも他の文化圏で通じるかどうか確証がありません。
（日本人でも、チェックマークを不正解の記号として否定の意味と捉える人もいるとのことです。）

### 代案
こういった違いへの対処について調べてみましたが、記号よりもテキストを使うようにという解説が多かったです。
バツ印は「禁止」、チェックマークは「実行」とかでしょうか。

### その他
読み上げ機能での利用を考慮するなら、記号の意味が通じるかどうかとは別の話として、ピクトグラムを含めテキストの対応をするべきと思います。

**Comment by yusuke** [comment]
文化圏（台湾など）によっては×が肯定の意味で使われることがあるなんていう話もありますね。

また、✓が青なのは「すべきこと」＝「指示」という意味でしょうか？
https://ja.wikipedia.org/wiki/JIS安全色
JIS的には青=指示、緑=安全、ですが安全、安心みたいな意味では緑の方が違和感がないかなという気もします。(素人なのでちょっとどちらにすべきなのかは分かりませんが)

また、英語が命令形(stay home, wash your hands)になっていたり、名詞になっていたり統一されていません。
stay at home, ventilate, wear mask, cover coughs, wash hands, avoid crowded spaces, avoid close contact, avoid confined spacesなどと命令形に統一してはいかがでしょうか？(私のPRではそのように統一していました)

**Comment by heykuro** [comment]
皆さま、いつもありがとうございます。

先日ご提示した改善案について皆さんからご指摘をいただいた内容を元に開発チームとも相談した結果、本Issueについては『ピクトグラムのグルーピングを変更することで、利用者から見た「すべきこと」と「すべきでないこと」の理解のしやすさを改善する』という目的に限定し、@yusuke さんからいただいているPull Request #187  の取り込みを進めさせていただきます。

今後ですが、グルーピング改善に加えて、今後もよりユーザーにとっての分かりやすさは追求していきたいと考えています。
いただいたフィードバックも踏まえ、また改めてピクトグラムや画面の改善案を共有させていただきますので、ぜひご意見をいただければと思います！
