### ISSUE TITLE
GitHub Actionsでサーバー側のCIを構築する

### ISSUE THREAD

**Issue by cocoa-dev** [cocoa-mhlw/cocoa#190]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

現在構築されているGitHub ActionsのCIでは、アプリ側のコードのみ確認しています。
サーバー側のコードがPRで修正されることは少ないですが、CIは必要だと考えます。

## 解決策についてお書きください / Describe the solution you'd like

GitHub Actionsでサーバー側のCIを構築する

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

特になし

## その他 / Additional context

特になし

-----
Internal Tracking ID: NFR2543

**Comment by tatsu-jp** [comment]
@cocoa-dev 
アプリ側のCIを参考にして、サーバ側CIを作成しました。

https://github.com/tatsu-jp/cocoa/pull/1/commits/2c62755e76395e08c8bac79984c5e6ba7186f3d9

実行結果は以下です。Job定義等は期待されているものでしょうか。コメント頂けると助かります。
https://github.com/tatsu-jp/cocoa/actions/runs/890146857

**Comment by keiji** [comment]
拝見します（実際に見るのは明日のなりそうです

**Comment by keiji** [comment]
実際に編集していただいたymlをforkした僕のリポジトリで実行して確認しました。
期待通りに動いていると思いますので、変更をPull Requestでいただけますか。

次の3つのパターンで動作確認をして、想定通りの動作をすることを確認しています。

ビルド・テストともに正常に完了するパターン
https://github.com/keiji/cocoa/actions/runs/896361223

ビルドが通らなくなる（コードが壊れている）
https://github.com/keiji/cocoa/actions/runs/896378369

ビルドは通るがテストが通らないパターン
https://github.com/keiji/cocoa/actions/runs/896418008

**Comment by tatsu-jp** [comment]
ご確認ありがとうございます！
今夜に作業できると思います。
