### ISSUE TITLE
画像の減色を行うことでアプリサイズを削減する

### ISSUE THREAD

**Issue by yusuke** [cocoa-mhlw/cocoa#193]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?
#41,  #114 に関連しますが、アプリのうち一定量を占める画像ファイルの容量が大きいです。

## 解決策についてお書きください / Describe the solution you'd like
減色を行うことで見栄えを損ねることなくサイズ削減が可能です。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered
画像によってビット数は調整する必要がありますが、2ビットまで減色しても見栄えを損なわない画像も多くあります。
機械的に全てのpng画像を2ビットに減色したところ画像サイズの合計は16.3MBから2.7MBまで削減されました。

## その他 / Additional context

/Covid19Radar/Covid19Radar.Android/Resources/mipmap-xxhdpi/ic_launcher.png を2ビットに減色した例です。11KB(11,104バイト)が1KB(1,010バイト)まで削減されています。
<img width="179" alt="ScreenShot 2021-05-26 10 43 22" src="https://user-images.githubusercontent.com/74894/119590163-33561b00-be0f-11eb-9428-62defd42d145.png">

----
Internal IDs:
- NFR 2494

**Comment by yusuke** [comment]
減色を試すために実行したコマンドは以下の通りです。
find . -name "*.png" | xargs -J% mogrify ./ -depth 2 %

大きく見栄えを損ねる画像もあるので実施する際は確認しながら個別に減色の程度を決めた方がいいです。(リソースの整理を行っている #72 ようなので、そちらが終わったらよろしければ着手します)

**Comment by keiji** [comment]
ありがとうございます。

CIについてはガイドラインで色指定がされているものがあるので「この色は変えない」のような指定ができるといいですね。
厚生労働省の方にCIガイドラインを確認します。いっそ開発チームのデザイン担当（？）に「色は変えずに減色できませんかね」って聞いてみようかなと思います（怒られるだろうか…）。

**Comment by yusuke** [comment]
はい、ImageMagickで一括、みたいな手抜きでなければ色合いを損なうことなく減色できます。

<img width="254" alt="ScreenShot 2021-06-03 23 10 29" src="https://user-images.githubusercontent.com/74894/120659000-e504e400-c4c0-11eb-9ce7-5dbbdc479dbf.png">
