### ISSUE TITLE
稼働状況の可視化に関する意見を募集します

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#194]
接触確認の状況について表示する機能（#128）と、接触確認が有効になっていない（設定の関係で正しく動作しない）ケースで利用者をナビゲートする画面について、UIデザイン案がきたので公開します。

わかりやすさ、伝わりやすさ、アクセシビリティの観点から意見をいただけると嬉しいです。

いただいた意見は随時検討して、取り込めるところは取り込みたいと考えています。
なお、#186 で課題が明らかになった情報設計についてはこのデザイン案には含まれていません（別途起案中です）。

![21_05_21 GitHub](https://user-images.githubusercontent.com/932136/119829090-d6a15000-bf35-11eb-85cd-5f28799de8df.png)

![21_05_21 GitHub copy](https://user-images.githubusercontent.com/932136/119829097-d903aa00-bf35-11eb-8848-dc1c4c443dfa.png)

**Comment by Takym** [comment]
下記の案と似ていますね。
https://github.com/Covid-19Radar/Covid19Radar/issues/534
https://github.com/Covid-19Radar/Covid19Radar/pull/705

**Comment by keiji** [comment]
背景に直接情報を配置することで、利用者にUI各部の優先順位をわかりやすく提示しているのだなと思ってい見ていました。
同じ方向性で以前にも提案されていたんですね。

**Comment by i-maruyama** [comment]
とても、いいですね。

- 「接触有無の最終確認日時」と「陽性者との接触の確認」が、難しいところですが、やはりあいまいです。一般ユーザーから見れば、接触有無の最終確認日時＝ボタンを押した時刻でも、あります。ボタン押しても日時が更新されないから、バグだと思われる可能性もあります。

 以下私見ですが、（ #197 で述べたように） FetchExposureKeyAsync ＝「接触を確認する」という事にすべきと思います。例えば、ボタンで「接触を確認」しようとしても、TEKが最新なら、submitBatch は動作しないことになります。

おそらくこのsubmitBatch の実行成功の最新日時を、「接触有無の最終確認日時」と表記されていると思います。この代案が非常に難しいのですが、一つだけあげておきます。
-- 接触有無の最終確認日時     （現状１１文字)
-- 新規陽性者との接触確認　（意図：日時は削除可能。ボタンで「接触を確認」しようとしても新規陽性「登録」者がいなければ、この日時は不変になるのも分かる。あと新規の情報は、みんな欲しい）

- 「接触有無が確認できません」については、上記のように難しいところです。なので、タイトルについては、「動作中」、「正常に動作していません」、「停止中」の三つで良いと思います。
- あと、通信の確認不可で「通信環境をご確認の上、再起動・・・」とありますが、これでは、省エネモードによるバックグランド停止が除外されており、しかもこの場合には何度再起動しても同じです。ここは、いっそのこと、一切の指示を無くしてHPへ誘導し、そこに原因と対処法の最新情報を掲示してはいかがでしょうか？

ちなみに、いま充電状態も表示させながらバックグラウンドテストしてるのですが、省エネモードは、充電して100%になると自動解除されるのを、今日知りました。このおかげで、COCOAのバックグラウンド動作が動いている人もいそうです。

**Comment by yoshitomo-g** [comment]
ものすごくすっきりした感じがします。上下の余白が広がったからでしょうか。
以下、気になったところです。

### 共通
対象：ボタンラベル「陽性者との接触を確認」
@i-maruyama さんも仰っているように、処理の結果を表示するだけなので表現を変えたいところです。「～を見る」という案も浮かびましたが、非視覚的な利用も考慮すると良くないよなぁという思いもあります。

### 接触有無の確認不可
対象：テキスト「接触有無が確認できませんでした。」
提案：「接触有無の確認ができていません。」
理由：確認できない状況が進行中なので。

また、@i-maruyama さんの次の提案に賛成します。1行で説明するのは無理だと思いますので。
> ここは、いっそのこと、一切の指示を無くしてHPへ誘導し、そこに原因と対処法の最新情報を掲示してはいかがでしょうか？

### 接触通知の停止中
対象：ボタンラベル「設定を変更」
提案：「理由を確認する」
理由：直接設定変更に進むのではないので。

**Comment by Meiryo7743** [comment]
### 接触通知のステータス欄について

直下にある「利用期間」や「陽性と診断されたら」と同じようにカード型の UI に統一した方が自然に見えそうです。

このアプリでは，ある一つのことに係わる情報を 1 つのカードに集約するデザインを採用しています。さらに，接触通知が停止しているときには，ボタンが表示されるわけですから，敢えて首尾一貫した見た目にしない理由が思い浮かびません……。（ボタンの配色も同様です）

### 「接触有無が確認できません」について

「接触有無が確認できません」→「エラー」のようにシンプルな文言はどうでしょうか。直後にその理由を説明する欄が設けられており，わざわざ見出しで詳しく述べる必要はないと考えます。いずれにせよ，他言語への対応も考慮すると，より簡潔に表現できないか検討の余地がありそうです。

エラーの対処法については，上で提案されているようにウェブページへ誘導する形式が望ましいでしょう。実装にあたっては，そのページを開くボタンを配置するのが良さそうです。

### 「本アプリを広めましょう」の部分

デザイン案では「COCOAを周りの人に知らせる」に差し替わっています。こちらの部分も変更するのでしょうか？　あるいは，旧版のデザインを基に編集した結果生じた単なるミスなのか……少しばかり気になってしまいました（恐らく後者だと推測しております）。

**Comment by tatsu-jp** [comment]
スッキリとして良いと思います。

OS/アプリの各役割や仕様を理解していないユーザーの視点で見ると、各ステータスが以下のように見える可能性がありそうだと感じました。各ステータスをどのような定義で考えているのを教えていただけると助かります(以下とは違う気がしています)。

```
「動作中」：接触確認(OS)ができている && 1日1回の定期チェックが成功している(日時から判定)
「接触有無が確認できません」：接触確認(OS)ができていない？何かに失敗している？
「停止中」：接触確認アプリを利用する上で必要な設定が有効になっていない
```

「接触有無が確認できません」は捉え方が複数あります。皆さんが提案されているようにQ&Aへ誘導するか、もう一つの案としては定義を絞る方が良いと思います。例えば、「接触有無が確認できません」=「定期チェックに失敗した(ダウンロードに失敗した)」という定義にして、単純に「毎日の接触確認処理に失敗しました」と表示した方が何が起きたかが分かりやすいと思います。ログを送付するへのリンクも表示することで、ユーザーがトラブル時のログ収集に協力しやすくなるのではないかと思います。

他の観点では、ステータスを細分化すべきかどうかも議論できればと思います。以下のように「接触有無が確認できません」というステータスを無くし、「動作中」の横のチェックマークアイコンを警告アイコンに変える表現でも十分なように思います。1日1回の定期チェックが成功しているかどうかは日時情報から判定可能ですし、2つのステータス(動作中/停止中)しかないので単純で分かりやすいと思うためです(警告時には、ポップアップ内の文字列を変える等の工夫があると分かりやすいかもです)。

```
「動作中(OK)」：接触確認(OS)ができている && 1日1回の定期チェックが成功している(日時から判定)
「動作中(WARNING)」：接触確認(OS)ができている && 1日1回の定期チェックに失敗した(日時から判定)
「停止中」：機能を利用する上で必要な設定が有効になっていない
```

**Comment by kvaluation** [comment]
## 最終確認の日時
　最終確認の日時の表示に賛成です。ありがとうございます。

　** 最終確認日時が「最新」であれば、最新であることをお伝えできたらより良いと思われます。 **

　一案としては、最終確認日時が「今日」か、今日でないかを表示でき、今日であれば、運用上、最新であると評価できます。
　「朝6時以降に、＜今日＞がでていなければ、もう一度起動してみてください」と保健所等の関係機関にもご説明できるかと思われます。
　＜今日＞がでていれば最新の陽性登録との照合済みですとご案内できます。

## 画像の日時
　接触有無の最終確認日時は、0:30から5:00ぐらいという現状にあわせるのが良いかと思います。Android側の時刻は12:30であれば、同日のお昼と思われます。

## 接触有無が確認できません
　素晴らしい機能でありがとうございます。
　「接触確認アプリCOCOAを再起動する」ボタンを配置できないでしょうか。
　「再起動をお試しください」で再起動の仕方など保健所等への電話問合せが増加したりしないようなご配慮をお願い申し上げます。

**Comment by heykuro** [comment]
@Meiryo7743 

ご意見ありがとうございます。

>デザイン案では「COCOAを周りの人に知らせる」に差し替わっています。こちらの部分も変更するのでしょうか？　あるいは，旧版のデザインを基に編集した結果生じた単なるミスなのか……少しばかり気になってしまいました（恐らく後者だと推測しております）。

こちら前者の方となります。COCOA自体が特性上、あまり立ち上げられないアプリではあるので、そこからシェアをされるということ自体が少ないのではということで今回のデザイン変更の中で全体のバランスも見つつ変更されています。このあたりもご意見あればいただけますと幸いです！

**Comment by Takym** [comment]
ページ上部の「動作中」について、背景を非表示にすると「壊れている」という印象を（少なくとも僕は）受けますので、背景を非表示にするのではなく色を変えて強調するのはどうでしょうか？ページ下部の共有ボタンの説明文は「より多くの人が使うと効果が高まる事」を広く認知して貰う為に消さない方が良いと思います。

**Comment by Meiryo7743** [comment]
@heykuro 

> こちら前者の方となります。COCOA自体が特性上、あまり立ち上げられないアプリではあるので、そこからシェアをされるということ自体が少ないのではということで今回のデザイン変更の中で全体のバランスも見つつ変更されています。このあたりもご意見あればいただけますと幸いです！


返信ありがとうございます。なるほど，意図的な変更なのですね。それでしたらリンクテキストにせず，いっそのことハンバーガーメニュー内に移動させてしまうのはどうでしょうか。

ホーム画面には接触関係の情報だけを配置して，それ以外のコンテンツはメニュー内に収めてしまう方が，より洗練された印象を受けます。

**Comment by i-maruyama** [comment]
「アプリを周りの人に知らせる」は、NonContactPage,  ThankYouNotifyOtherPage にもあります。（Command="{Binding Path=OnClickShareApp}"で共通ですが、翻訳文字列の static resource は違います。）

私自身は、どちらが良いか分かりませんが、同じ機能は今のように同じ文字列になっている方が、安心してクリックできます。

**Comment by keiji** [comment]
現状報告です。いただいた意見を元に反映したり反映しなかったりした案を開発チームから受け取っています。

公開をどうするかを検討中です。このIssueにコメントとして掲載することも考えたのですが、スレッドが延びているので後から来た人が読みにくいかもしれないので、別Issueにしようかなと思っています。

**Comment by keiji** [comment]
Discussionがスタートしたので、このIssueは今晩あたり閉じて、ブラッシュアップ済みのものをDiscussionで公開したいです。
