### ISSUE TITLE
[Android] WorkManagerをApplication#onCreateで再スケジュールする

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#196]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

https://github.com/cocoa-mhlw/cocoa/issues/136#issuecomment-846334884 より。

Android版の接触確認API（Google Play Services）は、システムが接触確認アプリを停止してバックグランド処理が実行されない場合に備えて「Force-stop Handling」を備えている。
Google Play Servicesは、Force-stop Handlingで６時間に１回の頻度でアプリのプロセスを再度起動して、WorkManagerのJobを復帰する。

ところが、一部の端末（some popular devices）では、Force-stopされたかを判定する処理でSecurityExceptionが発生するため、Force-stop Handlingが完了せず、Jobの復帰が行われない可能性がある。

https://github.com/androidx/androidx/commit/9b770633fafed35c5185f1cc2b52612a451ccdb9#diff-7794a8af74a01c5c6d2ee10558482274048bd3aa011aaca99459c2c5049fd7dd

> This helps workaround OEM introduced bugs in AlarmManager on some  popular devices

some popular devicesとは 🤔 

## 解決策についてお書きください / Describe the solution you'd like

WorkManagerにWorkerを登録する一連の処理を、現在のMainActivityからApplication#onCreateに移動する。

COCOA v1.2.3からWorkerのExistingPeriodicWorkPolicyがKEEPになっているので、アプリのプロセス起動時に再登録されても上書きされることはなく、現在の動作には影響がないと考える。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

WorkManagerにSecurityExceptionを無視するワークアラウンドが追加されている。

https://github.com/androidx/androidx/commit/9b770633fafed35c5185f1cc2b52612a451ccdb9#diff-7794a8af74a01c5c6d2ee10558482274048bd3aa011aaca99459c2c5049fd7dd

この変更が入ったバージョンにすることで課題を解決することができると考える。

[History](https://developer.android.com/jetpack/androidx/releases/work?hl=zh-tw#version_260_2)を見る限り`2.6.0-beta01`に入りそうだが、これを書いている時点では`2.6.0-beta01`はリリースされていない。

https://developer.android.com/jetpack/androidx/releases/work?hl=zh-tw#version_260_2

## その他 / Additional context
Force-stop Handlingがアプリのプロセスを再起動するか。実際に確認していない（WorkManagerのJobが復帰することは確認した）ので、あらかじめ実験して確認しておく。

Application IDがCOCOAと異なる場合でも、接触確認APIを利用中であればWorkManagerのJobは復帰したので、リリース版のCOCOAに限定されていない。実験は、接触確認APIを使ってWorkManagerにJobを登録するだけの最小限の機能のアプリを作るのが方がよさそう。

----
Internal IDs:
- NFR 2530

**Comment by b-wind** [comment]
https://developer.android.com/jetpack/androidx/releases/work#2.6.0-beta01

**Comment by b-wind** [comment]
誤解を招いてしまったようですが、 2.6.0-beta01 上記記述時点では Nuget には記載が無かったです。今見るとある模様。
ただし、Xamarin.AndroidX 側は更新されていないので結局しばらくは使えないのかなと……

**Comment by keiji** [comment]
Pull Requestを出しました。よく動いている。
