### ISSUE TITLE
開発用ブランチを作成する

### ISSUE THREAD

**Issue by Takym** [cocoa-mhlw/cocoa#200]
## その機能リクエストは何らかの問題に関連しますか
現在はプル・リクエスト(PR)が24件あります。
これらの PR を一旦開発用ブランチへマージし、動作確認できる様にします。
また、一つの PR が正しく動作できたとしても、別の PR をマージする事により正しく動作しなくなる可能性も有り得ます。
別々の PR をマージした時に正しく実行できるか実験する事もできる様になる筈です。

## 解決策についてお書きください
開発用ブランチ(`develop`)を作成して、PR をそのブランチへ一時的にマージします。
正常に動作する事が確認できた場合等に `master` へマージします。

## あなたが考える代替案についてご説明ください 
開発用ブランチを一つのみ作成するのではなく、機能・バージョン等に分けて複数のブランチを作成し管理します。
今の状況では一つでも充分だと思います。

## その他
以前に似た様な Issue (#43) が投稿されています。

**Comment by keiji** [comment]
これについては、#204 で触れられている `main - develop` 体制で解消されますか？（Pull Requestの運用周りは少し違っていますが）

**Comment by Takym** [comment]
充分解消されると思います。

**Comment by Takym** [comment]
#204 で解決できるのでこの Issue は閉じておきます。
