### ISSUE TITLE
ブランチ構成の変更

### ISSUE THREAD

**Issue by heykuro** [cocoa-mhlw/cocoa#204]
皆さま、いつもCOCOAの開発にご協力いただきありがとうございます。
COCOAの開発運用に関する大きなニュースが2つあります。

## 開発中のコードが公開されます
COCOAは現在(2021年6月1日時点)、2つのリポジトリで開発されています。
1つはオープンソースコミュニティの「GitHubリポジトリ」。もう一つが開発チームの管理している「内部リポジトリ」です。
これまでは内部リポジトリ側のコードは、新しいバージョンをリリースするタイミングでGitHubリポジトリに反映していました。これにより、新バージョンがリリースされるまでCOCOAの最新コードを見ていただくことができず、コントリビューターの皆さんにはご不便をおかけしていました。
この点について、新バージョンのリリースタイミングに加えて、定期的に内部リポジトリからGitHubリポジトリとの同期を行うようにしました。
これにより、コントリビューターの皆さんには、より早いタイミングで開発中のコードをご覧いただけるようになります。
同期は、おおよそ2週間に一回行う予定です。これは開発チームのスプリントの期間に合わせたものです。
2つのリポジトリ同期に伴って、GitHubリポジトリ側にも変更があります。

### developブランチの新設
内部リポジトリとの整合を取りやすくするためGitHubリポジトリに`develop`ブランチを新設して、以後デフォルトブランチとします。
developブランチが最新の開発コード、現在のmasterブランチ(→今回の変更に際してmainブランチへ変更します)は最新のリリース済のコードという位置づけになります。
デフォルトブランチの変更に伴い、すべてのPull Requestはdevelopに向けることになります。この作業はコラボレーター側で行う予定ですが、場合によってはPull Reqeustを出していただいている皆様のお力をお借りするかもしれません。その際はよろしくお願いいたします。

## Pull Requestのレビュアーに開発チームが加わります
これまで、GitHubリポジトリへのPull Requestの取り込みに当たっては、政府CIO補佐官をはじめとする数人のコラボレーターがレビューを行い、GitHubリポジトリのmasterブランチにマージし、その後、開発チームと最終調整をして内部リポジトリに反映する作業をしていました。
この方法は、開発チームの状況によっては割り込み作業を発生させることになったり、取り込み後の調整が大きくなることがあるなど、開発チームに大きな負荷をかけてしまうことがありました。また、GitHubリポジトリに取り込まれているにもかかわらず直近の新バージョンに含まれないなど、masterとリリースブランチが乖離する原因になっていました。
今後はPull Requestのレビュアーに開発チームが加わり、これまでのコラボレーターに加えて開発チームもPull Requestをレビューして技術的なフィードバックを行います。また、Pull Reqeustのレビューと取り込みタイミングについては開発チームが計画した上で行います。
これにより、GitHubリポジトリに取り込まれたPull Reqeustは、スムーズに内部リポジトリへ取り込まれることになります。
また、前述した内部リポジトリとの同期と合わせて、オープンソースコミュニティと開発チームがより密接に協力していけると考えます。

## その他
- これまでに関連issueとして #43  #200 をいただいていました。

---
Internal Tracking ID: NFR 1697

**Comment by keiji** [comment]
#210 をマージしたので`main`, `develop`作ります。

**Comment by keiji** [comment]
作成しました。
https://github.com/cocoa-mhlw/cocoa/branches

@kazgoto 
`main`ブランチの保護（masterと同じ条件）と、デフォルトブランチに`develop`ブランチを設定する作業をお願いします。

**Comment by kazgoto** [comment]
@keiji 対応完了しました。念のため確認お願いします。

**Comment by Takym** [comment]
ブランチ名について提案があります。

デフォルトブランチを `develop` にするのであれば、最新のリリース済みコードを格納している `master`/`main` ブランチは `latest` もしくは `stable` にするのはどうでしょうか？

**Comment by keiji** [comment]
開発チームの内部リポジトリと合わせる形で落ち着いた点なので、今からブランチ名変えない？　って調整始めるより、今はmainで行って、不都合がでたら改めて提案したいと思います。

mainやdevelopの位置づけについては、ちゃんと書かないといけませんね。

まずはwikiにまとめて、その後Pull Requestにして各種ドキュメントに反映します（いっそドキュメント系はwikiに移行した方がいいかな？）。

**Comment by keiji** [comment]
デフォルトブランチ変更した後、CI側の設定を変えないといけませんね。
やります。

**Comment by keiji** [comment]
#211 が取り込まれた後、`master`ブランチを消します。

**Comment by keiji** [comment]
@kazgoto
#212 が取り込まれているので`master`ブランチ削除してもらえますでしょうか。

**Comment by kazgoto** [comment]
@keiji `master` ブランチ削除完了しました。
