### ISSUE TITLE
[iOS] アプリ本体に接触通知が表示されてもプッシュ通知が送信されない可能性がある

### ISSUE THREAD

**Issue by parasite2006** [cocoa-mhlw/cocoa#207]
## 不具合の内容 / Describe the bug

接触確認アプリCOCOAにアクセスが許可されている機能の中に「通知」（プッシュ通知送信）が含まれていないため、アプリ本体に接触通知が表示されても本来送信されるべきプッシュ通知が送信されない可能性がある。
（接触通知受信時にプッシュ通知が送信されないと、ユーザーがたまたまアプリを起動してホーム画面上の「陽性者との接触を確認」ボタンを押すまで届いた接触通知が見過ごされることになる）

## 再現手順 / Steps to reproduce

1) iPhoneのホーム画面上で「設定」をタップ
2) 画面をスクロールし「接触確認アプリ」をタップ
3) 「"接触確認アプリ"にアクセスを許可」リストの「Siriと検索」の下に「通知」（四角な赤いアイコン）が表示されていない
（スクリーンショット1枚目）

## 期待される挙動 / Expected behavior

再現手順で表示される「"接触確認アプリ"にアクセスを許可」リストの「Siriと検索」の下に「通知」（四角な赤いアイコン）が表示される
（運営会社から健康管理サポートメッセージが届くとプッシュ通知を表示する健康管理アプリ"Health Amulet"の場合は、スクリーンショット2枚目のように「AMULETにアクセスを許可」リスト内に「通知」（四角な赤いアイコン）が表示されている）

## スクリーンショット / Screenshots

![IMG_0016](https://user-images.githubusercontent.com/84975567/120814872-42189c80-c58a-11eb-8693-d531b7236f60.PNG)
![HealthAmulet](https://user-images.githubusercontent.com/84975567/120814967-5bb9e400-c58a-11eb-877f-afcb879eaaed.PNG)

## 動作環境 / Environments

デバイス：iPhone SE2
OS：インストール時はiOS 14.5.1
インストール後iOS 14.6にアップデート
バージョン：1.2.2

## その他 / Additional context

テスト環境でiPhoneの実機にアプリをインストールし、スクリーンショット1のような状況で接触通知を受信させた時にプッシュ通知が表示されるかどうか検証をお願いします。

----
Internal IDs:
- Feature 1664

**Comment by yoshitomo-g** [comment]
アプリのプッシュ通知は、かなり初期の段階で無効化されたと記憶しています。現在は自前での通知は出さず、iOSに頼っている状態だと思います。

1.0.0から使っている環境では当該項目が表示されていますので、参考情報としてスクリーンショットを上げておきます。

デバイス：iPhone SE2（iPhone8から移行）
OS：14.5.1
バージョン：1.2.2
![IMG_0925](https://user-images.githubusercontent.com/77680020/120833259-8b71e780-c59c-11eb-8dde-d031a7b99ae5.PNG)

**Comment by keiji** [comment]
yoshitomo-gさんのコメントにあるように、現在のCOCOAはアプリに通知の機能を持たず、接触確認API側の通知を使ってアプリに誘導する仕組みになっています。
具体的には、陽性者との接触が確認されて、アプリが接触確認APIを通じて接触情報（ExposureInformation）を取得するタイミングで、システムが表示する通知です。

![IMG_0022](https://user-images.githubusercontent.com/932136/120911801-1bab4c00-c6c5-11eb-8ba1-dfc7f0ddb421.PNG)

![IMG_0023](https://user-images.githubusercontent.com/932136/120911808-24038700-c6c5-11eb-8be0-6734452f915b.PNG)

その上で、接触情報を取得したタイミングで通知を出すのは接触確認APIのv1の挙動です。v2を使うと接触情報（Exposure Window）を取得してもシステムは通知を出しません。
v2対応の際には、アプリ（COCOA）で独自の通知を出す必要があり、ご指摘のように通知の許可が必要になってくると思われます。

**Comment by parasite2006** [comment]
お二方、コメントどうもありがとうございます。v1上では現状でよくても、v2に対応する際には通知を許可する必要があるのですね。また接触通知受信時に出る通知のスクリーンショットもご提示いただきありがとうございました。ただ、よくある質問問(4)-1に見本として出ている「接触の検出を示す通知」のiOS版
<img width="596" alt="Notification" src="https://user-images.githubusercontent.com/84975567/121062176-bad45e80-c7ff-11eb-814a-99c7bedd90cd.png">
とは違っているのが気になります。この見本を現状にあわせて変更する必要があるのではないでしょうか？

**Comment by b-wind** [comment]
@parasite2006 keji さんの提示されてるスクショの事なら keji さんお手製アプリ経由で出した通知じゃ無いかなと。

現時点で接触があった場合、どのような表示が出てるかはよく知りません。アプリ側は特に変えていないと思いますが。

**Comment by parasite2006** [comment]
ご教示有難うございました。本物のアプリ上で陽性登録者との接触を知らせるために出る通知の体裁に変更がないのなら、よくある質問の説明用画像を変更する必要はありませんね。

**Comment by keiji** [comment]
> keji さんの提示されてるスクショの事なら keji さんお手製アプリ経由で出した通知じゃ無いかなと。

いいえ。ぼくの実験用アプリを使ってEN APIが出した通知です（ぼくの実験用アプリはローカル通知の許可を要求しません）。

EN APIはこんな感じの通知を出しますよ。（少なくともEN v1では）ローカル通知は使わなくても通知が表示されますよと説明しています。

**Comment by b-wind** [comment]
> いいえ。ぼくの実験用アプリを使ってEN APIが出した通知です

雑な説明で失礼しました。訂正頂いた内容を意図した発言でした。

**Comment by keiji** [comment]
> この見本を現状にあわせて変更する必要があるのではないでしょうか？

EN APIのバージョンごとに変わっている可能性がありますね。iOSの場合はEN APIのバージョンはiOSのバージョンに紐付くので、古いiOSを使っている人と、新しい人で表示内容が異なってきて難しいところです。

様々なバージョンの通知をギャラリーのような形式で掲載しても面白いかもしれませんね（利用者への価値提供と言うよりは、資料的な意味合いが強くなりますが…）。
