### ISSUE TITLE
[Android] WorkManagerに指定しているExistingPeriodicWorkPolicyの変更

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#21]
Android版のバックグラウンド処理（WorkManager）において`ExistingPeriodicWorkPolicy `に`ExistingPeriodicWorkPolicy.Replace`の値を指定しています。

https://github.com/cocoa-mhlw/cocoa/blob/20f3e8c570175f1ad693ccbf90ef74aff22de7fd/Covid19Radar/Xamarin.ExposureNotification/ExposureNotification.android.cs#L147-L149

これはGoogleが提供しているドキュメント[Exposure Notifications implementation guide](https://developers.google.com/android/exposure-notifications/implementation-guide#create-background-work)に基づいた記述と推測しますが、当該ドキュメントは2020年9月に更新されており、現在はExistingPeriodicWorkPolicyには`ExistingPeriodicWorkPolicy.KEEP`を指定するように記述が変更されています。

```
// Use a unique work to avoid multiple workers.
workManager.enqueueUniquePeriodicWork(
    PROVIDE_KEY_WORK_NAME,
    ExistingPeriodicWorkPolicy.KEEP,
    workRequest
)
```

[ドキュメントの更新履歴](https://developers.google.com/android/exposure-notifications/doc-change-log#enqueue-sample)によれば、`ExistingPeriodicWorkPolicy.Replace`を指定した場合、WorkManagerがシステムのJobSchedulerにジョブを追加しない問題が起こることがある。とのことです。

> This resolves an issue with WorkManager sometimes not adding a job to the system job scheduler.

最新のドキュメントの内容に基づいて、当該部分を`ExistingPeriodicWorkPolicy.KEEP`に変更することを強くお勧めします。

**Comment by keiji** [comment]
Issueとは直接関係ないのでコメントとして記載します。

現在のCOCOAの状況を大変、憂慮しています。

このIssueを見ている関係者の方は居られないのかもしれません。しかし、もし居られるならば、今一度、オープンソースのやり方でCOCOAを継続的に改善する方向へ舵を切ることを何卒ご検討ください。

もしそうなったならば、ぼくはAndroidアプリ開発に携わるソフトウェア開発者の一人として、お力になれるものと確信しています。

**Comment by heykuro** [comment]
@keiji  さん、遅くなりましたがご指摘ありがとうございます。

#25  #31 の対応に併せて、こちらも対応予定です。

```ExistingPeriodicWorkPolicy.KEEP```

に修正します。



また、コメントもありがとうございます。理想的なオープンソース開発にはまだ至れていないと思いますが、より良い開発プロセスを目指して進めていきたいと考えておりますので、今後ともよろしくお願いいたします。

**Comment by keiji** [comment]
v.1.2.3で `ExistingPeriodicWorkPolicy.KEEP` に変更されましたので本Issueはクローズします。
