### ISSUE TITLE
v1.2.4 での変更詳細が明記されていない

### ISSUE THREAD

**Issue by b-wind** [cocoa-mhlw/cocoa#212]
## 不具合の内容 / Describe the bug

v1.2.4 でどの Issue/PR が対応されたのか明記されていないので改善点を確認するのが厳しいなと。

## 再現手順 / Steps to reproduce

情報自体が不足しています。

## 期待される挙動 / Expected behavior

- 理想）開発チームからのcommitを Issue/PR に対応した部分は分けて貰う
- リリースコメントに対応する Issue を記述して貰う

## スクリーンショット / Screenshots

なし

## 動作環境 / Environments

GitHub 運用について

## その他 / Additional context

v1.2.3 では旧master ブランチへのマージコミットに記述されていました #122 。close されたものとして扱われるのでこれが見やすい訳では無いですが、参照自体は可能です。
すぐに対応が難しいようなら今後に向けての課題として貰って構いませんが、その場合どう言う形で示すのが望ましいかの議論があると良いと思います。

私自身は現状開発には参加していませんが、Twitter等で困っている人のサポート・GitHub への誘導等を行っているため変更点の把握は重要事項になっています。

**Comment by i-maruyama** [comment]
https://github.com/cocoa-mhlw/cocoa/issues/102 で議論されていたプロジェクトボード

https://github.com/cocoa-mhlw/cocoa/projects/2
https://github.com/cocoa-mhlw/cocoa/projects/1

は、どうでしょうか？（通常のリリースノートやChangeLog よりも、個人的には見やすいと思います。）ただし、 Readme.md には、リンクがあってよいかと思います。

**Comment by keiji** [comment]
i-maruyamaさんのご指摘の通り、機能としてはプロジェクトボードが近いと考えています。

@b-wind さん
> Twitter等で困っている人のサポート・GitHub への誘導等を行っているため変更点の把握は重要事項になっています。

Twitter等で困っている人のサポート、GitHubへの誘導等を行っていただきありがとうございます。

ところで、b-windさんのコメントが投稿後、数時間から数分で消えている。と言うことが何回か確認されています。またこれまでb-windさんがされたコメントがすべて削除されているという現象も確認されています。お使いの環境になんらか問題がないか、一度確認してみていただけませんでしょうか。

もしご自身の判断で削除した。環境に問題がないということであれば良いのですが、一度付いたコメントが消えると話がつながらなくなりますし、せっかく良い指摘をしていただいても「反応しても、また消えるかも」と、他のコントリビューターとのコミュニケーションに支障が出る恐れがあります。
GitHubコミュニティの円滑な運用にご協力をいただけると助かります。

**Comment by b-wind** [comment]
プロジェクトボードに集約するという事で有ればそれでも構いませんが、現時点で @keiji さんしか編集出来ない様に見受けられるので個人に頼ることの不安と（意図的出ないにしろ）ミスの発生をカバー出来る方が良いかなと思います。

プロジェクトボードも順次 close している運用の要ですので、どちらにしろreleaseからのリンクは有った方が良いと思われます。


> b-windさんのコメントが投稿後、数分から数時間で消えている。と言うことが何回か確認されています。

コメントしたは良い物の、コミュニティに投稿するにあたり適切な表現か悩み消したことは何度かあります。
関与する人間も変わっていっていますし現状のコミュニティ運営には合わない様に感じていて、出来るだけコメントしない方が良いと判断しています。
私のコメントはそのうち消えるものと思って、スルーして戴く方が良いかも知れません。

**Comment by Takym** [comment]
@b-wind さん
個人的には削除はせず、取り消し線で取り消してくださる方が助かります。

**Comment by i-maruyama** [comment]
以下
https://github.com/cocoa-mhlw/cocoa/pull/210/files
のようなコメントを OSS 側でつけてあげることも出来るようですね。（試しにやってみました。邪魔でしたら消しします）

**Comment by b-wind** [comment]
どの変更をCOCOAに取り込むか、取り込むとしたら変更が必要か、等の判断は開発チームとCollaboratorの皆さんが判断している物と認識しています。

その判断結果はもしかするとお手数をおかけするかも知れませんが、開発チームかCollaboratorの皆さんに提示して戴くのが良いと思います。
その視点からすると、プロジェクトボードは判断結果を反映したものに思えます。

PRにコミュニティー側でコメントを付けること自体は良いのですが、開発チームの意図と異なると間違い探しのようになってしまいかねません。
PR へのコメントはあくまでPRのレビュー内容とするのが良いと思います。
逆に、開発チームによって反映された物が意図した通り取り込まれているかどうかをレビューすることであれば悪くないと思います。

**Comment by keiji** [comment]
> どの変更をCOCOAに取り込むか、取り込むとしたら変更が必要か、等の判断は開発チームとCollaboratorの皆さんが判断している物と認識しています。
> その判断結果はもしかするとお手数をおかけするかも知れませんが、開発チームかCollaboratorの皆さんに提示して戴くのが良いと思います。

変更の取り込みとはPull Reqeustのことでしょうか。現時点でコラボレーターがレビューをしているものは条件が整えば取り込みますし、条件が整わなければ取り込まないという通常のOSSと同じ処理と認識していますね。

> 私のコメントはそのうち消えるものと思って、スルーして戴く方が良いかも知れません。

コントリビューターの皆さんからのコメントはどれも価値のあるものです。
書くのもそれなりの時間をかけるわけですし、読む方も時間を使って読んで考えて返信するわけなので、そのあたりご配慮をいただけるとうれしいです。ちなみに、b-windさんのこれまでのコメントに不適切なものがあったとはぼくは考えていません。

もちろん、現状のコミュニティ運営に合わないという判断は尊重します。

**Comment by b-wind** [comment]
> 変更の取り込みとはPull Reqeustのことでしょうか。現時点でコラボレーターがレビューをしているものは条件が整えば取りこみますし、条件が整わなければ取り込まないという通常のOSSと同じ処理と認識していますね。


認識の差異を確認させて下さい。


まずコミュニティ側の変更という事でPRをベースとしているという認識で結構です。


「現時点でコラボレーターがレビューをしているもの」と有りますが、 @keiji さんがレビューしている以外には殆ど見かけない。と言う印象です。（単に見かけの問題だとは思いますが、こちらからの視点としてはそうなります）



加えて、PR に付いては直接（旧）master に直接mergeされたものと、開発チームの内部リポジトリに取り込まれてからリリース時に（旧）master に取り込まれたものとの２種類があると言う認識です。


私が気にしているのは後者で、これはGitHub のUIから追うのは困難です。これを開発チーム側から明示して欲しいと思っています。
開発チームの内部リポジトリの存在を否定はしませんが、「通常のOSSと同じ」とはとても言えないと思います。


@keiji さんから見えている物は色々有るのだと思いますが、私を含む第三者から見て見えていない物があるという認識です。

**Comment by keiji** [comment]
話が発散しそうなので、Issueの主題である「v1.2.4の変更詳細が明記されていない」に関して、@b-wind さんの考える理想状態を教えてもらえますか？

**Comment by b-wind** [comment]
理想については Issue の説明に書いたとおりです。

妥協案としてはリリースの説明に対応した Issue が列挙してあることです。
該当Issueには1つのPRが対応するケースはそれだけで分かりますが、複数のPRが絡んでいる場合は採用したPRも併記してあるとよりよいと思います。

**Comment by keiji** [comment]
> 理想）開発チームからのcommitを Issue/PR に対応した部分は分けて貰う

理想状態とはこちらでしょうか。
以前は一つのコミットに様々な変更が含まれていましたが、v1.2.4のPull Requestではきちんとcommitが分けれていると認識しています。

https://github.com/cocoa-mhlw/cocoa/pull/210/commits

また今後の方針については #204 に記載していますが、これでは不足と言うことでしょうか。

**Comment by b-wind** [comment]
そうですね、こちらのコミットには複数の内容が入っており、一見してどのIssueに対応しているか分かりません。
https://github.com/cocoa-mhlw/cocoa/pull/210/commits/3e6a1a473143c1e9889f164bcd01f0c348d637bd


#204 に関しては実際にどうなるのか見てみないと分からないと言う気持ちが勝っており、何とも申し上げられないです。

**Comment by keiji** [comment]
では、#204 がどうなるか。ですね。
リリースコメントにプロジェクトボードへのリンクを記載しておきますね。

**Comment by b-wind** [comment]
> リリースコメントにプロジェクトボードへのリンクを記載しておきますね。

はい。ありがとうございます。
v1.2.4 に対する内容としては私の求める事項を満たしていると思います。

**Comment by b-wind** [comment]
この Issue そのものの問題は解決しましたが、運用に関する意識はどうもズレがあるなぁという印象です。
とはいえ、他の誰も気にしていないのでしたら自分一人グダグダ言うのも無駄なので別途Issue化などはしない方が良さそうですね。

繰り返しになりますが対応ありがとうございました。このIssueで成したいことは満たされたのでcloseとさせて頂きます。
