### ISSUE TITLE
/version.json が v1.2.2 を指したままである

### ISSUE THREAD

**Issue by b-wind** [cocoa-mhlw/cocoa#213]
## 不具合の内容 / Describe the bug

/version.json が v1.2.2 を指したままなので、旧バージョンからのアップデートを促すダイアログが出ません。
使わないことにしたのか、もう少し後から更新するつもりだったのかはこちらでは分かりかねます。

## 再現手順 / Steps to reproduce

1. https://covid19radarjpnprod.z11.web.core.windows.net/version.json を参照する

## 期待される挙動 / Expected behavior

v1.2.4 を指すようになる。

## スクリーンショット / Screenshots

無し。

## 動作環境 / Environments

すべて。

## その他 / Additional context

特になし。

**Comment by keiji** [comment]
ウェブに置いたファイルの更新作業は週ごとに行っていて、ちょうど先ほど更新が反映されたとのことでした。

**Comment by b-wind** [comment]
了解しました。
また更新されていることを確認しました。


タイミングにずれが生じる事自体は問題とは思いませんが、そのような運用である事はどこかに記述してあると嬉しいかも知れませんね。

**Comment by b-wind** [comment]
事象が解消された様なので、close とさせて頂きます。
