### ISSUE TITLE
ランチャーに表示するアプリ名について

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#216]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

>PlayストアでダウンロードするときはCOCOAって最初に書いてるのにインストールしたらアプリランチャーのどこにもCOCOAが出てこないのは分かりにくいんじゃないかなあって思ったりしました。
（COCOAで端末内検索してもなんも見つからない

（https://twitter.com/8796n/status/1401743971248865282 より）

iOSとAndroidでアプリ名が異なる。

 * 接触確認アプリ
 * 新型コロナウイルス 接触確認アプリ

Androidのランチャー（Pixel Launcher）では、アプリ名が省略されてしまう（iOSでは問題ない）

![device-2021-06-10-120249](https://user-images.githubusercontent.com/932136/121459105-9934cc00-c9e5-11eb-8136-c9973e105fa2.png)

![Screen Shot 2021-06-10 at 12 11 10](https://user-images.githubusercontent.com/932136/121459117-9e921680-c9e5-11eb-846d-971864b266e2.png)

## 解決策についてお書きください / Describe the solution you'd like

ランチャーに表示するアプリ名を「COCOA」にする。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

アプリ名を「接触確認アプリ COCOA」にする。

アプリ名を「COCOA 接触確認アプリ」にする。

> 端末のアプリ検索のキーワードって名称とべつに設定できないんですか？できるんだったら互換性を維持したままもっと端末検索ビリティが。

( https://twitter.com/__gfx__/status/1401814952730451971 より)

ランチャーからのアプリ検索で「COCOA」で検索できるようになるだけでも便利かも。

## その他 / Additional context
今はそれなりに知名度があるはずなのでシンプルに COCOA で通じて欲しい。

----
Internal IDs:
- Bug 2294

**Comment by keiji** [comment]
ランチャー（ホーム）に表示されるアプリ名を言語を切り換えて確認したところ、みんなバラバラだと言うことがわかった。

iOS
 - （日本語） 接触確認アプリ
 - （英語）COVID-19 Contact App
 - （中国語） COVID-19 Contact App
 - （未対応言語・ドイツ語）接触確認アプリ

Android
 - （日本語） 新型コロナウイルス　接触確認アプリ
 - （英語）COVID-19 Contact App
 - （中国語） 接触確認アプリ
 - （未対応言語・ドイツ語）COVID-19 Contact App

**Comment by fumiya-kume** [comment]
>（中国語） 接触確認アプリ

Android 版の中国語設定の時にカタカナが入るのは避けたほうがいいかも？
漢字だけならまだ読んでもらいやすいですが、カタカナは厳しそう...

ので、英語の時と同じく `COVID-19 Contact App` にしても良さそう。

**Comment by Takym** [comment]
`AppResources` では下記の様に定義されているみたいです。
https://github.com/cocoa-mhlw/cocoa/blob/c29d7a74a428ae9c2dfe563578cf37c404ce3503/Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx#L28-L29
https://github.com/cocoa-mhlw/cocoa/blob/c29d7a74a428ae9c2dfe563578cf37c404ce3503/Covid19Radar/Covid19Radar/Resources/AppResources.en.resx#L28-L29
https://github.com/cocoa-mhlw/cocoa/blob/c29d7a74a428ae9c2dfe563578cf37c404ce3503/Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hant.resx#L28-L29
https://github.com/cocoa-mhlw/cocoa/blob/c29d7a74a428ae9c2dfe563578cf37c404ce3503/Covid19Radar/Covid19Radar/Resources/AppResources.zh-Hans.resx#L28-L29

**Comment by fumiya-kume** [comment]
およよ、もしかして `.zh.resx` が無い...?

**Comment by Takym** [comment]
Android 側のアプリ名は `AppResources` とは違う名前を指定している様ですね。
https://github.com/cocoa-mhlw/cocoa/blob/c29d7a74a428ae9c2dfe563578cf37c404ce3503/Covid19Radar/Covid19Radar.Android/Resources/values/Strings.xml#L7
https://github.com/cocoa-mhlw/cocoa/blob/c29d7a74a428ae9c2dfe563578cf37c404ce3503/Covid19Radar/Covid19Radar.Android/Resources/values-ja/Strings.xml#L7
https://github.com/cocoa-mhlw/cocoa/blob/c29d7a74a428ae9c2dfe563578cf37c404ce3503/Covid19Radar/Covid19Radar.Android/Resources/values-en/Strings.xml#L7
https://github.com/cocoa-mhlw/cocoa/blob/c29d7a74a428ae9c2dfe563578cf37c404ce3503/Covid19Radar/Covid19Radar.Android/Resources/values-zh/Strings.xml#L7
https://github.com/cocoa-mhlw/cocoa/blob/c29d7a74a428ae9c2dfe563578cf37c404ce3503/Covid19Radar/Covid19Radar.Android/Resources/values-cn/Strings.xml#L7

@fumiya-kume さん
中国語は簡体字と繁体字を区別する必要があるので `.zh.resx` は作らないそうです。

**Comment by Takym** [comment]
iOS 側では下記の様になっています。
https://github.com/cocoa-mhlw/cocoa/blob/c29d7a74a428ae9c2dfe563578cf37c404ce3503/Covid19Radar/Covid19Radar.iOS/Resources/Base.lproj/InfoPlist.strings#L5
https://github.com/cocoa-mhlw/cocoa/blob/c29d7a74a428ae9c2dfe563578cf37c404ce3503/Covid19Radar/Covid19Radar.iOS/Resources/ja.lproj/InfoPlist.strings#L5
https://github.com/cocoa-mhlw/cocoa/blob/c29d7a74a428ae9c2dfe563578cf37c404ce3503/Covid19Radar/Covid19Radar.iOS/Resources/en.lproj/InfoPlist.strings#L5
https://github.com/cocoa-mhlw/cocoa/blob/c29d7a74a428ae9c2dfe563578cf37c404ce3503/Covid19Radar/Covid19Radar.iOS/Resources/zh.lproj/InfoPlist.strings#L5

**Comment by fumiya-kume** [comment]
>中国語は簡体字と繁体字を区別する必要があるので .zh.resx は作らないそうです。

なるほど。学びになります。

**Comment by Takym** [comment]
上記は少し見辛いので表にまとめました。

|言語        |`AppResources`                  |Android                           |iOS                               |
|:-----------|:-------------------------------|:---------------------------------|:---------------------------------|
|(既定)      |COVID-19 Contact App            |COVID-19 Contact App              |COVID-19 Contact App              |
|日本語      |新型コロナウイルス接触確認アプリ|新型コロナウイルス　接触確認アプリ|新型コロナウイルス　接触確認アプリ|
|英語        |COVID-19 Contact App            |COVID-19 Contact App              |COVID-19 Contact App              |
|繁体字中国語|COVID-19 接觸者確認 App         |新型肺炎密切接触者查询APP         |新型肺炎密切接触者查询APP         |
|簡体字中国語|新型肺炎密切接触者查询APP       |新型コロナウイルス　接触確認アプリ|                                  |

**Comment by i-maruyama** [comment]
> ランチャー（ホーム）に表示されるアプリ名を言語を切り換えて確認した。
> 
> iOS
> 
> * （日本語） 接触確認アプリ
> * （英語）COVID-19 Contact App
> * （中国語） COVID-19 Contact App
> * （未対応言語・ドイツ語）接触確認アプリ
> 
> Android
> 
> * （日本語） 新型コロナウイルス　接触確認アプリ
> * （英語）COVID-19 Contact App
> * （中国語） 接触確認アプリ
> * （未対応言語・ドイツ語）COVID-19 Contact App

私も確認しました。（iOS と Android が逆になっていると思います）

まず、 Android は ItemGroup を設定していませんので、それを治すだけＯＫのようです。
iOS のデフォルトは、トップの Info.plist のせいですので、これは英語にします。この２点の修正例は以下です。
https://github.com/i-maruyama/cocoa/commit/61ac55fda449dccfe28085f482167a3787bfed04

さて、残る iOS の中国語に対応するには、Takym さんがまとめられているように、 zh-Hans, zh-Hant を作る必要がありますが、現状のリソースファイルには、 
https://github.com/cocoa-mhlw/cocoa/tree/develop/Covid19Radar/Covid19Radar.iOS/Resources/zh.lproj
しかないです。これが原因に見えたのですが、画像ファイルも全部コピーするのか・・・と思って止めました。

iOS は、リソースアイコン等を被らないようにできればよいと思いますが、私は実験環境がないのでわかりません。

**Comment by Takym** [comment]
`/Covid19Radar/Covid19Radar.iOS/Resources/Base.lproj/InfoPlist.strings` より `/Covid19Radar/Covid19Radar.iOS/Info.plist` が優先して適用されるのですね。これは知りませんでした。

https://github.com/cocoa-mhlw/cocoa/blob/c29d7a74a428ae9c2dfe563578cf37c404ce3503/Covid19Radar/Covid19Radar.iOS/Info.plist#L30-L31

**Comment by b-wind** [comment]
各ストア・各言語設定での表示はどうなっているのだろうと少し気になりました。

（COCOA における中国語公式サポートは 簡体字 のみを指している…… と思っていましたが、そんな仕様はどこにも書いて無かった ）

**Comment by AyumuOzaki** [comment]
ランチャー名の「COCOA」への変更に大いに賛成致します。
アイコン下に表示されるアプリ名の字数は制限されており，簡潔なものの方が好ましいのではないかと私も思っている所でした。

**Comment by keiji** [comment]
これは次のバージョンでやることになりそうです。

**Comment by keiji** [comment]
Android, iOS版で、すべての言語でアプリ名を「COCOA」で統一することになりました。
