### ISSUE TITLE
`DateTimeUtility` のインスタンスを外部から簡単に書き変える事がでてしまう

### ISSUE THREAD

**Issue by Takym** [cocoa-mhlw/cocoa#223]
https://github.com/cocoa-mhlw/cocoa/pull/151#issuecomment-855713433 から

## 不具合の内容
https://github.com/cocoa-mhlw/cocoa/blob/8052045323e6a54826f04d3d2b705cf775736e1f/Covid19Radar/Covid19Radar/Common/DateTimeUtility.cs#L10
上記の `Instance` は外部から書き変える事ができるので日時の取得処理が壊される可能性があります。

## 再現手順
今の所は、テストプロジェクトからのみ書き換えられています。

## 期待される挙動
https://github.com/cocoa-mhlw/cocoa/blob/c29d7a74a428ae9c2dfe563578cf37c404ce3503/Covid19Radar/Covid19Radar/App.xaml.cs#L161
上記の関数にてサービスとして追加します。

## 動作環境

- デバイス：全て
- OS：全て
- バージョン：1.2.4
----
Internal IDs:
- NFR 2900

**Comment by keiji** [comment]
c496a3b2073bc0604dbd0232f21b183cc1dd4f75 が develop に取り込まれたのでcloseします。
