### ISSUE TITLE
DateTimeUtility.cs にMPL 2.0 のライセンス通知が含まれていない

### ISSUE THREAD

**Issue by b-wind** [cocoa-mhlw/cocoa#229]
## 不具合の内容 / Describe the bug

Covid19Radar/Common/DateTimeUtility.cs にMPL 2.0 のライセンス通知が含まれていません。

## 再現手順 / Steps to reproduce

以下を参照。
https://github.com/cocoa-mhlw/cocoa/blob/8052045323e6a54826f04d3d2b705cf775736e1f/Covid19Radar/Covid19Radar/Common/DateTimeUtility.cs#L1

## 期待される挙動 / Expected behavior

MPL 2.0 のライセンス通知が追記される

## スクリーンショット / Screenshots

なし。

## 動作環境 / Environments

すべて。

## その他 / Additional context

リリース前に確認プロセスがあると望ましいかも知れません。

----
Internal IDs:
- NFR 2704

**Comment by b-wind** [comment]
#224 にて対応が含まれている模様（タイトルから分かりませんが）

**Comment by b-wind** [comment]
GitHub ベースで考えるなら、push 時にライセンス付与してくれる Action 等はあります。
https://github.com/marketplace/actions/add-license-action


ライセンス通知が含まれてないとpush出来ない方が良いのかは悩み所。

**Comment by Meiryo7743** [comment]
今後のためにも，MPL ライセンスの記載漏れの事故が生じない仕組みを検討する必要がありますね……。

いま，内部リポジトリと GitHub 上での公開リポジトリの 2 つが存在し，定期的な同期がなされるわけです。したがって，リポジトリの置かれる環境に依存しない方法でチェックできるのが理想的と考えられます。

上記を踏まえ，Git hooks を導入してみるのはどうでしょうか。元々 Git に組み込まれている機能で，例えば clone や commit 時に任意の処理が走るというものです。

さらに念を入れるのでしたら，それこそ CI でチェックする仕組みを構築するのが良いでしょう。

cf. <https://git-scm.com/docs/githooks>

**Comment by b-wind** [comment]
みんな考える事は似てるなぁという感じで見てる。

https://github.com/google/addlicense

**Comment by b-wind** [comment]
無条件に MPL 2.0 にすると Xamarin.ExposureNotification とかで困りそう。

**Comment by b-wind** [comment]
基本的にこのIssueでは該当ファイルにどのような方法でも良いので追加されることを目標としています。
ライセンスヘッダ付与の自動化を考えている方々は別途その趣旨の Issue を立てて貰った方が良い様に思います。

**Comment by Takym** [comment]
#225 にて建てました。

**Comment by b-wind** [comment]
メモ：
https://github.com/kt3k/deno_license_checker

.licenserc.json 作例
```json
{
    "**/*.cs" : [
        "This Source Code Form is subject to the terms of the Mozilla Public",
        "License, v. 2.0. If a copy of the MPL was not distributed with this",
        "file, You can obtain one at https://mozilla.org/MPL/2.0/."
    ],
    "ignore" : [
        "Covid19Radar/Xamarin.ExposureNotification/",
        "Covid19Radar/Covid19Radar/Resources/AppResources.Designer.cs",
        "Covid19Radar/Tests/Covid19Radar.UITest/",
        "src/Covid19Radar.Api.Tests/"
    ]
}
```

GitHub Actions 版
https://github.com/kt3k/license_checker

**Comment by keiji** [comment]
c496a3b2073bc0604dbd0232f21b183cc1dd4f75 が developに取り込まれたのでcloseします。
