### ISSUE TITLE
未使用の TutorialPage5, ThankYouNotifyOtherPage の削除、または利用

### ISSUE THREAD

**Issue by i-maruyama** [cocoa-mhlw/cocoa#230]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

1. バグではありませんが、 TutorialPage5 (プッシュ通知の有効化)は使用されていません。
2. ThankYouNotifyOtherPage (陽性登録ありがとう)は使用されていません.

## 解決策についてお書きください / Describe the solution you'd like

1. TutorialPage5 は削除する[1]。サイズが減り、可読性があがります。また将来的なUI変更( #194 )でも、 TutorialPage5 は使われる気配はなく、そもそもこのページの「プッシュ通知の有効化」ボタンは使えません(下記コード)。
https://github.com/cocoa-mhlw/cocoa/blob/c29d7a74a428ae9c2dfe563578cf37c404ce3503/Covid19Radar/Covid19Radar/ViewModels/Tutorial/TutorialPage5ViewModel.cs#L22-L34

2. ThankYouNotifyOtherPage は利用する。
#194
## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

1. TutorialPage5 は将来的に使う予定であれば、残しておいて良いと思いますので、本 issue はクローズします。( DebugPage #160 のナビゲーションにも残します)
2. TutorialPage5 は削除せず、とりあえず、 csproj を用いて見えなくしておくか、Unused に移動する。
3. ThankYouNotifyOtherPage は削除する。(これだけ準備されていて使わなかった理由も何かあるのかもしれません）

## その他 / Additional context

[1] で「使用されていない」と言われても不安だと思いますので、 grep 検索などお試しください。念の為、perl でやっつけてページ遷移を作りました。(現在の developブランチ)全３２ページを調査し、grep 検索対象は155ファイル(App.xaml, App.xaml.csの除く)です。

![dot](https://user-images.githubusercontent.com/4100714/121761172-3ec47880-cb69-11eb-9592-372947bda2f0.png)

1. ThankYouNotifyOtherPage が孤立しているのがわかります。
2. ExceptionPage は、実は App.xaml.cs から呼ばれていますので必要です。
3. 矢印を見れば分かるとおり、TutorialPage5 からTutorialPage6 には遷移しますが、TutorialPage5 に遷移することはありません。

なにせ grep ですから、変なものを拾っている可能性はありますので、ミスありましたらコメントください。少なくともThankYouNotifyOtherPage とTutorialPage5については十分だと思います。

----
Internal IDs:
- NFR 2914

**Comment by tatsu-jp** [comment]
コミット履歴を少々調べてみました。

### TutorialPage5 について
https://github.com/Covid-19Radar/Covid19Radar/pull/680 の変更で、該当ページへ遷移しないように変更されています。
PRから削除した背景を読み取れませんでしたが、現時点では不要なように思います。

### ThankyouNotifyOtherPage について
以下の流れで、該当ページへの遷移の追加と削除がなされています。
作ったもののユーザーの同意を得ないとダメなことに気づいて無効化し、SubmitConsentPageを追加しているように見えますね。
直近でcocoa-devによって削除されているので、不要なように思います。

Add ThankYouNotifyOthers(4 Jun 2020) : https://github.com/cocoa-mhlw/cocoa/commit/9b2c1c70b3b94f515fc5662305ec6c1f7cfef8cd#diff-ead0fe1ddcb48057abbc9567ed0a6d2e03a1a69a1c6c3342b8ca8c8370336e9c

Fix Settings Pages(ThankyouNotifyOthersPageの無効化[DEBUG]) (5 Jun 2020): https://github.com/cocoa-mhlw/cocoa/commit/3bdaae003847c6b5ec1886a576279d19a7a7a583#diff-ead0fe1ddcb48057abbc9567ed0a6d2e03a1a69a1c6c3342b8ca8c8370336e9c

Add Submit Consent Page(9 Jun 2020) : https://github.com/cocoa-mhlw/cocoa/commit/93b483d044cfe0dced5382714decd23a032abac3#diff-ead0fe1ddcb48057abbc9567ed0a6d2e03a1a69a1c6c3342b8ca8c8370336e9c

ThankyouNotifyOthersPageへの遷移(DEBUG)の削除(2021年2月) : https://github.com/cocoa-mhlw/cocoa/commit/047b12bfc497e5e32bd96e24c2b5d76c8ca18bcf#diff-ead0fe1ddcb48057abbc9567ed0a6d2e03a1a69a1c6c3342b8ca8c8370336e9c

**Comment by i-maruyama** [comment]
> Add ThankYouNotifyOthers(4 Jun 2020) : 9b2c1c7
> "新型コロナウイルス感染症者等情報把握・管理支援システム（HER-SYS）から発行された処理番号を入力してください。過去14日間に本アプリであなたと接触した履歴のある人に通知が行きます。"
> "登録は匿名で行われ、氏名や連絡先など個人が特定される情報を登録する必要はありません。また、接触した場所の位置情報が記録や通知されることもありません。"
> "登録する"

昔は「登録用ページ」だったという事ですね。今は「陽性のご登録をいただきありがとうございました」なので、用途自体がいつの間にか変わったようですね。
