### ISSUE TITLE
Prism.Plugin.Logging.AppCenter への依存が残っている

### ISSUE THREAD

**Issue by b-wind** [cocoa-mhlw/cocoa#238]
## 不具合の内容 / Describe the bug

v1.2.4 に置いても Prism.Plugin.Logging.AppCenter パッケージへの依存が残っています。

実際は #58 で影響無いことを確認して頂いていますし、実害は無いと思うのですが
不要なパッケージですし、余計な疑いをかけられたくないと言う心情があります（個人情報を送信している等）

https://github.com/cocoa-mhlw/cocoa/blob/8052045323e6a54826f04d3d2b705cf775736e1f/Covid19Radar/Covid19Radar/Covid19Radar.csproj#L107

https://github.com/cocoa-mhlw/cocoa/blob/8052045323e6a54826f04d3d2b705cf775736e1f/Covid19Radar/Covid19Radar.Android/Covid19Radar.Android.csproj#L147-L149

## 動作環境 / Environments

- デバイス：Any
- OS：Android、iOS
- バージョン：v1.2.4 以前

## その他 / Additional context

単独での対処が手間がかかるようでしたら不要なファイルを削除する等、類似の Issue/PR で対応していただいて問題無いと思います。
----
Internal IDs:
- NFR 1663

**Comment by Aqua-ix** [comment]
私の手元で試した所、それほど手間は掛からなそうでしたのでPRさせて頂きます。

**Comment by b-wind** [comment]
詳細は確認していないが、FFImageLoadingLogger に依存関係がある様子。

纏めて消すという判断の様子。 https://github.com/cocoa-mhlw/cocoa/pull/239#discussion_r651384385

**Comment by b-wind** [comment]
DebugLogger による、FFImageLoading のロギングも一端削除。
