### ISSUE TITLE
`Xamarin.ExposureNotification` を NuGet から参照する様に変更する

### ISSUE THREAD

**Issue by Takym** [cocoa-mhlw/cocoa#241]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?
`Xamarin.ExposureNotification` のソースコードは丸ごとコピーされていますが、何か特別な理由はあるのでしょうか。
特に無ければ NuGet から参照する様に変更した方が無難だと思います。

## 解決策についてお書きください / Describe the solution you'd like
`Xamarin.ExposureNotification` を NuGet から参照する様に変更します。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered
現在のままでも特に問題は無いのでこのままにしておきます。

**Comment by b-wind** [comment]
古いバージョンをforkした物を取り込み、そのままと言う理解です。
バージョンアップは計画されていたと思いますが、現状は分かりませんね。

**Comment by keiji** [comment]
現在の`Xamarin.ExposureNotification`はオリジナルから結構変わってるんですよね。
たとえば、バックグラウンド処理（WorkManager）の`ExistingPeriodicWorkPolicy`が、今のCOCOAでは`Keep`ですが、オリジナル版では`Replace`です。

xamarin/XamarinComponentsにはPull Requestを出していますが反応がありません（あと、CLAの提出機構がなぜか働かない）
https://github.com/xamarin/XamarinComponents/pull/1108/files

ほかにも、変更に伴って既存のWorkManagerのジョブをキャンセルする仕組みなどが加わっています（これはコードを工夫すれば取り除けると思いますが）。

**Comment by b-wind** [comment]
CLA ってここから同意するのですかね。
https://cla.dotnetfoundation.org/xamarin/XamarinComponents?pullRequest=1108

**Comment by Takym** [comment]
`ExistingPeriodicWorkPolicy` は外側からは書き換える事はできないのでしょうか。

**Comment by Takym** [comment]
今ソースコードを読みましたが、外側からの書き換えはできないみたいですね。

**Comment by keiji** [comment]
こちらひとまずwon't fixに指定した上でcloseとはせず「条件が整えばNuGet参照に切り換えたいね」という扱いで行きたいと思います。

**Comment by tmurakami** [comment]
(すでにご存知かもしれませんが) Fhi.Smittestopp.App では`Xamarin.ExposureNotification.Init()`を利用せずに自前でバックグランド処理を実装しています。
Android: https://github.com/folkehelseinstituttet/Fhi.Smittestopp.App/blob/7c8e687a24d7e9d0f27f0885ee6d48d8a2c2e41e/NDB.Covid19/NDB.Covid19.Droid/Utils/BackgroundFetchScheduler.cs
iOS: https://github.com/folkehelseinstituttet/Fhi.Smittestopp.App/blob/7c8e687a24d7e9d0f27f0885ee6d48d8a2c2e41e/NDB.Covid19/NDB.Covid19.iOS/Utils/BackgroundServiceHandler.cs

COCOA でも、自前でバックグランド処理を持つことができれば NuGet を利用することができるのではないかと思っています。
いかがでしょうか？

**Comment by keiji** [comment]
Xamarin.ExposureNotificationはExposureWindow mode対応のCOCOA2で取り除く予定です。

Xamarin.ExposureNotificationがベースにしている`Xamarin.GooglePlayServices.Nearby.ExposureNotification`に[課題](https://github.com/xamarin/XamarinComponents/pull/1231)があります。課題を解決するPull Requestは出しており、取り込まれるのを待っている状態です。

Xamarin.ExposureNotificationのメンテナンスが継続するのが望ましいと考えていますが、次善の策として別のExposureNotificationライブラリを使った実装を`feature/cocoa2`で進めています。
本Issueについては`feature/cocoa2`がdevelopブランチに取り込まれたタイミングでクローズとする予定です。

**Comment by keiji** [comment]
時が過ぎ、現在のdevelopからはXamarin.ExposureNotificationがdevelopは含まれていませんので本IssueをCloseします。
