### ISSUE TITLE
厚生労働省ロゴのフォント変更に伴うCOCOA内にあるロゴ画像の変更【提案】

### ISSUE THREAD

**Issue by AyumuOzaki** [cocoa-mhlw/cocoa#243]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?
先日，COCOAを所管する厚生労働省のホームページを覗いてみますと，ページ右上に表示されるロゴのフォントに違和感を覚えました。以前のホームページと見比べてみますと，シンボルマークはそのままですが，どうやら「厚生労働省」ロゴの部分のフォントが丸ゴシックからより直線的な角ゴシックに変更されたようです。

![header_logo_mhlw](https://user-images.githubusercontent.com/60840386/122653890-c706d700-d182-11eb-829f-ec45c91d25cb.png)
↑旧ロゴ(2008～2021年)
参考リンク：https://web.archive.org/web/20210417134516/https://www.mhlw.go.jp/chosakuken/index.html

![MHLW](https://user-images.githubusercontent.com/60840386/122653892-c8380400-d182-11eb-8dd3-35ffde808eba.png)
↑新ロゴ(2021年～)
参考リンク：https://www.mhlw.go.jp/chosakuken/index.html

## 解決策についてお書きください / Describe the solution you'd like

COCOAでも，起動中の画面にアマビエの啓発アイコンとともに厚生労働省のロゴが，アプリ起動後の画面においてもハンバーガーメニューのアイコンの隣に厚生労働省のロゴが表示されます。

![Screenshot_2021-06-18-14-18-52 - コピー](https://user-images.githubusercontent.com/60840386/122598165-6ce51380-d0a7-11eb-93f6-9270f6e97c44.jpg)

もしかすると現時点でも，COCOAに梱包されているロゴ画像の差し替えが既に検討されているかもしれませんが，念の為，提案させていただきます。
選択肢は2つあります。一つは古いフォントを使用したロゴ画像使用を続行。もう一つは新しいフォントを使用したロゴ画像への変更です。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

ホームページではページによって，現状の新旧ロゴの併用(https://www.mhlw.go.jp/kinkyu/160930-2.html ，https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/cocoa_00138.html 参照)という状態がしばらく続く考えられます（なんだか，Yahoo! JAPANやGoogle，YouTube，Microsoft，ニコニコなんかが新しいロゴに変更した時を思い出します…）。ただ，トップページや新しく作成されたページから順に差し替えが進むと思われます。なお，COCOAでの新旧ロゴが併用されるという選択肢が選ばれる可能性については低いと考えており，私はどちらかのロゴに統一するべきだと考えています。

## その他 / Additional context

5月31日時点には，ホームページのロゴ差し替えが行われていたようです。

参考リンク：

ばらんすさんはTwitterを使っています 「厚生労働省HP上部の「厚生労働省」のフォントが変わったこと、何人気付いているんだろう…」 / Twitter https://twitter.com/neginegichukasa/status/1399290023082479616

----
Internal IDs:
- NFR 2799

**Comment by AyumuOzaki** [comment]
ラベル付け，ありがとうございます。

**Comment by b-wind** [comment]
ご連絡ありがとうございます。
ファイルのタイムスタンプを見る限り 5/28 付けで更新ですかね。
関係者確認後に変更の有無をご返答できるかと思います。

**Comment by AyumuOzaki** [comment]
ご返信ありがとうございます。やはり本省での確認が必要となるのですね。何卒，よろしくお願い致します。

**Comment by b-wind** [comment]
本省での確認…… といいますか、このリポジトリの運営は「内閣官房情報通信技術（IT）総合戦略室」ですし、参加者のほとんどはボランティアですので、厚生労働省の事情は別途連絡が無い限り分からないですね。

**Comment by AyumuOzaki** [comment]
なるほど。そうでしたか。厚労省のロゴですし，https://github.com/cocoa-mhlw/cocoa/issues/3 にもあるように，ライセンス上の確認もまた必要になるのだろうと推察します。

なお，ライセンス関連について追記しますと，厚生労働省シンボルマーク(ロゴの一番左の赤と青の人が手を上げている部分)の使用に関しては，日本政府標準利用規約（第2.0版）及びそれに準拠している厚生労働省ホームページの利用規約 でも「シンボルマークは適用外」となっており(それぞれ，クリエイティブ・コモンズ・ライセンスの表示4.0国際; CC BY 4.0 互換)，厚労省HP利用規約の別紙にあるシンボルマークの使用規定によれば「厚生労働省から依頼を受けてシンボルマーク入りの物品等を製作する場合」「厚生労働省の委嘱を受けて実施する事業等において製作する資料や物品に、厚生労働省の委嘱を受けていることを、シンボルマークを用いて表示する場合」等は使用できるようです。

私も最近までライセンス関連については知らない事も多かった為，後から来る人の為にもとりあえずまとめておきます。

参考：

「政府標準利用規約（第 2.0 版）」 
https://cio.go.jp/sites/default/files/uploads/documents/opendata_nijiriyou_betten1.pdf 

利用規約・リンク・著作権等｜厚生労働省
https://www.mhlw.go.jp/chosakuken/index.html

クリエイティブ・コモンズ (Creative Commons) — 表示 4.0 国際 — CC BY 4.0
https://creativecommons.org/licenses/by/4.0/legalcode.ja

シンボルマークの使用｜厚生労働省
https://www.mhlw.go.jp/kouseiroudoushou/symbol/shiyou.html

**Comment by keiji** [comment]
@AyumuOzaki 
b-windさんのコメントした「関係者確認後に変更の要不要をご返答できるかと思います」というのは、b-windさんご自身はそうなるだろうと考えているということです。実際のIssueの進行とは異なる場合がありますのでご注意ください。

**Comment by AyumuOzaki** [comment]
ご返信ありがとうございます。了解しました。

**Comment by b-wind** [comment]
言葉足らずで失礼しました。
基本 Collaborator となっている方の言葉を信用して貰って結構です。

**Comment by AyumuOzaki** [comment]
そうですか，わかりました。

**Comment by keiji** [comment]
先頃のコード反映で新ロゴへの置き換えを行ったので、ご報告します。
Issueの提出ありがとうございました。

![Screen Shot 2021-12-25 at 17 36 51](https://user-images.githubusercontent.com/932136/147381094-e9a6eb41-e6fe-4d19-937f-ea4dd8ce9806.png)
