### ISSUE TITLE
[Android] 診断キーサーバーと通信するタスクが定期実行されない

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#25]
**Describe the bug**
https://www.mhlw.go.jp/stf/newpage_16841.html

> 本来であれば、本アプリはGoogle社が提供する接触通知機能と連動し、陽性者が通知サーバーに登録した接触に関する情報を１日に１回程度各端末にダウンロードし、各端末内の記録と照合・通知を行う仕組みとなっています。Android端末13台/13ケースを用いて36時間後の状態を確認した限定的な検証の結果、本アプリがバックグラウンドから強制終了されてしまうことにより当該処理が実行されないケース、あるいはバックグラウンドで起動している状態であっても当該処理を定期的に実行していないケースが７ケース見つかりました。

**Expected behavior**
設定した間隔ごとにバックグラウンドタスクが実行される。

**Smartphone (please complete the following information):**
 - Device: Essential PH-1
 - OS: Android 10

----

## 考えられる原因
バックグラウンドタスクの処理実体`Covid19Radar.Services.ExposureNotificationHandler`内で`DependencyService.Resolve`を使って依存性の注入（Dependency Injection）をしていることが原因と考えられる。

```
private ILoggerService LoggerService => DependencyService.Resolve<ILoggerService>();
private IHttpDataService HttpDataService => DependencyService.Resolve<IHttpDataService>();
private IExposureNotificationService ExposureNotificationService => DependencyService.Resolve<IExposureNotificationService>();
```

これらの依存は`Covid19Radar.App`で設定されている。`Covid19Radar.App`の実行は`Covid19Radar.Droid.MainActivity`の`onCreate`で`LoadApplication`するタイミング（アプリの起動と同義）となる。

ユーザーがCOCOAアプリを起動した後、`Covid19Radar.App`が初期化されアプリのプロセスが残っている状態で前述の`DependencyService.Resolve`が行われた場合、バックグラウンド処理は問題なく実行される。

しかし、メモリ不足などの理由でAndroidのシステムが**アプリのプロセスを終了した場合**、次にユーザーがアプリ（MainActivity）を起動するまで`DependencyService.Resolve`は正しく実行されない。

`Covid19Radar.App`が初期化されていない状態で`DependencyService.Resolve`で取得した`LoggerService`, `HttpDataService`, `ExposureNotificationService`を使用した場合、例外（`System.Reflection.TargetInvocationException`）が発生することが確認されている。
結果としてバックグラウンド処理は失敗し、このケースでは`LoggerService`も正しく機能しないので、ログも取得できていないものと思われる。

また、バックグラウンドはWorkManager(JobScheduler)によって定期実行が設定され、端末を再起動した場合もWorkManagerによる定期実行は継続する。
**端末の再起動後、ユーザーがアプリを起動していない状態で定期実行が開始された場合**も、`Covid19Radar.App`が行われていない状態でバックグラウンドタスクが実行されることになる。

## 考えられる対策
バックグラウンドタスクの実行時、`Covid19Radar.Services.ExposureNotificationHandler`内の`LoggerService`, `HttpDataService`, `ExposureNotificationService`の3つのインスタンスが利用可能になるようにプログラムを変更する。

考えられる方法としては、`DependencyService.Resolve`を行わず前述した3つのインスタンスを生成するようにする。
または、`Covid19Radar.Droid.MainActivity`を起動する以外の方法で`DependencyService.Resolve`が正しく実行されるようにプログラムを変更する。

## 解消までの課題
`DependencyService.Resolve`を使わずに依存の解決を行うことは容易ではない。前述の3つのインスタンスは、さらに複数のクラスに依存しており、それらすべてを適切にインスタンス化する必要がある。

また、依存関係は最終的には各プラットフォーム（Android, iOS）固有のクラスに到達する（Androidでは`Covid19Radar.Droid.MainActivity.AndroidInitializer`）。

プラットフォーム固有クラスの依存は、各プラットフォームのプロジェクト（「Covid19Rader.Android」および「Covid19Rader.iOS」）の中で設定され、「Covid19Radar」のプロジェクトからは直接参照していない。
「Covid19Radar」プロジェクト内にある`Covid19Radar.Services.ExposureNotificationHandler`からプラットフォーム固有クラスは参照できない。

Xamarinでどのように解決するのが正しいか。UnityのようなDIコンテナを導入することで解決できるものか。調査と検討が必要となる。

**Comment by tmurakami** [comment]
本件、`ExposureNotificationHandler`が`App`クラスに依存しているからではないでしょうか？

以下の環境

- 端末: Essential Phone PH-1
- OS: Android 10
- Play Service Version: 21.02.14
- EN Version: 18210214000
- 開発者向けオプション: Stay awake, USB debugging

にて以下に示すコマンド($で始まる文字列)を実行した結果を示します。

```
$ adb shell dumpsys jobscheduler | grep JOB | grep covid19radar
  JOB #u0a216/890: f5bcd94 jp.go.mhlw.covid19radar/androidx.work.impl.background.systemjob.SystemJobService
$ adb shell cmd jobscheduler run -f jp.go.mhlw.covid19radar 890
Running job [FORCED]
$ adb logcat
[snip]
02-20 00:04:21.986  2535  5517 I ExposureNotification: ExposureNotificationChimeraService#onGetService with callingPackage=jp.go.mhlw.covid19radar [CONTEXT service_id=236 ]
02-20 00:04:21.993  2535 22650 I ExposureNotification: Utils#isSupported enabled=true [CONTEXT service_id=236 ]
02-20 00:04:21.993  2535 22650 I ExposureNotification: Utils#isBluetoothSupported requireMultiAdvertisement=false [CONTEXT service_id=236 ]
02-20 00:04:21.994  2535 22650 I ExposureNotification: isPrimaryUser=true, isWorkProfile=false [CONTEXT service_id=236 ]
02-20 00:04:21.996  2535 22650 I ExposureNotification: isDeviceSupported=true, isBluetoothSupported=true, BluetoothAdapter.isMultipleAdvertisementSupported=true [CONTEXT service_id=236 ]
02-20 00:04:21.996  2535 22650 I ExposureNotification: isPrimaryUser=true, isWorkProfile=false [CONTEXT service_id=236 ]
02-20 00:04:22.206 31757 31779 I WM-WorkerWrapper: Worker result RETRY for Work [ id=afca9ab0-b81a-435b-8cec-c5b7dda76191, tags={ crc64f5fe2524876ceee4.BackgroundFetchWorker } ]
```

上記ログの最終行にて`RETRY`が記録されていることから、恐らく下記行が実行されているのではないかと思います。
https://github.com/cocoa-mhlw/cocoa/blob/87ed432e4627ca6d30d2588031eebc5cd1f77eda/Covid19Radar/Xamarin.ExposureNotification/ExposureNotification.android.cs#L234

この時、動作情報ログには下記ログが記録されていませんでした。
https://github.com/cocoa-mhlw/cocoa/blob/047b12bfc497e5e32bd96e24c2b5d76c8ca18bcf/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L30
このことから、下記の`DependencyService.Resolve`に失敗しているのではないかと考えております。
https://github.com/cocoa-mhlw/cocoa/blob/047b12bfc497e5e32bd96e24c2b5d76c8ca18bcf/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L23

Android版 COCOA では日時の診断キーチェックに WorkManager の Worker を利用していますが、COCOA が起動していない状態で Worker が起動された場合`MainActivity.OnCreate`は実行されません。
つまり、下記の`LoadApplication`も実行されないということになります。
https://github.com/cocoa-mhlw/cocoa/blob/047b12bfc497e5e32bd96e24c2b5d76c8ca18bcf/Covid19Radar/Covid19Radar.Android/MainActivity.cs#L40

結果、下記の`RegisterTypes`も実行されないので
依存関係の解決ができなくなっているのではないでしょうか？
https://github.com/cocoa-mhlw/cocoa/blob/047b12bfc497e5e32bd96e24c2b5d76c8ca18bcf/Covid19Radar/Covid19Radar/App.xaml.cs#L81

もしもそうなのであれば、`App`クラスの DIコンテナに依存しないようにする作業が必要かと思われます。

※ 1/10 にサポートさん宛にお報せした受付番号[103695] および 2/20 にお報せした受付番号[103695-2] と同様の内容となります。

**Comment by keiji** [comment]
例外が発生してResult.InvokeRetry()が呼ばれている件、Debug_MockビルドのCOCOAで再現しました。

```
02-26 09:34:18.753  3953  4278 I mono-stdout: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: You MUST call Xamarin.Forms.Init(); prior to using it.
02-26 09:34:18.753  3953  4278 I mono-stdout:   at Xamarin.Forms.Device.get_PlatformServices () [0x00007] in <5ce60e3fe54742f5905a3fc8bfb15cea>:0
02-26 09:34:18.753  3953  4278 I mono-stdout:   at Xamarin.Forms.Device.GetAssemblies () [0x00000] in <5ce60e3fe54742f5905a3fc8bfb15cea>:0
02-26 09:34:18.753  3953  4278 I mono-stdout:   at Xamarin.Forms.DependencyService.Initialize () [0x00021] in <5ce60e3fe54742f5905a3fc8bfb15cea>:0
02-26 09:34:18.753  3953  4278 I mono-stdout:   at Xamarin.Forms.DependencyService.Get[T] (Xamarin.Forms.DependencyFetchTarget fetchTarget) [0x00000] in <5ce60e3fe54742f5905a3fc8bfb15cea>:0
02-26 09:34:18.753  3953  4278 I mono-stdout:   at Xamarin.Forms.DependencyService.Resolve[T] (Xamarin.Forms.DependencyFetchTarget fallbackFetchTarget) [0x00027] in <5ce60e3fe54742f5905a3fc8bfb15cea>:0
02-26 09:34:18.754  3953  4278 I mono-stdout:   at Covid19Radar.Services.ExposureNotificationHandler.get_LoggerService () [0x00000] in <6cb9c3e287154d03a442f9b82c1845e5>:0
02-26 09:34:18.754  3953  4278 I mono-stdout:   at Covid19Radar.Services.ExposureNotificationHandler..ctor () [0x00008] in <6cb9c3e287154d03a442f9b82c1845e5>:0
02-26 09:34:18.754  3953  4278 I mono-stdout:   at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
02-26 09:34:18.754  3953  4278 I mono-stdout:   at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in <c72658f647bc485bbfb8c9fcaa790862>:0
02-26 09:34:18.754  3953  4278 I mono-stdout:    --- End of inner exception stack trace ---
02-26 09:34:18.754  3953  4278 I mono-stdout:   at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x0001d] in <c72658f647bc485bbfb8c9fcaa790862>:0
02-26 09:34:18.754  3953  4278 I mono-stdout:   at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00095] in <c72658f647bc485bbfb8c9fcaa790862>:0
02-26 09:34:18.754  3953  4278 I mono-stdout:   at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache) [0x00009] in <c72658f647bc485bbfb8c9fcaa790862>:0
02-26 09:34:18.754  3953  4278 I mono-stdout:   at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark& stackMark) [0x00027] in <c72658f647bc485bbfb8c9fcaa790862>:0
02-26 09:34:18.754  3953  4278 I mono-stdout:   at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00020] in <c72658f647bc485bbfb8c9fcaa790862>:0
02-26 09:34:18.754  3953  4278 I mono-stdout:   at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00000] in <c72658f647bc485bbfb8c9fcaa790862>:0
02-26 09:34:18.754  3953  4278 I mono-stdout:   at System.Activator.CreateInstance (System.Type type) [0x00000] in <c72658f647bc485bbfb8c9fcaa790862>:0
02-26 09:34:18.754  3953  4278 I mono-stdout:   at Xamarin.ExposureNotifications.ExposureNotification.get_Handler () [0x000c9] in <09cd38cc9ad74773a5b6641e9c8bf236>:0
02-26 09:34:18.754  3953  4278 I mono-stdout:   at Xamarin.ExposureNotifications.ExposureNotification.UpdateKeysFromServer (System.Threading.CancellationToken cancellationToken) [0x0003a] in <09cd38cc9ad74773a5b6641e9c8bf236>:0
02-26 09:34:18.754  3953  4278 I mono-stdout:   at Xamarin.ExposureNotifications.BackgroundFetchWorker.DoAsyncWork () [0x0012e] in <09cd38cc9ad74773a5b6641e9c8bf236>:0
02-26 09:34:18.754  3953  4278 I mono-stdout:   at Xamarin.ExposureNotifications.BackgroundFetchWorker.DoWork () [0x00029] in <09cd38cc9ad74773a5b6641e9c8bf236>:0
02-26 09:34:18.754  3953  4278 D Covid19Radar: Exception has been thrown by the target of an invocation.
```

再現手順は次の通りです。

 * アプリを起動してWorkManagerにWorkRequestを追加する
 * 端末を再起動する（アプリが起動していない状態にする）
 * Workerの実行を待つ（ `adb shell cmd jobscheduler run` で強制的に実行しても良い）

**Comment by tmurakami** [comment]
検証ありがとうございます！

ログを見る限り、やはり`DependencyService.Resolve`に失敗しているように思えます。
@heykuro いかがでしょうか？

**Comment by keiji** [comment]
さらに試しに`ExposureNotificationHandler.cs`から`DependencyService.Resolve`はもとより、すべての`LoggerService`に関する記述を削除してみたところ、例外の発生はなくなりました。

Xamarinよくわからないので、ここを`DependencyService.Resolve`使わずに書き直す方法がよくわからないのですが、ひとまずアプリそのものを動くようにすることを最優先するのであれば、非常に乱暴ですが「ExposureNotificationHandler.csから`ILoggerService`全部消す」と言う方法もありそうですね。

**Comment by tmurakami** [comment]
バックグラウンド実行の場合`MainActivity.OnCreate`が呼ばれないので`Xamarin.Forms.Init`も実行されず、結果エラーになる、ということなのでしょうね。
`DependencyService`は Xamarin.Forms のクラスですから、先の私のコメントの`RegisterTypes`云々は誤りでした。すみません...

**Comment by keiji** [comment]
IssueのDescriptionに「考えられる原因」「考えられる対策」「解消までの課題」を追記しました。

`DependencyService.Resolve`を使わずに3つのインスタンスを手に入れようと頑張ってみましたが、1つのクラスをインスタンス化するために複数のクラスのインスタンスが必要になり、最終的には「Covid19Radar」プロジェクトから参照できないプラットフォーム固有クラスに行き着いて、挫折中です。

@tmurakami 
依存の設定は`Covid19Radar.App`で行われていますし、最終的なプラットフォーム固有クラスについても`MainAcitivty.onCreate`内の`LoadApplication(new App(new AndroidInitializer()));`で設定されていると理解しているので、間違いではないと思いますよ。

ぼくのXamarin力が高くないので、なぜ`Forms.Init`に着目したエラーメッセージが出るのかはわかりませんが
`Forms.Init`すればOKということでもない気がします。

**Comment by amay077** [comment]
> ぼくのXamarin力が高くないので、なぜForms.Initに着目したエラーメッセージが出るのかはわかりませんが
> Forms.InitすればOKということでもない気がします。

デバッグしたわけではないですが、
DependencyService は Xamarin.Forms の機能であり、それを使用するために Forms.Init が必要、という可能性はあるのかもしれません。

> UnityのようなDIコンテナを導入することで解決できるものか。

このプロジェクトでは  Prism.DryIoc(というか DryIoc) という DI コンテナ? がプロジェクトに組み込まれているようなので、これが Xamarin.Forms(というか UI層)に依存せず使えるものならば代替できそうですが、私は使用したことがなく真偽不明なのと、修正量は大きそうです。

DryIoc で、 AndroidInitializer.RegisterTypes 相当の処理を MainActivity ではなく MainApplication.OnCreate で行うことができれば、MainAcitivty や Xamarin.Forms に関係なく Resolve（DryIoc の Resolve 手法に書き換えが必要） できるような気がします。

**Comment by tmurakami** [comment]
@keiji お心遣い感謝します。

> なぜForms.Initに着目したエラーメッセージが出るのか

`DependencyService.Get`を呼ぶと`DependencyService.Initialize`が実行されます。
そのメソッドの下記行から
https://github.com/xamarin/Xamarin.Forms/blob/4.6.0/Xamarin.Forms.Core/DependencyService.cs#L92
`Device`の以下のメソッドを呼び出しています。
https://github.com/xamarin/Xamarin.Forms/blob/4.6.0/Xamarin.Forms.Core/Device.cs#L239-L242

そこで呼び出している`PlatformService`の中で、`s_platformServices`が`null`ということで例外をスローしているようです。
https://github.com/xamarin/Xamarin.Forms/blob/4.6.0/Xamarin.Forms.Core/Device.cs#L87

`PlatformService`の設定は`Forms.SetupInit`で行われるので、`Forms.Init`が未実行だと上記エラーが発生するように思います。
https://github.com/xamarin/Xamarin.Forms/blob/4.6.0/Xamarin.Forms.Platform.Android/Forms.cs#L303

DryIoc にも CommonServiceLocator があるようなので
https://www.nuget.org/packages/DryIoc.CommonServiceLocator/
それを使えば FHI の`DroidDependencyInjectionConfig`のようなことができるかもしれません。
https://github.com/folkehelseinstituttet/Fhi.Smittestopp.App/blob/dev/NDB.Covid19/NDB.Covid19.Droid/DroidDependencyInjectionConfig.cs
https://github.com/folkehelseinstituttet/Fhi.Smittestopp.App/blob/dev/NDB.Covid19/NDB.Covid19/ExposureNotifications/ExposureNotificationHandler.cs#L57

**Comment by keiji** [comment]
@amay077 ありがとうございます。
`MainApplication.onCreate`に`Xamarin.Forms.Forms.Init(this, new Bundle());`をいれて見ましたが状況は変わらずでした。

@tmurakami CommonServiceLocator調べてみます。

**Comment by keiji** [comment]
@tmurakami @amay077 ひとまずDryIoc.CommonServiceLocatorを使ってやったところまでをPRにしました。

`App`が初期化されていない状態でバックグランドタスクを起動してもLoggerServiceが動いているので、IoCコンテナ自体は動いている様子ですがDebug_Mockでしかテストしていないので実際の処理が本当にうまくいくかはわかりません（経路のどこかで`App`関連を使っていたらアウト）。

**Comment by keiji** [comment]
PullRequest #30 について実験した結果です。

 * バックグランドタスクの実行間隔を6時間（現在のCocoaに設定されている値）に設定
 * Mock_Debugビルドしたバイナリを実機（Pixel 3/API Level 30）にインストール
 * バッテリー駆動の状態で放置

実行間隔が8時間から13時間とムラはあるものの、定期的な実行ができていることが確認できました。

"2021/03/03 01:13:16"
"2021/03/03 09:17:25"
"2021/03/03 15:18:41"
"2021/03/04 04:34:32"
"2021/03/04 15:51:45"

ログを置いておきます。

https://gist.github.com/keiji/3b3b4ee48b08ec61cd90b7cba70bf287

**Comment by keiji** [comment]
@heykuro 今見たら help wanted のタグがついていますが、どんな助けがあればお力になれそうですか？

**Comment by heykuro** [comment]
@keiji  ありがとうございます。

すみません、ラベリングミスです。#31  で以下記載しましたように、現在実装内容についての検証を行っているところのため、一旦help wantedは外しますね。

>最終確定というよりは実装・検証を進めている段階なので、その中でまた問題点あればこちらでも共有させていただきたいと思います。 また、#25 と混ぜて書いてしまいましたが、そちらと分けて扱うようにします。

**Comment by keiji** [comment]
ここまで、いくつか解決策が出ています。基本的にこのIssueの解決方法として「バックグラウンドタスク（Worker）から`DependencyService`を使わないようにする」という点では共通していますね。

選択肢として「CommonServiceLocatorを使うか。使わないか」「DependencyServiceを全廃するか。一部でも残すか」の組み合わせで、#60 #61 については「DependencyServiceを全廃した上でCommonServiceLocatorを使わない」と言う方法ですね。

さて、開発担当チームと調整した現時点での方向性としては、まずは「バックグラウンドタスクの課題」を解決する。 その後「DependencyServiceへの依存を削除する」の２段構えと言うことになっています。

DependencyServiceを使わないようにしないと、バックグラウンドタスクの内容を変更するたびに問題が再発する可能性があり、今後の安全性を考える上でもDependencyServiceへの依存は削除するのがベスト。と言う点では開発担当チームの認識も一致しています。では、なぜすぐにやらないのかというと、純粋に日程的な話になってしまうので、ご理解いただければ幸いです。

@zipperpull 対応が２段構えになることで、今頂いているPull Requestの調整等、お手数をおかけすることになるかと思います。調整についてはぼくもサポートできますので、なにかできることがあったら言ってください。

**Comment by zipperpull** [comment]
コードを書いてみているのは私の個人的興味にすぎないですし PR がマージされることもとくに期待していないので
ご心配は無用かと思います。

2段構えでの修正というのも、想像はしていますが、修正してみた結果としては、
2段構えにするために余計な修正や確認作業が必要になってしまう可能性が高くて、
まったくお勧めはできかねるという印象です。。

もうテストが終わって不具合はないものと確信できていてリリース準備を始めているなら
問題ないのかもしれませんが、まだ改修中とか再修正とかの可能性があるなら、
2段構えにするのをあきらめたほうが安全なのではと思ってはいます。

**Comment by b-wind** [comment]
現時点で変更内容が開示されていないので１段目で問題が解決されているか確認等することがこちらでは不可能に思います。
判断するに足る情報が欲しいのではないのでしょうか。

**Comment by keiji** [comment]
> まったくお勧めはできかねるという印象です。。

理解できます。一時にやってしまった方が楽で、コードとしてもきれいになりますよね。

> もうテストが終わって不具合はないものと確信できていてリリース準備を始めているなら

ここについては、ぼくが個人的に同意できないところです。
ぼくの経験上、テストを始める以前にコードフリーズの段階を踏んで、大きな変更は次リリースに回すように調整するのが一般的です。明示的なコードフリーズがなくても「ここまで来たら大きく方針は変えない」と言う一線ーーリリースに向けたシュワルツシルト半径のようなものーーは存在するという認識です。
今回の場合、開発担当チームと話し合った結果、２段構えでいかないと厳しいなとぼくも思ったという次第です。

その上で、今回のzipperpullさんの提案はすばらしいものだと理解しているので大変心苦しく思います。今後、頂いたPull Requestについて、すみやかに、そして開発担当チームの負担が過大にならないような体制作りができるように工夫を続けていければと思います。

**Comment by zipperpull** [comment]
コードフリーズの段階を踏めるのが理想的だというのは同意しますが、設計ミスだった場合には
そのミスを小手先の修正で無理して埋めるよりはきちんと直した方が結果的には問題は減るという
話だと思ってはいます。

いずれにしてもコードが出てきているわけではないし想像で空中戦するのも意味がないので
余計な口出しでした。すみません

**Comment by keiji** [comment]
@zipperpull @b-wind 
#43 のこともありますし、スケジュールでコードフリーズの時期を明示できるのが理想なんですよね。
ぼく個人としては、現時点でできることをしながら、少しずつではありますが、良い方向に進めていきたいと考えています。
是非、力を貸してください。よろしくお願いいたします。

**Comment by b-wind** [comment]
確認ですが、「現時点でGitHub上にある解決策」のうち開発担当チームの目指そうとしている第一段階に部分的にでも含まれる物はありますか？
また、含まれる部分があるとしたら開発担当チームからの質問内容等はあるのでしょうか？


そう言った物があるのでしたら、ここに書いて貰えば良いと思いますし（私は殆どコード書けないので）案で良ければいくらでも協力するつもりです。


２段階で行くと言う方針に異論も無いです。


開発担当チームが第一段階の実装が終わった段階でコードフリーズと言う事で良いのでは無いかと思うのですが、如何でしょうか。


第二段階以降の調整については必要な部分もあるでしょうし、第一段階のリリース結果を見た上で別のIssueとして行うのが良いと思うのですが如何でしょうか？


#43 に付いては、現状の開発チームにおいて実施できそうな余裕があるか無いかがすべてに思えます。
スケジュール的に厳しいのであれば次回リリースまでに行うと言う事にならざるを得ないと思います。

**Comment by keiji** [comment]
@b-wind
> 何を協力すれば良いのか分からないです。

オープンソースコミュニティとしては、できる人が、できる時に、できることをする。と言うスタンスで良いと思いますよ。

個人的にはこのIssueは、COCOAにとってとても大きなものだと思っています。重要性はもとより、問題解決のための修正規模も当初ぼくが想定していたよりも大きくなっています。

その上で今のCOCOAにはそのほかにも、大きな課題に隠れて見過ごされている小さな課題があるだろうと考えています。

COCOAを実際に使ってもらった上で見つけた「気になったこと」をIssueとして投稿してもらうのも協力（貢献）と認識しています。アクセシビリティーの問題（ #50  ）に取り組んだり、ドキュメンテーションを整備（ #56 ）したり、.gitignore（ #59 ）のようなどちらかというとGit管理上の話、#57 などコードが書けなくてもできる修正もあります。

もちろん、もっと開発担当チームの方針や意見を聞きたいというご要望に応えられるように引き続き頑張ります。

**Comment by keiji** [comment]
v.1.23で修正したのでクローズします。何かあればreopneしてください
