### ISSUE TITLE
陽性登録の意思をアプリから事前登録する機能

### ISSUE THREAD

**Issue by parasite2006** [cocoa-mhlw/cocoa#256]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

現行の陽性登録手順では、保健所から陽性検査結果の電話連絡が来てからでないと陽性登録の意思表示ができない。しかも保健所は陽性登録の意思表示を聞いてからHER-SYSへのデータ登録を開始して本人確認用の処理番号発行操作を実行するので、検査結果通知から処理番号が届いて陽性登録を実行するまでの間に相当のタイムラグが生じてしまう。

## 解決策についてお書きください / Describe the solution you'd like

HER-SYSへのデータ登録開始時期を前倒しして検査結果を知ったユーザーができるだけ時間をおかずに陽性登録を実行できるよう、検査結果が届く前の段階で陽性登録の意思をアプリから登録できる機能を追加する。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

アプリのホーム画面上に「検査結果が陽性なら登録を希望する」といったボタンを追加で設ける。検査を受けることが決まってから結果が連絡されるまでの間にこのボタンを押し、次の画面上で「検査結果が陽性なら登録を希望しますか？」に「はい」を選ぶと次のいずれかの反応が生じる：

1) 折り返し陽性登録に使えるバーコードまたは番号が発行される
（陽性検査結果が連絡され次第、ユーザーはこれを本人確認に使って即時陽性登録を実行できる）
2) 画面上に「連絡先を入力」のテキストボックスが開くので、検査を受けることが決まった時に保健所に連絡先として届けてあるメールアドレスか携帯電話番号を入力すると、陽性登録事前承認者リストに登録され所轄の保健所に届く
（保健所はこのリストに登録された連絡先の持ち主が陽性判定された連絡を検査機関から受け次第、即HER-SYSにデータを優先登録して処理番号を発行する。HER-SYSへのデータ登録完了後、連絡先は事前承認者リストから消去される）

## その他 / Additional context

1) HER-SYSシステムの運用開始当時、データ登録は保健所を通して検査を受けることが決まった段階で行われることになっており、検査結果の連絡時には登録が完了して8桁の処理番号が確定していたからこそ、検査結果連絡時に請求すれば処理番号が発行されて陽性登録を実行でき、HER-SYS処理番号を陽性登録の本人確認手段として使うことに意味があった（ただし、HER-SYSへの移行が未完了で厚労省が処理番号発行操作を代行していた自治体では、厚労省が閉庁する土日祝日に処理が停止しタイムラグが生じていた）
。

2) ところが2020年10月14日付厚労省事務連絡
https://www.mhlw.go.jp/content/000683027.pdf
でデータ登録時期が入院例を除いて「陽性結果確定時」に後ろ倒しされてしまった結果（p.7の問11「検査結果が陰性の場合も入力が必要ですか」の答え参照）、検査結果の電話連絡時点でデータ登録が完了せず処理番号が未確定という事態が常態化し、処理番号は陽性登録の本人確認用として使い物にならなくなった。

3) 2021年1月8日付厚労省事務連絡
https://www.mhlw.go.jp/content/000717197.pdf
以降は、「積極的疫学調査実施要領」及び「調査票」が改定され、検査結果連絡時に処理番号発行を請求されたら調査表の「陽性登録希望」欄の「有」をチェックして優先的にHER-SYSにデータを登録し、完了後すぐ処理番号発行操作を行うことになったものの、感染拡大時にはデータ登録が遅れることに変わりはない。

代替案1では、事前に意思表示のあった陽性登録をHER-SYSから切り離し、（発症から検査結果確定までのタイムラグに上乗せされて接触確認アプリの感染拡大防止効果の低下につながる）結果通知から陽性登録実行までのタイムラグを最小化することができる。
代替案2では、陽性登録を保健所とHER-SYSから切り離さない前提の下、事前意思表示によりデータ登録時期を少しでも前倒しして結果通知から陽性登録実行までのタイムラグを縮めることを目指している。

**Comment by keiji** [comment]
こういうケースに対応できるように、いまの接触確認APIにはPreauthorize APIが追加されていますね。

今いただいている解決策はPreauthorize APIは使わない前提に見えます。また、HER-SYSの話も絡んできそうですが、COCOAはHER-SYSと直接通信していないと理解しているので、そのあたりの整理も必要と思います。

COCOAがどう変わるのか、陽性登録サーバーやHER-SYSがどういう動きをすることになるのか。Descriptionをみる限りでは読み取れませんでした。

登録意志の事前確認というコアな部分は共感するところがあります。一方、課題に対する解決策、代替策が煮詰まっていないと感じています。

このIssueはDiscussionに移して、そこで方法について一定の方向性が出てから、あらためてIssueにするのがよいと思いますが、いかがでしょうか。

**Comment by parasite2006** [comment]
@keiji 
> こういうケースに対応できるように、いまの接触確認APIにはPreauthorize APIが追加されていますね。

ご教示ありがとうございます。そういう機能がすでに追加されているとは全く存じませんでした。
Discussionに場を移してさらに色々な角度から議論していただければ大変嬉しく存じます。
（個人的には陽性登録のプロセスを保健所とHER-SYSから切り離すべしと考えています）
