### ISSUE TITLE
Xamarin.ExposureNotification直下のLICENSE.mdを取り除く

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#259]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

Visual Studio for macでソリューションを開くと、`LICENSE.md`がXamarin.ExposureNotification直下に表示される。LICENSE.mdに記載されているのはMPL 2.0だが、Xamarin.ExposureNotificationのライセンスはMIT Licenseなので、開発者に誤解を与える恐れがある。

<img width="303" alt="Screen Shot 2021-06-11 at 9 51 35" src="https://user-images.githubusercontent.com/932136/123726103-54a49e00-d8ca-11eb-9ca9-2f594839d8de.png">

## 解決策についてお書きください / Describe the solution you'd like

Xamarin.ExposureNotification以下に表示されている`LICENSE.md`を取り除く。リポジトリ直下の実体ファイル（ `LICENSE.md` ）は残したままにしておく。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

Xamarin.ExposureNotification以下に`LICENSE.md`を新規追加。MITライセンスを記述する。
ただしXamarin.ExposureNotificationのライセンス情報は`COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md`でカバーされているので、あまり意味がないと考える。

## その他 / Additional context
----
Internal IDs:
- NFR 2860

**Comment by Takym** [comment]
対応しました。
プロジェクトを丸ごとコピーしてきた名残だと思います。
