### ISSUE TITLE
transmission_risk_levelが4である意味

### ISSUE THREAD

**Issue by tmurakami** [cocoa-mhlw/cocoa#26]
https://github.com/cocoa-mhlw/cocoa/blob/cf58f2230ac5d26736334a52cf4b680725d8038d/src/Covid19Radar.Api/Models/V1DiagnosisSubmissionParameter.cs#L32
https://github.com/cocoa-mhlw/cocoa/blob/cf58f2230ac5d26736334a52cf4b680725d8038d/src/Covid19Radar.Api/Models/DiagnosisSubmissionParameter.cs#L43
について、Google/Apple がお勧めしている以下の意味付け

- 1: Confirmed test (Low)
- 2: Confirmed test (Standard)
- 3: Confirmed test (High)
- 4: Confirmed clinical diagnosis
- 5: Self report
- 6: Negative case
- 7: Recursive case

に従っているのでしょうか？それとも独自の意味付けをされているのでしょうか？
独自設定なのであれば(ソース上に何らかのコメントは欲しいですが)、以下の提案は無視してcloseしてください。

---
現在サーバ側で`4`固定となっている`transmission_risk_level`ですが、`3`にしたほうがよいのではないでしょうか？
理由は三点

1. 陽性者は必ず PCR等の検査を受けているため
2. GAEN v2 におけるレポートタイプとの整合性をとるため
3. 発症日を基準とした感染性の高さを考慮するため

です。

1 について
https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/dengue_fever_qa_00004.html#Q2
https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000121431_00132.html
によると、陽性確定には PCR等の検査が必須です。

2 について
https://developers.google.com/android/exposure-notifications/exposure-notifications-api
では`TemporaryExposureKey#reportType`は以下のように定義されています。

> 1: CONFIRMED_TEST. A medical provider has confirmed the user had a positive diagnostic test for COVID-19.
> 2: CONFIRMED_CLINICAL_DIAGNOSIS. A medical provider has confirmed the user had symptoms consistent with a COVID-19 diagnosis.

将来 v2 に移行されるのでしょうから、`transmission_risk_level`とレポートタイプを合わせておいたほうが良いように思います。

3 について
`Confirmed test`が3種類定義されているのは、発症日を基準とした感染性の高さに応じて`TransmissionRiskScore`を変更できるようにするためだと思われます。
例えば、

- Low: 発症日-14日〜-6日および+11日〜+14日
- Standard: 発症日-5日〜-3日および+6日〜+10日
- High: 発症日-2日〜+5日

といった具合です。
現在の COCOA は積極的疫学調査との整合性を取るために、発症日-2日(厳密には2日と21時間)から登録日前日までのTEKをサーバに送信していますが、この期間は感染性の高い期間に相当するのではないかと思います。

これらの理由により、`transmission_risk_level`には現在の`4`ではなく`3`を当てるのが妥当ではないかと考えております。

どの値を選んでもリスク値に変化はないのですが、それがそうである意味を明確にして頂けたらと思います。

**Comment by heykuro** [comment]
@tmurakami  こちらご指摘ありがとうございます。遅くなりすみません。

悩ましいところだったのですが、[利用規約](https://www.mhlw.go.jp/cocoa/kiyaku_japanese.html)上では、
>二 「陽性者」とは、新型コロナウイルス感染症の陽性診断が確定した者をいいます。
としているため、今は4でセットしています。

ただ、API v2移行後も想定して検討しきれていたわけではなく、先のAndroid通知障害対応の過程で取り急ぎセットしたものでなので、v2移行時にまたご指摘の点について検討することになると思います。
またその際にディスカッションさせていただけると嬉しいです。
