### ISSUE TITLE
CI の設定ファイルの統合と重複したStepの削除

### ISSUE THREAD

**Issue by fumiya-kume** [cocoa-mhlw/cocoa#267]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

GitHub Actions

## 解決策についてお書きください / Describe the solution you'd like

GitHub Actions の設定を眺めていていくつか気になる点がありました。
・CIの設定ファイルを一つに統合できそう。
・Server 側のCI設定をMatrixを活用することで一つのStepに統合できそう。
・上記に伴うStep名等のの変更

**Comment by keiji** [comment]
#268 を拝見しました。
複雑性を除去するのであれば、AppとServerの設定ファイルを統合するより、現状よりさらに切り離した方が良いと考えます。

本リポジトリにおいてApp（`Covid19Radar`以下）とServer（`src`以下）はソリューションファイルも別ですし、個別にビルドしている現状のアプローチに違和感はありません。一方で、Appのみの変更でサーバー側のビルドが行われるのは（その逆も）効率的ではないなと感じます。

Appのファイル（ソリューションファイルと`Covid19Radar`以下）が変更されたときだけ`CI`、Server関係のファイル（ソリューションファイルと`src`以下）が変更されたときだけ`CI-Server`の、それぞれビルドとテストを行うようにすれば、CI設定ファイルは独立したまま、将来的にApp側が膨れても見通しが悪くなることを避けられると思いますが、いかがでしょうか。

**Comment by keiji** [comment]
@fumiya-kume こちら、AppとServerの動作条件を規定して分離する件ですが、いかがでしょうか。
このIssueの内容を変えてもいいですし、新しくIssueを立てても良いかと思います。お忙しいようであればぼくの方でも対応可能です。

**Comment by keiji** [comment]
今回は #289 を採用したのでこちらはクローズします。
ご提案ありがとうございました。
