### ISSUE TITLE
実行環境の言語設定に依存しているUnit Testを修正してほしい

### ISSUE THREAD

**Issue by fumiya-kume** [cocoa-mhlw/cocoa#269]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

実行環境の言語設定に依存しているUnit Testが存在しています。
日本語環境以外で実行するとUnit Testが失敗するように見えます。

# 実行環境
- `日本語` 環境設定の Windows10
- Visual Studio 2022 Preview

### 失敗する Unit test

`Covid19Radar.UnitTests` プロジェクト内のクラスです。

- `ReAgreePrivacyPolicyPageViewModelTests#OpenWebViewCommandTests()`
- `ReAgreeTermsOfServicePageViewModelTests#OpenWebViewCommandTests()`

<img src="https://user-images.githubusercontent.com/16269075/124284175-b04f7f80-db87-11eb-991c-62dc1380c1f3.png" width="50%" />

## 解決策についてお書きください / Describe the solution you'd like

複数解決策があると思います。
個人的には1つ目の方法を強く推奨したいです。

- `Resources.AppResources` class をDIなりで取得するようにし、Unit Test では mock したクラスを渡すようにする
- Unit Test コードにて正規表現などを使いマッチ判定するようにする。

## その他 / Additional context

----
Internal IDs:
- NFR 2967

**Comment by keiji** [comment]
ありがとうございます。ご指摘のテストについてざっくり眺めてみました。

2つの解決策を提案していただいていますが、ぼくがこれを見て最初に考えたのは「テスト実行環境のロケールが日本語であっても、テストそのものは英語環境として（上書きして）テストを実行できないか？」と言うことです。

`LOCALE=en dotnet test` のようにして、環境変数を通じてロケールを設定できるなら、難しいことしなくても良さそうです。

次に考えたことは「この`actualUri`って`AppResource.*.resx`に定義された値をそのまま持ってきているだけで何のロジックを通っているわけでもないのに、なんでAssertしてるの？」と言うことです。

https://github.com/cocoa-mhlw/cocoa/blob/2a729494ad1efa1f3f3119b71e4623b672271557/Covid19Radar/Tests/Covid19Radar.UnitTests/ViewModels/HomePage/ReAgreePrivacyPolicyPageViewModelTests.cs#L58-L84

端末の情報を使って動的にクエリを構築しているならわかるのですが、`expected`を見る限り、決め打ちのURLをそのまま使う想定のようです。
これらのURLはそうそう変える箇所でもありませんし、本当にちゃんとテストしようとすると、さまざまなロケールを切り換えながら正しいURLが定義されているかを検証するみたいなことをしなければなりません。
その上で、繰り返しになりますが、ここは本質的には`AppResource.*.resx`との比較になるわけですから、URLの正しさを確認するならばViewModelのテストより`AppResource.*.resx`をチェックするテストを書いた方がスマートだと思います。

blameしてみたらcocoa-devが作った箇所のようなので、このテストを設けた意図について確認しますね。
場合によっては当該行を消すことも視野に入れて検討したいです。

**Comment by keiji** [comment]
現在`AppResources`のアクセススコープは`internal`なので、テストプロジェクトから参照できませんが、publicになるようにプロパティを変更すれば実現できますね。

Inaccessible, Internal, Resource Files? - stackoverflow
https://stackoverflow.com/questions/24833875/inaccessible-internal-resource-files

```
using Covid19Radar.Resources;

...

            Assert.Equal(1, actualCalls);
            Assert.Equal(AppResources.UrlPrivacyPolicy, actualUri);
            Assert.Equal(BrowserLaunchMode.SystemPreferred, actualLaunchMode);
```

ここは`AppResources.UrlPrivacyPolicy`と一致するURLが設定されていることを確認するテストになりす（`AppResources.UrlPrivacyPolicy`が間違っていることは検出できませんが、前述の通り、それはViewModelで確認することではないと考えてます）。

**Comment by Takym** [comment]
テスト処理の為だけに外部へ公開してしまうのは恐らく危険ですので、`public` へ変えるのではなく [InternalsVisibleTo](https://docs.microsoft.com/ja-jp/dotnet/api/system.runtime.compilerservices.internalsvisibletoattribute?view=netstandard-2.1) 属性を使うのは如何でしょうか？

**Comment by keiji** [comment]
@Takym ありがとうございます。たしかに、テストのためだけにスコープを公開するのはやり過ぎ感がありますね。

いろいろ検討した結果、テスト内で次のようにすれば言語設定を上書きできることがわかりました。こちらを追加するのはいかがでしょうか。

```
CultureInfo.CurrentUICulture = new CultureInfo("en", false);
```

`en-US`や`ja-JP`などのように言語-国を組み合わせることもできますが、今回は言語のみの指定で良いと思います。

`welcome-contribution` つけておきます。

**Comment by Takym** [comment]
> `en-US`や`ja-JP`などのように言語-国を組み合わせることもできますが、今回は言語のみの指定で良いと思います。

言語指定が不必要なのであれば `CultureInfo.InvariantCulture` でも十分だと思います。
