### ISSUE TITLE
ExposureNotificationバインディングを最新にする

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#278]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

現在のExposureNotificationライブラリとXamarinをバインディングしているパッケージは最新でなく、AndroidではAPI `1.8.3`、iOSでは`14.4`で追加された最新のAPI「PreAuthorized API」に対応していない。

https://www.nuget.org/packages/Xamarin.GooglePlayServices.Nearby.ExposureNotification/
https://www.nuget.org/packages/Xamarin.iOS.ExposureNotification/

PreAuthorized APIを使うにせよ、使わないにせよ、Android版は`GetStatus`メソッドのバインディングに齟齬があり、正常に動作しない不具合も見つかっている（ https://github.com/xamarin/XamarinComponents/issues/1094 ）。

## 解決策についてお書きください / Describe the solution you'd like

最新のAPIに対応したライブラリに更新する。
公式のNuGetから手に入るライブラリは対応していないので、独自にビルドしたNuGetパッケージをローカルに持つのが早い。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

Pull Requestは提出済み（https://github.com/xamarin/XamarinComponents/pull/1133 , https://github.com/xamarin/XamarinComponents/pull/1231 ）。

XamarinがこれらのPull Requestを取り入れてNuGetライブラリを更新するのを待つ手もあるが、提出から2ヶ月以上、反応がないので、今後の動きやすさを考えると進めてしまった方がいい（Xamarin側がPRを取り入れて合流できるならする）。

## その他 / Additional context

----
Internal IDs:
- NFR 3127

**Comment by tmurakami** [comment]
個人的にはぜひとも対応頂きたいと思っています。
というのも、1.8 のクライアントではタイムアウトが実装されているからです。
(`provideDiagnosisKeys`以外は 2分、`provideDiagnosisKeys`は 60分)
https://developers.google.com/android/exposure-notifications/release-notes#api_call_timeouts

以前 https://github.com/cocoa-mhlw/cocoa/issues/17#issuecomment-804354690 でちらっとお話しした障害について、すでにご存知かもしれませんが Google から障害報告が出ています。(PDF 注意)
https://www.gov.si/assets/ministrstva/MJU/SOJ-dokumenti-za-objavo/Aplikacija-Covid/Obvestilo-Google-o-nedelovanju.pdf
(上記報告はスロベニア当局の https://www.gov.si/novice/2021-01-15-aplikacija-ostanizdrav-deluje-dobro-in-sledi-posodobitvam-odziv-na-nekorektno-porocanje/ からダウンロードできます)

Java/Kotlin で実装している各国アプリでは、上記報告に従って API を呼び出している側でタイムアウトを実装しているのだろうと思いますが、COCOA では呼び出し側でタイムアウトを実装していません。
ですので、同じような障害を未然に防ぐためにも、最新の play-services-nearby-exposurenotification の導入を強く望みます。

**Comment by keiji** [comment]
ようやくENv2移行も終わり、現在 `play-services-nearby-exposurenotification-1.8.4.aar` を使っています。

最新は [play-services-nearby-exposurenotification-1.8.5.aar](https://github.com/google/exposure-notifications-android/blob/master/app/libs/play-services-nearby-exposurenotification-1.8.5.aar) なので、また切り替えるかどうか別Issueで検討します。
