### ISSUE TITLE
改変版の開発

### ISSUE THREAD

**Issue by Takym** [cocoa-mhlw/cocoa#28]
マージしなくても構いませんが、下記の様に大幅に改変しました事を報告させていただきます。
https://github.com/Takym/Covid19Radar
お忙しい中大変恐縮ですが評価の程宜しくお願いします。

**Comment by cocoa-dev** [comment]
@Takym さん、ご連絡ありがとうございます。ご紹介頂いたリポジトリは今後の参考にさせて頂きます。

今後もお気づきの点がありましたらぜひ Issue にてご指摘ください。
