### ISSUE TITLE
接触確認機能の許諾がオンになっていなかったときの文言がユーザーから見てわかりにくい

### ISSUE THREAD

**Issue by kazuhiro4949** [cocoa-mhlw/cocoa#288]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

許諾オフのときのアラートがXamarinでのアプリ開発者視点になっており、
ユーザーから見ると若干わかりにくい文言と思います。

```
COVID-19接触通知機能が承認されていません。各OSから承認するか、またはアプリの再インストール後に、再承認してください。
```

## 解決策についてお書きください / Describe the solution you'd like

「各OSから承認」という文言を削るか、OSごとに説明を入れるのがいいと思いました。
また、大半のユーザーは設定方法がわからないと思うので案内を入れたほうがいいかと思います。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

文言としては例えば↓のようにするといいかなと思いました。(承認という言葉もちょっと違うように思ったので変えております)
```
接触通知が承諾されていません。OSの設定メニューにある「接触通知」から承諾してください。またはアプリを再インストールして承諾してください。
```

また、可能であればヘルプページなどで各OSの設定へ行くためのステップを記載し、ダイアログからwebviewなりで飛べるようにしたほうが良さそうです。

## その他 / Additional context

iOS上で接触確認をオフにしたときの表示は以下になります。

<img src="https://user-images.githubusercontent.com/18320004/126897002-a25e45cb-f5c4-4d38-8c19-d5b14cc8ff2d.PNG" width="200" />

----
Internal ID: PBI3242

**Comment by keiji** [comment]
@kazuhiro4949 これは稼働状況表示で解決されたんでしたっけ。

**Comment by keiji** [comment]
#320 で対応されたという認識です。本Issueはクローズしますが、もし漏れ等があればreopenをお願いします！
