### ISSUE TITLE
[CI] 関連コードに変更があるときだけワークフローを起動する

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#289]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

現在のCI設定では、README.mdの変更でもすべてのワークフローが起動する。
また、Mobile側のコード変更で`CI-Mobile`だけでなく`CI-Server`も実行されてしまう（その逆も）。

## 解決策についてお書きください / Describe the solution you'd like

GitHub Actionsの`paths`とか`paths-ignore`を指定して、実行するワークフローを限定する。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

対応しない。
CI実行と言ってもすべての実行に数時間かかるわけではないので、現時点での優先順位はそれほど高くないと考える。

## その他 / Additional context

`CI-Mobile`と`CI-Server`を統合する案が #267 で提案されている。

**Comment by b-wind** [comment]
詳しく調べて無いので勘違いかもですが、関係の無さそうなPRでもCI-Serverが実行されている様に見えます。

https://github.com/cocoa-mhlw/cocoa/actions/workflows/CIserver.yml

**Comment by keiji** [comment]
お、関係ないPRって具体的にどれですか？

**Comment by b-wind** [comment]
なるほど。説明ありがとうございます。

途中で変更があったりしたのでしたら、一見分かり難くてもおかしくないかなとは思いました。


特に意図に反していないという事なので、当件これ以上掘り下げるつもりはありません。
