### ISSUE TITLE
ヘッダロゴのスペルミス (Welfar)

### ISSUE THREAD

**Issue by tmurakami** [cocoa-mhlw/cocoa#29]
**Describe the bug**

ヘッダロゴ中、厚生労働省さんの英語名表記にスペルミス (Welfar) があります。

**To Reproduce**

1. COCOA を起動する
2. メインページ上部のヘッダロゴを見る

**Expected behavior**

正しいスペル (Welfare) でロゴが表示される。

**Smartphone (please complete the following information):**

 - Device: Essential Phone PH-1
 - OS: Android 10
 - Version: 1.2.2

----
Internal Tracking ID: BUG 1763

**Comment by heykuro** [comment]
@tmurakami こちらご指摘ありがとうございます。今後対応します。

**Comment by keiji** [comment]
v1.2.3で修正したのでクローズします

**Comment by keiji** [comment]
勢い込んでCloseしちゃったけど、これiOS版にも共通する事象ですね。
Reopenして次回iOS版のリリースを待って改めてcloseしますね。
