### ISSUE TITLE
接触判定時にローカル通知を表示する

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#290]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

#207 に関連して、接触確認API（ExposureNotification）のExposureWindow mode（iOSではENv2）では、接触情報を取得するタイミングでシステムによる通知が表示されない仕様となっている。

そのため、バックグラウンドで実行した接触確認の結果（濃厚接触の可能性）をユーザーに知らせる手段がない。

また現在のコードでは接触情報の取得（ExposureInformations）タイミングでシステムが通知を表示している。
ExposureInformationsの取得後、後にもう一度フィルタリングする処理を挟んでいるため、取得したExopsureInformationsがすべてフィルターでドロップされた場合、「通知は表示されても接触記録がない」現象が発生する可能性がある。

https://github.com/cocoa-mhlw/cocoa/blob/91ba1ef94b5ec172038153eebf6de59f7903e23c/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L100-L119

（本来、Configurationで指定した閾値を超えた接触記録があるからExposureInformationsへのアクセスが可能になるので、起こりえないことではあるが、Twitterなどで「通知は来たけど接触なしと表示される」という投稿をみかけることがあり、気になっています）

## 解決策についてお書きください / Describe the solution you'd like

ローカル通知を実装して、ExposureInformationsをフィルターした結果、濃厚接触と判定されたタイミングで表示する。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

ExposureWindow mode（ENv2）対応時に合わせてやる。

けれど、プラットフォーム横断の通知実装は先にやっておきたい。

## その他 / Additional context

Legacy v1（iOSではENv1）では通知がシステムから通知と合わせて出ることになるので、違和感がないように調整する必要がある。
----
Internal IDs:
- Product Backlog Item 3194

**Comment by kazuhiro4949** [comment]
メモ: 後で確認
https://github.com/cocoa-mhlw/cocoa/pull/296#issuecomment-888304119

**Comment by kazuhiro4949** [comment]
手元の
- iOS 13.7, iPhone7
- iOS 14.5のiPhone 12 Pro max

で以下のあたりを軽く確認しましたが問題ありませんでした。

- 起動時の通知の許諾
- ローカル通知のスケジュール
