### ISSUE TITLE
厚生労働省のシンボルマークのライセンス

### ISSUE THREAD

**Issue by daisukekoba** [cocoa-mhlw/cocoa#3]
厚生労働省のシンボルマークを含む画像を使用していますが、厚生労働省のシンボルマークには使用条件があります。
https://www.mhlw.go.jp/kouseiroudoushou/symbol/shiyou.html

COCOAはMPL 2.0となっていますが、厚生労働省のシンボルマークを含む画像もMPL 2.0で良いですか？

参考: Covid-19Radar/Covid19Radar#653

**Comment by daisukekoba** [comment]
新情報があったので追記。

https://github.com/Covid-19Radar/Covid19Radar/issues/653#issuecomment-685807039
> また、厚生労働省ロゴにつきましては、一時許諾を得ての結果でしたが、現在は削除を行う予定となっております。

https://twitter.com/kazumihirose/status/1301541880023248897
> ずっとREADME書いてあるのになぁ、元にはなったが、Covid19radarは、COCOAじゃない、公式でも無い、取り込まれるかの補償も無いと、MPLv2なのは、ごく一部にお借りしたロゴマークというプロプライエタリが存在するからで、なお読むと解るけど著作者人格権公使も付記でダメ、もちろん僕自身も

上記からCovid-19Radarではシンボルマーク（ロゴ）についてはMPL 2.0ではないように思われますが、COCOAではどういう扱いですか？

**Comment by takahashim** [comment]
こんにちは、特にこのプロジェクトや派生元プロジェクトの関係者でもなければ法律家でもない、通りすがりの（OSSも扱う）プログラマの者です。

MPL 2.0についての一般的なお話ですが、MPL 2.0では [2.3. Limitations on Grant Scope](https://github.com/cocoa-mhlw/cocoa/blob/master/LICENSE.md#23-limitations-on-grant-scope) で許諾する範囲に制限がかけられています。

> This License does not grant any rights in the trademarks, service marks, or logos of any Contributor

 （[非公式な日本語参考訳](https://note.com/note_s/n/n4a0f37ea8920)より抜粋: 「本ライセンスは、貢献者の商標、役務商標、またはロゴのいかなる権利も許諾しません」）

厚生労働省のシンボルマークもこのlogosに該当すると考えると、MPL 2.0ではその配布物にシンボルマーク画像が含まれていたとしても、何かしらの権利を許諾しているわけではないと解釈できます。そのため、本プロジェクト以外でシンボルマーク画像を使用するには別途許諾を得る必要があるかと思われます。

もっとも、それはそれとして、https://github.com/Covid-19Radar/Covid19Radar/pull/691 のように別途README等でシンボルマークの使用条件について追記するのは悪くはないかもしれません（こちらについてはプロジェクトごとに判断するべきことで、私はそれこそ関係者ではないので判断できません）。

**Comment by daisukekoba** [comment]
Contributorを示すデータではなく、ソフトウェアのアイコンとして含まれるデータは

> This License does not grant any rights in the trademarks, service marks, or logos of any Contributor

の範囲ではないと考えました。

> 厚生労働省のシンボルマークを含む画像もMPL 2.0で良いですか？

このように書きましたが、マークはMPLの対象ではないと思うので、ライセンスについて追記した方が良いのでは？という意見です。

**Comment by b-wind** [comment]
ちょこちょこ言及される割には誰も対応に触れていないようなので。
リポジトリ内にあるファイルが特定のライセンスで統一されていない場合と言うのはそれほど珍しくなく、多くは README 等に注記すれば済む話と思います。

厚生労働省のシンボルマークは厚生労働省の物で、一般にOSSでライセンスされる事は有りません。
シンボルマークの利用に際し、要求される事項は以下にあります。
https://www.mhlw.go.jp/kouseiroudoushou/symbol/shiyou.html

個人的には (1) の適用と考えて差し支えないように思います。


対応案は２つ。
1. 厚生労働省のシンボルマークはリポジトリから削除し、アプリケーションビルドの際に使用する物とする（git の管理範囲からも外す方が良い）
2. README とう分かりやすい部分に厚生労働省からライセンスされて利用していることを明記する

**Comment by keiji** [comment]
大変お待たせしました。COCOAのアイコンロゴ（厚生労働省シンボルマーク）の権利は厚生労働省に帰属します。
MPL 2.0対応外となり「Copyright (C) Ministry of Health, Labour and Welfare, All Rights reserved.」の取り扱いとなります。

また、MPL 2.0対象でないファイルの権利関係を表記する件については #110 に集約します。
よろしくお願いいたします。
