### ISSUE TITLE
接触確認API バージョンアップ

### ISSUE THREAD

**Issue by kazgoto** [cocoa-mhlw/cocoa#300]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

本Issueの作成時点でCOCOAが利用している接触確認APIは、「Legacy V1」と呼ばれるバージョンを利用していますが、これは非推奨となっており、新しいバージョン（ExposureWindow mode, ENv2）への移行が強く推奨されています。

https://developers.google.com/android/exposure-notifications/exposure-notifications-api

> We strongly recommend migrating to ExposureWindow mode. This mode allows you to separately view and revise or revoke matches from multiple days, while still leaving enough quota to update six times per day. Although the legacy v1 mode has more quota that can be used to partition matches by day, your app wastes the user's battery to do so and can even sometimes run out of quota.

## 解決策についてお書きください / Describe the solution you'd like

COCOAをExposureWindow mode（iOSではENv2）に移行します。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

N/A

## その他 / Additional context

TBD

----
Internal IDs:
- Epic 3042
- Feature 3043

**Comment by b-wind** [comment]
iOS の特定バージョンについては v1 に相当するAPIしか実装されていません。

https://github.com/cocoa-mhlw/cocoa/discussions/334#discussioncomment-1213073


対象の iOS バージョンに対してどのような方向性で対処するかは指針が必要かと思われます。

- v1 のみ対応のiOSでは COCOA ではサポート対象外とする。
- v1 のみ対応のiOSでは v1 相当の動作を行う様にする。

その他にも考えられるかも知れませんが、おおよそどちらかになるかと思います。

**Comment by keiji** [comment]
@kazuhiro4949 
COCOA2のコード取り込みにあたって認識あわせをさせてください。
今 #573 で第一期のコードレビューが進行しています。#530 のPull Requestは、第2期のコードレビューに含めることになると思います。

#573 進行中も`feature/cocoa2`へのPull Requestのマージは進めるということで良かったでしょうか。
`feature/cocoa2`が常に最新（`develop`と同じ位置づけ）、コードレビューでの変更も逐次反映する。逆に`feature/cocoa2`の変更はコードレビュー中のブランチには反映しない（2期まで）。という認識でいきたいです。
