### ISSUE TITLE
Android 版 においてUserDataのマイグレーションに失敗するケースが有る

### ISSUE THREAD

**Issue by b-wind** [cocoa-mhlw/cocoa#31]
**Describe the bug**
Android 版 v1.2.2 においてバックグラウンドタスク実行時の設定マイグレーションに失敗するケースが有る

**Smartphone (please complete the following information):**
 - Device: [Android]
 - OS: [all]
 - Browser [none]
 - Version [1.2.2]

**Additional context**

v1.2.2 から UserData の保持方法が変更になりました。
この際、旧バージョンからのデータを Migrate する処理が追加になっています。
https://github.com/cocoa-mhlw/cocoa/blob/047b12bfc497e5e32bd96e24c2b5d76c8ca18bcf/Covid19Radar/Covid19Radar/ViewModels/HomePage/SplashPageViewModel.cs#L22-L29

アプリをv1.2.2にアップデート後、一度でも起動すればこの処理が行われ正常にマイグレーションが行われますが、
Android においてバックグラウンドタスクから呼び出した場合、Application.Current が参照出来ないためマイグレーションに失敗します。
（ Xamarin.Forms の初期化が行われていない為と思われる ）
https://github.com/cocoa-mhlw/cocoa/blob/047b12bfc497e5e32bd96e24c2b5d76c8ca18bcf/Covid19Radar/Covid19Radar/Services/UserDataService.cs#L91-L96

想定している前提条件
v1.2.2 以前にWorkerManagerにタスクが登録され、v1.2.2 アップデート後に同タスクが実行される状態である事
（確実にそうなるかは自信が無いので情報をお持ちの方は補足をお願いしたいです）

当 Issue は #30 内の指摘から単独のIssueとして切り出したものです。
Android 開発には不慣れなため、間違い等多々あると思いますのでその際は指摘をお願い致します。

**Comment by zipperpull** [comment]
この問題の原因は以下のようになっていて

- v1.2.1 以前で利用していた Application.Current.Properties は Xamarin.Forms に依存している
- Android では WorkManager の Worker が起動するタイミングでは Xamarin.Forms が初期化されていない可能性があるので Properties は読み書きできない
  - MainActivity を起動後、OS側でプロセスが終了させられなかった場合のみ偶然動く

このため現状のままだと Migrate を Worker から実行すること自体が困難ということになりそうです。解決案としては、

1. Migrate の処理だけ Xamarin.Forms に依存せずに直接 Properties ファイルを読み込んで実行する
2. Worker から (ExposureNotificationHandler から) Migrate するのはあきらめて、MainActivity が実行されたタイミングで移行する
3. v1.2.1 以前からのアップデート後、Migrate 未実行で Worker が起動された場合は Migrate をあきらめる(使用日数も 0日になる)
 
という案がありそうです。1. は iOS との差分をどう処理するかの問題があり、2. は Worker で ExposureNotificationService が呼ばれて新しい PreferencesService / SecureStorageService にデータが保存されてしまうので、MainActivity 実行時には Properties とマージする処理が必要になります。

v1.2.1 のユーザを切り捨てる判断ができるのであれば、3. の選択肢が一番楽なのかもしれません。
ただし、Worker の Migrate を単に削除してしまうと、Worker で更新した Preferences/SecureStorage の情報が Migrate で上書きされる状況になるので、アップデート後に接触通知があったユーザは起動後情報が消えるなどの問題を起こす可能性もありそうです(未検証)。
回避するには、Migrate 実行済みのフラグを PreferencesService に保存するなどの対応追加が必要ではないかと思われます。

**Comment by keiji** [comment]
イベントの入場条件に「COOCAのインストール後14日経過＋接触記録がないこと」が存在し、3 の使用日数のリセットは厳しいかもしれませんね。

https://twitter.com/ls_9mermaid/status/1354433072477786117

個人的には 1 か 2 が良いと思います。

2 に加えて、MainActivityを起動したタイミングで新しいバージョンのデータが存在していた場合、Application.Current.Propertiesからは使用開始日のデータに限定してMigrateする。のような手当をすると、実装負荷とユーザーへの影響のバランスが良いと考えます。

**Comment by tmurakami** [comment]
`ExposureNotificationHandler`の当該箇所では Migrate できているかどうかだけをチェックして、できていなかったら後続処理をスキップする、というのはどうでしょうか？
今は毎日起動をお願いしている状況なので、この不具合だけ修正してすぐにリリースすれば良いように思います。

**Comment by zipperpull** [comment]
DependencyService の問題を解決しないといずれにしても Worker からの起動がうまくいかないので、
この不具合だけ直すのはたぶん意味がなくて  #25 を直す前提になると思います。
また、v1.2.2 で Worker が起動できている一部ユーザ(一部端末？)は、すでに必ず MainActivity -> SplashPage を経由して Migrate も終わっているので大丈夫ではないかと思います。

なので対象となるのは v1.2.1 以前のユーザがアップデートした場合で、
後続をスキップする場合は、アプリをアップデートしたまま一度も通常起動しないユーザは
Worker だけ起動されてなにもしない状態になるので通知は受けられない状態になる可能性が出てきそうです。
(現状も通知は受けられない状態のユーザなので、悪化はしないかも)

**Comment by tmurakami** [comment]
> DependencyService の問題を解決しないといずれにしても Worker からの起動がうまくいかないので、
> この不具合だけ直すのはたぶん意味がなくて #25 を直す前提になると思います。

そうでしたね、すみません...

ただ`ExposureNotificationHandler`の当該箇所で Migrate できないのであれば、スキップするしかないのではないかとも考えています。
`LastProcessTekTimestamp`が復元できない場合、直近14日以内に接触通知を受けた v1.2.1 以前の利用者は更新後に再度同じ通知を受けてしまうのではないかと懸念しています。
(勘違いかも)

**Comment by zipperpull** [comment]
すくなくとも v1.2.1 は transmission_risk_level の問題で誰も通知が出ていないのでそれは問題ないかなと思っています(v1.1.3 とかの古いもので表示されるパターンまでは考えていないですがさすがにたぶん大丈夫ではないかと。。)

**Comment by tmurakami** [comment]
> すくなくとも v1.2.1 は transmission_risk_level の問題で誰も通知が出ていない

そういえばそうでしたね。
失念していました。
であれば個人的には 2 が良いように思います。

**Comment by zipperpull** [comment]
前言撤回してすみません。

v1.2.2 の修正のとき、サーバ側の以下のコミットで v1 API (v1.2.1 以前で使っている？)の
transmissionRiskLevel も 4 に書き換えてしまっていますね。。

https://github.com/cocoa-mhlw/cocoa/commit/cf58f2230ac5d26736334a52cf4b680725d8038d#diff-26d2c0fba561e4cc742d58a1ec6a1b6250dfed3654da595d72e0dcc4efa35ccaR32

そうなると、v1.2.1 以前のユーザでも現時点では MainActivity 起動時のチェックで通知が行われるパターンがあるのかもしれないですね？

**Comment by heykuro** [comment]
皆さま、レスポンス遅れましたがこちらありがとうございます。

いただいたご意見を参考にさせていただきながら今開発チームでも対応進めていますが、以下のような方針で進めています(PRをこちらに上げていないので説明ベースで分かりづらくすみませんが、中間的な共有として)。

問題点として、指摘いただいているXamarin.Formsが初期化されていない点について開発チームでも対応中です。
具体的には、Xamrin.Formsに依存している、Application.Current.Properpertiesは指摘いただいているようにバックグラウンド処理の際は初期化されていないので( @b-wind さんご指摘ありがとうございます)、その場合はXamarin.Formsの内部処理(Deserializer)を直接生成して呼ぶような形で回避するよう実装検討。


@zipperpull さんからいただいた、
>v1.2.1 のユーザを切り捨てる判断ができるのであれば、3. の選択肢が一番楽なのかもしれません。

という点については、切り捨ては考えておらず、Migrateが実行できる形での対応を考えています。


また、これも既に指摘いただいているように、このissueで指摘されている点だけでなく、DependencyServiceの問題についても対応します( #25 で指摘されている内容)。
通常起動されているときはDependencyServiceでインスタンス取得するが、バックグラウンド処理の場合は別処理でインスタンスをnewするよう実装する形です。

**Comment by zipperpull** [comment]
コードを見ていないのでなんともいえませんが、

> バックグラウンド処理の場合は別処理でインスタンスをnewするよう実装

一般論としては、安易にこれをやるとバックグラウンドでプロセス起動されたあと MainActivity が起動された場合に問題がありうるとは思うのでテストなどでの考慮をよろしくお願いします。

また、実装進めていますということだとこちらでは議論する意味もなさそうということになるのですがこの方針でよろしいのでしょうか？ @heykuro

**Comment by heykuro** [comment]
@zipperpull  ありがとうございます。いただいた内容も踏まえてテスト進めます。

> こちらでは議論する意味もなさそうということになるのですがこの方針でよろしいのでしょうか？

最終確定というよりは実装・検証を進めている段階なので、その中でまた問題点あればこちらでも共有させていただきたいと思います。 また、#25  と混ぜて書いてしまいましたが、そちらと分けて扱うようにします。

**Comment by b-wind** [comment]
Internal Repositoryに取り込まれたそうなのでcloseします。
リリース後に問題があれば再度 Issue を建てるのが良いかと思います。
