### ISSUE TITLE
NuGetライブラリ管理方法の調査

### ISSUE THREAD

**Issue by kazuhiro4949** [cocoa-mhlw/cocoa#312]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

NuGetの管理方法でプライベートなライブラリをバイナリとして含めずに済む方法があるか調べておく

## 解決策についてお書きください / Describe the solution you'd like

TBD

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

TBD

**Comment by keiji** [comment]
これ今のところnugetをそのまま取り込む方向にしているので一回閉じます。
何かあればreopenしてください。
