### ISSUE TITLE
[COCOA2][iOS] バックグラウンドでの接触確認

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#319]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

#300

Xamarin.ExposureNotificationからCappuccinoに移行するにあたって、バックグラウンドでの処理はアプリ側で実装する必要がある。

本IssueはiOSに限定して検討する。

## 解決策についてお書きください / Describe the solution you'd like

BGTaskSchedulerを使う。

## その他 / Additional context

iOS側の実装もCOCOAに関しては把握しているので、ひとまず @keiji が書ける。けれど現在のCOCOAを超えることは出来ないので、iOSのお作法的に問題ありそうなところや細かい調整を @kazuhiro4949 にお願いしたいです。

iOS 12.5系については現時点ではサポートの予定はないけれど、コードとして書く場合はどうなるか考えてはおきたい（BGTaskSchedulerが使えないと言うことは知っている）。

**Comment by kazuhiro4949** [comment]
以下のAppleのサンプルプロジェクトによるとiOS 12.5では分岐させて次のように実装する必要があります
https://developer.apple.com/documentation/exposurenotification/building_an_app_to_notify_users_of_covid-19_exposure

```swift
extension ENManager {
    
    /// On iOS 12.5 only, this will ensure the app receives 3.5 minutes of background processing
    /// every 4 hours. This function is needed on iOS 12.5 because the BackgroundTask framework, used
    /// for Exposure Notifications background processing in iOS 13.5+ does not exist in iOS 12.
    func setLaunchActivityHandler(activityHandler: @escaping ENActivityHandler) {
        let proxyActivityHandler: @convention(block) (UInt32) -> Void = {integerFlag in
            activityHandler(ENActivityFlags(rawValue: integerFlag))
        }
        setValue(proxyActivityHandler, forKey: "activityHandler")
    }
}
```

**Comment by keiji** [comment]
マージ済みなのでCloseします
