### ISSUE TITLE
[iOS]接触確認通知をタップしたあとで接触確認画面へ遷移する

### ISSUE THREAD

**Issue by kazuhiro4949** [cocoa-mhlw/cocoa#321]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

現在接触確認通知をタップするとHomePageが開くが、直接接触確認画面へ遷移させたい

## 解決策についてお書きください / Describe the solution you'd like

https://github.com/cocoa-mhlw/cocoa/issues/290
https://github.com/cocoa-mhlw/cocoa/pull/292

これらissue・プルリクの関連でiOS側のローカル通知タップ後の接触確認画面への遷移を実装する

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

上述の内容と同じ

## その他 / Additional context

----
Internal IDs:
- Product Backlog Item 3655

**Comment by keiji** [comment]
@kazuhiro4949 #292 （まだドラフトですが）を取り込んだ後でもいいので、iOS側の実装をお願いしても良いですか？

**Comment by kazuhiro4949** [comment]
[メモ] TODO記載内容に関して見終わってからissueはcloseする
https://github.com/cocoa-mhlw/cocoa/pull/324/files#diff-41dab84b2325b883223c81abfe57cf9987780cba889c7e72032d2f9dd043427eR57-R58
