### ISSUE TITLE
ENの状態のハンドリングを各PFで行ったほうがいいか、まとめてやったほうがいいか調査

### ISSUE THREAD

**Issue by kazuhiro4949** [cocoa-mhlw/cocoa#325]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

https://github.com/cocoa-mhlw/cocoa/pull/313#discussion_r688485483

こちらで議論していた、ENのエラーハンドリングを各PFで行ったほうがよくなるか別途検討します。
iOSとAndroidのそれぞれのエラーをまとめてswitch文でハンドリングしているが、
各PFのクラス内でハンドリングした上でCommon上では例外なりで渡されてきたメッセージをただ表示させるだけにしたほうが扱いやすいように思ったためIssue化しておきます。

## 解決策についてお書きください / Describe the solution you'd like

状態がiOS, Androidで個別に定義されているので、それぞれでハンドリングされている方がコードの役割分担が明確で扱いやすくなるかと思いました。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

iOS・Androidそれぞれで状態をハンドリング、Commonに表示させるデータを共通のフォーマットで返して、ViewModelでは表示処理のみを行う

**Comment by keiji** [comment]
> 各PFのクラス内でハンドリングした上でCommon上では例外なりで渡されてきたメッセージをただ表示させるだけ

ここで言うメッセージとは文字列のことでしょうか。

ぼくは、Cappuccinoから受け取った状態（複数）に応じて共通プロジェクトのViewModel側が振る舞いを決める現在の方式が良いと思います。

今回は現在の実装を引き写しただけなので、たまたま「状態に対応する文字列をAlertで表示するだけ」になっていますが、実際は状態に応じて挙動そのものを変える必要があります。

たとえば、新しいUI案ではBluetothが無効なときには有効化を案内して、Bluetoothの設定画面を開くボタン付きのダイアログを表示する挙動をプログラムしなくてはなりません。プラットフォームから文字列を渡すだけでは、このようなケースに対応しにくいと考えます。

またENのStatusは、Androidでは複数の値が返される場合があります（iOSは必ず１つ）。
たとえばBluetothがオフの例を見ると、Androidでは「Bluetooth OFF」と同時に「ENがOFF」と言う状態の二つが返されます。
このように複数の状態があるときにユーザーにどのように表示するかは（画面によって優先順位が変わってくるので）共通化できるものではなく、現在のViewModel側で振る舞いを決める方式が良いと考えています。

**Comment by tmurakami** [comment]
> たとえばBluetothがオフの例を見ると、Androidでは「Bluetooth OFF」と同時に「ENがOFF」と言う状態の二つが返されます。

iOS で Bluetooth が off の場合、`exposureNotificationEnabled` の結果はどうなるのか気になります ( `true` なのかな？)  。

あと、例えば Android の `LOW_STORAGE` のステータスに関しては、iOS 側には該当するステータスは無いようなのですが、エラーコードとしては存在しているようです。
https://developer.apple.com/documentation/exposurenotification/enerror/code/insufficientstorage

COCOA ではほとんどの例外をログに出力して終わりにしていたと思うので、このあたりのハンドリングは (ステータスも例外も) v2 対応とは別に一度整理したほうが良いのかもしれません。

**Comment by kazuhiro4949** [comment]
@keiji なるほどです。ViewModel側で状態ごとの実装の出し分けが必要になってくるんですね。

検討したほうがいいと思っている内容のポイントとしては、共通化されている画面が各PFの分岐を持たずそれらとは独立して仕様を持っているようにしたほうが良さそうという点です。
単純にテキスト以上のことをやる必要があるなどであれば、UIのパターンを状態(コンテナ)として共通部分に持ってそれらを各PFの実装から返すとかがいいのかなぁと思っています。

理由としては↓の辺からそう捉えております。

1. COCOAのクラス設計として画面周りはPFからは独立して作られており、PFで分岐されるものは別クラスの形でそれぞれ実装されている
2. 実作業の観点ではPF毎に動作確認・不具合調査するケースが多いと思うので、画面側にPF固有の分岐を作らずに影響範囲を小さくしたほうが労力が小さく済みそう

ただ、頭の中の世界としてはそういう感じに考えているんですが、実際にCOCOAの実装を見るとそのポリシー通りには作られていなさそうな部分がちょいあるのと、今対象としている状態がCappuccino内の実装を読むとCommonとして定義されているものだったので、そこまで意識しすぎなくてもいいのかなぁという気持ちになっておりますmm

**Comment by kazuhiro4949** [comment]
@tmurakami ありがとうございます、ちょっと見てみたいと思いますmm

> COCOA ではほとんどの例外をログに出力して終わりにしていたと思うので、このあたりのハンドリングは (ステータスも例外も) v2 対応とは別に一度整理したほうが良いのかもしれません。

理想状態の動線を外れるものは結構大胆に丸めたり握りつぶしたりしている部分多い印象はあるので、整理はしたほうが良さそうだと僕も思いました。

**Comment by kazuhiro4949** [comment]
こちらの件を
- iPhone 12 pro max
- iOS14.7.1
- 
で確認したところBluetoothがoffのときはexposureNotificationEnabledはtrueでした。

https://github.com/cocoa-mhlw/cocoa/issues/325#issuecomment-898966224

**Comment by tmurakami** [comment]
> BluetoothがoffのときはexposureNotificationEnabledはtrueでした。

iOS では Android と異なり、Bluetooth の on/off と EN の有効/無効が連動していないのですね。
お忙しい中ご確認ありがとうございました。

本題について、COCOA 開発者ではない私が意見を言うのは憚られるのですが敢えて言わせていただくと、(ステータスを共通化できないのであれば) 私は @kazuhiro4949 さんの「PF 側でハンドリング」案に賛成です。
共通側に Android や iOS といった文字列が現れるのは、例え動作に問題無かったとしても違和感があります。

**Comment by keiji** [comment]
ありがとうございます。
状態の共通化をしてプラットフォーム側でハンドリングするという取り組みは、現在のXamarin.ExposureNotificationが次のようにしています。

https://github.com/cocoa-mhlw/cocoa/blob/2a729494ad1efa1f3f3119b71e4623b672271557/Covid19Radar/Xamarin.ExposureNotification/ExposureNotification.shared.cs#L132-L140

ただ、共通化しようとするあまりに2つのプラットフォームに共通で存在する状態以外をUnknownとして捨ててしまっています。これではきちんとしたハンドリングができないとぼくは思います。

実際にはEN APIにはこれ以外の状態が、プラットフォーム固有の状態が存在します。

https://github.com/keiji/chino/blob/master/Chino.Common/ExposureNotificationStatus.cs

たとえばAndroidの`NO_CONSENT`と、iOSの`Unauthorized`はともにユーザーが接触確認アプリに、接触確認APIの利用を認めなかったときの状態です。現状のPRではこれを同じものとして取り扱っていますが、もし将来、この二つの挙動が違うことがわかれば共通化した状態を再び分ける必要が出てきます。
日本国内ではあまり考えなくても良いことかもしれませんが、接触確認APIが他のアプリに切り替わったときは、Androidでは`FOCUS_LOST`の状態になります。

その上で、設計としてどうするのが美しいかと言えば、それはもちろん @kazuhiro4949 さんや @tmurakami さんの仰る共通プロジェクト側にプラットフォームの要素が出てこないことが理想だと思います。

現状、プラットフォーム固有の状態を丸めず、将来の変更にも対応可能な方法を追求していければと思います。

**Comment by keiji** [comment]
これも現状で問題ない様子なのでクローズしようかなと思うのですが、急ぐ必要もないので次に一巡したときになにも動きがなければクローズと言うことで。
