### ISSUE TITLE
Issue / Pull Request Template の整理

### ISSUE THREAD

**Issue by halsk** [cocoa-mhlw/cocoa#33]
**Is your feature request related to a problem? Please describe.**
Issue / Pull Request テンプレートが英語のみ。

**Describe the solution you'd like**
Issue / Pull Request テンプレートが英語のみなので、日本語を併記する。Issue Template に Custom Template が残っているので削除。

**Comment by Meiryo7743** [comment]
当方でドキュメント（issue 及び PR のテンプレート）を修正し，pull request を出してもよろしいでしょうか……？

（既に進行中である，またはそちら側で行う内容のものでしたら，申し訳ありまん）

**Comment by halsk** [comment]
@Meiryo7743 さん、お申し出ありがとうございます。まだ当方では着手できておりません。もし可能であれば大変助かります！！

**Comment by Meiryo7743** [comment]
@halsk 了解です！

こちら側で当該テンプレートを修正した PR を出します。
