### ISSUE TITLE
接触日が UTC であることを明記する

### ISSUE THREAD

**Issue by tmurakami** [cocoa-mhlw/cocoa#335]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

よくある質問 [問④-13](https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/covid19_qa_kanrenkigyou_00009.html#Q4-13) に以下の記述があります。

> 問④-13　「陽性者との接触一覧」で日付ごとの接触件数が表示されますが、陽性者に限らず人と接触した覚えがない日に接触件数が表示されているのはなぜですか。
>
> 接触確認アプリが基盤としているAPIの仕組みでは、陽性者の日次鍵がJST（日本標準時）ではなく、UTC（協定世界時）を基準としているため、両者の時差により、午前０時から午前９時の間の接触については、実際に陽性者と接触があった日よりも１日前の分として表示されるケースがあります。

## 解決策についてお書きください / Describe the solution you'd like

接触一覧画面に但し書きでもあると良いのかなと思います。
ただし、連絡を受ける発熱センターのオペレーターさんなどは多少混乱するかもしれません。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

なし。

## その他 / Additional context

なし。

**Comment by b-wind** [comment]
UTC と言われても大抵の人は分からないと思いますので日付のみの表示を辞め、N月M日9時〜N月M+1日9時 の様に表記してしまった方が誤解は少ない気はします（見た目が悪いので気は進まないですが）
