### ISSUE TITLE
[iOS] CloseApplicationを適切に実装する

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#337]
> 本筋とは外れるのですが、この実装を読むとiOSの場合は意図的にアプリをクラッシュさせているようなのですが、なんのためにやっているんですかね？落としているのでその直下のloggerServiceのメソッドも呼ばれないんじゃないかなという気がしました(まだ実行はしていないです)。

_Originally posted by @kazuhiro4949 in https://github.com/cocoa-mhlw/cocoa/pull/315#discussion_r693333504_

----
Internal ID : NFR2611

**Comment by keiji** [comment]
@kazuhiro4949  @daisuke-nogami (Cc: @kazgoto, @heykuro ) 
これCOCOA2で対応しませんか。
具体的に言うと、養成情報登録の画面を終了してホーム画面に戻るだけにするのが良いかと思いますが、いかがですか？

**Comment by kazuhiro4949** [comment]
はい、そうしましょうか。

**Comment by kazuhiro4949** [comment]
とりあえず自分の方で進めてみます

**Comment by kazuhiro4949** [comment]
テスト追加したのでreopenします
