### ISSUE TITLE
[iOS] デバッグビルド用のEntitlementsを用意する

### ISSUE THREAD

**Issue by kazuhiro4949** [cocoa-mhlw/cocoa#340]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

COCOA2専用の対応ではないですが、デバッグビルドでexposure notificationを完全に使うときのEntitlements設定が存在していないので追加する

## 解決策についてお書きください / Describe the solution you'd like

デバッグビルドでもENManagerの一部APIが正常に動作する

**Comment by keiji** [comment]
https://github.com/cocoa-mhlw/cocoa/pull/314/files#diff-6d14b65242c38d419347fc8545bd0b1cc0a25361241e9b5a9eb75243c776e503

ここで入れてるやつでしょうか。

**Comment by kazuhiro4949** [comment]
あーそれです。そこで入るんですね

**Comment by kazuhiro4949** [comment]
別のissueがdoneになると自動的に解決するので閉じます
