### ISSUE TITLE
ドキュメント類のGitHub Pagesへの移行

### ISSUE THREAD

**Issue by heykuro** [cocoa-mhlw/cocoa#345]
皆さま、いつもCOCOAの開発にご協力いただきありがとうございます。
COCOAの運用に関するお知らせが2つあります。

## ドキュメント類をGitHub Pagesへ移行します
COCOAリポジトリは現在（2021年9月1日時点）、2つの場所でドキュメントを管理しています。
一つはリポジトリの中にあるファイルです。ここには`CONTRIBUTING.md`、`OPERATION_POLICY.md`など運用に関する情報を記載しています。
もう一つの場所は[Wiki](https://github.com/cocoa-mhlw/cocoa/wiki)です。こちらには「COCOAのビルドについて」「多言語対応時のリソースの追加・変更について」など、開発に関係する情報があります。
「開発に係わる情報を1つの場所に集約する #175 」の提案を受けた当初、すべての情報をWikiに集約することを想定して作業を始めました。

しかし、Wikiはリポジトリのコラボレーターにしか更新できず、またPull Requestを受け付ける仕組みもレビューをする仕組みもありません。リポジトリのコラボレーターであってもレビューを受けずにドキュメントを更新できるという状態は好ましくないと考えています。

この課題を解決するため、Wikiの内容をGitHub Pagesへ移行することにしました。
ドキュメントについてもリポジトリ内で管理します。リポジトリ内に `documentations` ディレクトリを作成して、その中でドキュメントを配置します。ドキュメントが変更されれば都度、Static Site Generator(Hugo)がHTMLに変換、GitHub Pagesを更新します。
この変更により、ドキュメントへのコントリビューションもスムーズに受付できるようになります。コントリビューターの皆様には `documentations` ディレクトリ内を変更するPull Requestを出していただきます（宛先はデフォルトの`develop`ブランチ）。

これに伴いWikiの更新は凍結し、一定期間後にWiki機能そのものを停止する予定です。
なお、GitHub Pages移行後も`README.md`や`LICENSE.md`、`COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md`など一部のファイルについては引き続きGitHub Pagesに含めずに管理する予定です。

## コントリビューターの一覧にお名前を記載させてください
COCOAのフォーク元である「COVID-19Radar」では、コントリビューターの情報を`CONTRIBUTORS.md`に記録していました。

COCOAでもそれに倣おうと検討をしていましたが、今回移行するGitHub Pagesに、コントリビューターの皆さんのお名前を掲載するページを設けることにしました。

これまでCOCOAにコントリビュートをしてくださった方で、一覧への記載を希望する方は[documentations/content/docs/contribution/contributors.md](https://github.com/cocoa-mhlw/cocoa/blob/develop/documents/content/docs/contribution/contributors.md)に、お名前を記載するPull Requestを出してください。

なお、ここで言う「コントリビュート」とは、Pull Requestが取り込まれることだけではなく、不具合の情報を寄せていただいた方、Issueにコメントをくださった方などもすべて含みます。

皆さまからのPull Requestをお待ちしています！

**Comment by keiji** [comment]
ここです！

https://cocoa-mhlw.github.io/cocoa/

README.mdからもリンク済みです（英語版は今のところありません）。

**Comment by b-wind** [comment]
README.md / README.ja.md から CONTRIBUTING.md へのリンクが切れていますね。


README は書き換えのみで済むと思いますが、Issue や外部から古いアドレスにリンクが張られている事もあるので削除では無く、新コンテンツへのリンクページに差し換える方が望ましい気がします。


余談かもですが、cocoa-mhlw/cocoa リポジトリが（９月１日から？）デジタル庁が運用していることはもう少し分かりやすい場所に有った方が良いかなと。

見落としであればすいませんが公式に案内は無かったと思いますし、ドキュメントが別サイトに移ったことでこちらに書かれている「当リポジトリ」の表す内容が不明瞭になってしまっていると感じます。
https://cocoa-mhlw.github.io/cocoa/docs/operation_policy/

**Comment by keiji** [comment]
> README.md / README.ja.md から CONTRIBUTING.md へのリンクが切れていますね。

Issueを作っておきました！

**Comment by keiji** [comment]
移行は終わっているのでCloseします。コントリビューターへの追加については独立したIssue（ #526 ）にしました。
