### ISSUE TITLE
[iOS] 通知の許諾を取らないといけない問題

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#359]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

iOSの接触確認APIバージョン1（ENv1）では、接触と判定されてENから情報を取得するタイミングでシステムから通知が出ていたが、ENv2ではそれが無くなりるためアプリ独自のローカル通知を実装する必要がある。

アプリから通知を表示するためには、利用者からローカル通知の許可を得なければならない。

ローカル通知自体は #297 で対応済みではあるが、問題は利用者が通知を拒否したとき。
iOSの仕様上、次から通知の許可を尋ねるダイアログは表示されない。通知を許可するには、利用者が設定画面を開いて切り換える必要がある。

ローカル通知が許可されない限り、接触確認で接触の可能性がある場合でもプッシュ通知は利用者に届かない。

「それが利用者の選択だ」と言えばそれまでではあるけれど、COCOAの性質上、通知は非常に重要。
アプリが自動でアップデートするのに任せ、長期間UIを起動しない利用者も当然想定されるため、バックグラウンドからも通知の許可を求める必要がある（現状の実装）。

一方、バックグラウンドから通知の許諾を求めるのは、利用者から見れば起動もしていないCOCOAが突然ダイアログを出してくるのだから驚くし、わけもわからず拒絶してしまう可能性がある。

そういった利用者にどうやってリカバリー方法を案内するか。
接触の可能性があることに気づかず、ある日アプリを開いてはじめて知る。のような形になるのは避けたい。

## 解決策についてお書きください / Describe the solution you'd like

COCOAのホーム画面に、通知が許可されていないことを表示して許可を促す（設定画面へのリンク？）。

通知を許可しなければENv2対応のCOCOAが正常に動作しないことを宣伝して利用者にアップデートと通知の許可を促す（広報面）。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

バックグラウンド処理で、プッシュ通知が許可されていないことを検知した場合、EN自体を停止する。

利用者がCOCOAを起動すれば通知状態から有効化への同線に乗せることが出来る。ただし、長時間ENを止めると端末内のRPI等が削除されるので利用者の接触情報を失わせることになる。この方法は可能な限り避けたい。

----
Internal ID: PBI 3885

**Comment by b-wind** [comment]
本日公開された、 v1.2.6 にアップデートしましたところ以下に有るような許可を求めるダイアログが表示されませんでした。
https://www.mhlw.go.jp/content/10906000/000829254.pdf


同端末では公開初期から導入していたので、当初有ったと言う通知設定が残っていたものと推測します。
想定されたフローかどうか分からなかったので、こちらに記載しておきます。

**Comment by b-wind** [comment]
> バックグラウンド処理で、プッシュ通知が許可されていないことを検知した場合、EN自体を停止する。


ENS 自体を停止する妥当性は無い様に思います。
どちらにせよ通知できないのですから、COCOA を起動した時点で表示されれば良いかと。


それとは別にApp Storeでの説明やアプリ内、SNS等で通知をOnにする事を求める努力は必要かと思います。

**Comment by keiji** [comment]
> 本日公開された、 v1.2.6 にアップデートしましたところ以下に有るような許可を求めるダイアログが表示されませんでした。
> https://www.mhlw.go.jp/content/10906000/000829254.pdf
> 該当端末では通知設定自体は許可になっていたので動作そのものに影響は無い様子。

これまで許諾を許可・拒否したユーザーに表示されないのは想定された動作ですね（それ以外やりようがない）。

あとできることと言えば、

 * 通知については泥臭く広報していく
 * チュートリアルに「通知をオンにしてください」のページを追加（iOSのみ？）
 * 通知が許可されていなければホーム画面に表示（設定への誘導）

くらいを考えています（現時点で確定していません）。

**Comment by b-wind** [comment]
上記とは別の環境で、 v1.2.6 で通知を求めるダイアログが出ないフローがありますね。
iOS の通知の一覧にも表示されていない（On でも Off でもなく項目自体が無い）
再現方法は確認中。


最終的にホーム画面で注意喚起されれば問題無い様にも思いますが、一応。

**Comment by keiji** [comment]
通知の許諾がないことをCOCOAのホーム画面で表示する仕組みを追加したので、本Issueをクローズします。
