### ISSUE TITLE
[Android] 動作情報をAndroid端末で保存した場合 .../Android/data/... 内に保存されてしまう

### ISSUE THREAD

**Issue by Murayu0225** [cocoa-mhlw/cocoa#360]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

Android端末にてCOCOAの動作情報を取得すると今現在、.../Android/data/jp.go.mhlw.covid19rader/files 内に保存されています。
ですが、このディレクトリへのアクセスはAndroid11より制限が厳しくなったため純正のファイルマネージャーを利用しないとアクセスできなくなっています。
普通に利用する際は問題ありませんが、あまり望ましい保存場所とは思いません。

↓Android11 でのストレージについて
https://developer.android.com/about/versions/11/privacy/storage?hl=ja#other-private-dirs

## 解決策についてお書きください / Describe the solution you'd like

COCOAの動作情報ログを共有ストレージへ保存を行う。
→動作情報の保存を共有ストレージへ行うには、権限の付与（ストレージアクセス）が必須になりあまり良くないかもしれません。

他国のアプリを利用してみたところ、 [corona-warn-app](https://github.com/corona-warn-app/cwa-app-android) ではエラーログ(zip)を確認する機能がありました。ですが、端末にアプリから直接保存する機能はなく、生成したzipファイルをメールアプリ等を利用して共有するように求めてきます。（例:Gmailアプリで自分から自分宛てにメールを送ってそのzipファイルを確認する）

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

- COCOAの動作情報を確認する機能を削除する。（役に立つことがあると思うのであまり良い代替案ではないかもしれません。海外のENSアプリをインストールして試してみたりしたのですが、この機能がついているENSアプリはあまりないため削除するのもひとつの方法かと思います。）
----
Internal ID: PBI 3886

**Comment by keiji** [comment]
ご指摘ありがとうございます。確認したところ現状はこのような感じですね。

![Screenshot (2021_09_04 15_08_47)](https://user-images.githubusercontent.com/932136/132084771-7f47d0f6-defc-4acf-8ed1-d022eb36e016.png)

この「ファイル管理アプリで…」のくだりが正しい記述でないと理解しました。

共有ストレージに置いていないのはパーミッションが必要と言うこともあると思いますが、他のアプリから意図せずアクセスできてしまう経路はなるべく作らない方がいいというのもあるかと個人的には思いました（開発チームには別途確認します）。

いただいた解決策では、共有機能を使う（corona-warn-app）の方式が良さそうです。
現在はダイアログに「OK」ボタンのみの表示ですが、これを「閉じる」「共有」として、共有からメールやGoogle Drive、NearBy Shareなどにつないでいくのが良いように思います。iOSでも同様の機能が実現できると良いのですが、いかがでしょうか> @kazuhiro4949 

また、この画面を触るなら #140 も入れてしまうのがよさそうです気（Pull Requestは別になりますが、画面仕様への反映などの工数的な意味で）。

**Comment by Murayu0225** [comment]
このIssue対応します。

**Comment by keiji** [comment]
@Murayu0225 ありがとうございます。お願いします。assignしておきます。

#140 についてもできればお願いしたいです。Pull Requestは別にしていただけると助かります（同時期に取り込めるように調整の準備しておきます）。
