### ISSUE TITLE
README.md / README.ja.md からCONTRIBUTING.mdへのリンクが切れている

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#391]
## 不具合の内容 / Describe the bug

https://github.com/cocoa-mhlw/cocoa/issues/345#issuecomment-917403370 で指摘のあった事項。

このIssueで対象とするのは表題の通り。

## 期待される挙動 / Expected behavior

CONTRIBUTING.mdではカバーしきれない情報を置くためにサイトを作ったので、リンク先はCOCOA Open Source Projectのトップページとする。

`CONTRIBUTING.md`の内容に対応するコンテンツに直接リンクせず、COCOA Open Source Projectのトップページを表示する。

 * https://cocoa-mhlw.github.io/cocoa/

> We welcome PullRequest and Issues to this repository. Please check CONTRIBUTING.md in advance before submitting.

これが

> We welcome PullRequest and Issues to this repository. Please check COCOA Open Source Project in advance before submitting.

こうなる。

> 本リポジトリへの PullRequest や Issues を歓迎いたします。事前に新型コロナウイルス接触確認アプリ（COCOA) への貢献についてのガイドラインをご確認の上、投稿いただければと思います。

これが

> 本リポジトリへの PullRequest や Issues を歓迎いたします。事前に「COCOA Open Source Project」を確認の上、投稿いただければと思います。

こうなる。

## その他 / Additional context

welcome-contriutionに指定します。

指摘のあったコメントで触れられている「CONTRIBUTING.md」で移転を案内することはしません。それをすると実質ファイルが消せなくなります。

外部から`CONTRIBUTING.md`にリンクしているサイトとしては、例えば @Murayu0225 さんの [COCOAにコントリビューターとして貢献しよう！](https://qiita.com/Murayu0225/items/aa62d073a06255b5e575)があるので、こちらについては変更のリクエスト送ります。

その他、リンク切れの箇所を見つけたら順次、対応をお願いしていく可能性がありますが、外部サイトのリンク切れについては当リポジトリのIssue等では取り扱いません。

**Comment by tatsu-jp** [comment]
@keiji さん、
本件、私の方で対応したいと思います。

一点確認させてください。
issue_templateの「技術的な内容以外のご要望・ご提案」のURLの変更先も、COCOA Open Source Projectのトップページで良いでしょうか？

**Comment by keiji** [comment]
そちらは`README.ja.md`の

> 技術的な点以外のご要望については、大変お手数ですが、Q&Aページに記載がありますお問い合わせメールアドレスにご連絡いただきますようお願い致します。

に合わせる形にしましょう。

> 技術的な内容以外のご要望については、本リポジトリでは扱いません。Q&Aページに記載がありますお問い合わせメールアドレスにご連絡いただきますようお願い致します。

でどうでしょう。

**Comment by tatsu-jp** [comment]
@keiji さん、PR発行したのでご確認お願いします。
