### ISSUE TITLE
動作中であることがわかる点滅ランプが大きくなっていく

### ISSUE THREAD

**Issue by Murayu0225** [cocoa-mhlw/cocoa#420]
## 不具合の内容 / Describe the bug

#419 にてバグを発見しましたので報告します。既知のバグでしたらすみません。

ホーム画面にて点滅している円ですが、素早く別画面に移動して素早くホームに戻ると緑色の円がどんどん大きくなっていくバグがありました。（他の方法でも起こるかもしれません。詳しくは、動画の方を確認してください。）

## 再現手順 / Steps to reproduce

私の場合の方法です。他の方法でも起こるかもしれません。

1. 'ホーム画面' に行き、
2. '陽性者との接触結果を確認' をクリックし、
3. 素早く 'ホーム画面' に戻ると、
4. 動作中ランプの点滅が大きくなっていきます。

## 期待される挙動 / Expected behavior

大きくなっていく点滅がなくなる。

## スクリーンショット / Screenshots

動画を取りました。動画の容量が大きいのでGoogle ドライブにアップロードしました。

https://drive.google.com/file/d/11iWSUvclmm9CWDRpavXC2WQci7FoLvXl/view?usp=drivesdk

## 動作環境 / Environments

- デバイス：Galaxy S10（例：Pixel 5、iPhone 6 等）
- OS：Android11（例：Android、iOS）
- バージョン：- (例：1.2.2)

## その他 / Additional context

----
Internal IDs:
- Bug 4008

**Comment by b-wind** [comment]
課題そのものとは少しズレますが、何故点滅させているのかちょっとよくわからないですね。


また、「JIS X 8341-3:2016 1.4.1 色の仕様の達成基準（レベルA）」に
```
色が,情報を伝える,動作を示す,反応を促す,又は視覚的な要素を判別するための唯一の視覚的手段になっていない。
```
と有りますので緑のランプのみで正常稼働を示しているとしたら不適切であるように思います。
（文字列などでも表現する必要がある）

**Comment by keiji** [comment]
稼働状況表示については色だけでなく、文字列でも記載しています。

**Comment by keiji** [comment]
@Murayu0225
ありがとうございます！　開発チームに確認したところ、コードの同期タイミングをまたいでいたので今回の反映されていないものの、すでに修正済みでした。

すばやく画面を切り換えると、アニメーションを管理するタスクがキャンセルされる前に次のタスクが始まること。フィールドのCancellationTokenSourceが差し替わってしまうので、キャンセルが正しく伝わらないことが原因でした。タスク内から参照するCancellationTokenSourceをローカル参照に切り換えて、さらにセマフォを取って多重実行を防止するコードを組み込まれていました。

該当の修正がマージされたらCloseします。

**Comment by Murayu0225** [comment]
わかりました。
確認していただきありがとうございます！

**Comment by kazuhiro4949** [comment]
もう実装は完了してるっぽいすが重複して取り組んでしまったので念の為僕の方でやったことをメモとして書いておきますー。
Animationクラスを使った実装に変えていて、それを使うとCancelTokenとLockを使わずに済みそうでした。
https://github.com/cocoa-mhlw/cocoa/pull/446/files

**Comment by Murayu0225** [comment]
このIssueは、#461 をビルドして解決している事が確認できました。
クローズしてもよろしいでしょうか。

**Comment by keiji** [comment]
@Murayu0225 はい。クローズしてください。
確認ありがとうございます！
