### ISSUE TITLE
リリースブランチ作成

### ISSUE THREAD

**Issue by takahr** [cocoa-mhlw/cocoa#43]
**Describe the solution you'd like**
アプリのストア公開前にリリースブランチで次回リリース予定の内容を開示して整理してみてはどうでしょうか

**Additional context**
前回 v1.2.2 のリリースではAndroid版での不具合が残ったままリリースすることになってしまったのですが、そういった事態をなくす(減らしていく)ための提案です。

具体的にリリースブランチをどう運用するかにはいくつか方法がありそうです。
これまでは master でストアの最新版ソースを開示する方針だったと思いますので、それを踏襲すると以下のような運用(案)が考えられると思います

- たとえば rc1.2.3 のようなブランチで次回リリースの内容を整理
- 実際にストアにリリースした際に rc1.2.3 ブランチを master にマージ
- master へのマージコミットに v1.2.3 タグをつけて、rc1.2.3 ブランチを削除

以下のページでは develop ブランチからの例ですが参考になるかもしれません
cf. https://dev.classmethod.jp/articles/git-flow-release/

**Comment by Takym** [comment]
#204 にてこの Issue は解決しているのではないでしょうか。

**Comment by keiji** [comment]
ありがとうございます。
リリース予定のものが公開されるという意味ではご指摘の通りです！
本IssueはCloseしますね。
