### ISSUE TITLE
iOSで動作状況のアニメーションが不正な状態になることがある

### ISSUE THREAD

**Issue by kazuhiro4949** [cocoa-mhlw/cocoa#445]
## 不具合の内容 / Describe the bug

iOSアプリでナビゲーションプッシュ -> ポップでホームに戻ってくると、動作状況のアイコンのアニメーションが不安定になる

## 再現手順 / Steps to reproduce

1. ホームに行き、
2. 陽性情報の登録をクリックし、
3. ナビゲーションの戻るを押す、
4. エラーが発生します。

## 期待される挙動 / Expected behavior

どこから戻ってきても正常にアニメーションする

## スクリーンショット / Screenshots

![IMG_1693](https://user-images.githubusercontent.com/18320004/136494143-3a18bc2c-b279-47ec-8a7b-2293f4c4e25d.PNG)

## 動作環境 / Environments

- デバイス：iPhone 12 Pro max
- OS：iOS
- バージョン：developブランチをビルドしたもの

**Comment by keiji** [comment]
Duplicate #420
