### ISSUE TITLE
DiagnosisKeyRepositoryのテストを整備

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#487]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

`feature/cocoa2`ブランチで診断キーをサーバーから取得する役割を担う[DiagnosisKeyRepository](https://github.com/cocoa-mhlw/cocoa/blob/feature/cocoa2/Covid19Radar/Covid19Radar/Repository/DiagnosisKeyRepository.cs)に対応するテストが整備されていない。

## 解決策についてお書きください / Describe the solution you'd like

テストを整備する。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

~~テストは書かない。~~

**Comment by kazuhiro4949** [comment]
@keiji こちらやりますー

**Comment by keiji** [comment]
お願いします！

**Comment by keiji** [comment]
@kazuhiro4949 Pull Request、ぼくの方でマージしました！
