### ISSUE TITLE
[Android] 端末の言語を変更後「プライバシーポリシーの改定」が再表示される

### ISSUE THREAD

**Issue by pinterior** [cocoa-mhlw/cocoa#49]
**Describe the bug**

Android端末の言語設定が英語の場合、COCOA起動時に「プライバシーポリシーの改定」画面を経由しない

**To Reproduce**

- プライバシーポリシー改定以前から使用し、改定の確認を行っていない環境を用意する
- 端末の言語設定を「日本語 (日本)」に変更する
- COCOAを起動する
- 「プライバシーポリシーの改定」画面が表示される
- 「確認しました」をタップせずにCOCOAを強制終了する
- 端末の言語設定を「English (United Kingdom)」に変更する
- COCOAを起動する
- 「プライバシーポリシーの改定」画面が表示されずにCOCOAのホーム画面に遷移する

**Expected behavior**

端末の言語設定にかかわらず「プライバシーポリシーの改定」に相当する画面による確認を経てからCOCOAが動作する

**Smartphone (please complete the following information):**
 - Device: SH-M08
 - OS: Android 10
 - COCOA Version: 1.2.2

**Additional context**

「プライバシーポリシーの改定」画面を表示しない場合に旧プライバシーポリシーに沿った動作をしているのであれば、問題ありません。

**Comment by Meiryo7743** [comment]
Android 8.0.0 が搭載された ZenFone Live L1（ZA550KL）で「端末の表示言語」を，

1. English (United States)
2. 日本語

……という順番で設定していますが，COCOA **v1.2.1** ではプライバシーポリシー改定画面が表示されていたことを確かに記憶しています。内容は英語で書かれていました。

「端末の言語」において「日本語」が（順序関係なしに）指定されているかどうかで改定画面を表示する可能性が変わるのか，もしくは **v1.2.2** から現れ始めた症状なのか……どうなんでしょうかね。

**Comment by pinterior** [comment]
ログを確認してみました。
ログから察すると改定を確認したことがあったようですが、それを失念していたようです。

日本語設定でエラーが発生しているのは、日時の文字列での保存・解釈がロケール依存になっているせいでしょうか。
他に`DateTime`型を使っている設定項目には`StartDateTime`(使用開始日時)があり、ちょっと心配になります。
https://github.com/cocoa-mhlw/cocoa/blob/047b12bfc497e5e32bd96e24c2b5d76c8ca18bcf/Covid19Radar/Covid19Radar/Services/TermsUpdateService.cs#L127-L131
https://github.com/cocoa-mhlw/cocoa/blob/047b12bfc497e5e32bd96e24c2b5d76c8ca18bcf/Covid19Radar/Covid19Radar.Android/Services/PreferencesService.cs#L61-L64
https://github.com/cocoa-mhlw/cocoa/blob/047b12bfc497e5e32bd96e24c2b5d76c8ca18bcf/Covid19Radar/Covid19Radar.Android/Services/PreferencesService.cs#L117-L120

- 英語でプライバシーポリシー改定画面が表示されない時
```
"2021/03/08 22:38:13","Info","Start","IsReAgree","/Users/runner/work/1/s/Covid19Radar/Covid19Radar/Services/TermsUpdateService.cs","104","Android","10","SH-M08","Physical","1.2.2","1612855445"
"2021/03/08 22:38:13","Info","Start","GetValue","/Users/runner/work/1/s/Covid19Radar/Covid19Radar.Android/Services/PreferencesService.cs","27","Android","10","SH-M08","Physical","1.2.2","1612855445"
"2021/03/08 22:38:13","Info","key=PrivacyPolicyLastUpdateDateTime, type=System.DateTime","GetValue","/Users/runner/work/1/s/Covid19Radar/Covid19Radar.Android/Services/PreferencesService.cs","28","Android","10","SH-M08","Physical","1.2.2","1612855445"
"2021/03/08 22:38:13","Info","End","GetValue","/Users/runner/work/1/s/Covid19Radar/Covid19Radar.Android/Services/PreferencesService.cs","71","Android","10","SH-M08","Physical","1.2.2","1612855445"
"2021/03/08 22:38:13","Info","termsType: PrivacyPolicy, lastUpdateDate: 15/12/2020 13:00:00, info.UpdateDateTime: 15/12/2020 13:00:00","IsReAgree","/Users/runner/work/1/s/Covid19Radar/Covid19Radar/Services/TermsUpdateService.cs","133","Android","10","SH-M08","Physical","1.2.2","1612855445"
"2021/03/08 22:38:13","Info","End","IsReAgree","/Users/runner/work/1/s/Covid19Radar/Covid19Radar/Services/TermsUpdateService.cs","134","Android","10","SH-M08","Physical","1.2.2","1612855445"
"2021/03/08 22:38:13","Info","Transition to HomePage","OnNavigatedTo","/Users/runner/work/1/s/Covid19Radar/Covid19Radar/ViewModels/HomePage/SplashPageViewModel.cs","56","Android","10","SH-M08","Physical","1.2.2","1612855445"
```

- 日本語設定でプライバシーポリシーの改定画面が表示されるとき
```
"2021/03/08 22:37:05","Info","Start","IsReAgree","/Users/runner/work/1/s/Covid19Radar/Covid19Radar/Services/TermsUpdateService.cs","104","Android","10","SH-M08","Physical","1.2.2","1612855445"
"2021/03/08 22:37:05","Info","Start","GetValue","/Users/runner/work/1/s/Covid19Radar/Covid19Radar.Android/Services/PreferencesService.cs","27","Android","10","SH-M08","Physical","1.2.2","1612855445"
"2021/03/08 22:37:05","Info","key=PrivacyPolicyLastUpdateDateTime, type=System.DateTime","GetValue","/Users/runner/work/1/s/Covid19Radar/Covid19Radar.Android/Services/PreferencesService.cs","28","Android","10","SH-M08","Physical","1.2.2","1612855445"
"2021/03/08 22:37:05","Error","Failed to get value of PrivacyPolicyLastUpdateDateTime","GetValue","/Users/runner/work/1/s/Covid19Radar/Covid19Radar.Android/Services/PreferencesService.cs","76","Android","10","SH-M08","Physical","1.2.2","1612855445"
"2021/03/08 22:37:05","Info","End","GetValue","/Users/runner/work/1/s/Covid19Radar/Covid19Radar.Android/Services/PreferencesService.cs","77","Android","10","SH-M08","Physical","1.2.2","1612855445"
"2021/03/08 22:37:05","Info","termsType: PrivacyPolicy, lastUpdateDate: 0001/01/01 0:00:00, info.UpdateDateTime: 2020/12/15 13:00:00","IsReAgree","/Users/runner/work/1/s/Covid19Radar/Covid19Radar/Services/TermsUpdateService.cs","133","Android","10","SH-M08","Physical","1.2.2","1612855445"
"2021/03/08 22:37:05","Info","End","IsReAgree","/Users/runner/work/1/s/Covid19Radar/Covid19Radar/Services/TermsUpdateService.cs","134","Android","10","SH-M08","Physical","1.2.2","1612855445"
"2021/03/08 22:37:05","Info","Transition to ReAgreePrivacyPolicyPage","OnNavigatedTo","/Users/runner/work/1/s/Covid19Radar/Covid19Radar/ViewModels/HomePage/SplashPageViewModel.cs","51","Android","10","SH-M08","Physical","1.2.2","1612855445"
```

**Comment by keiji** [comment]
Android端末（Google Pixel 3 / API Level 30）の言語設定「日本語（日本）」と「English (United Kingdom)」それぞれで`new DateTime().ToString()`の結果を見てみました。
結果は、どちらの場合も`0001/01/01 0:00:00`で、`DateTime.Parse`も問題なく行われていますね 🤔 

ログの出ているところは例外をcatchしている箇所なので、例外の具体的な種類を知れば、もう少し調査が進みそうです。

> プライバシーポリシー改定以前から使用し、改定の確認を行っていない環境を用意する

これけっこう難しそうなんですが、どんな風に用意するといいでしょうか（直接Preferenceに書き込んだり？）。

**Comment by b-wind** [comment]
本日時点でののプライバシーポリシー確認用URLです。

https://covid19radarjpnprod.z11.web.core.windows.net/ja/terms_update.json
```json
{
    "privacy_policy" : {
        "text" : "感染可能期間に陽性者と接触した可能性のある方にのみ通知するよう、アップデートしました。\n　・陽性者が発症日又は検査日を入力\n　・その約２日前以降に接触の可能性のある利用者に通知\n\nこれにともない、プライバシーポリシーを改定しています。\n改定内容を下記リンクからご確認ください。",
        "update_date" : "2020/12/15 13:00:00"
    }
}
```

**Comment by b-wind** [comment]
> これけっこう難しそうなんですが、どんな風に用意するといいでしょうか（直接Preferenceに書き込んだり？）。

@keiji 開発マシンのhosts弄ってlocalhost見に行かせたり、デバッグ用Proxyとか用意すると楽かもです。

**Comment by b-wind** [comment]
例外を拾ってるのはこのあたりのようですが、種類はログには出してないですね。

https://github.com/cocoa-mhlw/cocoa/blob/047b12bfc497e5e32bd96e24c2b5d76c8ca18bcf/Covid19Radar/Covid19Radar.Android/Services/PreferencesService.cs#L61-L79

**Comment by pinterior** [comment]
> Android端末（Google Pixel 3 / API Level 30）の言語設定「日本語（日本）」と「English (United Kingdom)」それぞれで`new DateTime().ToString()`の結果を見てみました。
> 結果は、どちらの場合も`0001/01/01 0:00:00`で、`DateTime.Parse`も問題なく行われていますね 🤔

adb backup が効いたので確認してみると、apps/jp.go.mhlw.covid19radar/sp/jp.go.mhlw.covid19radar.xml に保存されていた内容は以下の通りでした。dd/mm/yyyyフォーマットになっています。
```xml
    <string name="PrivacyPolicyLastUpdateDateTime">15/12/2020 13:00:00</string>
```


また、手元の端末(SH-M08)ではログの一部にも出力されている通り、English (United Kingdom)環境の`DateTime#ToString()`はdd/mm/yyyyであるようです。一旦COCOAアプリのデータを削除し、再度利用開始操作を行ったときも、やはり以下のように dd/mm/yyyy フォーマットで記録されていました。(現在日時が保存されていることにはやや疑問がありますが)
```xml
    <string name="PrivacyPolicyLastUpdateDateTime">09/03/2021 03:12:00</string>
```

この状態から日本語設定に切り替えて起動すれば「プライバシーポリシーの改定」画面が再度表示されると思ったのですが、
"09/03/2021"は日本語環境では今年の9月3日にパースされる(?)ようで、うまく再現はしません。


もともとの現象とは真逆の問題(確認画面が出ないことが問題なのではなく、再度出ることが問題)であるなど
こちらで継続するのは不適切かとも思うので、このIssueは一旦クローズしたいと思います。
問題の整理と容易な再現手順を用意後、(そのときにPreferenceServiceのDateTime保存方法に変更が入っていなければ)再度新たなIssueとして立てたいと思います。
ご協力ありがとうございました。

**Comment by b-wind** [comment]
少なくとも言語設定に寄ってデータの保存フォーマットが変わってしまうのはバグで有るように思います。

**Comment by pinterior** [comment]
おおもとの原因(端末・設定によってはフォーマットが変わってしまう点)を主題にするのが伝わりやすそうですね。

**Comment by b-wind** [comment]
初回同意時は今日の日付になる実装です。


今日の日付が９月３日と解釈されうるなら、その後日本語（日本）のまま使い続けると９月までのプライバシーポリシーの更新はすべて無視されることになりそうですね。

**Comment by keiji** [comment]
すみません。日付フォーマットが異なる件、こちらでも再現しました。
LocaleのCountryを「United Kingdom」にすると日付も「01/01/0001 00:00:00」になりますね。

**Comment by b-wind** [comment]
今朝取れたピチピチのスクショです。
![image](https://user-images.githubusercontent.com/144311/110423954-53feb680-80e5-11eb-9778-68dd449b9604.png)

**Comment by b-wind** [comment]
（画像がデカくて済みません）

先ほど再度取り直して貰いました。

UK での初回初回同意後の画面
![image](https://user-images.githubusercontent.com/144311/110424202-c1aae280-80e5-11eb-9f71-1fafc0c2c420.png)

JP での画面（再同意画面は表示されない）
![image](https://user-images.githubusercontent.com/144311/110424327-f9b22580-80e5-11eb-8dee-a51f37a14296.png)

念の為言語設定
![image](https://user-images.githubusercontent.com/144311/110424373-09ca0500-80e6-11eb-8105-1e757e670a69.png)

**Comment by pinterior** [comment]
> 初回同意時は今日の日付になる実装です。

(off-topicですが)表示されてから同意するまでのタイムラグに新しいプライバシーポリシーがデプロイされた時のことが気になったので、この動作について「やや疑問がある」としました。

**Comment by zipperpull** [comment]
もっとシンプルな別解があって、ただ今から再現させるのはちょっと面倒なのですが、

1. 2020/12/15 以前に初回起動・初期設定完了済みとする
2. GB ロケールに切り替えて、2020/12/15 以降にプライバシーポリシー再同意画面で同意する。この時点で PrivacyPolicyLastUpdateDateTime が "15/12/2020" になる
3. JP ロケールに切り替えて、COCOA 起動すると、同様に DateTime の Parse に失敗してプライバシーポリシー再同意画面が表示される(以下は上記 https://github.com/cocoa-mhlw/cocoa/issues/49#issuecomment-793660409 の 7. 以下と同様)

こういうパターンもありうるかもしれません。。

**Comment by Guest126** [comment]
上記のログの中で

> "2021/03/08 22:38:13","Info","termsType: PrivacyPolicy, lastUpdateDate: 15/12/2020 13:00:00, info.UpdateDateTime: 15/12/2020 13:00:00","IsReAgree","/Users/runner/work/1/s/Covid19Radar/Covid19Radar/Services

とあり、`lastUpdateDate: 15/12/2020 13:00:00` の部分からログの上では改定に同意していることが伺えるため、別解パターンが正解で、「改定の確認を行っていない環境」というのが誤認であることも含めての close だと考えます。

**Comment by Guest126** [comment]
> ただ今から再現させるのはちょっと面倒なのですが、

これについては上の方でプロキシを利用する方法が挙げられていましたが、当方では Android の SharedPreferences (/data/data/jp.go.mhlw.covid19radar/shared_prefs/jp.go.mhlw.covid19radar.xml) を rooted 環境で編集・保存することで再現を確認しています (non-root ならば Debug ビルドでも可) 。

**Comment by zipperpull** [comment]
@Guest126 さん

ありがとうございます。見落としていましたがもろもろ納得してすっきりしました。
