### ISSUE TITLE
お問い合わせメールにAPPデバイス情報とアプリバージョンを記載

### ISSUE THREAD

**Issue by takish** [cocoa-mhlw/cocoa#5]
**Is your feature request related to a problem? Please describe.**
不具合対応を行う際に、どの機種でどのOSでどのバージョンで不具合が発生しているかを切り分けるためにiOSかAndroidかなどOSの情報とアプリのバージョンをデフォルトで付与できるようにしたい。

**Describe the solution you'd like**
InqueryPageViewModelのBodyの本文の前に差し込まれるようにしたい

**Describe alternatives you've considered**
GMSに対応していない機種などもあるので、そのあたりの方からのお問い合わせが発生したときにシステムの不具合なのか、仕様上仕方がないことなのかに切り分ける必要がある。

**Additional context**
- 現状
<img width="300" alt="スクリーンショット1" src="https://user-images.githubusercontent.com/35608/92074323-c1592400-edf0-11ea-8e81-8c22877f2841.jpg">

- 追加したいもの
以下の例のように本文との間に環境情報を追加する
<img width="300" alt="スクリーンショット2" src="https://user-images.githubusercontent.com/35608/92074333-c74f0500-edf0-11ea-8abb-275cc30e0651.jpg">

**Comment by heykuro** [comment]
@takish さん、遅くなりましたがPRもいただきありがとうございます。

いただいたご指摘も踏まえ、v1.2.0にて動作情報送信時にデバイス情報、アプリバージョンを取得するようにしました。
