### ISSUE TITLE
COCOA v1.4.0 が起動しない

### ISSUE THREAD

**Issue by b-wind** [cocoa-mhlw/cocoa#517]
## 不具合の内容 / Describe the bug

先ほど App Store / Play Store にリリースされた v1.4.0 をインストールすると起動直後にエラーで落ちている様に見えます。

## 再現手順 / Steps to reproduce

1.  COCOA を起動する

## 期待される挙動 / Expected behavior

1. COCOA が正常に起動する。

## 動作環境 / Environments

- デバイス： iPhone SE 2nd, Galaxy S9
- OS：iOS 14.8.1 / Android 10
- バージョン：1.4.0

## その他 / Additional context

即死するので何も分からない。
Android 版もほぼ同様（一瞬 Splashscreen は出る ）

関係あるかどうか分かりませんが、一応既存バージョンからのバージョンアップです

----
Internal IDs:
- Bug 4663

**Comment by keiji** [comment]
Android版でも発生しているという情報がありますね。
すぐに調査します。

**Comment by anatawa12** [comment]
参考までにしかならないかと思いますが、クラッシュレポートです[Covid19Radar.iOS-2021-11-25-162951.zip](https://github.com/cocoa-mhlw/cocoa/files/7601114/Covid19Radar.iOS-2021-11-25-162951.zip)

**Comment by keiji** [comment]
現在、情報収集中です。Google Play ConsoleのAndroid Vitalsでは目立ってクラッシュが増えているようなデータは見当たっていません。ただ、SNS等で報告されている件数を考えると不具合は確実に起こっています。

まず最初にすべきことはクラッシュレポート（エラーログ）の確認です。これはぼくの手元の端末で発生していないので、不具合が今まさに起こっている人・端末から取得することになります（ @anatawa12 さんありがとうございます！）。

@kazuhiro4949 
iOS版のエラーログの確認、可能であればお願いできますか？

引き続き、開発チームとも連携して状況を確認していきます。

**Comment by keiji** [comment]
![2021-11-25](https://user-images.githubusercontent.com/932136/143403796-dc2ab16b-3d11-4504-b38b-bfbe4632e8bf.png)

**Comment by keiji** [comment]
原因らしきものがわかったので確認と修正作業に入ります。

おそらく現在バージョンの保存されているDateTime.ToString()の値が想定と違って、それを日付にパースし直すときにエラーが発生している。
端末か、ロケール等の設定に依存しているかは不明。

**Comment by keiji** [comment]
現時点で考えられる原因。

https://github.com/cocoa-mhlw/cocoa/blob/31c3481b27a3581255a83713b27bec422ca77a7f/Covid19Radar/Covid19Radar/Services/Migration/Migrator_1_3_0.cs#L65-L69

DateTime.Parseで取得したDateTimeはKindがUnspecifiedになるので、そのままdifferentialと計算できない。これは括弧の位置が違う。

本来はこうあるべき？

```
            try
            {
                dateTime = DateTime.SpecifyKind(DateTime.Parse(dateTimeStr), DateTimeKind.Utc) + differential;
            }
            catch (FormatException exception)
            {
                _loggerService.Exception($"Parse dateTime FormatException occurred. {dateTimeStr}", exception);
                dateTime = DateTime.UtcNow;
            }
```

この推測が正しいか、これから確認する。

**Comment by jmatsu** [comment]
@keiji 
↓で詰め込んでる `new DateTime()` だと DateTime.MinValue になるので、MinValue/MaxValue に加算減算が定義されていない、という仕様のようです。現在時刻が欲しいなら DateTime.Now にならないといけなさそうです。
https://github.com/cocoa-mhlw/cocoa/blob/60e00c701c5778c86a1931033b6158ed9d06090a/Covid19Radar/Covid19Radar/Services/Migration/Migrator_1_2_2.cs#L169

https://ideone.com/XJiYnM

<details>
<summary>Android11, Pixel3 XL, en_US, JST +9 の LogCat</summary>
11-25 16:48:32.645 24127 24127 D AndroidRuntime: Shutting down VM
11-25 16:48:32.646 24127 24127 E AndroidRuntime: FATAL EXCEPTION: main
11-25 16:48:32.646 24127 24127 E AndroidRuntime: Process: jp.go.mhlw.covid19radar, PID: 24127
11-25 16:48:32.646 24127 24127 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.ArgumentOutOfRangeException: The added or subtracted value results in an un-representable DateTime.
11-25 16:48:32.646 24127 24127 E AndroidRuntime: Parameter name: t
11-25 16:48:32.646 24127 24127 E AndroidRuntime:   at System.DateTime.op_Addition (System.DateTime d, System.TimeSpan t) [0x00024] in <bb489c88ab8346089eb86c81637acf15>:0
11-25 16:48:32.646 24127 24127 E AndroidRuntime:   at Covid19Radar.Services.Migration.Migrator_1_3_0.MigrateDateTimeToEpoch (System.String dateTimeKey, System.String epochKey, System.TimeSpan differential) [0x00020] in <c71ab29977b04539bf5d8a757ad7a472>:0
11-25 16:48:32.646 24127 24127 E AndroidRuntime:   at Covid19Radar.Services.Migration.Migrator_1_3_0.ExecuteAsync () [0x0004f] in <c71ab29977b04539bf5d8a757ad7a472>:0
11-25 16:48:32.646 24127 24127 E AndroidRuntime:   at Covid19Radar.Services.Migration.MigrationService.MigrateAsync (System.Version fromVersion) [0x0037e] in <c71ab29977b04539bf5d8a757ad7a472>:0
11-25 16:48:32.646 24127 24127 E AndroidRuntime:   at Covid19Radar.Services.Migration.MigrationService.MigrateAsync () [0x0010f] in <c71ab29977b04539bf5d8a757ad7a472>:0
11-25 16:48:32.646 24127 24127 E AndroidRuntime:   at Covid19Radar.ViewModels.SplashPageViewModel.OnNavigatedTo (Prism.Navigation.INavigationParameters parameters) [0x000b0] in <c71ab29977b04539bf5d8a757ad7a472>:0
11-25 16:48:32.646 24127 24127 E AndroidRuntime:   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <bb489c88ab8346089eb86c81637acf15>:0
11-25 16:48:32.646 24127 24127 E AndroidRuntime:   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <d3481191eb704303b66d8560a733b9c4>:0
11-25 16:48:32.646 24127 24127 E AndroidRuntime:   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <d3481191eb704303b66d8560a733b9c4>:0
11-25 16:48:32.646 24127 24127 E AndroidRuntime:   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <d3481191eb704303b66d8560a733b9c4>:0
11-25 16:48:32.646 24127 24127 E AndroidRuntime:   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.43(intptr,intptr)
11-25 16:48:32.646 24127 24127 E AndroidRuntime:        at mono.java.lang.RunnableImplementor.n_run(Native Method)
11-25 16:48:32.646 24127 24127 E AndroidRuntime:        at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
11-25 16:48:32.646 24127 24127 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
11-25 16:48:32.646 24127 24127 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
11-25 16:48:32.646 24127 24127 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
11-25 16:48:32.646 24127 24127 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7664)
11-25 16:48:32.646 24127 24127 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-25 16:48:32.646 24127 24127 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-25 16:48:32.646 24127 24127 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
11-25 16:48:32.651 24127 24127 I MonoDroid: UNHANDLED EXCEPTION:
11-25 16:48:32.653 24127 24127 I MonoDroid: Android.Runtime.JavaProxyThrowable: Exception of type 'Android.Runtime.JavaProxyThrowable' was thrown.
11-25 16:48:32.653 24127 24127 I MonoDroid:   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
11-25 16:48:32.653 24127 24127 I MonoDroid: android.runtime.JavaProxyThrowable: System.ArgumentOutOfRangeException: The added or subtracted value results in an un-representable DateTime.
11-25 16:48:32.653 24127 24127 I MonoDroid: Parameter name: t
11-25 16:48:32.653 24127 24127 I MonoDroid:   at System.DateTime.op_Addition (System.DateTime d, System.TimeSpan t) [0x00024] in <bb489c88ab8346089eb86c81637acf15>:0
11-25 16:48:32.653 24127 24127 I MonoDroid:   at Covid19Radar.Services.Migration.Migrator_1_3_0.MigrateDateTimeToEpoch (System.String dateTimeKey, System.String epochKey, System.TimeSpan differential) [0x00020] in <c71ab29977b04539bf5d8a757ad7a472>:0
11-25 16:48:32.653 24127 24127 I MonoDroid:   at Covid19Radar.Services.Migration.Migrator_1_3_0.ExecuteAsync () [0x0004f] in <c71ab29977b04539bf5d8a757ad7a472>:0
11-25 16:48:32.653 24127 24127 I MonoDroid:   at Covid19Radar.Services.Migration.MigrationService.MigrateAsync (System.Version fromVersion) [0x0037e] in <c71ab29977b04539bf5d8a757ad7a472>:0
11-25 16:48:32.653 24127 24127 I MonoDroid:   at Covid19Radar.Services.Migration.MigrationService.MigrateAsync () [0x0010f] in <c71ab29977b04539bf5d8a757ad7a472>:0
11-25 16:48:32.653 24127 24127 I MonoDroid:   at Covid19Radar.ViewModels.SplashPageViewModel.OnNavigatedTo (Prism.Navigation.INavigationParameters parameters) [0x000b0] in <c71ab29977b04539bf5d8a757ad7a472>:0
11-25 16:48:32.653 24127 24127 I MonoDroid:   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <bb489c88ab8346089eb86c81637acf15>:0
11-25 16:48:32.653 24127 24127 I MonoDroid:   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <d3481191eb704303b66d8560a733b9c4>:0
11-25 16:48:32.653 24127 24127 I MonoDroid:   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <d3481191eb704303b66d8560a733b9c4>:0
11-25 16:48:32.653 24127 24127 I MonoDroid:   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <d3481191eb704303b66d8560a733b9c4>:0
11-25 16:48:32.653 24127 24127 I MonoDroid:   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.43(intptr,intptr)
11-25 16:48:32.653 24127 24127 I MonoDroid:     at mono.java.lang.RunnableImplementor.n_run(Native Method)
11-25 16:48:32.653 24127 24127 I MonoDroid:     at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
11-25 16:48:32.653 24127 24127 I MonoDroid:     at android.os.Handler.handleCallback(Handler.java:938)
11-25 16:48:32.653 24127 24127 I MonoDroid:     at android.os.Handler.dispatchMessage(Handler.java:99)
11-25 16:48:32.653 24127 24127 I MonoDroid:     at android.os.Looper.loop(Looper.java:223)
11-25 16:48:32.653 24127 24127 I MonoDroid:     at android.app.ActivityThread.main(ActivityThread.java:7664)
11-25 16:48:32.653 24127 24127 I MonoDroid:     at java.lang.reflect.Method.invoke(Native Method)
11-25 16:48:32.653 24127 24127 I MonoDroid:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-25 16:48:32.653 24127 24127 I MonoDroid:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
11-25 16:48:32.653 24127 24127 I MonoDroid:
</details>

**Comment by keiji** [comment]
@jmatsu ありがとうございます。
そちらも合わせて確認します！

**Comment by kazuhiro4949** [comment]
@anatawa12 クラッシュログありがとうございます

**Comment by keiji** [comment]
手元でも再現したので、いくつかのパターンで修正案を検討中です。

@jmatsu
現在時刻にしてしまうと、利用規約とプライバシーポリシーに同意したことになってしまうのでよろしくないので、別のアプローチからの修正を検討中です。

**Comment by keiji** [comment]
`DateTime()`は`0001/01/01 0:00:00`で、そこからさらに9時間を引こうとしているので怒られている。

DateTime.MinValueと同値であれば引かないようにとか考えたけど、DateTime.MinValueと同値ではない`0001/01/01 0:08:00`から9時間引こうとするとやっぱり落ちるよねと。

先行きは見えてきたので、修正方法を決めます。

**Comment by keiji** [comment]
ホットフィックスのリリース準備を開発チームが進めています。

**Comment by keiji** [comment]
不具合の原因完全に理解した

**Comment by keiji** [comment]
ホットフィックス版（v1.4.1）のテストを終え、App Store, Google Play Storeへの提出を完了しました。

**Comment by keiji** [comment]
「完全に理解した」で終わるのは良くないので、調べたことをつらつらと記録します。
あくまでぼく個人の調査結果（見解）であり、GitHubにいる技術者に向けて技術的なコミュニケーションを行うために発信する内容です。
公式な発表ではありませんので、くれぐれも注意してください。

----

今回の不具合の根本的な原因は、率直に言えば、ぼくがマイグレーション処理が必要なタイミングを誤解していたという一点に集約します。

## マイグレーションが必要なタイミングについて
これまでの調査でぼくは、設定ファイルの形式に変更が加わったのはv1.2.2, v1.2.6 そしてv1.3.0（v1.4.0として配信）の「3つのタイミング」だと考えていました。

参考：設定ファイルの仕様
https://cocoa-mhlw.github.io/cocoa/docs/appendix/preference_specification/

しかし調査を進めると、v1.1.5からv1.2.0のタイミングでもApplication.Propertiesの仕様変更が行われていることが判明しました。
設定ファイルの形式に変更が加わったのは v1.2.0, v1.2.2, v1.2.6 そしてv1.3.0（v1.4.0として配信）の **「4つのタイミング」** でした。

具体的には、v1.2.0のタイミングで、[Covid19Radar/Covid19Radar/Services/TermsUpdateService.cs
](https://github.com/cocoa-mhlw/cocoa/commit/cc7ca40d6de6214d9a9078a36ba667f03b588434#diff-c5c0b0da9099aaa72756f80fccedd036090534ca8fc20482b66b9a8f21fa51e9)のなかでApplication.Propertiesに`TermsOfServiceLastUpdateDateTime `と`PrivacyPolicyLastUpdateDateTime`の2つの項目が追加されています。

この2つのキーは、読んで字のごとく利用規約と、プライバシーポリシーに合意した日時を記録しています。
v1.2.0より前のバージョンではこれら2つの情報は存在せず、合意したという事実を`IsOptined`と`IsPolicyAccepted`いうキーでそれぞれ保存していました。

https://github.com/cocoa-mhlw/cocoa/blob/142c70fee113e6086660040e260fe4dca2639985/Covid19Radar/Covid19Radar/Model/UserDataModel.cs#L83-L85

1.2.0でプライバシーポリシーへの再合意が必要になったことから、新しく日時を保存する仕組みを追加したものと考えます。

## なぜv1.2.0の変更に気づかなかったのか。

ぼくの不注意と言ってしまえばそれでおしまいなのですが、ぼくがマイグレーション処理を開発する際にデータの形式変更が発生した最初のタイミングと誤解していた`v1.2.2`のマイグレーション処理を参考にしたことが原因です。

v1.2.2のマイグレーション処理は、Application.Propertiesが複数スレッドからの同時アクセスで壊れる問題を回避するために、プラットフォーム固有のProperties形式に移行する目的で開発されました。

https://github.com/cocoa-mhlw/cocoa/blob/e106594fb8359f79f3fdb19cac4f26b800245f8f/Covid19Radar/Covid19Radar/Services/TermsUpdateService.cs#L47-L75

v1.4.0のマイグレーション処理（不具合の原因になったもの）についても、v1.2.2の内容とおおむね同じ処理をしています。

ぼくが考え違いをしていたのは、この処理の中で「applicationPropertyServiceに指定したキーがなかったときに`new DateTime()`を設定しておく」という処理がが、めったに発生しないと考えていたことです。

しかし、実際にはv1.1.5からv1.2.0を経由せず直接1.2.2にアップデートするとここを通ります。その場合、Application.Propertiesには`TermsOfServiceLastUpdateDateTime`と`PrivacyPolicyLastUpdateDateTime`のキーは存在しないからです。

つまり、v1.1.5以前のバージョンからv1.2.2以降のバージョンにアップデートしてこのマイグレーション処理が実行されると、`TermsOfServiceLastUpdateDateTime`と`PrivacyPolicyLastUpdateDateTime`には`new Date()`の値が記録されます。

[v1.1.5で起動した後v1.2.6にアップデートしてた直後のPreferenceファイル（Android）](https://github.com/cocoa-mhlw/cocoa/files/7603956/APP_PACKAGE_NAME.APP_PACKAGE_NAME.xml.txt)

この状態でv1.4.0のマイグレーション処理を通ると、今回の不具合が発生します。

## なぜv1.2.2からv1.2.6までで顕在化しなかったか

前述の通り、v1.2.2からv1.2.6でも`TermsOfServiceLastUpdateDateTime`と`PrivacyPolicyLastUpdateDateTime`の値に`new Date()`が設定される現象は発生していました。

しかし、v1.1.5から一度はプライバシーポリシーの改訂が行われているので、利用者がv1.1.5からv1.2.2からv1.2.6のいずれかのバージョンにアップデートした後、COCOAを起動すると、プライバシーポリシーの再同意画面が表示されます。利用者が新しいプライバシーポリシーに再同意するタイミングで`PrivacyPolicyLastUpdateDateTime`の値は正しい値となるため、問題になっていませんでした（new Date()の値であっても問題なく比較はできます）。

しかし、`TermsOfServiceLastUpdateDateTime`については再同意プロセスがないので、マイグレーション時に`new Date()`と記録されたまま更新されることなく眠り続けました。それが今回のv1.4.0のマイグレーション処理で問題となって顕在化したと考えています。

https://github.com/cocoa-mhlw/cocoa/blob/e66e79062a6494b3302108b2df71f719e80b05f5/Covid19Radar/Covid19Radar/Services/Migration/Migrator_1_3_0.cs#L60-L76

----

本件に関する技術的なまとめは以上です。ここからはホットフィックスの配信状況と、不具合の早期発見と対応、どうしたら今回のような出来事を防げたか。二度と同じ間違いをしないためにどうしたらいいかを考えていきます。

何か疑問、質問等あればコメントしてください。技術的な内容であれば可能な限りお答えします。

**Comment by b-wind** [comment]
> しかし、実際にはv1.1.5からv1.2.0を経由せず直接1.2.2にアップデートするとここを通ります。

記憶が正しければ私の手元ではファーストリリースからすべてのバージョンを順に適用してきた iPhone 環境で今回の現象が発生した。と言う認識です。
そう言う心づもりで記録等取っていたわけでは無いので記憶違いかも知れません。

**Comment by keiji** [comment]
@b-wind 
ありがとうございます。v1.2.0を経由するケースでも`TermsOfServiceLastUpdateDateTime`は作成されないことを追記しました！

**Comment by keiji** [comment]
iOS版について審査を通過し、v1.4.1を公開しました。

**Comment by daisuke-nogami** [comment]
実機とWebページ上でもv.1.4.1の公開表示がされていることを確認しました。
https://apps.apple.com/jp/app/cocoa-%E6%96%B0%E5%9E%8B%E3%82%B3%E3%83%AD%E3%83%8A%E3%82%A6%E3%82%A4%E3%83%AB%E3%82%B9%E6%8E%A5%E8%A7%A6%E7%A2%BA%E8%AA%8D%E3%82%A2%E3%83%97%E3%83%AA/id1516764458

**Comment by b-wind** [comment]
@daisuke-nogami ご連絡ありがとうございます。


手元の環境（実機）でアップデートしてみたところ、問題無く起動できました。

**Comment by hayashida-katsutoshi** [comment]
もしかしてUTCとローカル時間の変換をハードコードされているのでしょうか？　標準の変換関数を使わない理由があるのでしょうか？　アメリカや中国で同意した人は、違う時間が記録されてしまうのではないでしょうか？　標準関数を使えば時差とか勝手に吸収してくれます。

**Comment by anatawa12** [comment]
クラッシュレポートを生成した端末にてv1.4.1にて正しく起動することを確認できました。対応お疲れ様でした

**Comment by keiji** [comment]
@hayashida-katsutoshi ありがとうございます。もちろんユースケースさえ合えば標準の変換関数を使うことが第１選択肢なので詳しく教えてください。

今回の場合、次のような仕様のデータを取り扱う必要があります（[詳細](https://cocoa-mhlw.github.io/cocoa/docs/appendix/preference_specification/#ipreferencesservice-1)）。

 * 使用開始日や規約への合意日時が文字列型で保存されている
 * 日時を表す文字列にタイムゾーンが指定されていない
 * 使用開始日はUTCとして保存されているが、規約合意日時は日本標準時（JST）

ご指摘の通り、DateTimeを文字列への変換はロケールに依存しています。たとえばGBロケールでCOCOAを使用開始すると、DateTimeはGBロケールのフォーマットで文字列に変換されます。その結果を日本ロケールで読み込もうとすると日時の形式が違うのでパースできずエラーになったり（ https://github.com/cocoa-mhlw/cocoa/issues/124 ）、他のロケールでは月と日が入れ替わった状態で日時に変換されるという問題を抱えていました。

今回のマイグレーション処理では、文字列で示される日時をすべてUNIX Epoxhに変換することにしました。ご指摘の箇所になりますが、文字列型をDateTimeでパースした後、UTCとして取り扱った上で想定される時差分を加減算するという処理をしています。

https://github.com/cocoa-mhlw/cocoa/blob/0b3f7ede8bca1706e057f86292c1b03ba15b8558/Covid19Radar/Covid19Radar/Services/Migration/Migrator_1_3_0.cs

使用開始日（UTC）と規約合意日時（JST）を同じ変換メソッドで取り扱う都合から、引数として時差を指定して計算すれば一番シンプルに作れるだろうという選択をした結果、このような実装を選んでいます。

## FindSystemTimeZoneByIdについて
検討の過程で、標準関数を使ったパターンとしては次の方法を試しました。

[C#] UTCからJST、JSTからUTCへ変換する
https://www.ipentec.com/document/csharp-convert-utc-jst

この記事は`TimeZoneInfo jstZoneInfo = System.TimeZoneInfo.FindSystemTimeZoneById("Tokyo Standard Time");`でタイムゾーンを取得しています。これは公式ドキュメントでも`Tokyo Standard Time`を指定しています。

TimeZoneInfo.FindSystemTimeZoneById(String) メソッド
https://docs.microsoft.com/ja-jp/dotnet/api/system.timezoneinfo.findsystemtimezonebyid?view=net-6.0

しかし、Xamarinではこのコードが動きません。TimeZoneNotFoundExceptionが発生します。
.NETでは、WindowsとLinuxでこのあたりの取り扱いが異なるようで、Xamarinの場合、Linux準拠でタイムゾーンに`Asia/Tokyo`を指定すると動きます。

.NET CoreでWindowsとLinuxでタイムゾーンを識別するID表記が異なるという話
https://tech.tanaka733.net/entry/2020/02/timezone-id

こういった調査をする中で、ロケールの違いで不具合を抱えている中で、プラットフォームごとに挙動が違う、違うかもしれない関数を使うのはリスクがあると。−9時間しておけばいいのだから、単純にTimeSpanを使った実装でいく。という判断をした次第です。

もちろん、この判断が結果的に不具合の直接の要因となったのは事実です。シンプルにまとまって、不具合が起きにくい、もっと良いやり方があれば是非とも教えてください。

コメントで教えていただくのでもいいですし、このIssueを対象にPull Requestをいただくのも歓迎です。
よろしくお願いいたします。

**Comment by keiji** [comment]
Android版はただいま審査中です。
進捗があればお知らせします。

**Comment by b-wind** [comment]
TimeZoneInfo を取得するのに、 TimeZoneInfo.FindSystemTimeZoneById() を使うしか無さそうで指摘すべきIDもOS毎に異なると言うのは私も確認しています。


言語環境内で定義せずに、OSの設定に依存しているのはのは面白いとは思いますが使い勝手としては微妙と言わざるを得ないかなと。


その他の手段で定数などとして参照出来ればそれに越した事は無いと思います。

**Comment by hayashida-katsutoshi** [comment]
私はプログラマーとして各国語対応の製品開発に長年従事していますが、スマホは担当外なので経験がなく、Xamarinを使ったこともないということをまず言っておきます。そのためXamarinについての具体的なアドバイスはできませんし、pull requestを出すつもりも申し訳ありませんがありません。

日本専用のアプリでも、国外で使われる可能性は想定された方がよいです。むしろCOCOAは国外で使われるでしょう。国外在住の日本入国者は全員、外務省からインストールを命じられます。私はアメリカに住んでいますが、日本に一時帰国する前にCOCOAを入れました。今はアメリカに戻っており、今まさにCOCOAを立ち上げて見ています。日本のロケールに依存した処理を書くのはやめた方がよいでしょう。


使用開始日と合意日時は文字列で保存せず、int64のUTCで保存するとよいです(ToInt64/FromInt64)。既にUNIX Epochに変更されたとのことですが、int64には2038年問題がありません。Xamarinで使えなかったらすみません。

入力と表示だけスマホの現在のロケールに(つまり自分でロケールを指定せずに)変換するイメージです。日時のフォーマットはロケールによって異なりますが、システムが現在のロケールに合わせてやってくれるものであり、アプリは日時の文字列を操作しないのが望ましいです。特に国際化対応の場合、タイムゾーンやサマータイムは法改正によって変わることがあり、そのたびにアプリをいちいち修正していたら大変で、OSにその責任を押し付けた方が便利です。


FindSystemTimeZoneByIdにシステム間の差異がある問題がある、ということは理解しましたが、そもそも現在のロケールがなんであるかを調べる必要がないのではないかと思われます。現在のロケールを使えばよいです。その関数を使うことも最初からなかったのではないか、というのが私の意見です。

**Comment by b-wind** [comment]
keji さんが提示している各時刻は v1.4.0 「より前のバージョン」で使用されていたデータと認識しています。
これらが幾つかの不具合の原因となっていました。

v1.4.0 以降のバージョンではロケール依存の処理は（見落としが無ければ）していないはず。
v1.4.0 より前と以降での日時データの扱いが変わる事によるマイグレーション処理にのみやむを得ずロケール依存の処理が残ってしまっているとの認識です。

この為、v1.4.1 以降を使い続ける限りはロケール依存の処理は行わないと思われます。


to: @keiji 認識に間違いがありましたらお手数ですが訂正願います。

**Comment by hayashida-katsutoshi** [comment]
なるほど、v1.4.0では対応済みで、過去データとの互換性のためにやむを得ずロケール依存の処理が残っているとのことで理解しました。

ちなみにint64への変換はToInt64ではダメで、DateTime.Ticksを使わないといけないようです。もし今後参照された方のために念のため。

**Comment by b-wind** [comment]
> 使用開始日と合意日時は文字列で保存せず、int64のUTCで保存するとよいです(ToInt64/FromInt64)。既にUNIX Epochに変更されたとのことですが、int64には2038年問題がありません。Xamarinで使えなかったらすみません。


現状UNIX Epoch の保持では C# でいう long または ulong を使用していますね。
型としては 64bit 整数なので問題無い様に思います。


> ちなみにint64への変換はToInt64ではダメで、DateTime.Ticksを使わないといけないようです。


DateTime.ToUnixEpoch と言う専用っぽいメソッドを使っています。こちらでは問題ありそうでしょうか？

**Comment by hayashida-katsutoshi** [comment]
ToUnixTimeSecondsというのは知りませんでしたが、秒以下が無視できるのであれば問題ないんじゃないでしょうか。

DateTime.Ticksを紹介したのは、32bitだと私が勘違いしていたためです。64bitであるなら問題ないです。でもTicksは簡単でいいですよ。2000年が基準ですが。

**Comment by b-wind** [comment]
当 Issue を見ている方も結構いらっしゃる様なので告知も兼ねて確認させてください。


現時点で v1.4.0 をインストールし、不具合に遭遇しているケースでもENSによる接触確認自体は各OSによって行われていると言う認識です。
これは v1.4.1 にアップグレードしなくても変わりませんが、通知は恐らく出せなくなっているしアプリ内の確認も出来ないので
アップデート可能になり次第 v1.4.1 にアップデートする事が推奨されると言う事で良いでしょうか。

**Comment by keiji** [comment]
はい。その通りです。COCOAが起動しない場合も接触確認APIのBluetoothによる受発信機能は生きています。

バックグラウンドプロセスの初手でマイグレーションをしているので、そこから先に進めていない状況です。
一方、バックグラウンドプロセスのスケジュールは行われるので、v1.4.1にアップデートした後は定期ダウンロードが診断キーのダウンロードと接触確認が実行されると考えています。

**Comment by keiji** [comment]
@b-wind @hayashida-katsutoshi 
ありがとうございます。そうですね。今回のマイグレーション完了後はUNIX Epochになるので、UTCベースの数値型で取り扱うことになります。

また今後、文字列型に変換するときはRFC3339に準拠する。タイムゾーンは原則UTCと言うことで開発チームとも調整済みです。

----
本IssueについてはAndroid版のリリースが完了して、正常動作が確認された時点でクローズする予定ですが、現時点ではあくまでホットフィックスなので、より具体的な改善策を検討するために個別のIssueを作ろうと考えています。

個別のIssueでは、タイムゾーンによる時差計算の改善や、マイグレーション処理に対するユニットテストの拡充など、いくつかのIssueを作成する予定です（多分、作業するのは土曜日になります）。

**Comment by b-wind** [comment]
本題から外れるのですが、  TimeZoneInfo.FindSystemTimeZoneById() の扱いは .NET 6 で改善されるという情報もあるようですね。


https://devblogs.microsoft.com/dotnet/date-time-and-time-zone-enhancements-in-net-6/#time-zone-conversion-apis

**Comment by keiji** [comment]
Android版は引き続き審査中です。
コンソール上ではリジェクトのような大きなイベントもなく、粛々と審査が進んでいるという状況と認識しています。

**Comment by keiji** [comment]
Android版は審査完了。先ほど開発チームが公開処理を実行しました。

**Comment by b-wind** [comment]
Play Store には反映されているようですね。
実機ではキャッシュのせいかまだ確認出来ていません。

https://play.google.com/store/apps/details?id=jp.go.mhlw.covid19radar

**Comment by b-wind** [comment]
Play Store アプリのキャッシュ削除で更新できました。

v1.4.0 で問題が出ていた実機で v1.4.1 にアップデート。問題無く起動できることを確認しました。

**Comment by keiji** [comment]
ホットフィックス版（v1.4.1）についてiOS, Android版の双方でリリースが完了し、正常動作が確認されています。
今後の正式な修正と対応については #520 に、インシデントレポートの作成については #534 に引き継ぎ、本Issueについてはクローズします。

問題の発見と解決にあたって、皆さまからのご協力に感謝します。
本当にありがとうございました。
