### ISSUE TITLE
アニメーション無効化設定時、動作状況のステータスランプの表示が乱れる

### ISSUE THREAD

**Issue by Meiryo7743** [cocoa-mhlw/cocoa#519]
## 不具合の内容 / Describe the bug

手持ちの端末で COCOA を 1.4.0 に更新したところ，表題の現象を確認しました。

## 再現手順 / Steps to reproduce

1. 端末の設定 > Developer options > Animator duration scale をオフにする。または端末の設定 > ユーザー補助からアニメーションの無効化を有効にする。
2. アプリを起動する
3. 表題の現象が認められる

アプリを起動した直後なのか，別のページ（e.g. ヘルプページ）に遷移し，再度アプリのホーム画面に戻ったのかに関係なく発生するようです。

## 期待される挙動 / Expected behavior

ステータスランプの点滅が生じないこと。

## スクリーンショット / Screenshots

※スクリーンショットではなく動画です。

https://user-images.githubusercontent.com/46659204/143421108-aced0342-7196-4c6f-b295-9816e42567b5.mp4

## 動作環境 / Environments

- デバイス：ZenFone Live L1（ZA550KL）
- OS：Android
- バージョン：8.0.0

## その他 / Additional context

修正済みである #420 に近い現象ではありますが，全く同じものなのか判断しかねましたので，新たに作成した次第です。

**追記**：端末のアニメーション設定（Animator duration scale）を無効にしていたことが原因でした（cf. https://github.com/cocoa-mhlw/cocoa/issues/519#issuecomment-979856458）。

----
Internal PBI:4837

**Comment by keiji** [comment]
ありがとうございます！
こちらも確認して対応しますね。

**Comment by b-wind** [comment]
iOS だとこんな感じに。

https://user-images.githubusercontent.com/144311/143515555-7ffd3e1a-9313-432f-8f13-967744a3f447.MOV

**Comment by Meiryo7743** [comment]
あっ……，開発者設定で端末のアニメーションをすべて無効化していたのが原因でした（記載を失念しておりました）。検証してみたところ，どうやら Animator duration scale がオフの場合，あのような挙動になるようです。

以下，Animator duration scale を有効にした状態での動作画面です。

https://user-images.githubusercontent.com/46659204/143563351-993053cb-5f48-4cd5-b42a-42fcc6824bde.mp4

---

@b-wind 

添付された動画から原因を特定できました。ありがとうございます。

**Comment by keiji** [comment]
アニメーション無効化にしているとこんな風に表示されるんですね。
勉強になります。

一瞬 won't fix かなと思ったのですが、アニメーションオフはアクセシビリティにも関わる（ #50 ）ものなので、 アニメーションオフではどう見せるかはきちんと検討しないといけませんね。

**Comment by parasite2006** [comment]
なるほど、設定切替えで動かないようにすることもできるのですね。当方5月15日にiPhoneデビューしてCOCOA v1.2.2から使い始め、今回も問題なく1.4.0にアップデートできた口ですが、緑のランプの大きさが周期的に変わるのが心臓の鼓動のように見えて可愛いのでそのままにしておこうと思います。

**Comment by Meiryo7743** [comment]
> 一瞬 won't fix かなと思ったのですが、アニメーションオフはアクセシビリティにも関わる（ #50 ）ものなので、 アニメーションオフではどう見せるかはきちんと検討しないといけませんね。
> 
> 一瞬見えてしまっているのが不具合と感じる原因だと思うので、アニメーションオフの時は外周の緑色を ~まったく表示しない~ （半分だけ表示した状態にするほうがいい？）という挙動が良さそうです。

動作中アイコンの ripple effect は，このアプリらしさを醸し出している印象を受けます。ただ，何らかの理由からアニメーションを無効にしているユーザーにはそう見えないことも事実で，おしゃる通り，不具合と受け取られる恐れがありそうです。このため，アニメーションがオフの場合，波紋エフェクトを失くすのが良いと考えます。

さらに，動作中アイコン自体を✔ 付きの ● に差し替えるのも一案でしょう。どのような経緯があったのかは存じ上げませんが，https://github.com/cocoa-mhlw/cocoa/discussions/252#discussion-3426516 で示された案から変更となっていたのですね（✔ 付きの ● → 単なる ●）。原案の方がアニメーションの設定に依存せず，また，他のステータスアイコンと調和した見た目になりそうです。もちろん，動作状況は文字情報としても表示されていますが……。

**Comment by b-wind** [comment]
（アクセシビリティの？）設定に寄って表示方法が変わるという案ですと少し混乱を招きそうだなと言う気がします。


また、ウェブアクセシビリティ方針としても不可欠でないアニメーションは推奨されないようにも読めます。


https://waic.jp/docs/UNDERSTANDING-WCAG20/time-limits-pause.html
> 読み書き能力の低い利用者、読字障害及び知的障害のある利用者、及び注意力欠如障害のある利用者などにとっては、点滅するコンテンツは残りのウェブページの利用を困難にしたり、ときには不可能にしてしまうことがある。


このような障害を持つ利用者はアニメーションをオフに設定しているのかも知れませんが、全員にそれを期待するのは少し難しいかなとも思います。


アニメーションを伴わない表現が出来るのであればそちらに合わせるのが良いように感じました。

**Comment by b-wind** [comment]
形状による表現を組み合わせるはどうかと思ったのですが（緑の○、黄色い△、赤い× 等々）、日本以外の文化圏で同じ意味に捉えられるかは怪しいですね……

**Comment by keiji** [comment]
ひとまずタイトルを調整しました！

**Comment by keiji** [comment]
本件、 5d3a2e03d65bc476be90e2ad2ab691f88f9161a7 で対応済みと言う認識です。本Issueをcloseします。

アニメーションの実行を一度だけに限定したという処置になっているのは、課題が解決できなかったというわけでは決してなく、アクセシビリティの基準の中に「5秒を超えるアニメーションは非推奨」と言うものがあり、その点に準拠するための改修と言う位置づけとなります。

何かあればreopenをお願いします。
