### ISSUE TITLE
JSTの文字列からUTCのDateTimeへの変換を安全に行う手段を検討する

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#523]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

#520 に関連する課題。

タイムゾーンが指定されていない文字列をJSTとして取り扱った上でUTCに変換する必要から、次のように、まずKindにUTCを指定してから日本との時差9時間を減算して処理をしていた。

https://github.com/cocoa-mhlw/cocoa/blob/8deb6dd9bfba528bc4b229b75b84284786ad2323/Covid19Radar/Covid19Radar/Services/Migration/Migrator_1_3_0.cs#L60-L76

しかし、v1.2.2からのマイグレーションでdateTimeに`new DateTime()`が設定されているケースが存在する。
C#の`new DateTime()`は`DateTime.MinValue`（e.g. `0001/01/01 00:00:00`）となり、これ以上減算ができないことが #517 の不具合の要因の1つとなった。

## 解決策についてお書きください / Describe the solution you'd like

Hot-fix（ #518 ）では、減算で発生する例外をcatchしている。

https://github.com/cocoa-mhlw/cocoa/blob/0b3f7ede8bca1706e057f86292c1b03ba15b8558/Covid19Radar/Covid19Radar/Services/Migration/Migrator_1_3_0.cs#L63-L89

### `SpecifyKind(dateTime, DateTimeKind.Local)`でローカル時間に指定してから`ToUniversalTime()`する

利用者が使っている端末のロケールやタイムゾーン設定がJSTである保証はない。
利用規約の合意日時についてはJSTにする必要があり、齟齬があると利用規約の再同意が延々と表示される（時差の間）など、不具合の原因になりえる。

`DateTimeKind.Local`が日本であることを明示する方法がある？（Culture/GlobalCultureを指定できる？
調査が必要。

### `FindSystemTimeZoneById`でタイムゾーンを取得して`ConvertTimeToUtc`する

Windows系とLinux系でタイムゾーンに指定する値が異なるなど挙動が一定でなく早々に候補から外したが、再検討する。

参考: https://github.com/cocoa-mhlw/cocoa/issues/517#issuecomment-979676626

### 時差の補正をEpochベースで行う

時差の補正をDateTimeで行うから例外が発生する。UNIX Epochに変換してから時差を補正すればただの数値演算として取り扱うことができる。

`DateTime.MinValue`が表す日時（ `0001/01/01 00:00:00` ）はUNIX Epochだとどうなる？　減算することで下限値を下回れば、例外こそ発生しなくても新しい不具合を生むことになる。

## その他 / Additional context

日時のデータを作成する処理は過去のバージョンのものなので、今から変更すべきではない（ #522 ）。

すでに存在するある「文字列」を安全に取り扱うにはどうやるかを検討する。

あと、引数の`differential`がtypoという[指摘](https://twitter.com/nakayoshix/status/1463866423361503239)をもらったのでこちらも対応する

タイムゾーン変換の処理は利用規約が更新されているかを判定されている部分にもある。
変換手段の検討が終わったら、忘れずに変更する。

**Comment by b-wind** [comment]
> DateTimeKind.Localが日本であることを明示する方法がある？（Culture/GlobalCultureを指定できる？
調査が必要。


以前からたまに調べてはみていますが、 CultureInfo.CurrentCulture など、現在のCultureを指定したりすることは出来ますが JST を表す CultureInfo を取得する方法が標準では環境依存という認識です。

**Comment by RabbitProgram** [comment]
> DateTime.MinValueが表す日時（ 0001/01/01 00:00:00 ）はUNIX Epochだとどうなる？
これについてですが、UNIX Epochは`1970/1/1 00:00:00`からの経過秒数を表したものであるため、`DateTime.MinValue`の値はUNIX Epochで表現することはできません。
おっしゃる通りで、また例外が発生してしまう危険性があります。
参考：https://ja.wikipedia.org/wiki/UNIX%E6%99%82%E9%96%93

**Comment by b-wind** [comment]
> FindSystemTimeZoneByIdでタイムゾーンを取得してConvertTimeToUtcする


TimeZoneConverter というライブラリはあるようですね。

https://github.com/mattjohnsonpint/TimeZoneConverter

**Comment by b-wind** [comment]
> これについてですが、UNIX Epochは1970/1/1 00:00:00からの経過秒数を表したものであるため

本来はそう言う定義ですが、負の整数として表現される様です。

https://docs.microsoft.com/ja-jp/dotnet/api/system.datetimeoffset.tounixtimeseconds?view=net-6.0


ただし、そこから TimeZone オブジェクトに変換するときに例外が発生すると思われるので解決にはならなさそう。

**Comment by keiji** [comment]
ありがとうございます。
タイムゾーン処理とか人類がやるのはとても大変なので、実績のあるライブラリを使うのが一番正当なんですよね。

一度しか実行しないであろうマイグレーション処理のためにライブラリ一個入れるというのは大げさかと思ってしまった当時のぼくですが、JSONに含まれる規約の更新日時がJSTという仕様は現在も生きているので、ライブラリを入れるというのが最適ということになりそうです。

一度使ってみます！

**Comment by b-wind** [comment]
少し Issue の目的からは外れますが、 new DateTime() が問題になるのはわりと知られた問題の様でこのような記事も見かけました。

https://clown.cube-soft.jp/entry/2021/11/26/datetime-trap
> 私自身に関しては、対策として最近は ソフトウェアの初期リリース以前の時刻等、適当な時刻をそのプロジェクトでの最小値・初期値として決めてしまう と言う方針を取るようになりました

**Comment by RabbitProgram** [comment]
既存のJSTのDateTime型またはそれをtoString()したものを、UNIX Epoch（UTC）に置き換えるプログラムを考えました。
例え**new DateTime()であった場合でも**、例外が発生することなく変換できました。
参考になりますと幸いです。

https://gist.github.com/RabbitProgram/0b17c3de3a9c1a9608564c7654a7c06e

![zikkoukekka](https://user-images.githubusercontent.com/74450836/143671304-03d6a273-1174-4866-9c16-7fe8b0c5a346.png)

**Comment by b-wind** [comment]
@RabbitProgram  new DateTime() の返す値は DateTime.MinValue と同じなので、そもそも UTC ですね。

**Comment by RabbitProgram** [comment]
@b-wind はい、こちらのコードはCOCOAのこれまでの仕様をもとに作成しました。
なお、一部不要な処理があったので、53～60行目を修正しました。
https://gist.github.com/RabbitProgram/0b17c3de3a9c1a9608564c7654a7c06e#file-program-cs-L53-L60

**Comment by b-wind** [comment]
TimeZoneInfo.FindSystemTimeZoneById() を使う方法については私も keiji さんも認識していますが、指定すべきIDがOS依存であり特にCOCOAのターゲットである iOS/Android ではそれぞれ何を指定すべきかが明確で無いことを懸念しています。
（おそらくは Windows 以外ではIANA名である 'Asia/Tokyo' で問題無い気もしますが）


幾つかの資料を当たった上で、この問題に対処するには TimeZoneConverter が提示されることが多いので上のコメント（ https://github.com/cocoa-mhlw/cocoa/issues/523#issuecomment-980498892 ）で紹介しました。


MS の Blog （どう言う位置づけか分かりませんが）でも TimeZoneConverter が紹介されています。
https://devblogs.microsoft.com/dotnet/cross-platform-time-zones-with-net-core/

**Comment by b-wind** [comment]
> この処理を噛ますことで、これまでのnew DateTime()は-62135596800に置き換わります。

過去の経緯から new DateTime() 使ってしまっていると言う事実はありますが、できる限り排除する方針であると言う認識です。
ですので、すでに生成してしまった文字列をパースする必要はありますが、new DateTime() に相当する値を保存することはなくなると考えています。

**Comment by b-wind** [comment]
上記の内容は Issue #517 でやり取りした内容をベースにしていますので、当 Issue だけを見てコメント戴いたのでしたら分かりにくい状況かなとも思います。

**Comment by b-wind** [comment]
サンプルコードまで戴いたことはとても有り難いです。ありがとうございます。

**Comment by RabbitProgram** [comment]
こちらこそ、コメント下さりありがとうございます。

> その他 / Additional context
> 日時のデータを作成する処理は過去のバージョンのものなので、今から変更すべきではない（ #522 ）。
> すでに存在するある「文字列」を安全に取り扱うにはどうやるかを検討する。

こちらのIssue #523 のコメントや https://github.com/cocoa-mhlw/cocoa/issues/520#issuecomment-980494685 にあるように、以前の`new DateTime()`の記述についてはそのまま変更しない方向で検討されているようだったので、`new DateTime()`の場合でもうまくマイグレーションできるようなプログラムを https://github.com/cocoa-mhlw/cocoa/issues/523#issuecomment-980527739 でご紹介させていただきました。

確かに、私のプログラムではTimeZoneInfo.FindSystemTimeZoneByIdの部分がハードコードになってしまっているので、この部分は https://github.com/cocoa-mhlw/cocoa/issues/523#issuecomment-980498892 で仰るようにTimeZoneConverterライブラリに任せることでOS依存の処理を吸収させるのが良さそうです。

**Comment by b-wind** [comment]
> 以前のnew DateTime()の記述についてはそのまま変更しない方向で検討されているようだったので

こちらについては現状では、 Migrator_1_2_2 内の処理のみが対象と捉えています。

**Comment by b-wind** [comment]
補足。
下記のURLが指すURL内の update_date もパースの対象ですね。他に英語版と中国語版もあるはず。

https://covid19radarjpnprod.z11.web.core.windows.net/ja/terms_update.json

**Comment by keiji** [comment]
ありがとうございます。ひとまず仮ですが、修正のPull Request #525 を提出しました。

「`DateTime.MinValue`であれば計算しない」という手法は開発チームとの話し合いの中でも案としては出したのですが、「`DateTime.MinValue`でなくとも、たとえば0001/01/01 04:00:00」だとその条件に当てはまらず、計算に進んで同じ問題が起きる」と考えて採用しなかったという経緯があります。

そもそも論ですが、今回のケースで`0001/01/01 00:00:00`に対してタイムゾーンの補正をかけたときに、どのような値になるのが正しいかを考えてみました。`TimeZoneInfo.ConvertTimeToUtc`だと、日時は変わらず`0001/01/01 00:00:00`のままです。

これは @b-wind さんの意見でもありますが、設定ファイル内にDateTime.MinValueやそれに類する値を残しておくべきではないと、ぼくは考えています。そこでPull Requestでは、COCOAのリリース日以前であれば、リリース日に置き換えるようにしました。

TimeZoneの取得にはライブラリ「TimezoneConverter」を導入しました。
@RabbitProgram さんのサンプルにあった「`Unspecified`を明示的に指定する」部分は非常にためになりました。もともと対象となる文字列をParseするとUnspecifiedだと理解していましたが、万が一タイムゾーン付きの文字列が入力された場合、UTCやLocalになる可能性があることに気づかされました。

ひとまず、この処理が安全にできることを確認してから、JSON側のタイムゾーン変換も同様に対処していく予定です。

**Comment by keiji** [comment]
#525 の方法で、今回の問題を検出できるようにしたユニットテスト（ #527 ）を通ることを確認しました。
本Issueをクローズして、 developへのPull Request（ #531 ）へ引き継ぎます。
