### ISSUE TITLE
Xamarin.ExposureNotification の dev/api2-v2 をコードベースでマージ

### ISSUE THREAD

**Issue by moonmile** [cocoa-mhlw/cocoa#54]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

Xamarin EN v2 の対応のチェックのため。

## 解決策についてお書きください / Describe the solution you'd like

Xamarin EN v2 をコードベースをマージして、実機で試験をする。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

[XamarinComponents/XPlat/ExposureNotification/source/Xamarin\.ExposureNotification at dev/api\-v2 · xamarin/XamarinComponents](https://github.com/xamarin/XamarinComponents/tree/dev/api-v2/XPlat/ExposureNotification/source/Xamarin.ExposureNotification)

この dev/api-v2 ブランチを cocoa v1.2.2 にマージしてあります。

----
Internal IDs:
- Feature 1664

**Comment by b-wind** [comment]
#55 は close されていますし、#300 とその関連にて実装は進んでいるようなので当 Issue は close で良いのでは無いかと思います。

**Comment by moonmile** [comment]
この issue はクローズでよいと思います。
クローズしておきます。
