### ISSUE TITLE
TimeZoneInfo の取得方法を統一する

### ISSUE THREAD

**Issue by b-wind** [cocoa-mhlw/cocoa#554]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

LogFile に記録する TimeZone はJSTに固定されている。
この為 JST を表すTimeZoneInfoが必要だが、 TimeZoneInfo.FindSystemTimeZoneById で取得する形式となっている。

該当処理
https://github.com/cocoa-mhlw/cocoa/blob/99712d452169f9088f2a721be1b80ec11ad62910/Covid19Radar/Covid19Radar/Common/Utils.cs#L37-L60

呼び出し元
https://github.com/cocoa-mhlw/cocoa/blob/2a729494ad1efa1f3f3119b71e4623b672271557/Covid19Radar/Covid19Radar/Services/Logs/LoggerService.cs#L136

### （2021/12/11 追記） #578 に関連して

TimeSpam での演算はやめよう。
https://github.com/cocoa-mhlw/cocoa/blob/360150a71beca3e5a34a19c192a487261dc1dae7/Covid19Radar/Covid19Radar/Model/TermsUpdateInfoModel.cs#L31-L32

## 解決策についてお書きください / Describe the solution you'd like

Issue #523 で検討した手法に統一する。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

動いて居るので変えない。

ただし、同様の処理をバラバラの方法で行う事になる。

## その他 / Additional context

個人的にはログに記録する日時もUTCにしたいところだけれど、強い要望では無い。

----
Internal IDs:
- NFR 5077

**Comment by keiji** [comment]
人間が見る表示はローカルタイムの方がいいですね。
むしろJST/UTC固定より、こういうときこそLocalTimeを使った方がいいのでは（JST固定だと動作端末のタイムゾーン情報が落ちてしまう）と思います。

ギリギリまでUTCで取り扱って出力時にLocalTimeに変換（日時文字列にタイムゾーンを含める）くらいでしょうか。

**Comment by keiji** [comment]
むしろ、ここにタイムゾーン関係の処理があったのか…LoggerServiceからしか使われないないから気づいてなかった。
`JstNow`については、使われている箇所が`LoggerService`の1箇所しかない＋ログを出力するたびにタイムゾーンを取得する処理が走っているので、staticで持って一回で済むようにしたいですね。

Issueにある解決策と代替案でどちらかという意味では解決策の方「Timezone関係は1つのクラスにまとめる（#523 で統一する）」方向で行きたいですね。
一方、処理をすでにある`Utils`クラスにまとめるかは検討の余地があると考えています。`TimezoneUtils`とか、もう少し用途がわかる名前にしたい。

（そういえば `DateTimeUtility` というクラスもあるんだった。けど、これはServiceとして取り扱う提案されているので、ここへの移行は良くないかも）。

**Comment by b-wind** [comment]
> 人間が見る表示はローカルタイムの方がいいですね。

人間が見る…… というよりは本来の目的からすると開発チームがトラブルシューティングのために見るのが存在の第一目的なのかなと。

端末自体のタイムゾーン情報は言語設定（CultureInfo）と一緒に必要な場所でログ出力する方が適切かなと。
端末自体の設定を変えることで「ログファイル内の日時表示方法」が変わるのは嬉しく無さそう。


> ギリギリまでUTCで取り扱って出力時にLocalTimeに変換（日時文字列にタイムゾーンを含める）くらいでしょうか。
このあたりは出来れば Viewer側（COCOAの外）に任せたいのはあります。
専用のViewerでは無く Excel 等で開いている人も多いのかな？

**Comment by b-wind** [comment]
> 一方、処理をすでにあるUtilsクラスにまとめるかは検討の余地があると考えています。TimezoneUtilsとか、もう少し用途がわかる名前にしたい。

Utils クラス。使ってしまう気持ちは分かりますが、本件の様に見落としやすくなる一因だとは思います。

**Comment by b-wind** [comment]
私自身の運用経験から来る一般論ですが、クライアントとサーバーのログを突合等するケースを考えて同一のタイムゾーン・日時フォーマットの方が嬉しい等はありますね。

**Comment by b-wind** [comment]
話を広げてしまっていてなんなのですが、当 Issue の目的はあくまで処理方法の統一までとさせて戴きたいと考えます。
（検討の上 TimezoneUtils クラスなどに纏める・インスタンスの生成を効率化する所までは含む）

動作ログに出力する内容の変更は必要に応じて別 Issue にした方が良いかと思います。

**Comment by keiji** [comment]
AppConstantsに定数として定義して、アプリ内からは常に1つのインスタンスを使う（テストは別）ようにしました。
