### ISSUE TITLE
「ライセンス...」ボタンについて

### ISSUE THREAD

**Issue by rea-sna** [cocoa-mhlw/cocoa#562]
### Discussed in https://github.com/cocoa-mhlw/cocoa/discussions/561

<div type='discussions-op-text'>

<sup>Originally posted by **rea-sna** December  5, 2021</sup>
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?
アプリ内設定にある「ライセンス...」ボタンについてです。
iOSではボタンやラベルの文字が見切れると「...」がついてしまうので、「ライセンス」より先にある文字が見切れているのではないかという誤解を招いてしまう。（私もそう思ってました）

## 解決策についてお書きください / Describe the solution you'd like
ボタンを「ライセンス...」から「ライセンス」に変更する。

## その他 / Additional context
該当箇所のスクリーンショットです。
![IMG_1234](https://user-images.githubusercontent.com/47246905/144748204-4643e731-a2b6-4f0a-b9ab-3b5f609f4c21.PNG)</div>

----
Internal ID : PBI4954

**Comment by keiji** [comment]
最新のdevelopではアクセシビリティ対応の一環で対応しているとのことです。
手元で表示したらこんな感じになっていました！

![Screen Shot 2021-12-17 at 15 19 28](https://user-images.githubusercontent.com/932136/146498655-0a09642a-3774-464a-8de3-8392c006cae0.png)
