### ISSUE TITLE
陽性情報の登録画面で表示される確認ダイアログのボタンラベルが「同意する」になっている

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#57]
## 不具合の内容 / Describe the bug
陽性情報の登録画面で、「陽性情報登録」ボタンを押した後に表示される確認ダイアログのPositive Buttonのラベルが「同意する」になっている。

## 再現手順 / Steps to reproduce

1. '陽性情報の登録' に行き、必要事項を入力
2. '登録する' のボタンを押すと、
4. 表示される「陽性情報を登録しますか？」のダイアログのPositive Buttonのラベルが「同意する」になっている

## 期待される挙動 / Expected behavior
ユーザーの目的は陽性情報を登録することで、直前のボタンも「登録する」表記なのでPositive Buttonのラベルは「登録する」または「登録」がより適切と考えます。

## スクリーンショット / Screenshots

![Screenshot_1615811580](https://user-images.githubusercontent.com/932136/111155894-66db2480-85d8-11eb-8916-f8f007f49eea.png)

## 動作環境 / Environments

- デバイス：Android、iPhone 6
- OS：Android、iOS
- バージョン：すべてのバージョン
- システム言語：日本語

----
Internal Tracking ID: BUG 1784

**Comment by keiji** [comment]
「登録する」文字リソースはボタンのがあるから、それに差し替えたら解決できそう。

**Comment by Murayu0225** [comment]
このIssueをこのリポジトリで対応した場合、次のバージョンのCOCOAにて修正されるという考えで間違えないでしょうか。
開発担当チームの方で変更は、行わないのてしょうか。

**Comment by yoshitomo-g** [comment]
[アプリ利用規約](https://www.mhlw.go.jp/cocoa/kiyaku_japanese.html)の（本アプリによる情報の生成、記録及び提供等の仕組み）第4条第1項第五号に、次のようにあります。（強調は私による加工）
> (b)他のアプリ利用者のうち感染可能期間内に自らと接触状態となったことのある者については当該陽性者を個人として識別可能な情報の提供を受けずに不特定の感染可能期間内にある陽性者と接触した可能性がある旨を知ることができる状態となることについて、**別途同意した場合は**、(i)(A)管理システムに別途登録した自らの携帯電話番号又はメールアドレスに通知された処理番号及び(B)当該陽性者に新型コロナウイルス感染症の症状がある場合は発症日、ない場合には検査日を自らのアプリ導入端末に入力することにより、

このことから意図的に「同意する」としたように思えます。違和感はあるので、「陽性情報を登録しますか？」のほうを「陽性情報の登録に同意しますか？」とするのはどうでしょうか。GitHub上で検索した限りでは他に使用箇所もなく、変更しても問題はなさそうです。

https://github.com/cocoa-mhlw/cocoa/blob/235499fc7320c27c7dfb0ee63a1e7180d18c6b7b/Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx#L575-L578
https://github.com/cocoa-mhlw/cocoa/blob/235499fc7320c27c7dfb0ee63a1e7180d18c6b7b/Covid19Radar/Covid19Radar/ViewModels/HomePage/NotifyOtherPageViewModel.cs#L83

**Comment by Murayu0225** [comment]
> 「陽性情報を登録しますか？」のほうを「陽性情報の登録に同意しますか？」とするのはどうでしょうか。

私もその意見に賛成です。
ですが、何に同意をしているのかというのが、その文章だけでは、不透明だと思います。なので、1枚目の写真の赤枠部分に
「登録するには、アプリ利用規約の（本アプリによる情報の生成、記録及び提供等の仕組み）第4条第1項第五号に次の画面で同意する必要があります。」
と書いておいた方がよいかと思います。

2枚目の写真の陽性登録画面は、タイトル部分の「登録」を「同意しますか？」または「同意」に変更。
内容部分の「陽性情報を登録しますか？」を「アプリ利用規約の「本アプリによる情報の生成、記録及び提供等の仕組み」に同意しますか？」に変更。
というのは、どうでしょうか。

https://github.com/cocoa-mhlw/cocoa/blob/235499fc7320c27c7dfb0ee63a1e7180d18c6b7b/Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx#L89-L91
にて、ButtonCancelが英語で「Cancel」となっているのですが、他に影響がなければ日本語で「キャンセル」に変更するのは、どうでしょうか。(別途、Issueにて対応が必要かもしれませんが。)

![cocoa-1.jpg](https://user-images.githubusercontent.com/37988559/113230714-91192b80-92d4-11eb-92fa-9c79cee88b31.jpg)

![cococa-2.jpg](https://user-images.githubusercontent.com/37988559/113232110-77c5ae80-92d7-11eb-86c0-f130652d9f41.jpg)

**Comment by yoshitomo-g** [comment]
> [この部分](https://github.com/cocoa-mhlw/cocoa/blob/235499fc7320c27c7dfb0ee63a1e7180d18c6b7b/Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx#L89-L91) にて、ButtonCancelに英語で「Cancel」となっているのですが、他に影響がなければ日本語で「キャンセル」に変更するのは、どうでしょうか。(別途、Issueにて対応が必要かもしれませんが。)

リソースファイルが「Cancel」になっていましたので、こちらを修正するのがよさそうです。
https://github.com/cocoa-mhlw/cocoa/blob/235499fc7320c27c7dfb0ee63a1e7180d18c6b7b/Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx#L89-L91


> 追記
> このIssueですが、陽性情報の登録をする際に事前に **陽性登録への同意** というのページが表示されており、**同意して陽性登録** と書かれていることに気付きました。
> なので、同意という表記がおかしいというkeijiさんの元々のIssue内容の変更の方が正しいような気がしてきました。

手持ちのiPhoneで確認したところ、確かにそのようになっていました。これを踏まえたうえでの別の候補としては、「続ける」「継続する」とかでしょうか。#101 にもあるように登録者に余裕がない可能性を考えると、シンプルなほうがいいですね。思い切って「はい」「いいえ」くらいでもいいのかなと個人的には思うのですが。
![IMG_0871](https://user-images.githubusercontent.com/77680020/113280557-6902ea00-931f-11eb-886c-5a615b4fc7a5.PNG)

iOS版でのダイアログのスクリーンショットを、参考情報として添付します。
![IMG_0873](https://user-images.githubusercontent.com/77680020/113280851-d31b8f00-931f-11eb-8637-d9383e86f804.PNG)

**Comment by Murayu0225** [comment]
> リソースファイルが「Cancel」になっていましたので、こちらを修正するのがよさそうです。
https://github.com/cocoa-mhlw/cocoa/blob/235499fc7320c27c7dfb0ee63a1e7180d18c6b7b/Covid19Radar/Covid19Radar/Resources/AppResources.ja.resx#L89-L91

そうでしたか。ご指摘ありがとうございます。この場合、別途Issueをたてた方が良いかもしれないです。

確かに、登録者に余裕がない状況にあることを考えると

> 思い切って「はい」「いいえ」くらいでもいいのかなと個人的には思うのですが。

その案が一番良いと思います。

@keiji どうでしょうか。

**Comment by keiji** [comment]
ありがとうございます。

ダイアログのメッセージに「登録しますか」とあるので「はい」「いいえ」の方がシンプルで良い（陽性登録するユーザーは余裕がない状況である）という指摘もたしかにそうですね。

ユーザビリティの変更を伴うことなので、開発チームとも調整してお返事しますね。

**Comment by keiji** [comment]
お待たせしました。開発チームからのフィードバック＋中間報告です。

「はい」「いいえ」は、iOSのデザインガイドラインで避けるべき事項として挙げられているので審査で指摘されるリスクを考慮すると避けた方が良いとのことでした。

https://developer.apple.com/design/human-interface-guidelines/ios/views/alerts/

当初の案通り「登録する」「キャンセル」とするか、そもそも「同意する」としたのが（利用規約上）意図的なものであるか。最終的にどうするかは意思決定上の課題なので引き続き確認していきます。

**Comment by b-wind** [comment]
@keiji 仕組みで解決して行くほか無い事なので特に異論は無いのですが、GitHub の運用ルールについては個別の Issue の中だけで無く、どこかに纏めた方が良い様に思います。
纏める場所の指定は特に無いです。
