### ISSUE TITLE
AppCenter に動作ログが送られていないかの検証が必要

### ISSUE THREAD

**Issue by zipperpull** [cocoa-mhlw/cocoa#58]
## 不具合の内容 / Describe the bug

動作未検証なのですが、AppCenter の使用コードが一部残っており、動作ログを送信していないか確認が必要ではないでしょうか

## 再現手順 / Steps to reproduce

再現確認はしていません。

ソース上、以下の点が気になっています

- NuGet の Prism.Plugin.Logging.AppCenter パッケージへの依存がある https://github.com/cocoa-mhlw/cocoa/blob/61455dbf312e32968a71b3f67828df7a2acb11a3/Covid19Radar/Covid19Radar/Covid19Radar.csproj#L111
- ソース上も using Prism.Logging の記述箇所がある https://github.com/cocoa-mhlw/cocoa/blob/20f3e8c570175f1ad693ccbf90ef74aff22de7fd/Covid19Radar/Covid19Radar/Services/FFImageLoadingLogger.cs#L2  https://github.com/cocoa-mhlw/cocoa/blob/20f3e8c570175f1ad693ccbf90ef74aff22de7fd/Covid19Radar/Covid19Radar/Services/DebugLogger.cs#L2
- FFImageLoading 自体は各 xaml から使用している
- FFImageLoadingLogger クラスは参照箇所はないかも
- DebugLogger クラスは Android では使用していないが iOS では使用している https://github.com/cocoa-mhlw/cocoa/blob/20f3e8c570175f1ad693ccbf90ef74aff22de7fd/Covid19Radar/Covid19Radar.iOS/AppDelegate.cs#L34

単に削除漏れで無駄な依存関係があるだけかもしれないですが、念のため DebugLogger の出力が AppCenter に送られていないか検証した方がよさそうと考えています

## 期待される挙動 / Expected behavior

AppCenter へは動作ログなどを一切送信しないこと

## 動作環境 / Environments

- デバイス： 実機では未検証（例：Pixel 5、iPhone 6 等）
- OS： iOS（例：Android、iOS）
- バージョン： 1.2.2 以前全て (例：1.2.2)

## その他 / Additional context

プライバシーポリシーとの矛盾の可能性があるため単に削除というよりは要検証という記載にしてみました。

とはいえ Prism.Logging.AppCenter の挙動や使い方を調べていませんので、コード上でのチェックでも問題ないということかもしれないです(その場合は削除すればそれで問題ないかとは思います)

また、手元では Prism.Logging.AppCenter への依存を削除してもビルドなどには問題なさそうでした(Android のみしか試していないですが)

**Comment by heykuro** [comment]
@zipperpull  さん、ご指摘ありがとうございます(いつもありがとうございます)。

>単に削除漏れで無駄な依存関係があるだけかもしれないですが

ご指摘の通り、AppCenterへのログ送信機能についてすでに使用しておらず、削除漏れのコードと依存関係が残っているという形です。AppCenter側のコンソールも確認し、当該機能が除去された後に情報の送信（AppCenter上での受信）がないことを確認しています。

今後、依存関係や関連する残コードの整理は進めていきたいと思います。

**Comment by zipperpull** [comment]
お手数おかけしてすみません。

コンソールでの確認で充分なのかは微妙なところですが、
現時点では何か送信されている証拠があるわけでもないとは思うので
個人的にはひとまず問題ないように思いました
