### ISSUE TITLE
ダイアログのデザインが想定と異なる

### ISSUE THREAD

**Issue by Murayu0225** [cocoa-mhlw/cocoa#583]
## 不具合の内容 / Describe the bug

#394 のレビューにて開発チームから

> messageを空ではなくnullに設定すると、中心に空白ができることなくタイトルだけ入るようになると思います。空で入れている他の箇所もできればnullにした方がいいですね。

[引用元](https://github.com/cocoa-mhlw/cocoa/pull/394#discussion_r756619631)

とあったので他のstring値でemptyとなっている部分をnullに変更します。

## 再現手順 / Steps to reproduce

一番簡単に再現できる方法を書いておきます。

1. '陽性情報の登録' をクリックし、
2. '同意して陽性登録' をクリックし、
3. 必要事項を全て適当に入力し、
4. '登録' をクリックし、
5. ダイアログ画面で'キャンセル'をクリックすると、
6. '登録をキャンセルしました'と表示されます。

この「登録をキャンセルしました。」の表記のタイトルがemptyになっているのでnullに変更します。(他もあります)

## 期待される挙動 / Expected behavior

ダイアログの中心にできる余白がなくなる。

## スクリーンショット / Screenshots

| 変更前 | 変更後 |
| ------------- | ------------- |
| ![before](https://user-images.githubusercontent.com/37988559/145652661-d376b64e-7478-4295-8be8-a69439443b3f.jpg) | ![after](https://user-images.githubusercontent.com/37988559/145652675-51e8481c-9bb1-46df-a5a6-f6621762c0e5.jpg) |

----
Internal IDs:
- Product Backlog Item 2913

**Comment by keiji** [comment]
COCOA2に入れました。
