### ISSUE TITLE
`Resource.designer.cs`をGitの管理から除外する提案

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#59]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?
Covid19Radar.Android下にある`Resources/Resource.designer.cs`は、自動生成のファイル（Android Projectの`R`に相当）なのでGitの管理から除外するのが適切と考えます。

現在は`Resource.designer.cs`がGitの管理下にあり、ソリューション（プロジェクト）を読み込むと`Resource.designer.cs`が読み込まれて、場合によっては更新されます（diffに載る）。そのままコミットすると`Resource.designer.cs`が更新された記録が積み上がっていきます。しかし、自動生成ファイルである`Resource.designer.cs`には、バージョン管理システムで管理して、変更の差分を見る必然性は乏しいと考えます（このあたり、Xamarinをよく知る人の意見を聞きたいです）

`Resource.designer.cs`が変更されている例
https://github.com/cocoa-mhlw/cocoa/commit/3e765cf236eeeece366ad91d336e41ffcb724740#diff-19ac7f3b6ba8be87d398701aa40f7206e5cded2a5a772edf1da1fa4cd70c2257

## 解決策についてお書きください / Describe the solution you'd like
`Resource.designer.cs`を.gitignoreファイルへ追加し、さらに`Covid19Radar.Android/Resources/Resource.designer.cs`を削除したコミットをする。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered
Pull Requestに`Resource.designer.cs`を含めないことを、PRレビュー前の必須事項とする（コントリビューターの手間を考えると、素直に.gitignoreに追加した方法が良いと思います）。

### 参考記事
Xamarin 開発の GitIgnore ファイルを見直してみた - Xamarin 日本語情報
https://blog.ytabuchi.dev/entry/2017/11/15/123000

**Comment by zipperpull** [comment]
サンプルでも ignore しているのでこれを取り込むのがいいのではないでしょうか

https://github.com/xamarin/xamarin-forms-samples/blob/master/.gitignore

**Comment by b-wind** [comment]
全体的に似ている（と言うか恐らくsampleがベースになっている）ようなので比較してみて他にも検討すべきファイルがあれば同時に追加・削除してみても良いのかもと言う感じはしますね。
