### ISSUE TITLE
「陽性者との接触結果を確認」画面での接触の表示方式を変更する

### ISSUE THREAD

**Issue by daisuke-nogami** [cocoa-mhlw/cocoa#606]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

discussion #532 では議論の対象になっていないが、EN v2では接触が回数ではなく時間で把握され、
例えば60分の接触であれば30分のExposure Window2個を返して「2件」とされてしまいミスリードなため、
接触が回数で返されるv1を前提とした画面表示を変更する必要がある。
https://github.com/cocoa-mhlw/cocoa/discussions/532

## 解決策についてお書きください / Describe the solution you'd like

以下の様に分数表示で表示する。

- 「陽性者との接触確認」画面
  - ◯日間に合計◯分間
- 「陽性者との接触一覧」画面
  - 202x年xx月xx日 合計◯分間の接触

日数（◯日間の◯）は、 DaySummary の個数。各々の時間（◯分間の◯分）は、全Exposure Windowないし当該日のScanInstanceのうち、別途設定するパラメータで想定する閾値以上の TypicalAttenuationDb を持つScanInstanceの SecondsSinceLastScan の合計値を60で除算する。

v2.0.0以前のCOCOAからのバージョンアップ直後で、v2.0.0以前に接触通知が発生していた場合には、

- 「陽性者との接触確認」画面
  - 202x年xx月xx日以降 ◯日間に合計◯分間、202x年xx月xx日以前 ◯件
- 「陽性者との接触一覧」画面
  - 202x年xx月xx日 合計◯分間の接触　※v2インストール後の日
  - 202x年xx月xx日 ◯回の接触　※v2インストール前の日

と両者を併記する。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

表示形式を変更しない。

**Comment by b-wind** [comment]
v1 時点でも詳細な接触情報を知りたいと言う要望は時折目にします。（何時頃に濃厚接触が発生したのか等）


どこまで詳細にするかはシステム上・プライバシー保護上の問題が有るので検討は必要だと思いますが、丁寧で分かりやすい説明というのは求められていると感じて居ます。

**Comment by daisuke-nogami** [comment]
実際には何時頃というのはExposure Windowのデータからは分からないですし、それは犯人を特定するような思想なので受け入れがたいでしょうね…

もともとの◯件という表示は、回数ではリスクのイメージが湧きにくいので、個人的には時間表示になるのは、よりリスクの大きさの方に着目して貰える（例えば15分よりは30分の方が危ないと感じて貰えるだろう、など）ので、よい方向の変更だとは思います。

**Comment by daisuke-nogami** [comment]
言葉だと変更イメージが分かりにくいので画面イメージを作って見ました。

*「陽性者との接触確認」画面*
![image](https://user-images.githubusercontent.com/71449929/146542376-7c7b41f5-94e1-4955-b3dc-3c2e00babc86.png)

*「陽性者との接触一覧」画面*
![image](https://user-images.githubusercontent.com/71449929/146542647-9ea11950-98e0-4a9d-ad54-0ca173d74023.png)

**Comment by keiji** [comment]
こちらCOCOA 2.0.0で対応完了しているのでクローズします。
