### ISSUE TITLE
ベータ版用の起動時のダイアログ実装

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#616]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?
#598
ベータ版利用者に、今使っているアプリがベータ版であることを常に意識してもらいたい。

## 解決策についてお書きください / Describe the solution you'd like

ベータ版はベータ版と分かるように、アプリを起動するたびにダイアログで「ベータ版です」「不具合があるかも」「気づいたことがあったらGitHubに連絡してね」みたいな内容を簡単に表示したい（詳細画面は別途作成）

**Comment by b-wind** [comment]
ダイアログなどで積極的に注意を促すのも良いかと思いますが、メインの画面にバージョンとβであること、ENS のバージョンなど（これは可能かどうかよく分かっていません）を表記してしまっても良いのでは無いかなと。

Twitter などで見ていると取りあえずメイン画面のスクショ貼る人が多い事からの発想です。

**Comment by keiji** [comment]
ホーム画面の下とかにすかしのような形でバージョン（e.g. 2.0.0-beta01）とENSのバージョンを表示できるとうれしそうですね。
CappuccinoならENSのバージョンは取得できます（iOSでは2としか表示できませんが。

いっそ色味自体を変えてはどうだろうとも思っていたのですが、アクセシビリティ系の検討ができなくなるのでやめた方がいいかなと思い始めています。

**Comment by keiji** [comment]
スプラッシュ画面を改装して、起動の度にベータ版であることを知らせるようにしました。

![Screen Shot 2022-01-14 at 19 52 43](https://user-images.githubusercontent.com/932136/149504281-8a2f10c1-751f-42c1-96fe-f13ba8defcb7.png)

![Screen Shot 2022-01-14 at 19 52 47](https://user-images.githubusercontent.com/932136/149504309-0ff9f038-5a01-4987-8bc4-a3a83464ad73.png)
