### ISSUE TITLE
ベータ版用の「アプリに関するお問い合わせ」画面実装

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#617]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?
#598
ベータ版の問い合わせがプロダクト版の窓口に行かないようにしたい。

## 解決策についてお書きください / Describe the solution you'd like

「アプリに関するお問い合わせ」のフローを再構成する。

メールでのお問い合わせは削除。
動作情報を送信は残すけど、メールでの問い合わせフローではなくGitHubに誘導したい。
「アプリに関するお問い合わせ」直下に、ちゃんとGitHubについても書いておく。

**Comment by kazuhiro4949** [comment]
ベータ版のみメールの問い合わせを削除してGithub issueへのリンクを出すイメージですかね

**Comment by keiji** [comment]
コメント見落としてましたごめんなさい。こんな感じで進めています。
![Screen Shot 2022-01-11 at 3 01 16](https://user-images.githubusercontent.com/932136/148815785-314821c8-480a-4f4e-b175-1b93d7df8874.png)
