### ISSUE TITLE
Android 版でアプリアップデート後にログのローテートが正しく行われるか検証が必要

### ISSUE THREAD

**Issue by zipperpull** [cocoa-mhlw/cocoa#62]
## 不具合の内容 / Describe the bug

- ログのローテート処理 (LogFileService クラスの Rotate メソッド)が正しく呼び出されないおそれがあります

## 再現手順 / Steps to reproduce

ストアを利用しないと検証できない事象なのでコード上の確認のみですが、以下のような手順での検証が必要だと考えられます。

1. PlayStore にクローズドベータ版で問題ないので COCOA をアップロード
2. ストア公開版アプリをインストールして初期設定後 1. のベータ版に更新
3. 更新後、アプリアイコンから起動せず、かつ端末を再起動せずに 24時間以上経過後、ログがローテートされているか確認

## 期待される挙動 / Expected behavior

- 24時間以内にはログがローテートされること
- 特に、次バージョンで TEK の定期ダウンロード処理が正常化した場合に、単一のログファイルに大量のログが保存され続けることがないようにすること

## 動作環境 / Environments

- デバイス：Android ならどれでも（例：Pixel 5、iPhone 6 等）
- OS：Android（例：Android、iOS）
- バージョン：1.2.1 以降 (例：1.2.2)

## その他 / Additional context

v1.2.2 のコードでは、私が理解している動作としては以下のようになっています。

- Android 版では LogPeriodicDeleteServiceAndroid.cs にある LogPeriodicDeleteReceiver を 2箇所から呼び出しています
  - AlarmManager の PendingIntent https://github.com/cocoa-mhlw/cocoa/blob/b823e87df6986d91d2b06b6ff9a4b2b94bf5c0e4/Covid19Radar/Covid19Radar.Android/Services/Logs/LogPeriodicDeleteServiceAndroid.cs#L36
  - AndroidManifest.xml への android.intent.action.BOOT_COMPLETED の登録 https://github.com/cocoa-mhlw/cocoa/blob/b823e87df6986d91d2b06b6ff9a4b2b94bf5c0e4/Covid19Radar/Covid19Radar.Android/Services/Logs/LogPeriodicDeleteServiceAndroid.cs#L50
- また、AlarmManager への登録処理は、以下の 2箇所を通った場合に行われます
  - App.xaml.cs の OnStart から LogPeriodicDeleteServiceAndroid クラスの Init メソッド → SetNextSchedule メソッドの呼び出し https://github.com/cocoa-mhlw/cocoa/blob/b823e87df6986d91d2b06b6ff9a4b2b94bf5c0e4/Covid19Radar/Covid19Radar/App.xaml.cs#L149
  - LogPeriodicDeleteReceiver の OnReceive から SetNextSchedule メソッドの呼び出し(ローテート処理が1度呼び出された場合には次回を設定している)  https://github.com/cocoa-mhlw/cocoa/blob/b823e87df6986d91d2b06b6ff9a4b2b94bf5c0e4/Covid19Radar/Covid19Radar.Android/Services/Logs/LogPeriodicDeleteServiceAndroid.cs#L71
- その他、LogFileService の Rotate メソッドを App.xaml.cs と SendLogConfirmationPageViewModel から呼び出し(今回の現象にあまり関係がないので省略)

言い換えると、以下の場合には SetNextSchedule が呼ばれるので正しいように見えるのですが

- アプリ通常起動時 (App.xaml.cs)
- 端末再起動時 (BOOT_COMPLETED broadcast)

アプリをアップデートした場合には、AlarmManager の登録内容はいったんクリアされるはずなので、上記の2つのいずれかを実行するまで、AlarmManager による定期起動が行われないのではないでしょうか。

一見条件が厳しいようにも見えますが、アプリを自動アップデートする設定にしていて COCOA をふだん起動しないユーザが当てはまるので、確認・対応しておいた方が望ましいと考えています(とはいえログファイルのサイズが巨大化する可能性があるだけなので、動かないよりはマシですが)

解決方法としては以下のような方法が考えられるかと思います

- AlarmManager をやめて WorkManager に置き換え (アプリアップデート後も再設定の処理は自動的に行われる)
- android.intent.action.MY_PACKAGE_REPLACED などの broadcast を受信して AlarmManager を初期化する(念のためOSバージョンなどの制限がないか調査かテストが必要)
- ログ出力時にもローテートが必要かどうかのチェックを行うように修正(どうしても他の方法が取れない場合)

**Comment by keiji** [comment]
ぼく個人としては、ログのrotate処理についてはWorkManagerに移すのが良いと思います。
開発担当チームとも共有しますね。

**Comment by zipperpull** [comment]
補足ですが、元々の実装が WorkManager だった場合はアップデート後も維持されるんですが、
今回のように v1.2.2 では AlarmManager だったものを WorkManager に変える場合には
いずれにしても WorkManager への登録処理を行うために MY_PACKAGE_REPLACED の処理は
行う必要があるかなとは思っています。

**Comment by keiji** [comment]
今後のバージョンアップでMY_PACKAGE_REPLACEDを追加するとして、追加したバージョンの次のアップデートから効いてくると言う認識ですが、この認識で合ってますでしょうか。
どこかの時点で必ず一度、アプリを起動してもらわないといけないと言う認識です。

**Comment by zipperpull** [comment]
記憶違い・認識違いならすみません。
v1 には AndroidManifest.xml に書かれていなくて v2 で AndroidManifest.xml に書いたとして、
v2 にアップデートした時点で MY_PACKAGE_REPLACED は呼ばれると思っていました。
ただ、全く起動したことのないアプリケーションの場合には勝手に何か動くこともなかったとは
思うので、その辺の制限が関係していますか？

**Comment by keiji** [comment]
うーん。「やってみたことがない」というのが正直なところです。アプリを作る時には入れっぱなしではなくて起動してもらうという施策を一緒に考えるので……COCOAが特殊というか。

一度そこもチェックしてみた方が良さそうですね。もしMY_PACKAGE_REPLACEDを入れたバージョンから速やかに動くのであればそれでいいですし、動かない場合はアプリを起動してもらうように広報を…のような形です。

**Comment by zipperpull** [comment]
全く起動したことがなくてインストールしただけのアプリが勝手に動かない、という制限については
ログのローテートもされなくて問題ないはずです。

なので、すでに起動も初期設定もしたことがある既存ユーザが前提として、問題は、
そのユーザがアップデートした場合に MY_PACKAGE_REPLACED が追加されたとしていつそれが呼び出されるかだけ
考えればよいと思います。

**Comment by keiji** [comment]
実際に試してみました。
結論から言えば、新しいバージョンに`MY_PACKAGE_REPLACED`があれば、インストール時にBroadcastReceiverで更新イベントを受け取ることができます。

アップデート時の処理がやりやすくなりますね。

### 詳細
`app-debug-1.apk`は、AndroidManifest.xmlに`MY_PACKAGE_REPLACED`のIntent-Filterを入れていないもの。
`app-debug-2.apk`は、`MY_PACKAGE_REPLACED`のIntent-Filterを追加したものです。

（apkファイルをアップロードできなかったので、末尾に.zipをつけています。）
[app-debug-1.apk.zip](https://github.com/cocoa-mhlw/cocoa/files/6168441/app-debug-1.apk.zip)
[app-debug-2.apk.zip](https://github.com/cocoa-mhlw/cocoa/files/6168443/app-debug-2.apk.zip)


検証に使用したコードです。
[MyUpdateSample.zip](https://github.com/cocoa-mhlw/cocoa/files/6168433/MyUpdateSample.zip)

**Comment by zipperpull** [comment]
別案として、AlarmManager は削除して、ログのローテートは既存の WorkManager から呼び出すという方法がありました。
Worker が正しく動く前提では、これだけやれば MY_PACKAGE_REPLACED も BOOT_COMPLETED も不要になるし
Worker が動かない場合にローテートだけ自動実行してもさほど意味はない(App.xaml.cs でもやっているし)ので、
よりシンプルになりそうです

**Comment by keiji** [comment]
検証条件の確認をさせてください。

Descriptionに「ストアを利用しないと検証できない事象」とありますが、ぼくの手元では`adb install app-v1.apk`, `adb install -r app-v2.apk`で上書きインストールすることで`MY_PACKAGE_REPLACED`が受け取れることまでは確認しています。
AlarmManagerのキャンセルはこの手順では発生しませんか？
情報をお持ちでないなら一度そちらもやってみます。

**Comment by zipperpull** [comment]
すみません。MY_PACKAGE_REPLACED もストアアプリが必要かと思っていたのですがそうでもないようですし
(INSTALL_REFFERER 系の仲間かと思っていました)
だいぶ以前の記憶なので確認するには越したことはないと思います。

**Comment by keiji** [comment]
検証しました。
結論から言うとAndroid 2.2以降はアプリのアップデート時にもAlarmManagerの設定が引き継がれるようになっていることがわかりました。

> The answer appears to be that the AlarmManager alarms do keep running after an app update for most versions of Android. Certainly for Android 2.2 or above. The UninstallReceiver in AlarmManagerService was updated to handle package update without killing the alarms

 * Do Android AlarmManagers continue to run after an app update?
     * https://stackoverflow.com/questions/24521074/do-android-alarmmanagers-continue-to-run-after-an-app-update

Google Playでのアップデート時のみ挙動が異なるというのは考えづらく、また、2.1以前では確かにAlarmManagerはキャンセルされていたことから、Google Play経由でのアップデートでも同様の挙動であると考えます。

この結果を元に再検討した結果、アプリのアップデート時にAlarmManagerがキャンセルされないこと。再起動時にはBOOT_COMPLETEDで再設定されることから、ログのローテート機能は問題なく動作すると考えます。

## 検証について
検証は、次のように行いました。

AlarmManagerを設定して3分ごとにBroadcastを受けるアプリ[app-alarmmanager-debug-1.apk](https://github.com/cocoa-mhlw/cocoa/files/6175057/app-alarmmanager-debug-1.apk.zip)と
[app-alarmmanager-debug-2.apk.zip](https://github.com/cocoa-mhlw/cocoa/files/6175058/app-alarmmanager-debug-2.apk)を用意する
（それぞれVersionCodeが異なる。ソースコードは [MyUpdateSample2.zip](https://github.com/cocoa-mhlw/cocoa/files/6175062/MyUpdateSample2.zip)）

 * `adb install app-alarmmanager-debug-1.apk` で、VerisonCode 1のアプリをインストールする
 * アプリを起動する（AlarmManagerにより３分ごとに処理が行われる）
 * `adb shell dumpsys alarm` で、AlarmManagerの状態を確認（[alarmmanager1.log](https://github.com/cocoa-mhlw/cocoa/files/6175068/alarmmanager1.log)）
 * `adb install app-alarmmanager-debug-2.apk` で、VerisonCode 2のアプリをインストールする
 * `adb shell dumpsys alarm` で、AlarmManagerの状態を確認（[alarmmanager2.log](https://github.com/cocoa-mhlw/cocoa/files/6175070/alarmmanager2.log)）

検証の結果、AlarmManagerに登録したジョブはキャンセルされず継続していることが`adb shell dumpsys alarm` で確認しました。また、登録したジョブの動作も更新後のVersionCodeが使われていることを確認しました。

**Comment by zipperpull** [comment]
おーそうなんですね。お手数おかけしてすみません。
記憶とは一致しない気がしなくはないですが検証いただいたので間違いなさそうかとはおもいます。
失礼いたしました

**Comment by keiji** [comment]
大変有意義なIssueだったと思います。特に`MY_PACKAGE_REPLACED`について検証できたことは今後有用になってくると思います。

AlarmManagerについては、ぼく自身とても勉強になったのでブログに書こうと思います（もし検証が間違っていたら、教えてくれる人が出てくるかもしれませんし）。

本Issueはcloseしますね。
