### ISSUE TITLE
日本語バージョンの説明の追加

### ISSUE THREAD

**Issue by b-wind** [cocoa-mhlw/cocoa#65]
PR #19 を現運用方針に合わせるために建てた Issue です。
詳細は #19 をご覧下さい。

**Comment by keiji** [comment]
このIssueの終了条件ってどんなものになりますか。

#19 の取り込み可否が決まったら。みたいな感じでしょうか。

**Comment by b-wind** [comment]
そうですね。 #19 の扱いが決まった時点で close を意図しています。

**Comment by keiji** [comment]
主な論点はライセンス表記を翻訳するかどうか。と言う話だったので、READMEのライセンス表記は翻訳しないと言うことでPRはcloseしました。
