### ISSUE TITLE
運用基礎データの収集と開示

### ISSUE THREAD

**Issue by zipperpull** [cocoa-mhlw/cocoa#66]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

機能リクエスト以前に、運用基礎データをどの程度集計して開示できるかの検討が必要かと考えます。

以下のような目的を想定しています

- 機能リクエストの検討の際に参考とする
- 機能追加や不具合改修時にデータにどのように反映されるかを事前に検討する
- 運用上集められないデータがあるならば、そのボトルネックがなんなのかを明らかにしておく

## 解決策についてお書きください / Describe the solution you'd like

個人を特定するようなデータは集めない方針なのは前提として、
厚労省として集計しているデータ全てを出すことができない事情はあるかもしれませんが、
現状は公表されている情報がなさすぎると感じています。

- どのようなデータを集めているかの項目の開示と整理
- どのようなデータは集めないことに方針決定されているかの開示
- 開示しても問題ないものはデータそのものの開示

を検討いただければと思います。具体的に必要と考えるデータについては私がどうこういうよりも
issue 内で議論してもよさそうです。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

運用そのものを透明化することはこのプロジェクトでは目的とされていないのかもしれないですので、
クローズドで運用するという決定であればそれはそれで問題はないと思ってはいます。

ですが、オープンプロセスという試みとのことでしたのでできれば前向きな議論がなされることを期待したいです

## その他 / Additional context

また、そもそも github はソースレベル・開発レベルのみの話に限定したくて、
運用については範囲外であるということであれば close いただいてもいいのですが、
github のスコープを明示するような対応を別途行っていただくとよいかなと感じています

**Comment by zipperpull** [comment]
直近で必要と考えている具体的なデータとしては、Azure サーバ側での json と zip の1日あたりのダウンロード数があります。
厳密ではないかもしれませんがアクティブユーザ数に比例した値となることが考えられますし、
Android 版が定期ダウンロードが改善された次バージョンをリリースするにあたって、

- (もしデータが残っていれば)「Android 版は毎日COCOAを手動起動してください」のアナウンス前 (=v1.2.2 公開前)
- v1.2.2 公開後(現時点)
- 次バージョン公開後

での統計データを比較して、実際にユーザ環境で定期ダウンロードが改善していることを
外形的に観察できるように準備いただく必要があるかなと思っています。

なお、単純アクセス数カウントなので、個人を特定する情報にはあたらないと考えています。

**Comment by keiji** [comment]
この件、ぼくがよく理解できてないので教えてください。

目的として挙げられている「機能リクエストの検討の際に参考とする」というのは「誰が、誰に機能リクエストするケース」でしょうか。
「コントリビューターがこのリポジトリにIssueを投稿するに当たって、運用基礎データを参考にする」ということでしょうか。

ぼく自身、そういうのを見ながらIssueを作ったことがなく「アプリやサービスやフレームワークを使っていてる上で見つけた改善点（うまく動かないところや、もっとこうあって欲しい）という点を伝える」のが出発点になっています。
「Azure サーバ側での json と zip の1日あたりのダウンロード数」についても、観察する必要がある点については個人的にも同意します。その上で、Issueの課題になっている「運用基礎データの収集と開示」は、特定のIssueのclose要件としてではなく、もう少し定期的なニュアンスがあるのかな？　と理解しています。

どういうケースを想定しているのかもう少し教えてもらえるとありがたいです。

**Comment by zipperpull** [comment]
まず抽象論とは別により具体的にいうと issue #64 で私が勘違いした理由のひとつに、
「接触履歴に表示された日付には外出すらしていなくて感染の心当たりがない」みたいな
ことは少なくとも以前は twitter などでわりとよく見かける話だったと思うのですが、
そのために「日付表示がずれる不具合があるのでは」という先入観にはつながったわけです。

これは失敗例なので褒められた話ではないことは理解していますが、
データがあれば、正しく動いているのかいないのかが可視化されるし、正しくないならば
原因の推測にも役立つことがあると考えています。

さらに別の例としては、https://github.com/cocoa-mhlw/cocoa/issues/64#issuecomment-802400459 でも少し触れられているような、
現状の運用でも ユーザから見て通知がこない問題、あるいは保健所から見て通知が多すぎるけど
検査しても陰性で過剰な検査になってしまっている問題などが考えられると思うのですが、
そう言った場合に、実際にはアプリの不具合ではないか探したり、機能追加によって
運用改善したりといったことが必要になると思っています。

このような問題や改良点を見つけるための(個人を特定しない範囲での)指標としては、
パッと思いつくような例としては

- 通知が過剰あるいは過少になっていないかの確認のため
  - 保健所が濃厚接触者と判定した人に対して 
    - COCOA をインストールしているかどうかの比率
    - 通知が表示されたかどうかの比率
    - 実際に陽性だった人数の比率 
- COCOA に陽性登録した人数が統計的に妥当な範囲で収まっているかの確認のため
  - 全陽性確認者に対して COCOA をインストールしているかどうかの比率

などが考えられると思います。また、全国で傾向が同じなのか、陽性確認者が多すぎる地域では
これらの比率が異なるのかなども検討しても良さそうです。
(もちろん厚労省ではもっと深く検討してより良い指標で検証されているのであれば、
どのような指標で検証しているかを開示してほしいということです)

これらを全部コミュニティベースだけで回す必然性はないですが、
ブラックボックスにしておくより多くの目で改善していけるようなプロセスになっていれば
望ましいのではないかと考えたための提案です

**Comment by b-wind** [comment]
サポートへの問い合わせ内容を統計処理したもの等が開示されれば、使い勝手の改善提案や
バグ（新しいものや既存の物）への気づきが得られることも有ると思います。
（これはあくまで一例で、実際に開示できないかもですが）

**Comment by keiji** [comment]
まず一番大事なことは、 #64 については失敗例ではなく、成功例だとぼくは認識しています。

「正常に動作しないかもしれないという報告があり確認した結果、問題ないことがわかった」と言う成功例です。しかも確認までオープンソースコミュニティ内で完結しています（すみません。まだぼくの手元で検証しないのでcloseしていませんが…）。

また、結果的に事実とは異なる指摘があったとしても、それを投稿した人が「謝罪する」ことを是とするような流れを作ってしまうことは避けなければならないとぼくは考えています。「間違いのないIssueでなければ謝罪しなければならない」と言うメッセージを将来のコントリビューターに送ることになるからです。

そういうわけなのでzipperpullさんがご自分を責めることは誰にも利がないことです。
どうかお気になさらないでください。

**Comment by zipperpull** [comment]
喧嘩してもしかたないですが、トータルで成功したと考えることと、私の推測が間違っていて
失敗だったことは何も矛盾はないのです。

検証してない事象や間違った内容を投稿することやが全て問題だとは思っていません(もしそうなら投稿しません)が、
検証できることに気がつかなかったし結果的に間違えていたことで複数の方の手間をかけたことは
申し訳なかったし、できるだけそのようなことを起こさないようにはしていこうと思います
(絶対二度としないとかは言えませんが)

**Comment by keiji** [comment]
個人的には、日時情報の内部での持ち方とロケールをまたいだ時の処理は間違いを起こしやすいところと認識しています。実際に #51 のような課題もあるなかで、濃厚接触の日時表示がずれるのではないかと疑いを持つのはプログラマーとして当然のことで頼もしいとさえ思います。

運用基礎データの開示について話を戻しますが #64 が先入観があることから起こったという話ですが、具体的にどの情報があれば、先入観を払拭できたとお考えでしょうか。

ぼく自身、コードに疑いを持った時、仮にデータの中に反証となる数値があったとしても、それはたまたま起きていないだけと考えて検証し、正しく動くことを確認しておくのが最良のプロセスであると考えます。
今回の件がまさにそれで、運用基礎データの中に「先入観を払拭できる情報」があったとしても「データを見るかぎり大丈夫」は、新たな先入観を植え付けることになり、成功には決してつながらないとぼくは考えます。

ぼくは現時点では、オープンソースではコードをベースに課題の提案や解決策を探っていく方向で行きたいと考えています。「Issueのcloseにあたり、このようなデータが必要」といった検討や要望については、Issueのコメントの形で行えば足りるという認識です。

その上で「どんな運用基礎データが欲しいか」「開示されたとしてオープンソースコミュニティとしてどのように活かせるか」については、議論の余地があると考えます。引き続き、このIssueで検討していければと思います。

これについてはぼくの一存では決定できるとは思いませんので @heykuro @halsk の意見も伺いたいです。

**Comment by b-wind** [comment]
@keiji @zipperpull 議論が必要でしたら別のIssueを建てられた方が適切かと思います。

**Comment by keiji** [comment]
@b-wind 現時点で、目的と運用基礎データの定義がふんわりしていると思うのと、Descriptionにも「issue 内で議論してもよさそうです。」と書いてあるので、ここでやるのが良いと思いますよ。

**Comment by b-wind** [comment]
@keiji すいません、誤読していたので先のコメントは削除しました。

**Comment by keiji** [comment]
@b-wind 謝らないで！　誰にでも間違いはあるんですから「ご指摘に感謝」程度でいいんですよ！

**Comment by zipperpull** [comment]
例がよくなかったのだと思いますが、話が逆になっているわけですね。

> コードに疑いを持った時、仮にデータの中に反証となる数値があったとしても

→ 該当コードの内容の検証

> サポートへの問い合わせ内容を統計処理したもの

→ 動作不具合から不具合を含むコードを探す

> 運用統計情報

→ 動作に問題がないことの検証と目に見えづらい異常の早期発見

のように役割が異なっているので、それぞれの情報が別な意味で必要だと思います。

「オープンソースコミュニティとして」については、運営側が何を期待するかの問題なので
いったんご意見を待とうかとは思います

**Comment by zipperpull** [comment]
一応改めてありやまさんのコメントとのすれ違っていると思うところを埋めておくと、
これまでは、厚労省のページで通算ダウンロード数と陽性登録者数が公開されていますが、
それ以外にモニタリングなどを行っていたのかどうかすら非公開だと思います(認識違っていたらすみません)

今後問題を繰り返さないためには、まずはどんな指標をモニタリングする必要があるかを
整理した方がいいし、今後別のプロジェクトなどでも参考にできるのではということが
問題意識としてはあります。

そのデータそのものは開示できない場合でも、何をモニタリングするか
(またはモニタリングしてはいけないのか)を議論するとか、
あるいは厚労省で別の会議などですでに議論されているならばそれを開示して
今後の安心感につなげていくということをお願いできればと思っています。

**Comment by heykuro** [comment]
@zipperpull  さん、問題提起ありがとうございます。(既に触れていただいている点ですが)大前提として個人情報やプライバシーに配慮するというところは変えませんが、皆さんにご協力いただく上でより効率的、効果的に取り組んでいただくために必要な情報やその提供プロセスについてはぜひ引き続き議論させてください。
実際には取得のためのオペレーションも発生する場合があるため、現実的に可能かどうかなども判断軸となると思いますが、まずCOCOAとして取得可能な領域について検討していきたいと思います。

(具体的にこれ、というのがパッと出ず申し訳ありませんが、取り急ぎ。)

**Comment by zipperpull** [comment]
@heykuro さしあたっては https://github.com/cocoa-mhlw/cocoa/issues/66#issuecomment-803110532 こちらの件はモニタリングいただくことはできそうでしょうか？
仮に生データが公開できないとしても、アクティブユーザ数がどのくらいなのかというのは
把握されていたほうがよさそうです。

一例として考えているのは以下のようなイメージです
(より精度の高い調査方法はあるかもしれませんので一例です)

version.json とか terms_update.json のアクセス数はアプリをアイコンから起動して
SplashPage → HomePage を表示したユーザ数に相当しますし、
Configuration.json のアクセス数は ExposureNotificationService の呼び出し回数に相当するので
定期ダウンロード実行されたユーザ数+HomePageView を表示したユーザ数にほぼ相当すると思います
(シングルトンなので両方オンメモリで実行したユーザがどう数えられるかとか毎日定期ダウンロード
実行したら毎日 Configuration.json へアクセスしているかとかは別途実機テストして
確認いただいたほうがよいです)

list.json へのアクセス数と個別の zip へのアクセス数については、全ユーザが
毎日定期ダウンロード成功していれば、その日に生成された zip へのアクセス数と 
list.json へのアクセス数がほぼ一致するべきかと思いますが
実際には途中でダウンロード失敗しているユーザがいると思いますので
その割合などを見ることで異常があれば調査を始めることができるかもしれません

そのほか、規約の HTML のアクセス数で初回起動ユーザのカウントの代わりになるかもしれません。
これについては通常の使用中のユーザでも見ようと思えば見られるので厳密ではないですが。

これらのアクセス数(とくに今回のバージョンアップでは list.json と zip あたり) が
机上の計算通りになっているかいないかをいったん調べる体制が作れるか検討いただいて
今回のアプリリリースに備えることが必要かなと思っています。

また今回間に合うかは別ですが、アプリごとに User-Agent で例えば
iOS/Android の区別とアプリバージョンくらいをサーバに送るようにしておけば、
OSごとの傾向を調べることができるようになると思います。
この程度であればプライバシーの懸念は少ないのではとは思いますが方針として取得可能かどうかも
検討いただくとよさそうです

**Comment by zipperpull** [comment]
回答がいただける気もしないので close しておきます。
必要だと思われる方がもしいらっしゃるなら別 issue にでもしてください。

**Comment by heykuro** [comment]
(close済みですが、、)

@zipperpull さん、こちら遅くなり大変失礼しました。

>さしあたっては #66 (comment) こちらの件はモニタリングいただくことはできそうでしょうか？

こちらはAndroidの診断キーダウンロード障害への対応バージョンリリース後に、改善状況の確認観点でモニタリングする予定です。具体的には、リリース前後でのファイルダウンロード状況の変動を見ていくことになります。

また、今年度の体制で取り組む課題の一つとして、個人情報・プライバシーへの十分な配慮のもとでのモニタリング範囲の見直しというのを入れていきますので、他のご提案いただいた内容についても検討内容として入れさせていただきます(このあたりもまたご共有していければと思います)。
