### ISSUE TITLE
リスク算出をUIに繋ぎ込む

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#673]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

リスク算出を #671 #672 で実装中だが、リスクに応じたUI（ #645 #647 ）への繋ぎ込みが行われていない。

## 解決策についてお書きください / Describe the solution you'd like

リスク算出の仕組みを「リスクの高い接触有り」「リスクの極めて低い接触あり」「接触無し」それぞれのUIに繋ぎ込む。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

やる。

**Comment by keiji** [comment]
@daisuke-nogami 
今見たら接触の可能性の行で「14分間の接触」となっていました。スコアは2100です。
これ今は切り捨てなので、切り上げで15分になるかやってみます。

![Screen Shot 2022-01-17 at 14 53 00](https://user-images.githubusercontent.com/932136/149723895-eaec2bd8-6c6e-4e76-9b80-9d3b78645c87.png)

**Comment by keiji** [comment]
元データがきっかり840秒ですね。DailySummaryとExposureWindowsを出します。

**Comment by keiji** [comment]
```
{
  "daily_summary": {
    "DateMillisSinceEpoch": 1642377600000,
    "DaySummary": {
      "MaximumScore": 2100.0,
      "ScoreSum": 2100.0,
      "WeightedDurationSum": 2100.0
    },
    "ConfirmedClinicalDiagnosisSummary": {
      "MaximumScore": 0.0,
      "ScoreSum": 0.0,
      "WeightedDurationSum": 0.0
    },
    "ConfirmedTestSummary": {
      "MaximumScore": 2100.0,
      "ScoreSum": 2100.0,
      "WeightedDurationSum": 2100.0
    },
    "RecursiveSummary": {
      "MaximumScore": 0.0,
      "ScoreSum": 0.0,
      "WeightedDurationSum": 0.0
    },
    "SelfReportedSummary": {
      "MaximumScore": 0.0,
      "ScoreSum": 0.0,
      "WeightedDurationSum": 0.0
    }
  },
  "exposure_widndows": [
    {
      "CalibrationConfidence": 3,
      "DateMillisSinceEpoch": 1642377600000,
      "Infectiousness": 2,
      "ReportType": 1,
      "ScanInstances": [
        {
          "MinAttenuationDb": 27,
          "SecondsSinceLastScan": 300,
          "TypicalAttenuationDb": 29
        },
        {
          "MinAttenuationDb": 28,
          "SecondsSinceLastScan": 300,
          "TypicalAttenuationDb": 31
        },
        {
          "MinAttenuationDb": 26,
          "SecondsSinceLastScan": 240,
          "TypicalAttenuationDb": 29
        }
      ]
    }
  ]
}
```

**Comment by daisuke-nogami** [comment]
こちら、今のパラメータでは端末を50cm以内など非常に近接させた時には、15分未満でも閾値を超えることがあるためですね…（多様な端末で、1m/2mを区分しつつ1mを漏らさず検知するためには、「15分未満で閾値を超えないようにする」のは難しいと考えます）
考慮漏れすいません。

現時点で、「濃厚接触者にあたる可能性があり行政検査の対象とする」ときの条件としては15分以上となる必要がありますので、条件判定にExposure Windowの接触時間の合計を足す必要があり、その場合には、閾値以下の信号検知を表示する画面についても、閾値を超える数値が表示されてしまうので、表示の修正が必要ですね。

表示修正を少し検討してみます。

**Comment by keiji** [comment]
いっそ1mと言う記述をはずして、条件をぜんぶ表示するようにしましょうか。


※ 現在の基準値は1170以上のスコアです。

※ 現在の基準値は1170以上のスコア、かつ15分以上の時間です。

※ 現在の基準値は1170以上のスコア、かつ15分以上の時間、かつ20db以上の電波強度（減衰）です。

みたいなイメージです。
一般利用者にはわかりにくいですか…？

**Comment by daisuke-nogami** [comment]
確かに、接触通知を出さなかった画面で出すなら

> ※現在の基準値は1170以上のスコア、かつ15分以上の時間です。

が正しくて1番よさそうな表現ですね。
アプリの説明として「1m以内15分以上の接触を通知する」ことが掲げられているので、
軽い理解でよい利用者なら「この組み合わせが1ｍ以内を判断する条件なのか」と思うでしょうし、
もう少し詳しく知りたい方には、スコアの説明をひと言でするのは難しいので、アプリ外で解説する必要がありますし…

**Comment by daisuke-nogami** [comment]
#754 としてissueを立てました！

**Comment by keiji** [comment]
こちらは完了してCOCOA v2.0.0としてリリース済みなのでクローズします。
