### ISSUE TITLE
接触状況確認画面のテキスト調整

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#678]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

https://github.com/cocoa-mhlw/cocoa/pull/647#pullrequestreview-849219859

このあたりの調整事項を担当するIssue

## 解決策についてお書きください / Describe the solution you'd like

変更（調整）する。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

テキストは翻訳をお願いしたあと、再反映することになるので、開発チームにお任せする。
けれど、画面への収まりとかも見たいので、こちらでも対応するのが良いと思う。

## その他 / Additional context

![Screen Shot 2022-01-14 at 10 12 45](https://user-images.githubusercontent.com/932136/149434173-35c0a296-7305-48ce-8459-b5bbe5f76bf4.png)

**Comment by keiji** [comment]
これも考える
https://github.com/cocoa-mhlw/cocoa/pull/674#discussion_r782670045

**Comment by keiji** [comment]
https://github.com/cocoa-mhlw/cocoa/pull/647#discussion_r782175011

```
陽性登録者のスマートフォンの信号を受信しましたが、数m以上離れておりリスクはありません。行動圏内には陽性登録者がいましたので、引き続き感染予防に留意しながらお過ごし下さい。
↓
陽性登録者のスマートフォンの信号を受信しましたが、信号のリスクスコアは閾値を下回っていました。行動圏内には陽性登録者がいましたので、引き続き感染予防に留意しながらお過ごし下さい。
```

「閾値」という言葉は専門用語に近いので、より一般的な用語に改めた方が良いと思います。「基準値」とかどうでしょう。

また、伝えたいのは「基準値を下回っていた」と言うこともそうですが、言葉を返すと「基準値を超える信号はなかった」と言うことでもあるので、利用者に不安を与えタンク内場合は、そのように言い換える手もあるかと思います。

**Comment by keiji** [comment]
https://github.com/cocoa-mhlw/cocoa/pull/647#discussion_r782177065

```
14日間のうちに、リスクが低いものを含め陽性登録者との接触はありません
↓
14日間のうちに、陽性登録者の端末からの信号を受信していません
```

「端末」「スマートフォン」の表記揺れがあります。スマートフォンに統一するのはどうでしょうか。

**Comment by keiji** [comment]
https://github.com/cocoa-mhlw/cocoa/pull/647#discussion_r782179688

> 最終的には #646 の "DailySummary_DaySummary_ScoreSum" を読む必要がある（がv2.0では閾値 1170 をベタ打ちか）

設定ファイルから読まないといけませんね。別途Issueで対応します。

**Comment by keiji** [comment]
https://github.com/cocoa-mhlw/cocoa/pull/647#discussion_r782180972

> ※スコアは、信号強度と受信時間を元に算出されており、1m以内・15分以上の接触があると 1170 以上になります。

受動態を避け、一文を短くすることで理解しやすくなる傾向にあるので、次のように記述するのはどうでしょうか。

> ※スコアは、受信した信号の強さと時間から算出しています。1m以内・15分以上の接触で 1170 以上になるように設定しています。

**Comment by keiji** [comment]
https://github.com/cocoa-mhlw/cocoa/pull/647#discussion_r782181516

> （20.0以上が濃厚接触の可能性の通知対象）

「COCOAの通知＝濃厚接触 **ではない** 」ということは重要なので、この点、修正の必要があると考えます。

**Comment by keiji** [comment]
画面タイトルの「接触確認の動作状況」も、機能の名前であって利用者が知りたい情報ではないと考えます。

シンプルに「陽性登録者との接触状況」にするか、それだと接触の可能性と混同される（この画面はリスクが低いという話なので）ことを避けたいなら「基準値を超える接触はありません」とかどうでしょうか。

**Comment by keiji** [comment]
ここまでの提案を組み込んだらこんな感じになります。
表示スコアが高いのは無理矢理この画面を表示しているからで、実際には「接触がありました」の画面が表示されるはずのデータです。

「陽性登録者のスマートフォンから受信した信号は基準値を下回っていました」これ長すぎるのでもう少し短くしたい。

![Screen Shot 2022-01-14 at 10 55 20](https://user-images.githubusercontent.com/932136/149438132-8bfda820-c008-4ac4-9f74-dd8c9b891e49.png)

![Screen Shot 2022-01-14 at 10 55 35](https://user-images.githubusercontent.com/932136/149438148-bd6821cc-0782-4d10-b903-69f643fbb459.png)

**Comment by daisuke-nogami** [comment]
メッセージの「！」マークを外し、背景も白色に変更をした方がよい（という個別提案をいただき同感でしたので反映した方がよい）と思います。

「！」マークと黄色にしていたのは、もともと、「過去14日間の接触」画面と別の画面だったので信号を受信している/していないで差をつけるためのものでしたが、
「過去14日間の接触」で濃厚接触の可能性通知と同じカテゴリの画面に入ると、「濃厚接触の可能性」と同じマークでは逆のメッセージになってしまうためです。

**Comment by keiji** [comment]
Pull Request #712 だしました。

@daisuke-nogami 
引き続きテキスト・デザイン調整しましょう。やっぱり元に戻してでも大丈夫です。

@kazuhiro4949
このリポジトリの featureブランチとして作っているので、もし何か変更あれば直接pushしてしまってください。

**Comment by daisuke-nogami** [comment]
変更案のpull-requestで良いと思いましたのでapproveしてきました！
