### ISSUE TITLE
[COCOA2] Menuからの接触状況確認ページへの遷移

### ISSUE THREAD

**Issue by kazuhiro4949** [cocoa-mhlw/cocoa#681]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

こちらのissueに合わせてメニューからの導線もつける

https://github.com/cocoa-mhlw/cocoa/issues/678

## 解決策についてお書きください / Describe the solution you'd like

メニュー項目としてExposureCheckPageへの遷移を追加する

## その他 / Additional context

- Menu用のアイコンを作成する必要がある

**Comment by keiji** [comment]
これメニュー（ドロワー）からの導線付けるって画面の検討にありましたっけ。

**Comment by daisuke-nogami** [comment]
当初の検討での導線は週次の通知でしたが、通知が未実装なこと・通知を消しても確認できる必要があることから
どこかに導線をつける必要がありまして、1番汎用的であろうメニュー（ドロワー）を選択したものです。

導線をつけうる場所
- メニュー（ドロワー）
- ホーム画面の「動作中」の近辺
- 「陽性者との接触結果確認」画面
- 週次の通知

**Comment by keiji** [comment]
本来ホーム画面から遷移する（ホーム画面の下にある）画面に、上位のドロワーから直接遷移できるのは、アプリの構造に関する誤ったメッセージを利用者に与えて混乱の元なのでやめましょう。

1. ホーム画面からハイリスクな接触が**あれば**、まずそれを提示する（ContactedNotifyPage）。
2. ハイリスクな接触がない場合はリスクの極めて低い接触が**あれば**提示する（ExposureCheckPage）。
3. 接触がなければ「接触無し画面」を表示する（ExposureCheckPage）。

これでいいと思います。理由は次に書きますね。

----

ドロワーは、UIの中でかなり上位の位置です。
接触確認アプリの主要機能は「接触確認」と「陽性情報登録」ですが、そのどちらの機能についてもドロワー内にメニューとして設けられていません。

ハイリスクな接触が存在する期間は、ハイリスクな接触だけを1.の画面で表示すればよく、併せて2.の画面を確認する必要性はないと考えます。1.の画面が出ている時点で接触確認機能が動いていることは明白ですし、1.と2.で比較したときに2つの画面の重要性は等価ではないからです。

仮に1.が表示されるイベント後に、別のイベントとして2.が表示されたとします。後から表示される2.には「極めてリスクの低い」と表示されるわけです。このとき、1.の表示が優先なのか、2.の画面が優先なのか、利用者が混乱する危険があります。UI位置づけ的にはドロワーの中にある2.の方が優先ということになってしまいます。

**Comment by daisuke-nogami** [comment]
ありがとうございます。
こちらご提案の通りに進めることで調整すすめて行きます。
理由は、いただいた理由に加えて、

> ・将来的な改変を考えると、ナビゲーションは極力シンプルにしておきたい
> 　仮にドロワーを開いて確認するメンタルモデルが確立されると取り除く場合の障壁となると思います。

というご意見も加えて、となります。

そして、この調整が発生した背景には、COCOAというツールの目的に対する認識があっていない
（あけすけにいうなら省内でも深く考え切れていない）こともあるように思いました。

元々は「自分にリスクがあるときに教えてくれるアプリ」に止まっていましたし、
未知の感染症で、情報があっても適切な行動を選べなかったこともあり
情報量・情報開示範囲を絞り込む必要も強く、その発想が抜けきっていない所があります。
一方、知見の蓄積や社会側の対応の進展（検査を受けやすいなどの直接的なものだけではなく、
リモートでの勤務・生活が出来る体制なども少しずつ整ってきた）を踏まえると、もう少し
「周囲の状況をしるダッシュボードアプリ」として活かしていただいて適切な行動を生み出したい、
という要望も確実に大きくなってきております。

そのあたり、目的に立ち返って共通認識を作りながら、枝葉の部分で妙なブレがおこらないように
調整をしていきます。
よろしくお願いいたします。
