### ISSUE TITLE
ライセンスファイルの管理について方針を決める

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#69]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?
ライブラリーの追加や削除などによってライセンスファイルの記述に変更があった場合、どのように管理するか方針を決める必要がある。

#9 でやりとりした結果、現状は利用しないライセンス関係のファイルがアプリのリソースに含まれていることがわかった。

ライブラリーの追加や削除によってライセンスファイルの更新は必要になるので、ライセンスの記述に変更がある場合「どこを変更すればいいのか」を明確にして、あらかじめコントリビューターに知らせた方が良い。

## 解決策についてお書きください / Describe the solution you'd like
ライセンスの更新があっときに、どのファイルを変更するかを定めて、わかりやすい場所に記載する。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered
Androidアプリなら自動的に使っているOSSライブラリーを検索して、ライセンスやCopyrightを作成してくれるプラグインがあるけど、Xamarinではよく知らないのでまた調べてみます。

 * License Tools Plugin for Android: https://github.com/cookpad/LicenseToolsPlugin
 * OSS Licenses Gradle Plugin: https://github.com/google/play-services-plugins/tree/master/oss-licenses-plugin
----
Internal IDs:
- Feature 2942
- NFR 2860
- NFR 2290
- NFR 1470

**Comment by b-wind** [comment]
ふと気がついたのですが、COCOA アプリからは「COCOAアプリ自体のライセンス」を簡単に知る方法がないですね？
設定 -> ライセンス から辿れるのは 3rd party ライセンスの一覧なので。
（よくある質問にあるかもですが、ぱっと見で探せない……）

**Comment by keiji** [comment]
ライセンス情報は`COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md`に集約します。

ライセンスに更新があった場合、ファイル`COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md`をHTMLに変換したものを`license.html`として、プラットフォームそれぞれ次の場所に配置します。

 * Android
   * `/Covid19Radar/Covid19Radar.Android/Assets` ディレクトリ
 * iOS
   * `Covid19Radar/Covid19Radar.iOS/Resources` ディレクトリ 

現状、ライセンスファイルの変換はGitHub Flavorであればよく、手動で行っている。これはライセンスの変更が週一程度の頻度では起こらないと考えているため。頻繁に発生するようであれば（それは開発工程を考え直した上で）、CIでの変換を検討する。

のようなことをWikiに書いたらこのIssueはCloseします。

**Comment by keiji** [comment]
https://github.com/cocoa-mhlw/cocoa/wiki/COCOA%E3%81%8C%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%A6%E3%81%84%E3%82%8BOSS%E3%81%AE%E3%83%A9%E3%82%A4%E3%82%BB%E3%83%B3%E3%82%B9%E6%83%85%E5%A0%B1%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

書きました。
