### ISSUE TITLE
同意時にサーバーからユーザーに渡される UserUuid の問題

### ISSUE THREAD

**Issue by moonmile** [cocoa-mhlw/cocoa#7]
接触管理アプリ COCOPA をインストールした後、同意を行ったときに、サーバーから UserUuid というものが渡されるようです。

コードを見るとこの UserUuid を陽性者登録するときにも使っているのですが、ユーザーを特定できる可能性があるコードですので、取り除いたほうがよいのではないでしょうか。

- UserDataModel 
   - https://github.com/cocoa-mhlw/cocoa/blob/master/Covid19Radar/Covid19Radar/Model/UserDataModel.cs

```c#
    public class UserDataModel : IEquatable<UserDataModel>
    {

        /// <summary>
        /// User UUID / take care misunderstand Becon ID
        /// </summary>
        /// <value>User UUID</value>
        public string UserUuid { get; set; } // ※

        /// <summary>
        /// Secret key
        /// </summary>
        /// <value>Secret Key</value>
        public string Secret { get; set; }

        /// <summary>
        /// Jump Consistent Seed
        /// </summary>
        /// <value>Jump Consistent Seed</value>
        public ulong JumpConsistentSeed { get; set; }

        /// <summary>
        /// StartDate
        /// </summary>
        public DateTime StartDateTime { get; set; }
```
### 参照先

- 同意するときの呼び出し PostRegisterUserAsync 
	- PostRegisterUserAsync
		- https://github.com/cocoa-mhlw/cocoa/blob/master/Covid19Radar/Covid19Radar/Services/HttpDataService.cs#L44
- 陽性者登録するときの呼び出し UploadSelfExposureKeysToServerAsync
	- UploadSelfExposureKeysToServerAsync
		- https://github.com/cocoa-mhlw/cocoa/blob/master/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L223
	- CreateSubmissionAsync
		- https://github.com/cocoa-mhlw/cocoa/blob/master/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L263
	- DiagnosisSubmissionParameter
		- https://github.com/cocoa-mhlw/cocoa/blob/master/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L288

ご検討をお願いします。

**Comment by rocaz** [comment]
このuserUuidの利用を続けると全利用者における不用意なプライバシー侵害へ繋がる可能性があり、またこの存在は厚労省のプラポリにも記載がありません。
https://www.mhlw.go.jp/stf/seisakunitsuite/japanese_pp_00027.html
単に「陽性者登録の取消」(オプトアウト)を行いたい場合には、Googleのリファレンスにあるように、発行した処理番号を単純に使うのでは無く、OTPとして一旦Verification Serverにて確認後「陽性者にのみ」厚労省による署名済みJWT(JWS)を一度発行し、これを持って実際の陽性者登録を行うことで「関係の無い全利用者」にユニークキーを発行すること無く陽性者だけからのオプトアウトが確実に可能と出来ます。
https://google.github.io/exposure-notifications-server/design/verification_protocol

**Comment by b-wind** [comment]
コードへのリンクがmasterを参照しているため、Issue 記述当時とズレが生じている様に思います。
Issue 作成時点の日付から v1.1.1 を参照していると仮定し、v1.2.2 との差分を提示します。

- UserDataModel
  - https://github.com/cocoa-mhlw/cocoa/blob/b03037f5c2e21256e69b3eb291b6a68d66f0c076/Covid19Radar/Covid19Radar/Model/UserDataModel.cs#L16-L20
  - https://github.com/cocoa-mhlw/cocoa/blob/047b12bfc497e5e32bd96e24c2b5d76c8ca18bcf/Covid19Radar/Covid19Radar/Model/UserDataModel.cs#L8-L16

- PostRegisterUserAsync.HttpDataService
  - https://github.com/cocoa-mhlw/cocoa/blob/b03037f5c2e21256e69b3eb291b6a68d66f0c076/Covid19Radar/Covid19Radar/Services/HttpDataService.cs#L43-L69
  - https://github.com/cocoa-mhlw/cocoa/blob/047b12bfc497e5e32bd96e24c2b5d76c8ca18bcf/Covid19Radar/Covid19Radar/Services/HttpDataService.cs#L51-L72

- UploadSelfExposureKeysToServerAsync.UploadSelfExposureKeysToServerAsync
  - https://github.com/cocoa-mhlw/cocoa/blob/b03037f5c2e21256e69b3eb291b6a68d66f0c076/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L222-L254
  - https://github.com/cocoa-mhlw/cocoa/blob/047b12bfc497e5e32bd96e24c2b5d76c8ca18bcf/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L274-L347
- UploadSelfExposureKeysToServerAsync.CreateSubmissionAsync
  - https://github.com/cocoa-mhlw/cocoa/blob/b03037f5c2e21256e69b3eb291b6a68d66f0c076/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L292-L302
  - https://github.com/cocoa-mhlw/cocoa/blob/047b12bfc497e5e32bd96e24c2b5d76c8ca18bcf/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L381-L390
- UploadSelfExposureKeysToServerAsync.DiagnosisSubmissionParameter
  - https://github.com/cocoa-mhlw/cocoa/blob/b03037f5c2e21256e69b3eb291b6a68d66f0c076/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L292-L302
  - https://github.com/cocoa-mhlw/cocoa/blob/047b12bfc497e5e32bd96e24c2b5d76c8ca18bcf/Covid19Radar/Covid19Radar/Services/ExposureNotificationHandler.cs#L381-L390
  
  
 素人目に見ると、いずれの箇所でもv1.2.2ではUserUuidパラメーターは存在しておらず、当 Issue の懸念は取り除かれたように見えます。
 再度のチェックをお願いしたく思います。

**Comment by moonmile** [comment]
御意。現状の v1.2.2 で UserUuid は取り除かれているので、ここはクローズしていいと思います。

**Comment by cocoa-dev** [comment]
@moonmile さん、ご確認いただきありがとうございます。おっしゃる通り v1.2.2 で解消したのでこの Issue はクローズします。
今後もお気づきの点がありましたらぜひ Issue にてご指摘ください。
