### ISSUE TITLE
不要な画像リソースを削除する

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#70]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?
#41 に関連して、アプリケーションのサイズが多い理由として、重複する画像リソースが含まれていることが挙げられます。

言語に依存しない画像を削除することで、アプリケーションパッケージをよりコンパクトにできると考えます。

## 解決策についてお書きください / Describe the solution you'd like

重複したリソース全部消す。

Androidの仕様上、リソース修飾子を元にResourceManagerが端末や端末の設定に適したリソースを検索します。

 * drawable-xxhdpi
     * image1.png
 * drawable-xxhdpi-ja
     * image1.png

この場合、`image1.png`が同じ内容である場合、`drawable-xxhdpi-ja`の`image1.png`は削除できます（`drawable-xxhdpi`の`image1.png`）が選択される。

iOSもほぼ同様で`Base.lproj`を基準に、差し替えの必要な画像リソースだけを選択する仕組みがあります。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

ありません。

----
Internal IDs:
- NFR 1789
- NFR 1788

**Comment by zipperpull** [comment]
Android の drawable に関してだけ言えば常にリサイズされて
解像度依存しないものは drawable-nodpi に置く方法があるのと、
apk をやめて app bundle にすれば解決されたりするのでは思います

**Comment by keiji** [comment]
Android版はv1.2.3で反映済みです。
本Issueは、iOS版のリリース後にクローズする予定です。

**Comment by keiji** [comment]
v1.2.4でiOS版がリリースされたのでクローズします。

**Comment by keiji** [comment]
iOSの方はまだ取り込まれてなかった… #40 の変更とは別に対応します。
