### ISSUE TITLE
Xamarin Exposure Notificationライセンスの削除とCappuccinoのライセンス追加

### ISSUE THREAD

**Issue by kazuhiro4949** [cocoa-mhlw/cocoa#702]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

EN用のライブラリが差し代わっているのでライセンス情報を更新する
https://github.com/cocoa-mhlw/cocoa/wiki/COCOAが使用しているOSSのライセンス情報について

関連issue:
https://github.com/cocoa-mhlw/cocoa/issues/322

## 解決策についてお書きください / Describe the solution you'd like

- ライセンス情報を更新する

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

-

## その他 / Additional context

-

**Comment by keiji** [comment]
これアプリ内から表示するライセンスですね。
COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.mdの方は更新済みなので、あとはAndroid, iOSが持っているHTMLを更新する。と言う流れになると思います。

ベータ版対応でもしなければならないので、ぼくの方で担当しましょうか？

**Comment by keiji** [comment]
@kazuhiro4949 
こちらどうしましょう

**Comment by kazuhiro4949** [comment]
見落としてました、対応します
