### ISSUE TITLE
陽性者との接触結果確認ボタンを押してから画面遷移までタイムラグがある

### ISSUE THREAD

**Issue by kazuhiro4949** [cocoa-mhlw/cocoa#703]
## 不具合の内容 / Describe the bug

iOSでタップ後すぐに反応せず、少し経ってから画面遷移がされる。
繰り返しタップできるため２重の遷移も発生する。

## 再現手順 / Steps to reproduce

1. ホームに行き、
2. 陽性者との接触結果確認ボタンをクリックし、
4. 繊維がずれる。

## 期待される挙動 / Expected behavior

タップしたらすぐに画面遷移する

## スクリーンショット / Screenshots

https://user-images.githubusercontent.com/18320004/149348061-4c305408-6fea-46c2-a9bb-b207e480cc3b.MOV

## 動作環境 / Environments

- デバイス：iphone12promax
- OS：iOS
- バージョン：15.2

## その他 / Additional context

デバッグ環境のみで発生する問題かは不明

**Comment by keiji** [comment]
こちら確認しました。

ContactedNotifyPageViewModelの`Initialize`上で重めの処理をしているので、ボタンを押してから表示されるまで時間がかかっているようです。

この処理を非同期にして、まずは画面遷移を終えてProgressDialogを表示、準備ができ次第画面を更新…とすると体験は改善しそうですね（本当はダイアログじゃなくて画面に読み込み中表示を出したいけど、ダイアログでも今よりはかなりいい感じの動きになると思います。このあたり事前計算も含めて継続的に考えていきたいです）。

**Comment by kazuhiro4949** [comment]
↑の状態が発生しているのは遷移前の接触結果確認のときでした。
Configの通信などが行われた時にラグが発生するケースが出そうです。

CommandやInitializeのイベント自体はasyncとなっており、非同期に実行はされていました。

ボタンはユーザー操作にあたるものでレスポンスが必要なため、押したらUserDialogsのShowLoadingを呼んで完了したらHideするで検討しています。
遷移後は画面表示が一瞬遅延する可能性がありますが、連続で画面全体を覆う読み込みを表示させるのも良くないのと少ししたら表示されるので一旦そのままにしようと思います。
