### ISSUE TITLE
`infectiousness_when_days_since_onset_missing` の値について確認

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#705]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

#696 を元に、各Configurationをフォールバックする設定を #704 にて調整中です。

`apple_exposure_config_v2`, `google_diagnosis_keys_data_mapping_config` における `infectiousness_when_days_since_onset_missing` の設定値について現在は `1 = Infectiousness.Standard` となっていますが、これは `2 = Infectiousness.High` が適切ではないかという確認です。

この値（ `infectiousness_when_days_since_onset_missing` ）は、診断キーに `DaysSinceOnsetOfSymptoms` が設定されていないときの感染性をどのように扱うかを決めておく値です。

「`DaysSinceOnsetOfSymptoms` が設定されていないとき」とは「COCOA1系からの陽性情報登録」と考えてもらって差し支えありません。

COCOA1系が診断キーを送る範囲は、発症日または検査日からおおよそ2日前（時差を考慮して3日前）からとなっています。

この設定を`infectiousness_for_days_since_onset_of_symptoms` に当ててみると、-3, -2, -1に割り当てられている値は今は `2 = Infectionsness.High` です。

このことから、COCOA1系からの陽性情報登録の診断キーとの互換性を高く保つためには `infectiousness_when_days_since_onset_missing` を `2 = Infectionsness.High` に設定する方が表現として適切と考えました。

「表現として適切」とする理由は、現在の設定ではどちらであっても `InfectiousnessWeights` に違いはなく、結果に影響を及ぼさないと考えているためです。

一方、現在の`infectiousness_for_days_since_onset_of_symptoms` では +10 を超える値については `0 = Infectiousness.None` が割り当てられています。
COCOA1系においては、送信する診断キーの始期でフィルタリングしますが、終期ではフィルタリングしておらず+11以降も送ってしまいます。その場合、COCOA1から登録されている診断キーについては +11 以降も高い感染性を有しているとして接触確認されることになります（ただ、これについてはInfectiousness.Standardでもあまり変わらないので「最新のCOCOA2で陽性情報登録してね」と言い続けるしかない気はします）

## 解決策についてお書きください / Describe the solution you'd like

表現として正しい方向に設定しておく。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

今のままいく。

とはいえ、当該設定は1週間に一回しか設定できない制約があるので、なるべく再設定は発生しないようにしておきたいと考えています。

**Comment by daisuke-nogami** [comment]
こちら、COCOAの位置づけを側の定義としても、おっしゃるとおりデフォルト値はHighが正しいと考えました。
具体的な設定も含めてApproveします！
