### ISSUE TITLE
プロダクト版で陽性情報登録ができない

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#711]
## 不具合の内容 / Describe the bug

開発チーム・サーバー監視チームよりアラート。

本日 11:44 より、陽性情報登録の完了（登録成功）レスポンスをしていない状況。

リリースしているCOCOA（プロダクト版）で陽性情報登録ができない。正しい処理番号を入力しても「処理番号が違うか…」と表示されて陽性情報登録が完了しない。

## 再現手順 / Steps to reproduce

陽性情報登録をする。

AppLinks経由でも、手動入力でも同じと考えられる。

## 期待される挙動 / Expected behavior

処理番号が正しければ、陽性情報登録が完了する。

## 動作環境 / Environments

- デバイス： すべてのデバイス
- OS：Android / iOS
- バージョン：すべてのバージョン

## その他 / Additional context

COCOAのアプリをはじめ、陽性情報登録サーバーについてリリースをしていない認識。

陽性情報登録サーバーのバックエンドにある処理番号を確認するサーバーから「処理番号が違う」レスポンスが返ってきていることを確認。

当該サーバーは、開発チームの管轄外のため現在詳細確認中。

**Comment by keiji** [comment]
15:04頃から、正常登録がログに出力されることを確認。以前失敗しているケースもあるとのこと。

**Comment by keiji** [comment]
状況の共有です。

処理番号発行数（陽性者数）の急増により、SMSの送信が追いついていない。
処理番号が発行されてから、実際に陽性者の手元に届くまでに有効期限（現在は1時間）が経過しているため、今回の事象が発生していると思われる。

**Comment by keiji** [comment]
今後同様の事象の発生を防止するための方策の一つとして、まずはSMS送信のキャパシティ拡張する措置を行う連絡を受けています。

より厳密に言うと、SMS送信機能はほかの用途でも陽性者への連絡に使っている。今回はCOCOAの処理番号のSMS送信について分割する措置をするとのことです（別のサーバーを割り当てる？　詳細は未確認

**Comment by b-wind** [comment]
単純に疑問に思ったのですが、「処理番号の有効期限切れ」というレスポンスが返ってくるわけではないのですね。

**Comment by keiji** [comment]
「処理番号を確認するサーバー」についてはCOCOAの境界を超えるので言えることが少なくなるのですが、
たとえば「メールアドレス」と「パスワード」の組み合わせでログインするシステムがあったとして、入力したメールアドレスはシステムに存在しない（登録されていないとき）に「アカウントがありません」、メールアドレスは存在するけどパスワードが異なるときに「パスワードが違います」と表示してしまうと、アカウントの存在を知られてしまうので、すべて一括で「メールアドレスまたはパスワードが違います」のような取り扱いにする。のに似ていますね。

公開されている情報からの推測になりますが、先日のプライバシーポリシー改訂まで期限切れの処理番号は削除されていたので、期限切れか存在しないかをサーバー自身も判別できなかったのもありそうです。

今回はSMSの送信の滞留を改善して対応となりましたが、期限そのものの見直しが必要という意見はかねてより出ています。今回の出来事を機に再度検討する流れになりそうです。

**Comment by b-wind** [comment]
> 先日のプライバシーポリシー改訂まで期限切れの処理番号は削除されていたので、期限切れか存在しないかをサーバー自身も判別できなかったのもありそうです。


なるほど、そう言う処理だった可能性があるのですね。
様々な要件と検討の結果なのだと思いますし、現時点で特に要望等はありません。


それとは別に処理番号の通知は遅れれば遅れるほど陽性者登録もずれ込みますし、デメリットは大きそうに思います。
SMS送信のキャパシティを増やす方向は適切な対処と感じました。

**Comment by keiji** [comment]
本日午後より、現象の再発が確認されています。
確認したところ、やはりSMSの送信数の増加により遅延が発生しているとのことです。

SMSサーバーをさらに増強する事に加えて、追加の対応策についても検討中です。

**Comment by keiji** [comment]
発生から10日経ち、2度目の週末については特段エラー率が上がることもなかったと聞いています。

SMSサーバーの増強が効果を上げているようです。
本Issueをクローズし、引き続き追加の対応策について検討を進める予定です。

**Comment by keiji** [comment]
サーバーチームより、現象の再発が報告されたのでreopenします。

現象としては「陽性情報登録サーバー経由で処理番号を確認しているサーバーに対する問い合わせがすべてタイムアウト」というものです。

22:45～23:14まで発生しており、現在は改善傾向にあります。

**Comment by keiji** [comment]
2月からは同様の事象は発生したいないので本件Closeします。

再び発生したときは別にIssueを作ります。
