### ISSUE TITLE
陽性情報の再試行時に「しばらくそのままでお待ちください」ダイアログが表示されない

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#716]
## 不具合の内容 / Describe the bug

COCOA1では、陽性情報登録のときに処理番号の不一致などの理由でサーバーから失敗が返された後、再度「登録する」ボタンを押すと、

「登録を開始します
しばらくそのままでお待ちください」

と表示され、実際にサーバーにアクセスする前に一定時間のDelayを設けている。

また、陽性情報登録に３回失敗すると、

「登録回数の上限に達しました。
アプリを終了します」

と表示してアプリ自体を強制終了する。

COCOA2では、これと異なる挙動をしていて、登録は何回でも試すことができるし、規定回数はなく、アプリを強制終了しない。

## 再現手順 / Steps to reproduce

陽性情報登録画面から正しくない処理番号を入力して陽性情報登録を試みる。

## 期待される挙動 / Expected behavior

これ個人的にはCOCOA1の挙動に違和感があるので、可能であれば、COCOA2の挙動に変更したいです。

再試行の時に時間をおくのも、規定回数超過で画面を前に戻すのも、おそらく不正登録（総当たり）対策だと思うのだけど、そもそもCOCOAで不正をするモチベーションが想像できません。

AppLinksの導入もあって処理番号の入力ミスは激減したと考えていますが、 #711 のようなことも有るわけで、正しいと確信している番号を入力したときに、これは体験として良くないと思います（もちろん、何度再試行できたとしても、#711 の体験が向上するわけではありませんが…

@daisuke-nogami 
今準備しているテスト計画に、これ系（再試行時にダイアログを…）の確認項目有りますか？
今から変更するのが厳しそうな時のために、ひとまずCOCOA1系に合わせた仕様でPull Reqeust出しますが、可能であれば調整をお願いしたいです。

## 動作環境 / Environments

- OS：Android/iOS
- バージョン：COCOA2

## その他 / Additional context

じゃあ、今のCOCOA2の挙動が意図をしたものかというと、マージ時のミスとかが重なった偶然の産物（ダイアログを表示するロジック自体はコード上に存在するが機能していないだけ）。

現在の挙動を継続するとしても、コードの調整は必要。

**Comment by daisuke-nogami** [comment]
確かリトライ回数を確認するリグレッションテストはなかったので、COCOA2実装のままでも良さそうな気がします。仕様書含めて確認します。

**Comment by daisuke-nogami** [comment]
まだ仕様書は見れていませんが、リグレッションテストでは、delayが起こることの検証は行っておらず、delayをなくすことの障害はなさそうです。
（自分用メモ・シナリオS-4）

リトライ回数の制限ですが、こちらはリグレッションテストで確認しています。
回数制限を完全に外すとすると、陽性登録サーバーの処理の負荷も一応考える必要はあるかと思いました、が、大きな負荷を与えない上限回数を真面目に定義すると100回とか大きな数字になって、検証コストに見合わない仕様になりそうです…
あと、勘違いで誤入力を連打するときには、見直さず何度も連打するのはあるあるで（昔、住基カードをそれでロックした苦い思い出が…）、数回ミスしたときにクールダウンを促すdelayを入れるのはあり、とは思います、が、現行の「強制終了」はやり過ぎですね…

仕様書の記述確認してからではありますが、
- delayと強制終了は不要
- 連続何回かの失敗で何か追加の挙動を入れるかどうかは要検討

かと思いました（出先確認で舌足らず表現すいません）

**Comment by daisuke-nogami** [comment]
仕様書発見しました。操作に関する記述は

> 処理番号の認証に失敗した場合には、エラーメッセージを表示する。

だけでしたので、仕様書には縛られず考えられそうです

**Comment by keiji** [comment]
確認ありがとうございます！

強制終了はやり過ぎにしても、いきなり「無制限にしておきましたのでよろしく」も乱暴かもしれないですね。
以前のPull Request #511 で林さんが、ホーム画面に戻るようにしてくれているので、ここからさらに変えるのも焦りすぎかな（ぼくが）と思い直しました。v2.0.0では遅延有り、ホーム画面に戻る挙動でリリースしてみて利用者の反応を見ましょうか（Twitterとかで）。

ひとまず仕様書に明記してあるわけではないと言うことがわかったのは収穫ですね。ありがとうございます。
