### ISSUE TITLE
ContactedNotifyPageでHTTPClientの例外が発生した際にクラッシュする

### ISSUE THREAD

**Issue by kazuhiro4949** [cocoa-mhlw/cocoa#723]
## 再現手順 / Steps to reproduce

1. 接触確認画面 に行き、
3. リクエストのキャンセルやDNS Lookupのエラーを発生させる 
4. アプリがクラッシュする

## 期待される挙動 / Expected behavior

クラッシュせずに問題が発生したことと問い合わせへの誘導を行う

## 動作環境 / Environments

- デバイス：すべて
- OS：Android, iOS
- バージョン：すべて

**Comment by keiji** [comment]
情報の提供として、今のNotifyOtherPageでは各Region毎に一回のアクセスをしています。これは先んじてExposureWindow modeの陽性情報登録に対応していたデバッグ環境（en-calibration-server）ではregionをBodyではなくURLのパスに指定していたためです。

V3DiagnosisApiではregionはBodyに入れるので、アクセスを各Region毎にする必要はありません。もっと言えば、今のCOCOAは複数regionの指定に対応していないと理解しています（settings.jsonのsupportRegionsが配列ではなく文字列）。

対応についてはtry catchで囲んで例外を取るだけでも良いと思いますし、抜本的に解決するならアクセスそのものを一本化しても良いと思います。

**Comment by kazuhiro4949** [comment]
NotifyOtherPageではなくContactedNotifyPage上でクラッシュしていました

**Comment by keiji** [comment]
あ、サーバーからRiskConfiguration取ってくるときのtry catch漏れ……かな？

もしそうだとしたら、取ってこられなかったときにどうするかですね。

**Comment by kazuhiro4949** [comment]
異常系なので特には何もせず再アクセスとお問い合わせへの案内を表示させるようにしました

https://github.com/cocoa-mhlw/cocoa/pull/725#issuecomment-1013645748

**Comment by keiji** [comment]
ダイアログ表示いい感じですね。
メッセージで「不明なエラー」だと突き放した感じがあるので、例えば

「設定ファイルを取得できません」とかどうでしょう。

タイトル「設定ファイルを取得できません」

メッセージ案１「接触の基準値を設定するファイルを取得できませんでした。ネットワークが不安定か、サーバーが混み合っている可能性があります。ご迷惑をおかけして申し訳ありません。時間をおいて再度お試しください。」

メッセージ案２「時間をおいて再度お試しください。接触の基準値を設定するファイルを取得できませんでした。ネットワークが不安定か、サーバーが混み合っている可能性があります。」

「『お問い合わせ』より動作情報の送信…」と書いてしまうと、一時的な不具合でも問い合わせした方がいいのかなと思ってしまうかもしれないので、まずは初期対応としての「時間をおいて再度お試し」を案内するに留めるのが良いと思います。

案２は、初期対応（利用者がどうすればいいか）を１文目に持ってくることで、全部読まなくてもいいようにした物です。

**Comment by kazuhiro4949** [comment]
設定ファイル取得時のエラーハンドリングはこの辺りに追加したため、
ViewModel上で発生する例外はこちらが把握できているもの以外になります。
そのため扱いとしては想定外の問題をクラッシュさせずにキャッチしておくためのものになります。
https://github.com/cocoa-mhlw/cocoa/pull/725/files#diff-23e5a2c74f15e6092efc9fc53f350a3d2de52fbbbf72b0f29324c8d04364ef55R141-R143

時間を置いて再アクセスを促す意図で以下の文言でいかがしょうか。
ネットワークの問題の可能性は低いのですが、再アクセスしてもらう理由をつけるために入れています。

「確認画面へのアクセスに失敗しました」
「ご迷惑おかけして申し訳ありません。ネットワークが不安定か、サーバーが混み合っている可能性があります。時間をおいて再度お試しください。」
