### ISSUE TITLE
`./github/ISSUE_TEMPLATE/config.yml` の修正

### ISSUE THREAD

**Issue by Meiryo7743** [cocoa-mhlw/cocoa#73]
## 不具合の内容 / Describe the bug

以前マージされた PR #48 で [`./github/ISSUE_TEMPLATE/config.yml`](https://github.com/cocoa-mhlw/cocoa/blob/master/.github/ISSUE_TEMPLATE/config.yml) を追加しました。ところが，「その他」のメニューが全く現れず，本来の役割を果たせていません。

## 再現手順 / Steps to reproduce

1. <https://github.com/cocoa-mhlw/cocoa/issues/new/choose> にアクセスする

## 期待される挙動 / Expected behavior

この現象について [GitHub Community](https://github.community/t/support-for-mailto-in-github-issue-template-config-yml/169752) で尋ねたところ，`mailto:` で始まるリンクは非対応とのことでした。また，現状可能な解決策として，短縮 URL に変換することを提案されました。

これを踏まえ，今の状態を解消するためには以下の 2 つの方法が考えられます。

- `mailto:` のリンクを短縮 URL 化したものに置き換える
- Q&A のリンクに差し替える

前者の場合，期待通りの動作を得られます。一方，短縮するにあたっては外部サービスを利用する必要があり，厚労省のメールアドレスを含むリンクをそうしても良いのか（個人的に）気になるところです。

後者のように `README.md` に記載のものと同じリンク先に修正する方法も解決策として挙げられます。ただ，こちらは厚生労働省のページからユーザー自身の手でそのアドレスを探し出してもらう形になり，直接的でないことがネックです。

## その他 / Additional context

※『COCOA』のアプリケーション自体には影響しない内容ですので，対応は後回しで構いません。

**Comment by Meiryo7743** [comment]
https://github.com/cocoa-mhlw/cocoa/blob/b823e87df6986d91d2b06b6ff9a4b2b94bf5c0e4/.github/ISSUE_TEMPLATE/config.yml#L3-L5

要修正箇所は 4 行目のところです。

**Comment by keiji** [comment]
Descriptionにも記載があるようにアプリの動作には影響がないのでbugを割り当てるのには迷いがありましたが、指定が機能していないという意味でbugを割り当てました。

提案のあった2つの方法だと、ぼくは「Q&Aへのリンク」が妥当と思います。
GitHubがサイトへのリンクを意図して`./github/ISSUE_TEMPLATE/config.yml`の機能を設計したのであれば、それに沿った運用をした方がいいと考えています。

**Comment by b-wind** [comment]
@keiji 「GitHub のcocoaリポジトリ運用に関するもの」という意味合いのラベルを作って割り当てるのが良いと思います。


どこかにリンクを張るという意味では、CONTRIBUTING.md へのリンクが良いのかなと。

CONTRIBUTING.md の側でも「技術的な内容以外の〜」項目を一つ格上げして書いた方が意図が伝わりやすくなるかなと思います。
https://github.com/cocoa-mhlw/cocoa/blob/master/CONTRIBUTING.md

**Comment by Meiryo7743** [comment]
@keiji

ラベルについてですが，この場合は「documentation」の方が適切かと……。今付けられている「bug」は，どちらかというと，アプリ自体の動作が異常なことを指摘する issue のために用いられるのが適当と考えています。

**Comment by b-wind** [comment]
このIssueとは直接関係ないですが、ラベルが表す意味とか GitHub の運用自体についての意見・質問はどこに出すのが良いのだろうかと言う疑問を持ちました。

**Comment by keiji** [comment]
ありがとうございます。documentationに変更しました。
ぼくはラベル機能をフィルター用途に使っています。「運用」については他の課題とセットで（付随して）語られることがほとんどで「運用」のラベルだけでフィルターして見たいという需要は僕自身にはなかったりしますね。

現時点でラベルを付ける権限はCollaboratorが持っていますね。ラベルが表す意味については、今回僕が bug を付けてMeiryo7743さんの助言で訂正したように、適宜そのIssue内で話し合っていけばいいと考えています。運用に関してもしかりで「こういう課題がある。こうするともっと良くなるよ」というのはIssueにしてもらえればと思います。

**Comment by b-wind** [comment]
すでに付いているラベルの意味もよく分からなくて、 この Issue に waiting-for-confirmation が付いているのはどう言う意味なんでしょう？
意味が分からないケースが多いので自分は何かをフィルタする為に使う事は今は出来なさそうです。

**Comment by keiji** [comment]
@b-wind 
このコメント内で他のCollaboratorの意見も聞いているので、そちらの反応待ちという意図で waiting-for-confirmation を付けています。
https://github.com/cocoa-mhlw/cocoa/issues/73#issuecomment-805320061

各ラベルの意味については、Issue一覧のLabelをクリックするとラベルの一覧とDescription見られます。

**Comment by b-wind** [comment]
> このコメント内で他のCollaboratorの意見も聞いているので、そちらの反応待ち

ここが分からなかったので一つ理解が出来ました。
反応待ちなので、議論はストップしないといけないのかと思っていました。

> 各ラベルの意味については、Issue一覧のLabelをクリックするとラベルの一覧とDescription見られます。

どれも主語が曖昧すぎてやっぱり理解するのは難しそうです。

**Comment by Meiryo7743** [comment]
@b-wind @keiji 

おっしゃる通り，補佐官のお二人の意見を頂戴できるまで待つしかなさそうです。回答を得次第，PR を作ろうと考えております。

---

なお，（これまでの流れで話題に上った）このリポジトリの運用に関する事柄については，本件とは別に issue を建てていただくか，discussions を有効にし，そこで熟考なさるのが良いかもしれません。

また，ラベルの一覧及び使用目的の説明は <https://github.com/cocoa-mhlw/cocoa/labels> からご覧になれます。

**Comment by halsk** [comment]
反応遅くなり失礼しました。
直接メールアドレスよりは、厚労省のQ&Aに行くのが良いかと思いますが、あのページにいきなり飛ぶのは動線としてわかりにくいですよね。
@b-wind さんから提案いただいたように、以下の方向性が良さそうですがいかがでしょうか。

* config.yml では一旦 CONTRIBUTING.md に飛ばす
* CONTRIBUTING.md を組み替える

```
技術的な内容以外のご要望、ご意見などは Q&Aページに記載がありますお問い合わせメールアドレスにご連絡いただきますようお願い致します。
技術的な内容以外の Issue 、COCOAの改善に関係がないと思われるご意見については、コメント無しにクローズさせていただくことがありますのでご了承ください。
```

を抜き出し、以下のようにする

```
## 技術的な内容以外のご要望・ご提案について
技術的な内容以外のご要望、ご意見などは [Q&Aページ](https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/covid19_qa_kanrenkigyou_00009.html)に記載がありますお問い合わせメールアドレスにご連絡いただきますようお願い致します。
技術的な内容以外の Issue 、COCOAの改善に関係がないと思われるご意見については、コメント無しにクローズさせていただくことがありますのでご了承ください。
```

**Comment by Meiryo7743** [comment]
@halsk 

ご返信ありがとうございます。それで良いと個人的に思っております。

ただ，一つだけ申し上げると，Q&A ページの URL ではなく，メールアドレスが記載されているセクションまで遷移するリンクの方が適切と思われます。あのページの目次は，どういうわけか二段階仕掛けになっていて，多くの人に混乱を招く恐れがありますので……。

具体的には，`https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/covid19_qa_kanrenkigyou_00009.html` を `https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/covid19_qa_kanrenkigyou_00009.html#Q8-1` にして，よりスムーズな誘導にしたいところです。どうでしょうか……？

```md
## 技術的な内容以外のご要望・ご提案について
技術的な内容以外のご要望、ご意見などは [Q&Aページ](https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/covid19_qa_kanrenkigyou_00009.html#Q8-1)に記載がありますお問い合わせメールアドレスにご連絡いただきますようお願い致します。
技術的な内容以外の Issue 、COCOAの改善に関係がないと思われるご意見については、コメント無しにクローズさせていただくことがありますのでご了承ください。
```

**Comment by halsk** [comment]
@Meiryo7743  さん、おっしゃるとおりだと思いました！

**Comment by Meiryo7743** [comment]
了解です！　PR 出しておきます。

**Comment by halsk** [comment]
修正されました！ @Meiryo7743 様、皆様、ご協力ありがとうございました！
![image](https://user-images.githubusercontent.com/16509/112962312-358a5900-9181-11eb-8539-1548a98a58c8.png)
