### ISSUE TITLE
`settings.json` をGitの管理下から外す

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#749]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

`settings.json`は現在`.gitignore`に指定されている。

https://github.com/cocoa-mhlw/cocoa/blob/c5e480b43779b8dec3f196947c7971f147c51e8f/.gitignore#L383-L385

しかし、.gitignoreに指定するより前のタイミング（Covid19Radar時代）でGitの管理下に置かれた様子。

https://github.com/cocoa-mhlw/cocoa/commit/72c2d4f2d9f83b37404b2fd42bc63858768acf7e#diff-5bdec46c6ceb5e47888fee275ff5ab1440d1abf52b50473c698a6aac3fb14810

https://github.com/cocoa-mhlw/cocoa/commit/7e0910d80b39d730b5e0a61c6c9b99fe6277cfa7

APIキーなどのセンシティブな情報を含むため、誤ってcommitされるのを防ぎたい。

## 解決策についてお書きください / Describe the solution you'd like

`settings.json` を `settings.json.sample`に名称変更（rename）する。
`settings.json`の内容に依存したテストがいくつかあるので、その辺りもケアする（skip指定されてる？）。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

気をつけて、余計な情報がコミットされないようにする（しかし人間の注意力には限界がある

## その他 / Additional context

----
Internal IDs:
- NFR 6303

**Comment by b-wind** [comment]
機密情報が誤ってcommitされるのを防ぐという意味では git-secrets の導入などでしょうか。


https://blog.katsubemakito.net/git/git-secrets

--register-azure オプションを追加した fork
https://github.com/msalemcode/git-secrets
