### ISSUE TITLE
現在のENv2のパラメータではiPhoneの接触通知を出す感度が低いのを改善する

### ISSUE THREAD

**Issue by daisuke-nogami** [cocoa-mhlw/cocoa#755]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

理論値と実機の長時間接触のデータ収集に基づいてパラメータを設計していたが、
パラメータ検証で短時間の接触を模擬したところ、iPhone同士の接触通知の発生感度が非常に低くなっていた。

背景：
電波強度は、同じ距離であっても端末の向きによって変化する。
事前の調査では、iPhoneの電波強度はよく調整されているとの情報があったため、Android機種を多めにデータ収集を行った。
その段階では、Android, iPhoneともに、端末の向きによる電波強度の変化は少なかったため、
理論値を元にパラメータを設計した。
パラメータ検証では、シェアの大きいiPhoneを中心に15分の接触を多数発生させたところ、
Androidは引き続き端末の向きに影響をうけなかったが、iPhoneは電波強度が弱くなる傾向が強く、
閾値を超えないリスクスコアが多く発生した。

## 解決策についてお書きください / Describe the solution you'd like

iPhone同士の接触の感度が落ちすぎないようにパラメータを改善する。
Androidでは15分未満の接触が閾値を超えるケースが増えるが、これは別Issue #754 で対応されるため、
誤った通知を出すことは抑制できるので、特異度に悪影響を与えない。

## その他 / Additional context

パラメータ検証結果のログからシミュレートすると感度は70％を越える。
追っかけで設定を記載したpull-requestを送る。

**Comment by keiji** [comment]
iOSとAndroidでパラメーターファイル自体分けちゃいますかと聞こうとして、もともとAndroidとiOSで設定パラメーター分けてあったと気づいた。

**Comment by daisuke-nogami** [comment]
どうもiOS側が発信するAdvertisingのTxPowerに傾向の違いがあるか、
あるいはAndroidのキャリブレーションの仕組みが上手くワークしてないようで、
陽性者側のOSが分からないとパラメータを決め打ちできないんです…
（Android側も、リファレンス機であるPixel4を間に挟んだキャリブレーション情報しかもっていないので
　しかたないと思いますが）

**Comment by keiji** [comment]
いや、Xamarin.ExposureNotificationの時みたいにAndroid/iOSで設定共有してたらURL分けるとか必要でしたけど、Cappuccinoなら何の問題もないです。

**Comment by daisuke-nogami** [comment]
接触者側端末のEN（特にAndroid）に、「接触した陽性者側の端末のOSがiOSならこのパラメータ、Androidならこのパラメータ」と設定できればいいんですが、そういう設定はなかったので…（接触者側のOSだけ影響するなら楽だった）
