### ISSUE TITLE
言語設定が「日本語、English、简体中文」以外の場合に表示言語が「English」にならない場合がある

### ISSUE THREAD

**Issue by kazuhiro4949** [cocoa-mhlw/cocoa#768]
## 不具合の内容 / Describe the bug

テストチームからの指摘

OSの言語設定を「日本語、English、简体中文」以外の言語に設定した際に、前述の三言語のうちで直近に選択していた言語で表示される。

## 再現手順 / Steps to reproduce

1. OSの「設定」より、「言語と地域」の設定を「日本語」に設定する。
2. OSの「設定」より、「言語と地域」の設定を「한국어」に設定する。
3. アプリを起動し、「ホーム」画面で表示されている言語を確認する。

## 期待される挙動 / Expected behavior

「言語と地域」が「日本語、English,简体中文」以外に設定されている場合に、COCOA内の言語表示が「English」で表記されること。

## 動作環境 / Environments

- デバイス：iPhone8
- OS：iOS
- バージョン：13.7

**Comment by kazuhiro4949** [comment]
Resources.jaのテキストが使われているが、フォントはSTHeitiになっている

**Comment by keiji** [comment]
以前も話が出た覚えがありますが、前のタスクが残っているだけじゃないかと思います。

Xamarin.Formsはフォントの大きさ変えたり言語を変えても反映されず、一回タスクをキルしないと反映されないので。

タスクのない状態（スプラッシュ画面が表示される）から始めてるか、明日にでもテスト工程を確認してみましょう。

**Comment by kazuhiro4949** [comment]
原因はCFBundleDevelopmentRegionの指定なのですが、最新のdevelopではすでに修正済みのようでした

https://github.com/cocoa-mhlw/cocoa/commit/eb2897a80a6ea8d1b7d2457bfb0c4c1363e471b9#diff-2dd0ce0162569b348189ecc08bb24c39c6a0fb7d519ab9797237c1111644abaf
