### ISSUE TITLE
[Android] datepickerdialogの背景色が見にくい

### ISSUE THREAD

**Issue by Murayu0225** [cocoa-mhlw/cocoa#803]
## 不具合の内容 / Describe the bug

アクセシビリティ的な内容です。
COCOA2での~~datapicker~~datepicker(恥ずかしいミスをしました)の背景色(水色)が文字色(白)と似ていてわかりにくくなってしまっている。
元々は背景色が黒、文字色が白でした。

## 再現手順 / Steps to reproduce

1. '陽性情報の登録 → 同意して陽性登録' をクリックし、
2. '症状ボタン' のどちらかを選択し、
3. 日付入力欄がでてくるのでそこをクリック。

## 期待される挙動 / Expected behavior

見やすい色にする。(黒と白など)

## スクリーンショット / Screenshots

| COCOA | COCOA2 |
| ------------- | ------------- |
| ![before](https://user-images.githubusercontent.com/37988559/150664018-d967a374-c78a-450a-bdb6-546b1af54da9.jpg) | ![after](https://user-images.githubusercontent.com/37988559/150664023-0e1ae423-eb20-4ec7-909e-c3f5f67500b0.jpg) |

## 動作環境 / Environments

- デバイス：Galaxy S10
- OS：Android
- バージョン：v2.0.0-beta01 (betaにしてしまったのでv1.4.1での配色がどうなっていたのかわかりません。スクリーンショットは、たまたまビルドしてスマホに残っていたv1のCOCOAの画像です。(いつのビルドか不明))

**Comment by b-wind** [comment]
COCOA のアクセシビリティ方針には含まれていませんが、所謂カラーユニバーサルデザインなどは気になりますね。

以下は東京都のガイドラインです。（PDF）
https://www.fukushihoken.metro.tokyo.lg.jp/kiban/machizukuri/kanren/color.files/colorudguideline.pdf

楽なのは白黒にしてしまうか、カラーユニバーサルデザイン推奨配色セットから選んでくるのが無難ですかね。
（ここではディスプレイのカラーマネージメントには触れないこととします）

**Comment by Meiryo7743** [comment]
手元の Android 端末で確認したところ，v1.4.1 では白黒の配色のようです。

![datapicker COCOA v1.4.1](https://user-images.githubusercontent.com/46659204/150667006-31de1caa-f2c2-4dbc-89f6-0d8a2f96fb16.png)

**Comment by keiji** [comment]
ダイアログ周りはなにも変えておらず、適用されているカラー（Teal系？）もリソース指定にない。一体どこから来たのか。

ひとまずXamarin.Forms.Visual.Materialのバージョンを戻して現象が継続するか確認してみます。

**Comment by keiji** [comment]
そもそも Xamarin.Forms.Visual.Material 取り除いてもなにも変わらないので、ここは無関係っぽい。

**Comment by keiji** [comment]
AndroidのDatePickerのヘッダーカラーは通常だとスタイルの `colorPrimary` の色が採用されるはずだけど、Xamarin.Forms通すと適用されていない。

**Comment by keiji** [comment]
いいニュース
ミニマムなPrismアプリで `android:colorAccent` を指定してDatePickerのヘッダーの色を変えられるところまでは確認済み。

悪いニュース
COCOAに同じことをしても色が変わらない

**Comment by keiji** [comment]
いけた！
あとでPull Request出す。

![Screen Shot 2022-01-23 at 20 15 44](https://user-images.githubusercontent.com/932136/150675776-2d46cd24-4a12-43fa-ab3a-0c4e90a585bf.png)

**Comment by keiji** [comment]
Pull Requestだしました。

![Screen Shot 2022-01-23 at 22 58 25](https://user-images.githubusercontent.com/932136/150682638-a08090d0-c498-4201-b2ed-36922ed288e1.png)
