### ISSUE TITLE
COCOA ログチェッカーへのリンクをホームに追加したい

### ISSUE THREAD

**Issue by yanskun** [cocoa-mhlw/cocoa#805]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

https://cocoa-log-checker.com/
こちらの存在をネットニュースで知った。
COCOA は使っているが、ログチェックができるのは知らなかったので、せっかくなら、リンクを追加してあげたほうがいいかなと

## 解決策についてお書きください / Describe the solution you'd like

トップページの下部（空白部分）もしくは、ハンバーガーメニューにブラウザに飛べるリンクを設けるだけ

**Comment by daisuke-nogami** [comment]
こちら、現在開発中の次期バージョンで、接触通知に至らなかった信号受信があった場合に、COCOA内でその旨を表示するよう準備中であることをとりいそぎ共有いたします。

https://github.com/cocoa-mhlw/cocoa/issues/605

**Comment by yanskun** [comment]
回答ありがとうございます！

それはすごいいいですね！

次期バージョン楽しみにしています
