### ISSUE TITLE
[iOS] バックグラウンドタスクが短期間で繰り返し実行されている

### ISSUE THREAD

**Issue by kazuhiro4949** [cocoa-mhlw/cocoa#807]
## 不具合の内容 / Describe the bug

ログを見る限り、バックグラウンドタスクが30分おきに繰り返し実行されている

## 再現手順 / Steps to reproduce

1. アプリを起動する
2. バックグラウンドにアプリを持っていく

## 期待される挙動 / Expected behavior

想定ではもっと幅をとって数時間おきに実行される

## 動作環境 / Environments

- デバイス：iPhone
- OS： iOS
- バージョン：15.0

**Comment by kazuhiro4949** [comment]
こちらの不具合調査中に発見
https://github.com/cocoa-mhlw/cocoa/issues/799

**Comment by keiji** [comment]
これぼくがIDENTIFIERを形式とは異なるものを設定したのが原因でした。解決済みなのでクローズします。
