### ISSUE TITLE
英語版/中国語版の利用規約が未だにCovid-19Radarのリポジトリを参照している（MPL違反の疑い）

### ISSUE THREAD

**Issue by Guest126** [cocoa-mhlw/cocoa#82]
## 不具合の内容 / Describe the bug

[英語版](https://www.mhlw.go.jp/cocoa/kiyaku_english.html)および[中国語版](https://www.mhlw.go.jp/cocoa/kiyaku_chinese.html)の接触確認アプリケーション利用規約第5条の3において参照しているリポジトリURLが、COCOA ( https://github.com/cocoa-mhlw/cocoa )ではなくCovid-19Radar ( https://github.com/Covid-19Radar/Covid19Radar )のままになっている。

[MPL v2.0 3.2(a)](https://www.mozilla.org/en-US/MPL/2.0/#distribution-of-executable-form)では、バイナリの受領者に対してソースコードを合理的な手段で入手する方法を通知する必要があると定めており、日本語版では接触確認アプリケーション利用規約第5条の3がそれを（偶然にも？）担保している。

しかし、現状では日本語版以外の利用者がCOCOAのソースコードの入手方法を知り得ないため、MPL違反となっている可能性が高い。

## 再現手順 / Steps to reproduce

1. 端末のロケールを英語または中国語（簡体字）に変更する
2. COCOAを利用開始する
3. ハンバーガーメニューを開く
4. 利用規約(Term of use/使用条款)を表示する

## 期待される挙動 / Expected behavior

すべての言語の利用者にソースコードを合理的な手段で入手する方法を通知すること

## スクリーンショット / Screenshots

![英語版](https://user-images.githubusercontent.com/63546117/112756482-50918780-9020-11eb-8ca2-f79da418a058.png)
![中国語版](https://user-images.githubusercontent.com/63546117/112756485-52f3e180-9020-11eb-8150-d7bfe6a56184.png)

## 動作環境 / Environments

- デバイス：Any
- OS：Any
- バージョン：1.2.2（特定のアプリバージョンではなくサーバ側リソースに依存）

**Comment by keiji** [comment]
ありがとうございます！

ご指摘の内容ですと、Term of Useを更新するのはもちろん必要ですが、もっとも良いのはCOCOAそのもののライセンスとコードの入手場所を示す表示を別途行うことですね。

**Comment by Guest126** [comment]
はい、そのように思います。#69 でも

>COCOA アプリからは「COCOAアプリ自体のライセンス」を簡単に知る方法がない

と指摘されていましたので、合わせて解決できるのがベストです。

これについては別途 Issue を立てるべきですか、それとも #69 か、あるいはここで続けるべきですか？

**Comment by keiji** [comment]
「COCOAそのものの」についてはIssueにしてしまいましょう。
Term of Useの方を片付けてからの対応になると思われます。

**Comment by keiji** [comment]
英語および中国語版の利用規約に、ただしいCOCOAのURL（GitHubリポジトリ）が掲載されていることを確認しました。

<img width="940" alt="Screen Shot 2021-04-13 at 17 52 53" src="https://user-images.githubusercontent.com/932136/114525611-33e08b00-9c81-11eb-8f1c-8b0ec82db4a8.png">

<img width="940" alt="Screen Shot 2021-04-13 at 17 53 14" src="https://user-images.githubusercontent.com/932136/114525663-3fcc4d00-9c81-11eb-9a24-afdb7cfd9076.png">
