### ISSUE TITLE
[a11y][Android] フォントサイズを変更するとボタンのデザインが崩れる

### ISSUE THREAD

**Issue by fumiya-kume** [cocoa-mhlw/cocoa#834]
## 不具合の内容 / Describe the bug

ボタンのテキストが二行になる or 枠線そのpaddingが極端に狭くなります。

## 再現手順 / Steps to reproduce

1. 端末の `設定アプリ>ユーザー補助>テキストと表示>フォントサイズ ` に行き、
2. フォントサイズを最大にする
3. COCOA2 を開きHome画面 or その他画面にいくと
4. ボタンのデザインが崩れます

## 期待される挙動 / Expected behavior

ボタンのテキストに応じて横幅を広げるのはどうでしょうか？

## スクリーンショット / Screenshots

Normal size | Big size
:--: | :--:
<img src="https://user-images.githubusercontent.com/16269075/151629203-074f2dfd-f02a-4e36-aec6-a63ed833b8d9.png" width="300" /> | <img src="https://user-images.githubusercontent.com/16269075/151629178-22870aac-5fb4-48be-964a-b52870c06e9e.png" width="300" />

## 動作環境 / Environments

- デバイス：Pixel 6 Pro 
- OS： Android 12
- バージョン：2.0.0-beta02

**Comment by b-wind** [comment]
ウチの親のスマホなども老眼で常に最大サイズのフォントを指定しているのでこんな感じの表示になりますね。
慣れてしまって違和感を覚えなくなってしまっていました。

**Comment by b-wind** [comment]
> ボタンのテキストに応じて横幅を広げるのはどうでしょうか？

横幅の調整は様々な機種の解像度を考慮する必要があり難しそうな？気がしました（実際の所はよく分からず）


現時点では取りあえず文字に角丸の枠が被らないようにして欲しいかなと言う印象です。
どちらかというと縦方向に余裕を付ける事になるでしょうか。

**Comment by fumiya-kume** [comment]
> > ボタンのテキストに応じて横幅を広げるのはどうでしょうか？
> 
> 横幅の調整は様々な機種の解像度を考慮する必要があり難しそうな？気がしました（実際の所はよく分からず）
> 
> 現時点では取りあえず文字に角丸の枠が被らないようにして欲しいかなと言う印象です。 どちらかというと縦方向に余裕を付ける事になるでしょうか。

固定横幅ではなく、 
min-width: wrap_content
max-width: match_parent

みたいな感じにするといいのかもです。(Android な擬似コードで表現してみました)

**Comment by takikunxo** [comment]
横から失礼します。

>ボタンのテキストが二行になる or 枠線そのpaddingが極端に狭くなります


paddingのvalueが元々、0だったみたいです。

>現時点では取りあえず文字に角丸の枠が被らないようにして欲しいかなと言う印象です。
>どちらかというと縦方向に余裕を付ける事になるでしょうか。

こちらの観点での修正ですとpadding追加すれば済むのではないかと思っています。
