### ISSUE TITLE
COCOA自体のライセンス表示とソースコード入手先を追加

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#84]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

MPL 2.0の3.2で、ソースコード形式のコピーを合理的な手段で入手する方法を通知する必要があると定められている(MUST)。

https://www.mozilla.org/en-US/MPL/2.0/#distribution-of-executable-form

> 「使用者」が「保護対象ソフトウェア」を「実行可能形式」で頒布する場合：
>
> a. 第3.1項で述べたとおり、当該「保護対象ソフトウェア」は「ソースコード形式」で公開される必要があり、また「使用者」は「実行可能形式」の受領者に対して、当該「ソースコード形式」のコピーを適時に合理的な手段で、受領者への頒布にかかる費用を上限とする料金で入手する方法を通知する必要がある。

https://github.com/opensource-jp/licenses/blob/main/MPL-2.0/MPL-2.0.md#32-%E5%AE%9F%E8%A1%8C%E5%8F%AF%E8%83%BD%E5%BD%A2%E5%BC%8F%E3%81%AE%E9%A0%92%E5%B8%83

現在のCOCOAは利用規約中にリンクを記載。また「アプリに関するお問い合わせ」から「よくある質問」のリンク先の問７−２「ソースコードはどこかで公開されていますか。」にCOCOAのリポジトリURLを記載している（利用規約中のリンクについては #82 を参照）

利用規約中のリンクは目に留まりにくく、ソースコードの入手を希望するユーザーに本来必要でない負荷を賭ける可能性がある。

## 解決策についてお書きください / Describe the solution you'd like

COCOAのアプリ内に、COCOAのライセンスとソースコードの入手先を示すURLを表示する。

https://github.com/cocoa-mhlw/cocoa/issues/69#issuecomment-804527550

ユーザーは表示を見ることで、COCOAのライセンスとソースコードの入手先を確認できる。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

利用規約の該当部分のフォントサイズを上げる。またはセクションを独立することで可読性を上げることでも対応できますが、利用規約のデザインを大きく変更する事になるので、この方法が現実的かはわかりません。

----
Internal IDs:
- NFR 6286

**Comment by Guest126** [comment]
完全に代弁したIssueの提出ありがとうございます。表示場所としては

メニュー > アプリの設定 > ライセンス (現在は https://covid19radarjpnprod.z11.web.core.windows.net/license.html を参照)

が第一候補だと思います。ただ、このページは迂闊に日本語訳できないので、英語のままでユーザーの理解に繋がるか（通知したことになるのか）と言われれば微妙な気もしています。

**Comment by Takym** [comment]
設定ページに「開発に参加する」という項目を作成して、そこからリポジトリを開ける様にするのはどうでしょうか？MPL に適合するのと同時に、アプリの開発に参加してくださる人も増えると思います。

# UI例

## 開発に参加する
貴方も一緒に COCOA を開発しませんか？下記の GitHub リポジトリから開発に参加する事ができます。
リポジトリ：https://github.com/cocoa-mhlw/cocoa

**Comment by keiji** [comment]
こちら対応済みなのでcloseします。
![Screen Shot 2022-05-17 at 13 31 42](https://user-images.githubusercontent.com/932136/168729428-703c3c40-a6cc-4534-be9d-1843f8793dcd.png)

いくつか派生したIssue( #941 #940 )があるので、引き続き改善を続けます。
