### ISSUE TITLE
保存されているExposureWindowをデバッグメニューからCSVでエクスポートする

### ISSUE THREAD

**Issue by kazuhiro4949** [cocoa-mhlw/cocoa#843]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

デバッグのためにExposureWindowをエクスポートできるようにする

## 解決策についてお書きください / Describe the solution you'd like

デバッグページからcsvでエクスポートできるようにする

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

シリアライズされたファイルを直接取得する

**Comment by daisuke-nogami** [comment]
ExposureWindowをエクスポートする仕様のイメージはこちらです。
https://github.com/keiji/en-calibration-server/commit/714a9d8bb2ce018c89b2c5fcc2961a2f611ed8e4

加えて、日付がEpochになっているのは人間が可読な表現がありがたく。

**Comment by keiji** [comment]
これdevelopに取り込まれてるので、クローズしてもいいですね。
