### ISSUE TITLE
COCOA2(v2.0.0) リリース

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#847]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

検討の結果、現在のdevelopおよびクローズドベータ版から、いくつか機能を引いてリリースする。

## 解決策についてお書きください / Describe the solution you'd like

`release/v2.0.0`で作業する。

 - [x] 「基準値未満の接触画面」を閉じる
     - スコア等の取り扱いをもう少しクローズドベータ版で検討する
 - [x] 陽性情報登録APIを「V2DiagnosisApi」を使うように切り替える
     - V3DiagnosisApiは #840 を入れてから切り替える
     - コードはできているが、利用規約・プライバシーポリシー変更が必要になるため調整が終わるまではリリースできず、仮にV3DiagnosisApiを使ってしまうと、すぐにV4DiagnosisApiを作ることになりメンテナンス効率が落ちる
 - [x] 接触情報をSecureStorageに保存するようにする
     - 暗号化して保存する記述が利用規約等に含まれているため、暗号化しない変更を含むリリースをするには利用規約等を改正する必要がある。
     - #840 の変更が控えていて、短期間で利用規約等を複数回変更するよりは、いっそ「暗号化」によせておく方がいい（SecureStorageを使わないようにする変更は必須ではないので、またどこかのタイミングで）

## その他 / Additional context

クローズドベータ（ #848 ） を公開してからやる。

**Comment by keiji** [comment]
オープンβ公開からしばらくたちました。結構厳しい条件のオープンベータでしたが、数百人（正確な人数は後日公開したいです）の方に参加して頂いています。本当にありがとうございます。

いまのところ大きな問題も検出されておらず、そろそろ良いだろうと言うことで、コミュニティからいただいた翻訳の改善（#944）、行政側から状況に合わせてテキストの変更などの調整（#945）を行ったものを「COCOA v2.0.0」として、本日（2022/04/05）、Android/iOS版ともに審査提出しました。

審査通過次第、リリースを開始する予定です。今回から完全公開ではなくローリングアップデートを行います。
リリース状況はこちらで共有します。

**Comment by keiji** [comment]
Google Play StoreとApp Storeで審査通過を確認しています。
問題が発生しない限り、明日の日中にローリングアップデートを開始する予定です。

**Comment by b-wind** [comment]
App Store ではすでに公開されたようですね。

**Comment by keiji** [comment]
AppStore/Google Playともに現在の公開率は1%です。AppStoreだとアップデートしようと思えばできるようですね（この仕様を知らなかった）。

行政側のウェブサイト・FAQとかは更新手続き中なので、それが終わったらまた報告します。

**Comment by keiji** [comment]
トップページとFAQの更新完了を確認しました。~~が、iOSの対応バージョンが変わったという記述が抜けているので確認中です。~~ 反映しました。


新型コロナウイルス接触確認アプリ（COCOA) COVID-19 Contact-Confirming Application
https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/cocoa_00138.html

接触確認アプリ よくある質問
https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/covid19_qa_kanrenkigyou_00009.html

**Comment by keiji** [comment]
公開率2%です（AppStoreは自動で公開率が上がるので、Android版もそれに合わせようと言うことになっています）。

Twitter（やってない）とか見る限りは、v2.0.0で接触通知が届いたという話もありますね。

iOSでは「接触チェックに表示される「一致したキーの数」が積算される事象を調査する #961 」ということに起因して「一致したキーの数がすごい多い」みたいなツイートも散見され「これFAQ更新するか？　いや、そもそも接触チェック画面はCOCOAの範囲外だし、説明する方が混乱するかな……」って思っています。

**Comment by b-wind** [comment]
> 「一致したキーの数がすごい多い」みたいなツイートも散見され


念の為仕様をある程度把握する必要はありますが、基本的には Apple に問い合わせて欲しい事項ですね。
以前からOSのログを参照するように案内はしてないはずですし、今後の iOS アップデートでさらに変更になっても答えられないいと言うのもあります。



（ログ出力内容が変わっているという）問い合わせがあり、（調査中ではあるが現状）COCOAの動作上特に問題は無いと認識していると言うQ&Aなら有っても良いかも知れません。

**Comment by b-wind** [comment]
反面、動作に疑問があればCOCOAが疑われるだろうと言う可能性を考えると、慎重に対応した方が良いのかもですね。
万一見過ごしたバグがあると大変ですし。

**Comment by keiji** [comment]
現在、公開率は50%です。

Twitterなどを見ていると、結構v2.0.0で通知が出たというツイートが見当たりますね。
一方、スクリーンショットがあるものはiOSばかりで、Androidで出たと確定していないのが気になっています。

テストの過程でAndroidで接触通知が出ることは確認していますし、COCOAはiOSユーザーの方が格段に多いのですが……引き続きSNSを注視しています。

**Comment by keiji** [comment]
Androidで接触通知が出ることが確認できました（接触してしまった方がいるので決して喜べないのですが、機能的には動作は確認できた）。

https://twitter.com/yukuraisi/status/1513793005698023432

**Comment by keiji** [comment]
公開率は100%となりました。
