### ISSUE TITLE
COCOA2(v2.0.0) パブリックベータ公開準備

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#848]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

検討の結果、現在のdevelopおよびクローズドベータ版から、いくつか機能を引いてリリースする。

## 解決策についてお書きください / Describe the solution you'd like

 - [x] v2.0.0 betaは接触通知が出ても公費負担の検査の対象外であることを明記する
     - これはv2.0.0で接触通知の基準が「回数」から「時間」に変わるため（接触通知APIの仕様に基づく）
     - 変更についてはv2.0.0リリース前に事務連絡で関係各所に通知するが、パブリックベータはそれより前の公開になるため、取り扱いとしては公費負担にしない整理とする
     - v2.0.0より後のバージョンのパブリックベータでは公費負担での取り扱いになるように調整を進める
 - [x] 「基準値未満の接触画面」を閉じる
     - スコア等の取り扱いをもう少しクローズドベータ版で検討する
 - [x] 陽性情報登録APIを「V2DiagnosisApi」を使うように切り替える
     - V3DiagnosisApiは #840 を入れてから切り替える
     - コードはできているが、利用規約・プライバシーポリシー変更が必要になるため調整が終わるまではリリースできず、仮にV3DiagnosisApiを使ってしまうと、すぐにV4DiagnosisApiを作ることになりメンテナンス効率が落ちる
 - [x] 接触情報をSecureStorageに保存するようにする
     - 暗号化して保存する記述が利用規約等に含まれているため、暗号化しない変更を含むリリースをするには利用規約等を改正する必要がある。
     - #840 の変更が控えていて、短期間で利用規約等を複数回変更するよりは、いっそ「暗号化」によせておく方がいい（SecureStorageを使わないようにする変更は必須ではないので、またどこかのタイミングで）

**Comment by keiji** [comment]
`release/openbeta-01` の内容でAndroid版のCOCOAを審査提出しました。

Androidで参加
https://play.google.com/store/apps/details?id=jp.go.mhlw.covid19radar

ウェブで参加
https://play.google.com/apps/testing/jp.go.mhlw.covid19radar

**Comment by keiji** [comment]
Android版については審査が通り、公開の準備は完了しています。
公開操作は 行政内の調整結果を受けて 実施します。

![Screen Shot 2022-02-25 at 0 53 12](https://user-images.githubusercontent.com/932136/155564154-5ed7d9d3-0713-44a6-ad74-85cac07ecbf2.png)

**Comment by kvaluation** [comment]
オープンβ版公開ありがとうございます。

https://cocoa-mhlw.github.io/cocoa/docs/contribution/open_beta_version/#%e5%8f%82%e5%8a%a0%e3%81%ab%e5%bd%93%e3%81%9f%e3%81%a3%e3%81%a6%e3%81%ae%e7%95%99%e6%84%8f%e7%82%b9

> iOSでは、（iOS特有の留意点を書く、TestFlightの使用方法など）

となっておりました。

**Comment by keiji** [comment]
書かねば。

しかし有山はTestFlightが分からぬ。

**Comment by daisuke-nogami** [comment]
ああ…すいません。完全に私の見落としです。
そして、特にTestFlight特有の難しいこと、は特になかったので「先にTestFlightを入れておくとスムーズです」くらいしかありませんね…
（次回のオープンβを入れるときには、今回のオープンβの情報を消す、など、何らかの手間がかかるはずですが、影響範囲はクローズドβ版を利用されているリテラシーの高い方に限られているので、レポートいただきつつ次回加筆します…）

**Comment by daisuke-nogami** [comment]
https://github.com/cocoa-mhlw/cocoa/pull/917 をmerge前だったのでこちらにまとめて載せて対応します…
