### ISSUE TITLE
利用規約の更新があっても再確認を行わない

### ISSUE THREAD

**Issue by b-wind** [cocoa-mhlw/cocoa#85]
## 不具合の内容 / Describe the bug

COCOA 1.2.2 において、起動時に利用規約・プライバシーポリシーの更新確認の為以下のアドレスにアクセスしています。
https://covid19radarjpnprod.z11.web.core.windows.net/ja/terms_update.json
```json
{
    "privacy_policy" : {
        "text" : "感染可能期間に陽性者と接触した可能性のある方にのみ通知するよう、アップデートしました。\n　・陽性者が発症日又は検査日を入力\n　・その約２日前以降に接触の可能性のある利用者に通知\n\nこれにともない、プライバシーポリシーを改定しています。\n改定内容を下記リンクからご確認ください。",
        "update_date" : "2020/12/15 13:00:00"
    }
}
```

実装上は "terms_of_service" キーを "privacy_policy" と同様に併記すれば確認画面が出ると思われます。

書き換え例
```json
{
    "terms_of_service" : {
        "text" : "sample text1.",
        "update_date" : "2020/12/15 13:00:00"
    },
    "privacy_policy" : {
        "text" : "sample text2.",
        "update_date" : "2020/12/15 13:00:00"
    }
}
```

## 再現手順 / Steps to reproduce

サーバー上での書き換え作業が必要のため困難。

## 期待される挙動 / Expected behavior

上記 JSON ファイルにて、"terms_of_service" キーが提供された場合、利用規約の再同意画面がでる。

ただし、現状記述されていないのは何らかのミスか意図的なものか不明。

## 動作環境 / Environments

- デバイス：（Any）
- OS：（Android/iOS 共）
- バージョン：(1.2.2)

## その他 / Additional context

利用規約自体はプライバシーポリシーと同日（2020/12/15）に更新されているので、不要であると言う訳では無いように思えます。

**Comment by keiji** [comment]
利用規約やプライバシーポリシーの更新確認については、診断キー取りに行くバックグラウンド処理でも確認してない様子ですね。

このIssueはフォアグラウンド（起動時）についてでしょうか。バックグラウンドも含めた指摘でしょうか（バックグラウンドの方は大がかりな変更になりそうですね）。

**Comment by b-wind** [comment]
この Issue ではフォアグラウンドの処理を問題としています。

おっしゃる通りバックグラウンド動作時にも確認はしてないはずですが、それをどのようにユーザーに知らせるかがネックになりそうなので（通知などを出すならパーミッションを取らないといけない等）一端分けた方が良いと判断しています。

**Comment by zaruudon** [comment]
利用規約はそれ自体に一方的に変更できると書かれているので同意を取る必要がないということなのではないでしょうか。

**Comment by b-wind** [comment]
> 利用規約はそれ自体に一方的に変更できると書かれているので同意を取る必要がないということなのではないでしょうか。

利用規約もプライバシーポリシーも、変更自体は一方的です。
ただ、告知も何も無くユーザーが変更を認識していないのは別の話かと思います。

**Comment by zaruudon** [comment]
GetTermsUpdateInfoの中にJSONを直接書いてDebug_Mockで確認画面を出してみました。

![20210330_2](https://user-images.githubusercontent.com/74974601/112954349-4636d100-9179-11eb-8786-0ee7c66d7363.png)

>利用規約もプライバシーポリシーも、変更自体は一方的です。
>ただ、告知も何も無くユーザーが変更を認識していないのは別の話かと思います。

一般に契約の内容は相手方の同意がなければ変更できませんが、利用規約は携帯電話の利用契約などにみられるような定型約款の一方的変更を可能とする条項を置いている(12条)ので扱いが異なることについては説明ができるのではないかと思いました。
規約が変更されたことすら一切明示されていないことには良い印象を持つことができませんし、プライバシーポリシーと同じ程度の説明があったほうがよいとは思っています。

**Comment by b-wind** [comment]
> 規約が変更されたことすら一切明示されていないことには良い印象を持つことができませんし、プライバシーポリシーと同じ程度の説明があったほうがよいとは思っています。

このあたり、厚労省の方針としてユーザーが認識しなくて良い問い言う指示があるのでしたらそれに従うのですが、
現状はそれも不明なのでこの Issue ではその確認も行いたいと思っています。

**Comment by yoshitomo-g** [comment]
次のように処理はありますので、問題として扱うのは更新情報が提供されていないことではないでしょうか。
https://github.com/cocoa-mhlw/cocoa/blob/970bbf812295a6e1e35e8eaf37e338dcfcc5b8f9/Covid19Radar/Covid19Radar/ViewModels/HomePage/SplashPageViewModel.cs#L36-L44

2021年3月30日18時52分の時点で、[アプリの利用規約](https://www.mhlw.go.jp/cocoa/kiyaku_japanese.html)には次のようにあります。

> （本利用規約への同意）
> 第３条 アプリ利用者は、本利用規約の定めに従って本アプリを利用しなければならず、本利用規約の内容を十分に理解した上で、本利用規約に同意しない限り、本アプリを利用できません。
> ２ アプリ利用者は、実際に本アプリの利用を開始した場合には、本利用規約の内容を十分に理解した上で、本利用規約に同意したものとみなされます。

利用開始時には同意を確認するプロセスがありましたが、変更された場合にはそれをせず、新しい内容を知らないまま利用を続けている場合を同意済みと扱えるものなのかどうかが気になります。[民法第548条の4（定型約款の変更）](https://elaws.e-gov.go.jp/document?lawid=129AC0000000089#Mp-At_548_4)によると事前の十分な告知が必要なようですが、それに該当するようなこともなかったと思います。

**Comment by b-wind** [comment]
> 次のように処理はありますので、問題として扱うのは更新情報が提供されていないことではないでしょうか。

サマリにも記述しましたが、おっしゃる通りサーバー側の更新チェック用JSONに利用規約の更新が記述されていません。
https://covid19radarjpnprod.z11.web.core.windows.net/ja/terms_update.json
サーバー側さえ書き換えれば @zaruudon さんに確認頂いた様な画面が出るものと考えています。


民法上の取り扱いももちろんですが、サーバー側のファイル更新内容が何らかの意図した物か、単に忘れているのかが知りたいのと必要であれば今後も含めて必要なときに必要な対応をして貰えれば良いかなと考えています。

**Comment by yoshitomo-g** [comment]
> 民法上の取り扱いももちろんですが、サーバー側のファイル更新内容が何らかの意図した物か、単に忘れているのかが知りたいのと必要であれば今後も含めて必要なときに適宜対応をして貰えれば良いかなと考えています。

そうですね。法的なことは専門家にお任せするしかなく、残りも厚生労働省側での確認が必要になりますから、ひとまずは対応待ちということに。

**Comment by Guest126** [comment]
> 民法第548条の4（定型約款の変更）によると事前の十分な告知が必要なようですが、それに該当するようなこともなかったと思います。

利用者の利益になる変更の場合は告知期間が不要で、利用者の不利益になる変更の場合は、その程度に応じた告知期間が必要ということのようですね。

**Comment by halsk** [comment]
@b-wind 皆様、ありがとうございます。こちらのご意見

**Comment by halsk** [comment]
@b-wind 様、皆様、ありがとうございます。こちらのご意見については承りましたが、本GitHubは [CONTRIBUTING.md](https://github.com/cocoa-mhlw/cocoa/blob/master/CONTRIBUTING.md) にも記載されている通り、技術的な対応を行うためのものです。
ご意見として厚生労働省には伝えますが、@yoshitomo-g 様が書かれているように、ここで法的な議論を行うことは意図しておりません。
また、現時点で不具合であるというわけではありませんので、何か厚生労働省側での指示があるまではペンディングとさせてください。

**Comment by b-wind** [comment]
@halsk 本件の回答次第では不用なコードやテストを省いたり、無用なデータを保存していることを辞めるなどの対処が可能と思います。
こちらも含めて技術的な内容では無いと言う事でしょうか。私自身は法的な解釈は当初から目的としていないことを付記します。

**Comment by halsk** [comment]
@b-wind  ご意見ありがとうございます。おっしゃるとおり、技術的な議論については価値があると思っていますので、Issue はオープンにしております。
ペンディングとするのは、確認の処理を実際に実装するかどうかです。
やることになったら適宜リリース計画に組み込みます。

**Comment by Guest126** [comment]
@b-wind さん

> @halsk 本件の回答次第では不用なコードやテストを省いたり、無用なデータを保存していることを辞めるなどの対処が可能と思います。

それは今までの話になかったので、もっと具体的な説明を要すると思います。

**Comment by b-wind** [comment]
@Guest126 おっしゃる通り、問題としている点の説明不足であったことは反省しているところです。
法的な扱いが問題で有るかのように誤解させてしまった人いらっしゃいます。


ただ、厚生労働省様からの返答次第で何をどうするかは変わりうると考えており、現時点では方針を示すのも難しいと判断しています。

**Comment by b-wind** [comment]
@halsk あくまで厚生労働省様の回答ありきなので些細な事かも知れませんが、「確認の処理」自体は実装されています。ただし使われていません。

**Comment by b-wind** [comment]
厚生労働省様からの返答がある・ないにかかわらず wantfix とのことで、現時点でここで議論する内容は無いかと思われます。


一端 close しますので何らかの動きがあったり、必要と思われる方がいれば再度 Issue を立てて頂けると幸いです。
