### ISSUE TITLE
接触日時が午前であることを明記する

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#877]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

Discussionでの提案を受けて、特に米国では24時間表記はしないのでAM/PMの指定は重要になる。

https://github.com/cocoa-mhlw/cocoa/discussions/865#discussioncomment-2200478

## 解決策についてお書きください / Describe the solution you'd like

午前9時（9:00 AM）と明記する。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

Discussionでの提案の通り「から24時間」という表記にする。
その場合も開始時刻に午前表記は必要。

**Comment by keiji** [comment]
### 月をまたがない場合

![Screen Shot 2022-02-18 at 11 18 45](https://user-images.githubusercontent.com/932136/154605623-4c6733df-e3c9-4a78-85c2-d89f25383521.png)

### 月をまたぐ場合

![Screen Shot 2022-02-18 at 11 16 42](https://user-images.githubusercontent.com/932136/154605653-7faa6575-983d-429c-910c-5481863e78c6.png)

### 年をまたぐ場合

![Screen Shot 2022-02-18 at 11 19 23](https://user-images.githubusercontent.com/932136/154605601-f8ba0872-9b19-434c-9815-272ea5d066bd.png)

**Comment by b-wind** [comment]
TimeZone と Locale (CultureInfo) に従うとのことなので、UTCの0時をUSの主要なTimeZoneで表記するとPMになるのでは。と言う細かいツッコミ。

**Comment by keiji** [comment]
いや、細かくないですね。かなり重要ですね。

ありがとうございます！　直します（今夜ならまだ間に合うはずなので。

**Comment by keiji** [comment]
こんな感じにしました（ちょうど翻訳が上がってきたので適用しました）。

日本語（タイムゾーン: JST）

![Screen Shot 2022-02-22 at 23 41 16](https://user-images.githubusercontent.com/932136/155174494-9e48744c-2df5-43dd-8bb8-8d2b5d891336.png)

英語（タイムゾーン: PST）

![Screen Shot 2022-02-23 at 1 20 37](https://user-images.githubusercontent.com/932136/155174574-edcc1b3c-a919-460e-af19-6c8314bcbba9.png)

中国語（タイムゾーン: PST）

![Screen Shot 2022-02-23 at 1 21 22](https://user-images.githubusercontent.com/932136/155174612-0c655d03-30b9-4632-891b-3c23409dc497.png)
