### ISSUE TITLE
`.editorconfig` を追加する

### ISSUE THREAD

**Issue by Meiryo7743** [cocoa-mhlw/cocoa#89]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

現在，コーディング規約の設定ファイルが存在していません。そのため，開発環境によっては改行コード，インデント幅の混在などを始めとする問題が生じる可能性があります。

例えば，[`.json`](https://github.com/search?q=repo%3Acocoa-mhlw%2Fcocoa+extension%3Ajson&type=Code&ref=advsearch&l=&l=) を見てみると，インデント幅が 2 字なものがあれば，他方で 4 字の字下げが行われているファイルもあります（もっとも，この場合はさほど問題になりませんが……）。

## 解決策についてお書きください / Describe the solution you'd like

`.editorconfig` を追加する。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

各種エディターの設定ファイルをそれぞれ追加する方法でも対応できます。ただ，`.editorconfig` のそれに比べると現実的とは言い難いでしょう。

**Comment by b-wind** [comment]
.editorconfig にも批判はあるっぽいですが、現状のコーディングルール不在の状況よりは遙かに良いと思います。
私自身フォーマットに無頓着で注意されることが多いのであるとすごく助かります。

**Comment by b-wind** [comment]
#92 に関連して、新規ファイル作成時に所謂UTF-8 BOMが付かないようになっているとありがたいです。
ファイルを見る限り、その設定も入っているように見受けられますが自信が無いので。
