### ISSUE TITLE
ライセンス内に無関係なドメインへのリンクが含まれる

### ISSUE THREAD

**Issue by watanabetoshinori** [cocoa-mhlw/cocoa#9]
アプリの設定画面から参照されているライセンスファイル内に「Json.net」というドメインへのリンクが含まれていますが、こちらはサードパーティライブラリの名称であり、リンクとして扱うべきドメイン名ではないように思われます。

- [アプリが参照しているHTMLファイル](https://covid19radarjpnprod.z11.web.core.windows.net/license.html)
`<h2 id="jsonnet"><a href="http://Json.NET">Json.NET</a></h2>`

- プロジェクト内の元ファイル
https://github.com/cocoa-mhlw/cocoa/blob/97e042e444599fe44afbe8046118edd6f8daeab3/Covid19Radar/Covid19Radar/Resources/html/license.html#L101

他のライブラリにおいてもライブラリ名にリンクは設定されていないため、意図したものでなければこちらのリンクは削除した方が良いのではないでしょうか。
----
Internal IDs:
- NFR 1470

**Comment by b-wind** [comment]
こちら確認したところ、COCOA v1.2.2 では該当箇所にリンクは貼られていないようです。（iPhone / Android にて確認）
現COCOA内で参照しているのは license.md の方では無いかと推測します。
https://github.com/cocoa-mhlw/cocoa/blame/v1.2.2/Covid19Radar/Covid19Radar/Resources/html/license.md#L97


この場合該当箇所の削除よりは license.html の削除が適当に思えます。


実際にどのファイルかリンクされているのか確認しますが、xamarin は不得意なため分かる方がいらっしゃればコメントをお願いしたく思います。

**Comment by b-wind** [comment]
リポジトリ内を検索する限りでは、以下のパラメーターが該当しそう。

https://github.com/cocoa-mhlw/cocoa/blob/047b12bfc497e5e32bd96e24c2b5d76c8ca18bcf/Covid19Radar/Covid19Radar/settings.json#L10

**Comment by keiji** [comment]
タイトルを「アプリから利用されていないHTMLファイルがリソースに含まれている」に変えた方がいいかもしれないですね

**Comment by b-wind** [comment]
どちらかというと、「アプリからはリポジトリ内のライセンスファイル類には直接アクセスしてない。」と言えそうです。

**Comment by b-wind** [comment]
リポジトリトップのライセンス一覧と、lisence.md は一致していますが、
https://github.com/cocoa-mhlw/cocoa/blob/v1.2.2/COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md

COCOAが参照している license.html では内容が違いますね。
https://covid19radarjpnprod.z11.web.core.windows.net/license.html

license.html の方が古くて、Font のライセンスが追記されていないです。

**Comment by b-wind** [comment]
サーバー側の運用ルールに疑問を感じます。

**Comment by keiji** [comment]
これは合わせないといけないですね。あとで別にIssueを作ります。

「サーバーの運用ルールに疑問を感じる」と言う点については、ぼくはよくわかっていないので教えてください。
サーバーの運用ルールにどのような疑問を感じているのか（サーバーの運用ルールの問題なのか）、意識のすりあわせができればIssueの方向性を決めやすいので教えてもらえると嬉しいです。

**Comment by b-wind** [comment]
単純に、サーバーの運用ルールがどのようになっているのかまるで分からないと言う事を意図しています。
あるか無いかもこちらからは推測するしかないので。

さし当たり当Issueで判明した内容としては、
- PR などで参照するライブラリを追加した場合、COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md に追記すれば良いと考えていた
- このファイルはアプリからは参照されないのでサーバー側でも別途更新して頂く必要がありそう
- この際、COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md をみて対処して頂けるのか、HTML 化ぐらいはこちらで作成する必要があるのかが不明

という点が課題として考えられそうです。

**Comment by b-wind** [comment]
サーバー側をどう更新して貰うか（我々は何をすべきか・しないべきか）を別Issueにするのは同意です。

この Issue の目的は少なくとも以下２ファイルの削除とするのが良いかと思います。（Issue タイトルとはだいぶズレましたが）
- https://github.com/cocoa-mhlw/cocoa/blob/v1.2.2/Covid19Radar/Covid19Radar/Resources/html/license.md
  - 参照されていない
- https://github.com/cocoa-mhlw/cocoa/blob/v1.2.2/Covid19Radar/Covid19Radar/Resources/html/license.html 
   - 参照されていない
   - 内容が古い

**Comment by zipperpull** [comment]
削除する以外にも、リポジトリ内の別ディレクトリに移して、別途サーバへデプロイする運用に変える方法もあると思います。
これは運用方針の問題なので勝手に決められないとは思いますが、サードパーティソフトウェアのライセンスの話なので
ソースと一体管理にできるならそのほうがよさそうです。

一応中身をみてみたのですが、AndroidAltBeaconLibrary はさすがにもう使っていないので消したほうがよさそうなのと、
CommonServiceLocator を使うならライセンス表記の追加がいりますね

https://github.com/unitycontainer/commonservicelocator/blob/master/LICENSE

**Comment by b-wind** [comment]
こちらが意味合い的に同じで内容は最新なので、こちらを主な管理対象とし他の物はここを元に生成すれは良いのでは（と言うのを書き忘れていました。）
https://github.com/cocoa-mhlw/cocoa/blob/v1.2.2/COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md

**Comment by keiji** [comment]
現在サーバーに公開されているライセンスファイルにはJson.NETはリンクになっていません。
また、本リポジトリからは当該ファイルは削除する方向で進んでいます（ https://github.com/cocoa-mhlw/cocoa/pull/115#discussion_r668403589  ）。 

本Issueは #212 が取り込まれればcloseされるようにしてあります。もし212が不採用になれば別途削除対応します。
