### ISSUE TITLE
[A11Y][iOS] 画面読み上げ（VoiceOver）を有効にするとスクロールができなくなる

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#913]
## 不具合の内容 / Describe the bug
開発チームが発見した課題。

iOS版で画面の読み上げ（VoiceOver）機能を有効にするとスクロールができなくなり、スクロールしないとボタンが押せない陽性情報登録などの操作を完了できない。

## 再現手順 / Steps to reproduce

1. 'VoiceOver'を有効にして、
2. COCOAを起動して
3. 「陽性情報登録」ボタンを選択する
4. 陽性情報登録前の確認画面でスクロール操作（VoiceOver利用時は三本指でスクロール）

## 期待される挙動 / Expected behavior

VoiceOverで画面の読み上げが問題なく行われ、スクロールして画面下部の要素にもアクセスできる。

## 動作環境 / Environments

- デバイス：iOS端末
- OS：iOS
- バージョン：COCOA v2.0.0 （COCOA v1.4.1では発生せず）

## その他 / Additional context

iOS版のXamarin.Formsには、画面内の要素移動がおかしくなる課題に対応するため`TabIndex`を設定すると、スクロールができなくなるバグがある様子。

[Bug] Accessibility Xamarin.Forms the scroll is not following the reading elements on iOS #11793
https://github.com/xamarin/Xamarin.Forms/issues/11793

Xamarin.Formsの4.8.x系から入ったバグで、v1.4.1が正常に動いていたのはそれより前のバージョンのXamarin.Formsを使っていたため。
バグ自体は2020年の6月に報告されていて、現在まで解決されていない様子。

**Comment by keiji** [comment]
現時点で考えられる対処法は2つ、

 * Xamarin.Formsを4.7系に戻す（古いバージョンにもそれなりに問題がある
 * 要素からTabIndexを取り除く（読み上げ順序が想定と異なるなどの問題がある

正直、ライブラリを前のバージョンに戻すというのは現実的でなく、TabIndexの削除でひとまず操作可能になるのであれば、そちらを選びたい（ベストな選択肢ではなく、操作できないよりはましという認識）。

**Comment by b-wind** [comment]
暫定対策に異論は無いのですが、最終的に解決出来るのかは気になりますね。
Issue https://github.com/xamarin/Xamarin.Forms/issues/11793#issuecomment-767191132 のコメントを見る限り、https://github.com/xamarin/Xamarin.Forms/pull/13300 で改善されるかも。と言う所でしょうか。


該当の PR は Xamarin.forms 5.0.0-sr1 にて取り込まれているようです。
https://docs.microsoft.com/ja-jp/xamarin/xamarin-forms/release-notes/5.0/5.0.0-sr1#january-19-2021---xamarinforms-5001905-500-service-release-1

**Comment by keiji** [comment]
Issue閉じられていないので、まだ問題が残っている可能性があります。

これ本当に困りますね……:thinking:

**Comment by b-wind** [comment]
https://github.com/xamarin/Xamarin.Forms/issues/12456#issuecomment-1007773528

TabIndex は間違った使い方をされてきて、他のコントロールのアクセシビリティを阻害する。
XamarinCommunityToolkit に含まれる、SemanticOrderView がよりアクセシビリティの高い代替手段。と言う所？

**Comment by b-wind** [comment]
https://devblogs.microsoft.com/xamarin/the-journey-to-accessible-apps-meaningful-content-ordering/
> Therefore, the general wisdom from accessibility experts is that TabIndex should not be used.

> SemanticOrderView, which is now implemented in the [Xamarin Community Toolkit](https://github.com/xamarin/XamarinCommunityToolkit/) (XCT), allows folks to [indicate the order](https://github.com/xamarin/XamarinCommunityToolkit/blob/main/samples/XCT.Sample/Pages/Views/SemanticOrderViewPage.xaml.cs) in which a group of [labelled controls](https://github.com/xamarin/XamarinCommunityToolkit/blob/main/samples/XCT.Sample/Pages/Views/SemanticOrderViewPage.xaml) should be navigated via screen readers, as captured in the sample XAML and C# code below.

**Comment by keiji** [comment]
v2.0.1で対応済みです。何かあればreopenするのでコメントください。
