### ISSUE TITLE
接触データのエクスポート機能を追加する

### ISSUE THREAD

**Issue by keiji** [cocoa-mhlw/cocoa#928]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?
これまで接触通知APIシステムの設定画面から接触確認結果をJSONで取得すると`MatchCount`が記載されていて、陽性者のキーとの一致数について不完全ながら確認できた。

また、この仕組みを使ったサードパーティのサービスもあり、一定の支持を得ていると個人的に認識している。

COCOAログチェッカー
https://cocoa-log-checker.com/

iOSでENv2に切り替えると、`MatchCount`のキーが出力されなくなることがDiscussionで報告された。
https://github.com/cocoa-mhlw/cocoa/discussions/921#discussioncomment-2392052

システムの出力するJSONについてはCOCOAは関与しておらず、`MatchCount`たなくなるのは、ENv2に更新することによって生じる仕様変更と認識している。

一方、COCOAが意図的に情報を制限したと受け取る利用者がいる可能性がある。また、バージョンアップによって自由が損なわれることは利用者のバージョンアップへの意欲をそぐものなので、可能な限り避けたいと個人的には思う。

## 解決策についてお書きください / Describe the solution you'd like
接触情報（DailySummaryとExposureWindow）のエクスポート機能を追加する。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

COCOA2でも閾値未満の接触画面を実装したが、クローズドベータに搭載したところで行政内での調整が進まず、以降、搭載が未定になっている。

https://github.com/cocoa-mhlw/cocoa/issues/823

これを搭載できればひとまずログ解析ツールよりも確実な情報提供を実現できるが、何度も言うが搭載は未定になっている。

## その他 / Additional context
基本的にアプリが保存しているデータは利用者のものなので、利用者が確認できることが正道と考える。

----
Internal IDs:
- Product Backlog Item 6777

**Comment by kvaluation** [comment]
COCOA2の閾値未満の接触画面が良いと思います。搭載して欲しいです。

画面例はこちらです
https://github.com/cocoa-mhlw/cocoa/discussions/903#discussioncomment-2413011

**Comment by keiji** [comment]
搭載できるように、引き続き行政内での調整を進めていく所存です。

**Comment by keiji** [comment]
これちょっとプライオリティ上げたい。
#967 に必要。
