### ISSUE TITLE
英語版の誤訳について

### ISSUE THREAD

**Issue by kasmide** [cocoa-mhlw/cocoa#939]
## 不具合の内容 / Describe the bug

複数箇所に誤訳と思しき文が見られます。

## 再現手順 / Steps to reproduce

1. 言語設定を英語にする
1. 「Register positive test result」を押す 
1. 次のような文が表示される: 「If you register your positivity on the application, a code will be daily generated on your smartphone and uploaded to the notification server」(陽性情報をアプリに登録すると、毎日コードがスマートフォンで生成され通知サーバーに送信される, 登録後にコードを毎日生成して送信する旨)、「people who have come in close contact (略) with you 2 or more days before the day the symptoms started or the day you were tested」(検査や症状の始まる2日以上前に濃厚接触した人, 原文と逆の意味) 

## 期待される挙動 / Expected behavior

原文と同じ意味の文が表示される。

## 動作環境 / Environments

- デバイス：Xperia 1 II
- OS：Android 11
- バージョン：2.0.0-openbeta01

## その他 / Additional context
上記以外にも軽微なミスや不自然な表現が見られるので、もしよければですが誤訳部分を含めた英語翻訳の改善の PR を出させて頂きたいと考えているのですが大丈夫でしょうか。

**Comment by keiji** [comment]
ありがとうございます。 「2日前から」が「2日以上前まで」になっていると言うことですね。
開発チームに共有します！

また、Pull Requestについても頂けると大変ありがたいです！　いただくそのままを取り込めるか現時点でお約束できないのが心苦しいのですが、少なくとも、ご指摘頂いているような誤訳はきちんと直すことを原則として進めたいと考えています。
