### ISSUE TITLE
ライセンス表示ページ 冒頭、「COVID-19Radar community」表記について

### ISSUE THREAD

**Issue by b-wind** [cocoa-mhlw/cocoa#940]
## 不具合の内容 / Describe the bug

https://github.com/cocoa-mhlw/cocoa/blob/f80fd0f6fe8bdc3e992a79ac2a04bdd910ac1094/COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md?plain=1#L1-L5

冒頭部分に「COVID-19Radar community」の表記が多く残っている。
COCOA の使う Third Party Software の取捨選別はすでにCOCOAの開発チーム他の責任において行われていると言う認識。
現状だと「COVID-19Radar community」が何らかの責任・影響力を持っている様に読み取れてしまうので適切な内容に変更した方が良いと思います。
なお、この変更によって「COVID-19Radar community」の名誉を貶める意図はなく、そのような効果も持たないと考えます。

## 期待される挙動 / Expected behavior

「COVID-19Radar community」を「COCOA developer team」（またはより適切な表現）に書き換える。

## その他 / Additional context

----
Internal IDs:
- NFR 7662

**Comment by b-wind** [comment]
冒頭の文章、そもそも **Third Party Software のライセンス文は原文のみ正しい意味を持つ** から勝手に翻訳などを行わないことと言う COVID-19Radar community 自身の編集方針だった様に想像される。


つまりアプリ内から **エンドユーザーに対して何らかのメッセージを伝える目的では無い** とも考えられるので、現状では記述自体が意味を成さないとも考えられるかも知れ無い。
この場合削除してしまって構わないかも知れ無い。

**Comment by keiji** [comment]
`COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md`がどのような意図で書かれたのかは承知していませんが、これはリポジトリに配置しているCopyrightに関するファイルで、必ずしもアプリ内で同様のものをリンクする必要はないと理解しています。

要件を満たしていれば、独自のものに置き換えることはできるのではと個人的には考えています。
一方、連携チーム・開発チームに確認して、場合によっては法律上の妥当性を確認してまで、アプリ内表記からCOVID-19Radar communityの記述を取り除く強い動機があるかと言われると……それよりも優先すべき課題が山積している。と言うのが正直なところだったりします。

**Comment by b-wind** [comment]
現状の無いようであれば法的な問題が無い事が確認されていると言う事でしょうか。
であれば私からは特に何も言う事は無いです。

**Comment by daisuke-nogami** [comment]
記載内容に誤りがあるかというと、ないと思います。
COCOAの元となったCOVID-19Radarプロジェクトが、組み込んでいる各種ライブラリのライセンス条件に従って、ライセンスを示しているものであり（後述）、現状のCOCOAも、もともとのライセンス条件に従ってソースコードに手を加えて利用をしているのは事実です（し、明示的にforkしていないので、派生した別アプリとも言いにくいですね）。

また、「このようなファイルの冒頭にCOVID-19Radarプロジェクトの名前があることが誤認を招くのでは」という指摘については、 @keiji さん指摘の通りアプリ内から閲覧するものではないこと、アプリは厚生労働省の名義でリリースされていること、本レポジトリは厚生労働省が所有してコントロールしていることから、Githubを見に来る方に誤認を招く恐れも少ないかと思います。

直近、このような課題を整理して連携チーム・開発チームに伝えるのが私の役割となっていますが、自分がこの仕事に割り当てている業務時間が限られている中では、他の課題を優先して検討したい、というのが、私の考えになります。

==
以下、冒頭の文章の2行目以降を自分の理解のために訳したものを置いておきます。

> このファイルには、以下のプロジェクトのコンポーネントが組み込まれています。
> 
> COVID-19Radarコミュニティは、これらのコンポーネントをCOVID-19Radarコミュニティのソフトウェアライセンス条項に基づいてあなたにライセンスします。
> ただし、そのコンポーネントが元のライセンスのままであることを要求するオープンソースライセンスの下でライセンスされたコンポーネントは、COVID-19Radarコミュニティによって元のライセンス条項に基づいてあなたに提供されるものとします。
> 
>  COVID-19Radarコミュニティが当該コンポーネントを受領した際のオリジナルの著作権表示およびライセンスは、情報提供の目的で以下に記載されています。

**Comment by b-wind** [comment]
まず、優先度云々については私からコメントすべき内容では無いと思いますし、特に急がせるような意図もありません。

**Comment by b-wind** [comment]
アプリからは COPYRIGHT_THIRD_PARTY_SOFTWARE_NOTICES.md を直接参照している訳ではありませんが、このファイルを元にライセンスページのHTMLファイルを自動生成（ #904 ）しているようですので、ライセンスページにも該当の表記はあります。

アプリ内から閲覧される内容であるという点が伝わっていないのかなと思いました。

<img src="https://user-images.githubusercontent.com/144311/172112244-7f5ec0b1-817d-42a6-804b-2fec536709cf.png" width="50%">

**Comment by daisuke-nogami** [comment]
こちらアプリ内の表示があることに気づかず失礼いたしました。

たぶん、置き換えること自体よりは、置き換え先のチーム名の表記を固めることにより負荷がかかりそうですので、
その点も勘案して引き続き、検討対象に残っていると認知して参ります…

**Comment by b-wind** [comment]
少なくともアプリ内で表示すべき内容としては該当の段落自体が不要なのでは無いかとも思うのですが、この場合でも様々な検討が必要でしょうか？

**Comment by keiji** [comment]
こちらぼくが引き取ります。

野上さんの言うとおり検討は必要です。が、どのように変えるとわかりやすいかというイメージを固めるために、Pull Requestの形で作業をするのが良いと思います。

**Comment by keiji** [comment]
Pull Requestは出しました。要するにこれ、(C) でどこの名前を書くか。なんですよね。

個人的にはCOCOAは厚生労働省が配布していて、リポジトリのOrganizationも cocoa-mhlw なので、厚生労働省の英語名である Ministry of Health, Labour and Welfare. になるのだと思いますが……リポジトリの運用はデジタル庁（Digital Agency）ですし、力を合わせて「連携チーム」という呼び方をすることもあります。

かといって、コントリビューターの皆さんの力もあって今があるわけで、ざっくり「COCOA Team」にしていいのであれば、その方が嬉しい気もしますね。

**Comment by daisuke-nogami** [comment]
私としても、いろいろな状況を全部勘案すると、COCOA Teamがよいと思います。

また、COCOA Teamと言う名称とすることに対して、明確に何らかの反対をされることもないと思うので、COCOA Teamに直す変更を進めてよいと思います。
