### ISSUE TITLE
[Android] root CA証明書を端末にインストールする（ユーザ証明書を信頼する）と通信が傍受できてしまう

### ISSUE THREAD

**Issue by tmurakami** [cocoa-mhlw/cocoa#96]
## 不具合の内容 / Describe the bug

https://github.com/cocoa-mhlw/cocoa/issues/95 にあるように、現状 mitmproxy 等を利用して通信内容を復号できてしまうようです (私は検証していません、すみません)。
特殊な環境であるとは言え、通信内容が傍受できてしまうのは (COCOA 開発者さん達の考え次第ですが) 良くないのでは？と考えています。

## 再現手順 / Steps to reproduce

https://github.com/cocoa-mhlw/cocoa/issues/95#issuecomment-810906925

## 期待される挙動 / Expected behavior

少なくともリリース版 COCOA においては、通信が傍受できない。

## 動作環境 / Environments

https://github.com/cocoa-mhlw/cocoa/issues/95#issuecomment-810906925

## その他 / Additional context

以下の対応で当該 issue は解決するのではないかと考えています。

- `HttpClient`の構成を`AndroidClientHandler`にする
https://docs.microsoft.com/ja-jp/xamarin/android/app-fundamentals/http-stack

- プリインストールされた CA のみを信頼するよう`base-config`を設定する(Android 9の設定にする)
https://developer.android.com/training/articles/security-config?hl=ja#base-config

ついでに iOS 版の`HttpClient`構成についても、MS が推奨している`NSUrlSessionHandler`になっているか確認 (なっていなければ設定) されると良いかと思います。
https://docs.microsoft.com/ja-jp/xamarin/cross-platform/macios/http-stack

**Comment by b-wind** [comment]
全く出来ないとデバッグが大変という面があるので、リリース版は各種対策を施して傍受を防ぐ。
デバッグビルドでは一定のルールの下、一部許可するぐらいが落とし所なのかなと思います。

現状では iOS の方が通信の傍受は容易いですね。

**Comment by b-wind** [comment]
一般論として ルートCA は通常のサーバー証明より遙かに長い有効期限があるので、頻繁な更新は無いと思われます。
ただし、セキュリティ上の都合等で急遽変わる事もまま有るので ルートCAの監視という定期タスクが増えることは確実ですね。
無視は出来ない要素です。

**Comment by keiji** [comment]
ユーザーが能動的に通信を見に行くパターンですね。

特殊とはいえ、ユーザーが知らないうちにこの手順を実行されて、知らない間に傍受される（それに気づかない）という可能性はありますか？

技術的な対応案についてもありがとうございます。
対応策があるならどちらを選ぶか（または第３以降の選択肢があるか）ですね。

開発チームの方にもきちんと共有します。

**Comment by Guest126** [comment]
#95 にあるように、現状 mitmproxy 等を利用して通信内容を復号できてしまうのは、再現手順の中でデバッグ用に「プロキシの root 証明書を端末にインストールする」という手順を踏んだからです。「プロキシの root 証明書を端末にインストールする」というのは白地手形を振り出すのと同義です。

「プロキシを使うことで通信が傍受できてしまう」というのがそもそも認識の誤りで、「root CA証明書を端末にインストールする（ユーザ証明書を信頼する）と通信が傍受できてしまう」というのが正確な表現になると思います。

**Comment by b-wind** [comment]
@Guest126 さんの手順も私の紹介した手順も基本的には「ユーザーが自発的にルートCA」を導入することを前提にしています。
企業管理者が導入することも有ると思いますが、それもユーザーの同意があるものとして扱います。


これらの手順の範囲では「勝手に傍受される」のでは無く「自分が見たいからそう設定した」物と扱って頂きたいです。
そうなるように手順は年々ややこしくなっています。


Android/iOS 共にバージョンが上がるにつれ、「何らかの仕組みで勝手に傍受される」ケースは対策が成されています。
もっともそれでも完全に防ぐことは出来ないですが、別の話です。

**Comment by tmurakami** [comment]
@Guest126 

> root CA証明書を端末にインストールする（ユーザ証明書を信頼する）と通信が傍受できてしまう

ご指摘ありがとうございます。タイトル修正しておきました。

ちなみに`HttpClient`構成が`AndroidClientHandler`になっていれば、Proxy を経由していない問題も解決するのではないかと思っています。
当該Handler はネイティブの`HttpURLConnection`を利用するので。
https://github.com/xamarin/xamarin-android/blob/main/src/Mono.Android/Xamarin.Android.Net/AndroidClientHandler.cs

**Comment by keiji** [comment]
@b-wind さん
> これらの手順の範囲では「勝手に傍受される」のでは無く「自分が見たいからそう設定した」物と扱って頂きたいです。

わかりました。つまるところ「ユーザーが自発的に自分の通信を見ることを制限すべきかどうか」と言う話でしょうか。

COCOAはソースコードを公開していて、通信手順はだれでも確認できるので、ユーザーが見たいというのであれば、ここを制限する理由はないとぼくは思っています。もし見落としている点があれば教えてください。

**Comment by b-wind** [comment]
> わかりました。つまるところ「ユーザーが自発的に自分の通信を見ることを制限すべきかどうか」と言う話でしょうか。


私としてはこれはそのような話であると考えています。
直接的（個人的）にはデバッグ目的に使っているというのも有りますが。


もちろんその結果、本来の動作でプライバシーを蔑ろにするような事が無いように注意をする必要がありますので、それについて具体的な指摘が有れば対応すべきと思います。

**Comment by tmurakami** [comment]
@keiji

個人で覗き見る分には良いのではないかと思います。
ただ @b-wind さんの

> 企業管理者が導入することも有ると思いますが、それもユーザーの同意があるものとして扱います。

はちょっと気にかかります。
陽性者情報はセンシティブだと思うので、もしも企業管理者が陽性登録を傍受できてしまうとしたら、個人的には問題だと思っています。

**Comment by b-wind** [comment]
> 陽性者情報はセンシティブだと思うので、もしも企業管理者が陽性登録を傍受できてしまうとしたら、個人的には問題だと思っています。

普通はウィルス対策などの目的で導入するもので、わざわざ企業管理者が覗くシチュエーションは中々無いとは思うのですが、
事例が無いわけでも無いですので、懸念点として考えておいた方が良いかも知れませんね。


基本的にはスマホ全体が企業の管理下（所有権も普通は企業側）なのでそのような状況ではCOCOAを導入しないぐらいしか今は思いつきません。

**Comment by tmurakami** [comment]
https://developer.android.com/training/articles/security-config?hl=ja#base-config
に記載の Android 9 の設定ができれば良いかと。

**Comment by b-wind** [comment]
@tmurakami Android 9 以降はそれが何もしなくても（つまり今も）そうなっているのですが、リリースビルドはそれで良いとしてデバッグビルドでもその制限のままでは辛いと言う事情があります。

**Comment by tmurakami** [comment]
@b-wind 夜分お疲れさまです。

個人的にもデバッグビルドでは制限を緩和しても良いのではないかと思っています。
とはいえ、root を取っていない一般人には EN を使ったテストができない(はずな)ので、どこまで意味があるものなのかはわかりませんが...

**Comment by b-wind** [comment]
#95 の対応によって、ここで語られているような形の傍受は出来なくなったと認識しています。
特に何かしたいという事が無ければ close で良いのでは無いかと。

**Comment by tmurakami** [comment]
@b-wind

その他 / Additional context にある

> プリインストールされた CA のみを信頼するようbase-configを設定する(Android 9の設定にする)

の対応ができていないようなので、close していません。

個人的には

- OS バージョン毎の差異を無くすべき
- より厳しい設定 (Android 9 の設定) に合わせるべき

だとは思っていますが、工数かけてまでやることかどうか私には判断できませんので、開発担当の方々でご検討頂ければと思います。
対応しないと明言頂ければ、close します。

**Comment by b-wind** [comment]
失礼。古い Android version への対応を失念していました。

現状だと、minSdkVersion=23 targetSdkVersion=29 となっていますね。

この場合だと、Android 9（API レベル 28）以上と同じ扱いという認識でしたが、実際はどうなのでしょう？（あまり自信なし）

**Comment by tmurakami** [comment]
AndroidManifest.xml の minSdkVersion/targetSdkVersion に依らす、COCOA がインストールされた端末の OS バージョンに依存する認識です。
Android 6 端末であれば、今でも #95 の手順にあるように mitmproxy の証明書を端末にインストールすれば COCOA の通信を覗き見ることができるのではないかと思います。
試してはいませんが…

**Comment by tmurakami** [comment]
私が勘違いしておりました。
まず、`android:networkSecurityConfig`は Android 7 から用意されたものでした。
ですので Android 6 では関係ありません。

また、Android 7 の NetworkSecurityConfig.java
https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-7.0.0_r34/core/java/android/security/net/config/NetworkSecurityConfig.java#191
を見る限り、デフォルトでは targetSdkVersion が

- `Build.VERSION_CODES.M`以下であればユーザー証明書を信頼する
- `Build.VERSION_CODES.M`より大きければ、ユーザー証明書を信頼しない

ようになっているようです。

ですので @b-wind さんのおっしゃる通り、現状ユーザー証明書を信頼することはないように思います。
(ただし上記コードを見る限り、少なくとも Android 7 端末においては`cleartextTrafficPermitted`は`true`であるように思えますが、それは本件とは関係ありません)

本件 close します。

**Comment by b-wind** [comment]
@tmurakami さん。コードレベルの確認までして戴いてありがとうございます。
