### ISSUE TITLE
[Android] SafetyNet 構成証明をオフライン検証する

### ISSUE THREAD

**Issue by tmurakami** [cocoa-mhlw/cocoa#99]
## その機能リクエストは何らかの問題に関連しますか / Is your feature request related to a problem?

サーバ側の`DeviceValidationAndroidService`ですが、SafetyNet 構成証明をオンライン検証しているように見うけられます。
https://github.com/cocoa-mhlw/cocoa/blob/9fb874b4eb82fb87c522c0f76466bcaafac822b4/src/Covid19Radar.Api/Services/DeviceValidationAndroidService.cs#L168

https://developer.android.com/training/safetynet/attestation?hl=ja#verify-attestation-response
https://developers-jp.googleblog.com/2017/12/10-things-you-might-be-doing-wrong-when.html
によると、オンライン検証はテスト専用だそうです。

## 解決策についてお書きください / Describe the solution you'd like

オフライン検証に切り替えた方が良いように思います。

## あなたが考える代替案についてご説明ください / Describe alternatives you've considered

オフライン検証のコード例については、[android-play-safetynet のサンプル ](https://github.com/googlesamples/android-play-safetynet/tree/master/server) の`OfflineVerify.cs`を参照下さい。
https://github.com/googlesamples/android-play-safetynet/blob/master/server/csharp/OfflineVerify.cs

## その他 / Additional context

次のバージョンのソースコードが公開されてからにしようと思っていたのですが、せっかく立ちよったので他にも issue をいくつか挙げておきます。

なお SafetyNet については
https://github.com/mh-/exposure-notification-ble-python/blob/master/doc/some_thoughts_on_the_en_concept.md

> The SafetyNet ToS state that this "works by collecting hardware and software information, such as device and application data (...), and sending that data to Google for analysis". I think that's fine in general, but an actual COVID-19- warning app should not invoke this API only when a user has been infected, but independently of this - so that the device data cannot be linked to this sensitive information.

とあり、Google が SafetyNet で取得した陽性者端末情報と他の情報(ロケーション履歴とか？)をリンクできる可能性があるかもしれません。

----
Internal Tracking ID: NFR 1792

**Comment by keiji** [comment]
Issueありがとうございます！

SafetyNetの現在の検証方法について、開発チームに確認しますね。

**Comment by keiji** [comment]
ぼくがかみ砕く必要があったので、現時点でわかっていることを列挙していきます。

 * 今回の課題はアプリが通信するサーバー側にある（アプリをアップデートすることなくに改善できる
 * SafetyNet Attestation APIは、Androidデバイスが正規のものであるか（Androidの互換性チェックをパスしているか、rootedでないか）を検証する仕組み
 * COCOAやサーバーで関係する実装は次の図のClient AppとClient Backend
   * https://developer.android.com/training/safetynet/attestation?hl=ja
 * Client App（COCOA）が取得した証明書情報をClient Backend（サーバー）に送信して検証することで、Androidデバイスが正規のものであるか確認している
 * 検証はJWS（JSON Web Signature）メッセージの送信元を確認することで行う。
 * 現在のClient Backend（サーバー）側の実装はこれをオンライン（Googleが用意したサーバー）で行っている
 * Googleが用意したサーバーはテスト目的に限定されていて、本来はClient Backend（サーバー側）で閉じて行うべき
 * Googleが用意したサーバーにはクォーターがあり、一日あたりの利用回数が10,000回に制限されている
 * COCOAの場合、陽性登録の段階でこの検証を行っている
 * 一日の陽性登録者数が10,000人を超えると検証が行えなくなり、陽性登録が正常に完了しない可能性がある（要確認
 * 一日の陽性登録者が10,000人を超えなくても、Googleが「オンラインの検証 API は初期段階のテスト専用であり」と示しているとおり、オンライン検証はプロダクトに利用する想定ではない（Backend内部で検証すべき

もし認識に齟齬があればご指摘いただければと思います。

もう一点、いただいたexposure-notification-ble-pythonの件について教えてください。これはどちらかというとプライバシー上の懸念で、アプリ側の課題という理解で間違いないでしょうか。

ざっくり、接触確認アプリ（Client App）で、陽性登録のタイミングでのみSafetyNet Attestation APIで検証する構造にすると「このアプリからSafetyNet Attestation APIを利用したユーザーは陽性者」とGoogleが判断できる可能性が生まれる。と言うような内容と受け取っています。

これについてはClient App（COCOA）の変更が必要で、たとえば陽性登録以外のタイミング——利用開始時など——や、ランダムの間隔でダミーのSafetyNet Attestation APIのリクエストを出すとか、そういった対応で対応できそうだなとぼくは思っています。これは別にIssueにした方がいいかもしれませんね。

**Comment by tmurakami** [comment]
> もし認識に齟齬があればご指摘いただければと思います。

1点だけ確認させて下さい。

> 一日の陽性登録者数が10,000人を超えると検証が行えなくなり、陽性登録が正常に完了しない可能性がある（要確認

こちら SafetyNet Attestation API の呼び出し自体の割り当て
https://developer.android.com/training/safetynet/attestation?hl=ja#quota-monitoring

> 重要: SafetyNet Attestation API の呼び出しの割り当ては、デフォルトで 1 日あたり 10,000 リクエストです。

を指している(オンライン検証の 10,000 リクエスト/日 とは別に割り当てがある)のであれば、要確認というところも含めて私の認識と相違ありません。

> もう一点、いただいたexposure-notification-ble-pythonの件について教えてください。これはどちらかというとプライバシー上の懸念で、アプリ側の課題という理解で間違いないでしょうか。

おっしゃる通りプライバシー上の懸念です。

> 「このアプリからSafetyNet Attestation APIを利用したユーザーは陽性者」とGoogleが判断できる可能性が生まれる。と言うような内容と受け取っています。

同じ認識です。

> これについてはClient App（COCOA）の変更が必要で、たとえば陽性登録以外のタイミング——利用開始時など——や、ランダムの間隔でダミーのSafetyNet Attestation APIのリクエストを出すとか、そういった対応で対応できそうだなとぼくは思っています。

前述の SafetyNet Attestation API 自体の割り当てを考慮する必要があるのではないかと思います。

> これは別にIssueにした方がいいかもしれませんね。

後日、別 issue として挙げることにします。
(多分遅くなります)

**Comment by keiji** [comment]
> 一日の陽性登録者数が10,000人を超えると検証が行えなくなり、陽性登録が正常に完了しない可能性がある（要確認
ここで示しているクォータは、オンライン検証のもの（ 10,000 リクエスト/日）を想定しています。

SafetyNet Attestation API自体のクォータは、おそらくGoogleに言えば拡大できると認識していますが、オンライン検証はそもそもテスト目的とされているので、ここはお願いしても拡大してくれないだろうな。という目算からです。

**Comment by keiji** [comment]
@tmurakami 
Issueの提出、ありがとうございます。開発チームに確認をして、検証のオフライン移行について対応することになりました。
すべての対応を完了した時点で、あらためてご報告します。
